/*
 * From ap_payment
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ap.component;


import classinterface.NavigatorFormInt;
import common.component.FrmBrowseData;
import common.component.FrmMainFrame;
import java.sql.SQLException;
import kopkar.ap.objectclasses.ap_paymentext;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import kopkar.ap.objectclasses.ap_payment_detail1ext;
import kopkar.ap.objectclasses.ap_payment_detail1extcol;
import kopkar.ap.objectclasses.ap_payment_detail2ext;
import kopkar.ap.objectclasses.ap_payment_detail2extcol;
import kopkar.ap.objectclasses.ap_payment_detail3ext;
import kopkar.ap.objectclasses.ap_payment_detail3extcol;
import kopkar.gl.objectclasses.gl_kalender_detail1ext;
import kopkar.gl.objectclasses.gl_kalenderext;
import kopkar.gl.objectclasses.gl_kalenderextcol;
import kopkar.utils.browsecontroller;
import org.kazao.calendar.KazaoCalendarDateTimeException;
import utils.CodeException;
import utils.GlobalModel;
import utils.GlobalUtils;
import utils.selectallJTable;

/**
 *
 * @author  Generator
 */

public class Frmap_payment extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmap_payment";

    ap_payment_detail1extcol objd1s;
    ap_payment_detail2extcol objd2s;
    ap_payment_detail3extcol objd3s;
    browsecontroller obrowse=new browsecontroller();

    FrmMainFrame mf ;
    DefaultTableModel model_invoice=null;
    DefaultTableModel model_dnote=null;

    ap_paymentext obj=new ap_paymentext();
    ap_payment_detail1ext objd1=new ap_payment_detail1ext(obj);
    ap_payment_detail2ext objd2=new ap_payment_detail2ext();
    ap_payment_detail3ext objd3=new ap_payment_detail3ext();
    private ap_payment_detail1ext objd1tmp;
    private ap_paymentext objtmp;
   
    /** Creates new form Area */
    public Frmap_payment() throws CodeException {
        initComponents();
    }
    
    public Frmap_payment(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
        model_invoice=(DefaultTableModel) jtbldetail_invoice.getModel();
        model_dnote=(DefaultTableModel) jtbldetail1_dnote.getModel();

        showtahun();
        showbulan();
    }

    private void showtahun() {
        gl_kalenderextcol okal=new gl_kalenderextcol();
        try {
            okal.initdata();
            jcmbyop.removeAllItems();
            for (int i=0;i<okal.size();i++){
                gl_kalenderext o = okal.get(i);
                jcmbyop.addItem(o.getyop());
            }
            jcmbyop.setSelectedItem(GlobalUtils.toInt(GlobalUtils.formatDate(GlobalUtils.sessiondate,"yyyy")));
        } catch (SQLException ex) {
            Logger.getLogger(Frmap_payment.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void showbulan() {
        gl_kalenderext okal=new gl_kalenderext();
        gl_kalender_detail1ext o;
        try {
            if (jcmbyop.getSelectedIndex()>-1){
                jcmbmop.removeAllItems();
                if (okal.initdata((Integer) jcmbyop.getSelectedItem())) {
                    for (int i = 0; i < okal.getDetail1().size(); i++) {
                        o=okal.getDetail1().get(i);
                        jcmbmop.addItem(GlobalUtils.getMonthName(o.getmop()));
                    }
                }
                jcmbmop.setSelectedItem(GlobalUtils.getMonthName(GlobalUtils.toInt(GlobalUtils.formatDate(GlobalUtils.sessiondate,"MM"))));
            }
        } catch (CodeException ex) {
            Logger.getLogger(Frmap_payment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();
        jlbldocument_number = new javax.swing.JLabel();
        jtxtdocument_number = new javax.swing.JTextField();
        jlbldocument_status = new javax.swing.JLabel();
        jtxtdocument_status = new javax.swing.JTextField();
        jlbldocument_date = new javax.swing.JLabel();
        jlblreference = new javax.swing.JLabel();
        jtxtreference = new javax.swing.JTextField();
        jlbldscription = new javax.swing.JLabel();
        jtxtdscription = new javax.swing.JTextField();
        jlbltotal_entry = new javax.swing.JLabel();
        jtxttotal_entry = new javax.swing.JTextField();
        jlbltotal_payment = new javax.swing.JLabel();
        jtxttotal_payment = new javax.swing.JTextField();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbldetail_invoice = new selectallJTable(model_invoice);
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbldetail1_dnote = new selectallJTable(model_invoice);
        jlbldocentry = new javax.swing.JLabel();
        jlblsupplier_code = new javax.swing.JLabel();
        jlblpayment_type = new javax.swing.JLabel();
        jlblpayment_ammount = new javax.swing.JLabel();
        jtxtpayment_ammount = new javax.swing.JTextField();
        jtxtsupplier_code_desc = new javax.swing.JTextField();
        jtxtdocentry = new javax.swing.JTextField();
        jbtnBrowse2 = new javax.swing.JButton();
        jbtnBrowse1 = new javax.swing.JButton();
        jtxtsupplier_code = new javax.swing.JTextField();
        jlbldocdate = new javax.swing.JLabel();
        jlblyop = new javax.swing.JLabel();
        jlblmop = new javax.swing.JLabel();
        jlblpayment_total = new javax.swing.JLabel();
        jlblpayment_balance = new javax.swing.JLabel();
        jtxtpayment_balance = new javax.swing.JTextField();
        jtxtpayment_total = new javax.swing.JTextField();
        jcmbyop = new javax.swing.JComboBox();
        jcmbmop = new javax.swing.JComboBox();
        jcmbpayment_type = new javax.swing.JComboBox();
        kzodocument_date = new org.kazao.calendar.KazaoCalendarDate();
        kzodocdate = new org.kazao.calendar.KazaoCalendarDate();
        jopt_complete_status_draff = new javax.swing.JRadioButton();
        jopt_complete_status_complete = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AP Payment");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : AP Payment");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 200, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(410, 110, 30, 20);

        jlbldocument_number.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_number.setText("No.Dokumen");
        getContentPane().add(jlbldocument_number);
        jlbldocument_number.setBounds(70, 110, 140, 13);

        jtxtdocument_number.setEditable(false);
        jtxtdocument_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdocument_number.setText("document_number");
        jtxtdocument_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocument_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdocument_number);
        jtxtdocument_number.setBounds(260, 110, 150, 23);

        jlbldocument_status.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_status.setText("Status");
        getContentPane().add(jlbldocument_status);
        jlbldocument_status.setBounds(450, 90, 140, 13);

        jtxtdocument_status.setEditable(false);
        jtxtdocument_status.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdocument_status.setText("document_status");
        jtxtdocument_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtdocument_statusActionPerformed(evt);
            }
        });
        jtxtdocument_status.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocument_statusFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdocument_status);
        jtxtdocument_status.setBounds(640, 90, 150, 23);

        jlbldocument_date.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_date.setText("Tgl.Dokumen");
        getContentPane().add(jlbldocument_date);
        jlbldocument_date.setBounds(70, 130, 140, 13);

        jlblreference.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblreference.setText("Referensi");
        getContentPane().add(jlblreference);
        jlblreference.setBounds(70, 150, 140, 13);

        jtxtreference.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtreference.setText("reference");
        jtxtreference.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtreferenceFocusGained(evt);
            }
        });
        getContentPane().add(jtxtreference);
        jtxtreference.setBounds(260, 150, 280, 23);

        jlbldscription.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldscription.setText("Keterangan");
        getContentPane().add(jlbldscription);
        jlbldscription.setBounds(70, 170, 140, 13);

        jtxtdscription.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdscription.setText("dscription");
        jtxtdscription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdscriptionFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdscription);
        jtxtdscription.setBounds(260, 170, 280, 23);

        jlbltotal_entry.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltotal_entry.setText("Jumlah Entri");
        getContentPane().add(jlbltotal_entry);
        jlbltotal_entry.setBounds(450, 110, 140, 13);

        jtxttotal_entry.setEditable(false);
        jtxttotal_entry.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttotal_entry.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxttotal_entry.setText("total_entry");
        jtxttotal_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxttotal_entryActionPerformed(evt);
            }
        });
        jtxttotal_entry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttotal_entryFocusGained(evt);
            }
        });
        getContentPane().add(jtxttotal_entry);
        jtxttotal_entry.setBounds(640, 110, 150, 23);

        jlbltotal_payment.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltotal_payment.setText("Total Bayar");
        getContentPane().add(jlbltotal_payment);
        jlbltotal_payment.setBounds(450, 130, 140, 13);

        jtxttotal_payment.setEditable(false);
        jtxttotal_payment.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttotal_payment.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxttotal_payment.setText("total_payment");
        jtxttotal_payment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttotal_paymentFocusGained(evt);
            }
        });
        getContentPane().add(jtxttotal_payment);
        jtxttotal_payment.setBounds(640, 130, 150, 23);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(360, 30, 170, 20);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(530, 30, 130, 20);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(660, 30, 140, 20);

        jToolBar1.setFloatable(false);
        jToolBar1.setFont(new java.awt.Font("Dialog", 1, 10));

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_newfile.gif"))); // NOI18N
        btnNew.setMnemonic('n');
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNew);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_save.gif"))); // NOI18N
        btnSave.setMnemonic('s');
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);

        btnUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_undo.gif"))); // NOI18N
        btnUndo.setMnemonic('u');
        btnUndo.setToolTipText("Undo");
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUndo);

        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_del.gif"))); // NOI18N
        btnDel.setMnemonic('d');
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDel);

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_move_first.gif"))); // NOI18N
        btnFirst.setMnemonic('q');
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFirst);

        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_move_prev.gif"))); // NOI18N
        btnPrev.setMnemonic('w');
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPrev);

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_move_next.gif"))); // NOI18N
        btnNext.setMnemonic('e');
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNext);

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_move_last.gif"))); // NOI18N
        btnLast.setMnemonic('r');
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLast);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(260, 190, 330, 34);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 10));

        jPanel1.setLayout(null);

        jtbldetail_invoice.setFont(new java.awt.Font("Dialog", 0, 10));
        jtbldetail_invoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Pilih", "No.Faktur", "Tgl.Faktur", "Jt.Tempo", "Nilai Faktur", "Ttl. Bayar", "Sisa", "Jml. Bayar", "Nilai Akhir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbldetail_invoice.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtbldetail_invoice.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtbldetail_invoice.setSurrendersFocusOnKeystroke(true);
        jtbldetail_invoice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtbldetail_invoiceFocusGained(evt);
            }
        });
        jtbldetail_invoice.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtbldetail_invoicePropertyChange(evt);
            }
        });
        jtbldetail_invoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbldetail_invoiceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtbldetail_invoiceKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtbldetail_invoice);
        jtbldetail_invoice.getColumnModel().getColumn(0).setMinWidth(40);
        jtbldetail_invoice.getColumnModel().getColumn(0).setPreferredWidth(40);
        jtbldetail_invoice.getColumnModel().getColumn(0).setMaxWidth(40);
        jtbldetail_invoice.getColumnModel().getColumn(1).setMinWidth(90);
        jtbldetail_invoice.getColumnModel().getColumn(1).setPreferredWidth(90);
        jtbldetail_invoice.getColumnModel().getColumn(1).setMaxWidth(90);
        jtbldetail_invoice.getColumnModel().getColumn(2).setMinWidth(80);
        jtbldetail_invoice.getColumnModel().getColumn(2).setPreferredWidth(80);
        jtbldetail_invoice.getColumnModel().getColumn(2).setMaxWidth(80);
        jtbldetail_invoice.getColumnModel().getColumn(3).setMinWidth(80);
        jtbldetail_invoice.getColumnModel().getColumn(3).setPreferredWidth(80);
        jtbldetail_invoice.getColumnModel().getColumn(3).setMaxWidth(80);
        jtbldetail_invoice.getColumnModel().getColumn(4).setMinWidth(90);
        jtbldetail_invoice.getColumnModel().getColumn(4).setPreferredWidth(90);
        jtbldetail_invoice.getColumnModel().getColumn(4).setMaxWidth(90);
        jtbldetail_invoice.getColumnModel().getColumn(7).setMinWidth(90);
        jtbldetail_invoice.getColumnModel().getColumn(7).setPreferredWidth(90);
        jtbldetail_invoice.getColumnModel().getColumn(7).setMaxWidth(90);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 710, 120);

        jTabbedPane1.addTab("Info Payment", jPanel1);

        jPanel2.setLayout(null);

        jtbldetail1_dnote.setFont(new java.awt.Font("Dialog", 0, 10));
        jtbldetail1_dnote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Pilih", "No.D/N", "Tgl.Faktur", "Jt.Tempo", "Nilai Faktur", "Ttl. Bayar", "Sisa", "Jml. Bayar", "Nilai Akhir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbldetail1_dnote.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtbldetail1_dnote.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtbldetail1_dnote.setSurrendersFocusOnKeystroke(true);
        jtbldetail1_dnote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtbldetail1_dnoteFocusGained(evt);
            }
        });
        jtbldetail1_dnote.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtbldetail1_dnotePropertyChange(evt);
            }
        });
        jtbldetail1_dnote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbldetail1_dnoteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtbldetail1_dnoteKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jtbldetail1_dnote);
        jtbldetail1_dnote.getColumnModel().getColumn(0).setMinWidth(40);
        jtbldetail1_dnote.getColumnModel().getColumn(0).setPreferredWidth(40);
        jtbldetail1_dnote.getColumnModel().getColumn(0).setMaxWidth(40);
        jtbldetail1_dnote.getColumnModel().getColumn(1).setMinWidth(90);
        jtbldetail1_dnote.getColumnModel().getColumn(1).setPreferredWidth(90);
        jtbldetail1_dnote.getColumnModel().getColumn(1).setMaxWidth(90);
        jtbldetail1_dnote.getColumnModel().getColumn(2).setMinWidth(80);
        jtbldetail1_dnote.getColumnModel().getColumn(2).setPreferredWidth(80);
        jtbldetail1_dnote.getColumnModel().getColumn(2).setMaxWidth(80);
        jtbldetail1_dnote.getColumnModel().getColumn(3).setMinWidth(80);
        jtbldetail1_dnote.getColumnModel().getColumn(3).setPreferredWidth(80);
        jtbldetail1_dnote.getColumnModel().getColumn(3).setMaxWidth(80);
        jtbldetail1_dnote.getColumnModel().getColumn(4).setMinWidth(90);
        jtbldetail1_dnote.getColumnModel().getColumn(4).setPreferredWidth(90);
        jtbldetail1_dnote.getColumnModel().getColumn(4).setMaxWidth(90);
        jtbldetail1_dnote.getColumnModel().getColumn(7).setMinWidth(90);
        jtbldetail1_dnote.getColumnModel().getColumn(7).setPreferredWidth(90);
        jtbldetail1_dnote.getColumnModel().getColumn(7).setMaxWidth(90);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 710, 120);

        jTabbedPane1.addTab("Info Debit Note", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(70, 380, 720, 160);

        jlbldocentry.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocentry.setText("No.Entry");
        getContentPane().add(jlbldocentry);
        jlbldocentry.setBounds(70, 230, 140, 13);

        jlblsupplier_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsupplier_code.setText("Kode Supplier");
        getContentPane().add(jlblsupplier_code);
        jlblsupplier_code.setBounds(70, 290, 140, 20);

        jlblpayment_type.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblpayment_type.setText("Tipe Bayar");
        getContentPane().add(jlblpayment_type);
        jlblpayment_type.setBounds(70, 330, 140, 20);

        jlblpayment_ammount.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblpayment_ammount.setText("Jumlah Bayar");
        getContentPane().add(jlblpayment_ammount);
        jlblpayment_ammount.setBounds(70, 350, 140, 20);

        jtxtpayment_ammount.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtpayment_ammount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtpayment_ammount.setText("payment_ammount");
        jtxtpayment_ammount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtpayment_ammountFocusGained(evt);
            }
        });
        jtxtpayment_ammount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtpayment_ammountKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtpayment_ammountKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtpayment_ammount);
        jtxtpayment_ammount.setBounds(260, 350, 150, 23);

        jtxtsupplier_code_desc.setEditable(false);
        jtxtsupplier_code_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsupplier_code_desc.setText("supplier_code");
        jtxtsupplier_code_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsupplier_code_descActionPerformed(evt);
            }
        });
        jtxtsupplier_code_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsupplier_code_descFocusGained(evt);
            }
        });
        getContentPane().add(jtxtsupplier_code_desc);
        jtxtsupplier_code_desc.setBounds(260, 310, 270, 23);

        jtxtdocentry.setEditable(false);
        jtxtdocentry.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdocentry.setText("docentry");
        jtxtdocentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtdocentryActionPerformed(evt);
            }
        });
        jtxtdocentry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocentryFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdocentry);
        jtxtdocentry.setBounds(260, 230, 150, 23);

        jbtnBrowse2.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse2.setText("...");
        jbtnBrowse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse2);
        jbtnBrowse2.setBounds(410, 230, 30, 17);

        jbtnBrowse1.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse1.setText("...");
        jbtnBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse1);
        jbtnBrowse1.setBounds(410, 290, 30, 17);

        jtxtsupplier_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsupplier_code.setText("supplier_code");
        jtxtsupplier_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsupplier_codeActionPerformed(evt);
            }
        });
        jtxtsupplier_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsupplier_codeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtsupplier_code);
        jtxtsupplier_code.setBounds(260, 290, 150, 23);

        jlbldocdate.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocdate.setText("Tgl Entry");
        getContentPane().add(jlbldocdate);
        jlbldocdate.setBounds(450, 230, 140, 13);

        jlblyop.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblyop.setText("Tahun");
        getContentPane().add(jlblyop);
        jlblyop.setBounds(450, 250, 140, 13);

        jlblmop.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmop.setText("Bulan");
        getContentPane().add(jlblmop);
        jlblmop.setBounds(450, 270, 140, 13);

        jlblpayment_total.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblpayment_total.setText("Total Bayar");
        getContentPane().add(jlblpayment_total);
        jlblpayment_total.setBounds(450, 330, 140, 13);

        jlblpayment_balance.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblpayment_balance.setText("Sisa Bayar");
        getContentPane().add(jlblpayment_balance);
        jlblpayment_balance.setBounds(450, 350, 140, 13);

        jtxtpayment_balance.setEditable(false);
        jtxtpayment_balance.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtpayment_balance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtpayment_balance.setText("payment_balance");
        jtxtpayment_balance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtpayment_balanceFocusGained(evt);
            }
        });
        getContentPane().add(jtxtpayment_balance);
        jtxtpayment_balance.setBounds(640, 350, 130, 23);

        jtxtpayment_total.setEditable(false);
        jtxtpayment_total.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtpayment_total.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtpayment_total.setText("payment_total");
        jtxtpayment_total.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtpayment_totalFocusGained(evt);
            }
        });
        getContentPane().add(jtxtpayment_total);
        jtxtpayment_total.setBounds(640, 330, 130, 23);

        jcmbyop.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbyop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmbyop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbyopItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbyop);
        jcmbyop.setBounds(640, 250, 80, 20);

        jcmbmop.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jcmbmop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcmbmop);
        jcmbmop.setBounds(640, 270, 160, 20);

        jcmbpayment_type.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbpayment_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tunai", "Transfer", "Return" }));
        jcmbpayment_type.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbpayment_typeItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbpayment_type);
        jcmbpayment_type.setBounds(260, 330, 160, 20);

        kzodocument_date.setFont(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date.setFontDate(new java.awt.Font("Dialog", 0, 10));
        getContentPane().add(kzodocument_date);
        kzodocument_date.setBounds(260, 130, 100, 20);

        kzodocdate.setFont(new java.awt.Font("Dialog", 0, 10));
        kzodocdate.setFontDate(new java.awt.Font("Dialog", 0, 10));
        getContentPane().add(kzodocdate);
        kzodocdate.setBounds(640, 230, 100, 20);

        buttonGroup1.add(jopt_complete_status_draff);
        jopt_complete_status_draff.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jopt_complete_status_draff.setSelected(true);
        jopt_complete_status_draff.setText("Draff");
        getContentPane().add(jopt_complete_status_draff);
        jopt_complete_status_draff.setBounds(70, 550, 52, 24);

        buttonGroup1.add(jopt_complete_status_complete);
        jopt_complete_status_complete.setFont(new java.awt.Font("Dialog", 0, 10));
        jopt_complete_status_complete.setText("Complete");
        getContentPane().add(jopt_complete_status_complete);
        jopt_complete_status_complete.setBounds(150, 550, 123, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jtxtdocument_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtdocument_statusActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdocument_statusActionPerformed

private void jtxttotal_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxttotal_entryActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jtxttotal_entryActionPerformed

private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
    objd1tmp=objd1;
    objd1=new ap_payment_detail1ext(obj);
    obj.settotal_payment_tmp(obj.gettotal_payment());
    obj.settotal_entry_tmp(obj.gettotal_entry());
    showdatadetail1();

    setToolBardetail1();

    jTabbedPane1.setEnabledAt(1, false);
    jTabbedPane1.setSelectedIndex(0);

}//GEN-LAST:event_btnNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            saveData();
        } catch (CodeException ex) {
            Logger.getLogger(Frmap_payment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        if (istatus==0){
            obj.settotal_payment(obj.gettotal_payment_tmp());
            obj.settotal_entry(obj.gettotal_entry_tmp());
            objd1=objd1tmp;
            showdatadetail1();

            jtxttotal_payment.setText(GlobalUtils.formatnumber(obj.gettotal_payment_real()));
            jtxttotal_entry.setText(GlobalUtils.formatnumber(obj.gettotal_entry_real()));
        }
}//GEN-LAST:event_btnUndoActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        try {
            objd1.delete();
            obj.settotal_payment(obj.gettotal_payment()-objd1.getpayment_total());
            obj.settotal_entry(obj.gettotal_entry()-1);
            if (!objd1.moveNext()){
                objd1.movePrevious();
            };
            obj.update();
            jtxttotal_payment.setText(GlobalUtils.formatnumber(obj.gettotal_payment()));
            jtxttotal_entry.setText(GlobalUtils.formatnumber(obj.gettotal_entry()));
            showdatadetail1();
        } catch (CodeException ex) {
            Logger.getLogger(Frmap_payment.class.getName()).log(Level.SEVERE, null, ex);
        }

}//GEN-LAST:event_btnDelActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        try {
            objd1.moveFirst();
            showdatadetail1();

            jtxttotal_payment.setText(GlobalUtils.formatnumber(obj.gettotal_payment_real()));
            jtxttotal_entry.setText(GlobalUtils.formatnumber(obj.gettotal_entry_real()));
        } catch (CodeException ex) {
            Logger.getLogger(Frmap_payment.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        try {
            objd1.movePrevious();
            showdatadetail1();

            jtxttotal_payment.setText(GlobalUtils.formatnumber(obj.gettotal_payment_real()));
            jtxttotal_entry.setText(GlobalUtils.formatnumber(obj.gettotal_entry_real()));
        } catch (CodeException ex) {
            Logger.getLogger(Frmap_payment.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try {
            objd1.moveNext();
            showdatadetail1();

            jtxttotal_payment.setText(GlobalUtils.formatnumber(obj.gettotal_payment_real()));
            jtxttotal_entry.setText(GlobalUtils.formatnumber(obj.gettotal_entry_real()));
        } catch (CodeException ex) {
            Logger.getLogger(Frmap_payment.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try {
            obj.refresh();
            showData();
            objd1.moveLast();
            showdatadetail1();

            jtxttotal_payment.setText(GlobalUtils.formatnumber(obj.gettotal_payment_real()));
            jtxttotal_entry.setText(GlobalUtils.formatnumber(obj.gettotal_entry_real()));
        } catch (CodeException ex) {
            Logger.getLogger(Frmap_payment.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_btnLastActionPerformed

    private void jbtnBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse1ActionPerformed
        // TODO add your handling code here:
          obrowse.showbrowser(obrowse.ap_supplier, "", jtxtsupplier_code,jtxtsupplier_code_desc);
          objd1.setsupplier_code(jtxtsupplier_code.getText());

          showdatadetail2();
          showdatadetail3();
    }//GEN-LAST:event_jbtnBrowse1ActionPerformed

    private void jtxtdocentryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdocentryFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtdocentryFocusGained

    private void jtxtsupplier_codeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsupplier_codeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsupplier_codeFocusGained

    private void jtxtpayment_ammountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtpayment_ammountFocusGained
        // TODO add your handling code here:
          jtxtpayment_ammount.setSelectionStart(0);
          jtxtpayment_ammount.setSelectionEnd(jtxtpayment_ammount.getText().length());
    }//GEN-LAST:event_jtxtpayment_ammountFocusGained

    private void jtxtpayment_totalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtpayment_totalFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpayment_totalFocusGained

    private void jtxtpayment_balanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtpayment_balanceFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpayment_balanceFocusGained

    private void jbtnBrowse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jbtnBrowse2ActionPerformed

    private void jtxtsupplier_code_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsupplier_code_descFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsupplier_code_descFocusGained

    private void jtxtsupplier_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsupplier_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsupplier_codeActionPerformed

    private void jtbldetail_invoiceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtbldetail_invoiceFocusGained
        // TODO add your handling code here:
        if (jtbldetail_invoice.getRowCount()==0){
            insertnewlastrow();
        }
}//GEN-LAST:event_jtbldetail_invoiceFocusGained

    private boolean lastrowisempty() {
        if (model_invoice.getRowCount()>0){
            if (GlobalUtils.churuf(model_invoice.getValueAt(model_invoice.getRowCount()-1, 1)).equalsIgnoreCase("")){
                return true;
            }
        }
        return false;
    }

    private void insertnewlastrow() {
        if (!lastrowisempty()){
        model_invoice.addRow(new Object[model_invoice.getColumnCount()]);
        model_invoice.setValueAt(model_invoice.getRowCount(), model_invoice.getRowCount()-1, 0);
        model_invoice.setValueAt(0, model_invoice.getRowCount()-1, 3);
        model_invoice.setValueAt(0, model_invoice.getRowCount()-1, 4);

        GlobalUtils.selectCellTable(jtbldetail_invoice, model_invoice.getRowCount()-1, 1);
        } else {
            GlobalUtils.selectCellTable(jtbldetail_invoice, model_invoice.getRowCount()-1, 1);
        }
    }

    private void cekdetail_invoice() {
        int row = jtbldetail_invoice.getSelectedRow();
        int col = jtbldetail_invoice.getSelectedColumn();


        ap_payment_detail2ext appod=new ap_payment_detail2ext();
        if (row > objd2s.size() - 1) {
            appod = new ap_payment_detail2ext();
            appod.setstatus(ap_payment_detail2ext.Status_Insert);
            objd2s.add(appod);
        } else {
            appod = (ap_payment_detail2ext) objd2s.get(row);
            if (!appod.getstatus().equals(ap_payment_detail2ext.Status_Insert)&&!appod.getstatus().equals(ap_payment_detail2ext.Status_delete)){
                appod.setstatus(ap_payment_detail2ext.Status_update);
            }
        }
        
        appod.setjumlah_bayar(new Double(0));
        appod.setpayment_type(GlobalUtils.churuf(jcmbpayment_type.getSelectedIndex()+1));
        
        objd1.calculatetotal();
        
        appod.setpilih(Boolean.parseBoolean(GlobalUtils.churuf(model_invoice.getValueAt(row, 0))));
        if (appod.getpilih()){
            appod.setjumlah_bayar(appod.getsisaFaktur());
            if (GlobalUtils.toDbl(GlobalUtils.churuf(model_invoice.getValueAt(row, 7)))>0){
                appod.setjumlah_bayar(GlobalUtils.toDbl(GlobalUtils.churuf(model_invoice.getValueAt(row, 7))));
            }
        } 
        if (objd1.getpayment_balance()<appod.getjumlah_bayar()){
            appod.setjumlah_bayar(objd1.getpayment_balance());
        } 

        objd2s.set(row, appod);

        objd1.calculatetotal();
        obj=objd1.getObj();
        model_invoice.setValueAt(appod.getpilih(), row, 0);
        model_invoice.setValueAt(appod.getjumlah_bayar(), row, 7);
        model_invoice.setValueAt(appod.getnilaiAkhirFaktur(), row, 8);

        jtxttotal_entry.setText(GlobalUtils.formatnumber(obj.gettotal_entry()));
        jtxttotal_payment.setText(GlobalUtils.formatnumber(obj.gettotal_payment()));
        jtxttotal_entry.setText(GlobalUtils.formatnumber(obj.gettotal_entry()));
    }

    private void cekdetail_dnote() {
        int row = jtbldetail1_dnote.getSelectedRow();
        int col = jtbldetail1_dnote.getSelectedColumn();


        ap_payment_detail3ext appod=new ap_payment_detail3ext();
        if (row > objd3s.size() - 1) {
            appod = new ap_payment_detail3ext();
            appod.setstatus(ap_payment_detail3ext.Status_Insert);
            objd3s.add(appod);
        } else {
            appod = (ap_payment_detail3ext) objd3s.get(row);
            if (!appod.getstatus().equals(ap_payment_detail3ext.Status_Insert)&&!appod.getstatus().equals(ap_payment_detail3ext.Status_delete)){
                appod.setstatus(ap_payment_detail3ext.Status_update);
            }
        }

        appod.setjumlah_bayar(new Double(0));
        objd1.setpayment_type(GlobalUtils.churuf(jcmbpayment_type.getSelectedIndex()+1));
        appod.setpayment_type(objd1.getpayment_type());
        objd1.calculatetotal();

        appod.setpilih(Boolean.parseBoolean(GlobalUtils.churuf(model_dnote.getValueAt(row, 0))));
        if (appod.getpilih()){
            appod.setjumlah_bayar(appod.getsisaFaktur());
            if (GlobalUtils.toDbl(GlobalUtils.churuf(model_dnote.getValueAt(row, 7)))>0){
                appod.setjumlah_bayar(GlobalUtils.toDbl(GlobalUtils.churuf(model_dnote.getValueAt(row, 7))));
            }
        } 
        
        objd3s.set(row, appod);

        objd1.calculatetotal();
        obj=objd1.getObj();
        model_dnote.setValueAt(appod.getpilih(), row, 0);
        model_dnote.setValueAt(appod.getjumlah_bayar(), row, 7);
        model_dnote.setValueAt(appod.getnilaiAkhirFaktur(), row, 8);

        jtxtpayment_ammount.setText(GlobalUtils.formatnumber(objd1.getpayment_ammount()));
        jtxttotal_entry.setText(GlobalUtils.formatnumber(obj.gettotal_entry()));
        jtxttotal_payment.setText(GlobalUtils.formatnumber(obj.gettotal_payment()));
    }

    private void jtbldetail_invoicePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtbldetail_invoicePropertyChange
        // TODO add your handling code here:
        int irow=jtbldetail_invoice.getSelectedRow();
        int icol=jtbldetail_invoice.getSelectedColumn();

        if (irow>-1){
            cekdetail_invoice();

            objd1.calculatetotal();
            jtxtpayment_total.setText(GlobalUtils.formatnumber(objd1.getpayment_total()));
            jtxtpayment_balance.setText(GlobalUtils.formatnumber(objd1.getpayment_balance()));
//            jtxttotal_entry.setText(GlobalUtils.formatnumber(obj.getrab_entry()));
//            jtxttotal_payment.setText(GlobalUtils.formatnumber(obj.getrab_amount()));
        }
}//GEN-LAST:event_jtbldetail_invoicePropertyChange

    private void jtbldetail_invoiceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbldetail_invoiceKeyPressed
        // TODO add your handling code here:
//        int col=jtbldetail.getSelectedColumn();
//        int row=jtbldetail.getSelectedRow();
//        switch (evt.getKeyCode()){
//            case KeyEvent.VK_F5:
//                evt.consume();
//                switch (jtbldetail.getSelectedColumn()){
//                    case 1:
//                        obrowse.showbrowser(obrowse.gl_rab, "", jtbldetail);
//                        showfaktur((Integer)jtbldetail.getSelectedRow());
//                        jtbldetailPropertyChange(null);
//                        GlobalUtils.selectCellTable(jtbldetail, row, 3);
//                        break;
//                }
//                break;
//            case KeyEvent.VK_INSERT:
//                evt.consume();
//                insertnewlastrow();
//                break;
//            case KeyEvent.VK_DELETE:
//                evt.consume();
//                if (jtbldetail.getSelectedRow()<appods.size()){
//                    ap_payment_detail2ext o = appods.get(jtbldetail.getSelectedRow());
//                    o.setstatus(ap_payment_detail2ext.Status_delete);
//                }
//                jtbldetailPropertyChange(null);
//                break;
//            case KeyEvent.VK_ENTER:
//                evt.consume();
//                break;
//        }
}//GEN-LAST:event_jtbldetail_invoiceKeyPressed

    private void jtbldetail_invoiceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbldetail_invoiceKeyReleased
        int col=jtbldetail_invoice.getSelectedColumn();
        int row=jtbldetail_invoice.getSelectedRow();
        // TODO add your handling code here:
        if (evt.getKeyCode()==evt.VK_ENTER&&row>-1){
            switch (col){
                case 8:
                    
                    break;
            }
        }
}//GEN-LAST:event_jtbldetail_invoiceKeyReleased

    private void jtbldetail1_dnoteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtbldetail1_dnoteFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbldetail1_dnoteFocusGained

    private void jtbldetail1_dnotePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtbldetail1_dnotePropertyChange
        // TODO add your handling code here:
        int irow=jtbldetail1_dnote.getSelectedRow();
        int icol=jtbldetail1_dnote.getSelectedColumn();

        if (irow>-1){
            cekdetail_dnote();

            objd1.calculatetotal();
            jtxtpayment_total.setText(GlobalUtils.formatnumber(objd1.getpayment_total()));
            jtxtpayment_balance.setText(GlobalUtils.formatnumber(objd1.getpayment_balance()));
        }
    }//GEN-LAST:event_jtbldetail1_dnotePropertyChange

    private void jtbldetail1_dnoteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbldetail1_dnoteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbldetail1_dnoteKeyPressed

    private void jtbldetail1_dnoteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbldetail1_dnoteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbldetail1_dnoteKeyReleased

    private void jtxtsupplier_code_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsupplier_code_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsupplier_code_descActionPerformed

    private void jtxtdocentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtdocentryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtdocentryActionPerformed

    private void jcmbyopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbyopItemStateChanged
        // TODO add your handling code here:
        showbulan();
}//GEN-LAST:event_jcmbyopItemStateChanged

    private void jtxtpayment_ammountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpayment_ammountKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpayment_ammountKeyPressed

    private void jtxtpayment_ammountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpayment_ammountKeyReleased
        // TODO add your handling code here:
        GlobalUtils.domasking(jtxtpayment_ammount);

        objd1.setpayment_ammount(GlobalUtils.toDbl(jtxtpayment_ammount.getText()));
        jtxtpayment_balance.setText(GlobalUtils.formatnumber(objd1.getpayment_balance()));
    }//GEN-LAST:event_jtxtpayment_ammountKeyReleased

    private void jcmbpayment_typeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbpayment_typeItemStateChanged
        // TODO add your handling code here:
        objd1.setpayment_type(GlobalUtils.churuf(jcmbpayment_type.getSelectedIndex()+1));
        if (jcmbpayment_type.getSelectedIndex()==2){
            jTabbedPane1.setEnabledAt(1, true);
        } else {
            jTabbedPane1.setEnabledAt(1, false);
        }
    }//GEN-LAST:event_jcmbpayment_typeItemStateChanged

private void jtxtdocument_numberFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtdocument_number.setSelectionStart(0);
    jtxtdocument_number.setSelectionEnd(jtxtdocument_number.getText().length());
}                                               

private void jtxtdocument_statusFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtdocument_status.setSelectionStart(0);
    jtxtdocument_status.setSelectionEnd(jtxtdocument_status.getText().length());
}                                               
                                           

private void jtxtreferenceFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    jtxtreference.setSelectionStart(0);
    jtxtreference.setSelectionEnd(jtxtreference.getText().length());
}                                         

private void jtxtdscriptionFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
    jtxtdscription.setSelectionStart(0);
    jtxtdscription.setSelectionEnd(jtxtdscription.getText().length());
}                                          

private void jtxttotal_entryFocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    jtxttotal_entry.setSelectionStart(0);
    jtxttotal_entry.setSelectionEnd(jtxttotal_entry.getText().length());
}                                           

private void jtxttotal_paymentFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxttotal_payment.setSelectionStart(0);
    jtxttotal_payment.setSelectionEnd(jtxttotal_payment.getText().length());
}                                             


private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
    browsecontroller ob=new browsecontroller();
    ob.showbrowser(ob.ap_payment, "", jtxtdocument_number);
    try {
        if (!jtxtdocument_number.getText().equalsIgnoreCase("")){
            obj.initdata(jtxtdocument_number.getText());
            showData();
        }
    } catch (CodeException ex) {
        Logger.getLogger(Frmap_payment.class.getName()).log(Level.SEVERE, null, ex);
    }
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmap_payment().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    public javax.swing.JButton btnDel;
    public javax.swing.JButton btnFirst;
    public javax.swing.JButton btnLast;
    public javax.swing.JButton btnNew;
    public javax.swing.JButton btnNext;
    public javax.swing.JButton btnPrev;
    public javax.swing.JButton btnSave;
    public javax.swing.JButton btnUndo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jHeader;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowse1;
    private javax.swing.JButton jbtnBrowse2;
    private javax.swing.JComboBox jcmbmop;
    private javax.swing.JComboBox jcmbpayment_type;
    private javax.swing.JComboBox jcmbyop;
    private javax.swing.JLabel jlbldocdate;
    private javax.swing.JLabel jlbldocentry;
    private javax.swing.JLabel jlbldocument_date;
    private javax.swing.JLabel jlbldocument_number;
    private javax.swing.JLabel jlbldocument_status;
    private javax.swing.JLabel jlbldscription;
    private javax.swing.JLabel jlblmop;
    private javax.swing.JLabel jlblpayment_ammount;
    private javax.swing.JLabel jlblpayment_balance;
    private javax.swing.JLabel jlblpayment_total;
    private javax.swing.JLabel jlblpayment_type;
    private javax.swing.JLabel jlblreference;
    private javax.swing.JLabel jlblsupplier_code;
    private javax.swing.JLabel jlbltotal_entry;
    private javax.swing.JLabel jlbltotal_payment;
    private javax.swing.JLabel jlblyop;
    private javax.swing.JRadioButton jopt_complete_status_complete;
    private javax.swing.JRadioButton jopt_complete_status_draff;
    private javax.swing.JTable jtbldetail1_dnote;
    private javax.swing.JTable jtbldetail_invoice;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtdocentry;
    private javax.swing.JTextField jtxtdocument_number;
    private javax.swing.JTextField jtxtdocument_status;
    private javax.swing.JTextField jtxtdscription;
    private javax.swing.JTextField jtxtpayment_ammount;
    private javax.swing.JTextField jtxtpayment_balance;
    private javax.swing.JTextField jtxtpayment_total;
    private javax.swing.JTextField jtxtreference;
    private javax.swing.JTextField jtxtsupplier_code;
    private javax.swing.JTextField jtxtsupplier_code_desc;
    private javax.swing.JTextField jtxttotal_entry;
    private javax.swing.JTextField jtxttotal_payment;
    private org.kazao.calendar.KazaoCalendarDate kzodocdate;
    private org.kazao.calendar.KazaoCalendarDate kzodocument_date;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        objd1=obj.getObjd1();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();
        objd1=obj.getObjd1();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();
        objd1=obj.getObjd1();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();
        objd1=obj.getObjd1();
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jtxtdocument_number.setText("");
        jtxtdocument_status.setText("");
        try {
            kzodocument_date.setDate(GlobalUtils.sessiondate);
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmap_payment.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtxtreference.setText("");
        jtxtdscription.setText("");
        jtxttotal_entry.setText("");
        jtxttotal_payment.setText("");
        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");
    }

    public void newData() throws CodeException {
        istatus=1;
        objtmp=obj;
        obj=new ap_paymentext();
        obj.setdocument_date(GlobalUtils.sessiondate);

        objd1=new ap_payment_detail1ext(obj);
        objd1.setdocdate(GlobalUtils.sessiondate);
        objd1.setmop(GlobalUtils.getMonth(GlobalUtils.sessiondate));
        showData();
        
        setToolBar(iformtype,istatus);

        jTabbedPane1.setEnabledAt(1, false);
    }

    public void newDataDetail1(){
        objd1tmp=objd1;
        objd1=new ap_payment_detail1ext(obj);
        objd1.setdocdate(GlobalUtils.getCurrentDate());
        objd1.setyop(GlobalUtils.toInt(GlobalUtils.getYear(GlobalUtils.sessiondate)));
        objd1.setmop(GlobalUtils.toInt(GlobalUtils.getMonth(GlobalUtils.sessiondate)));
        objd1.setpayment_type("1");
        showdatadetail1();


    }

    private void showdatadetail1(){
        jtxtdocentry.setText(GlobalUtils.churuf(objd1.getdocentry()));
        try {
            kzodocdate.setDate(GlobalUtils.formatDate(objd1.getdocdate(),"MM/dd/yyyy"));
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmap_payment.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtxtsupplier_code.setText(objd1.getsupplier_code());
        jtxtsupplier_code_desc.setText(objd1.getsupplier_code_desc());
        jcmbyop.setSelectedItem(objd1.getyop());
        System.out.println(jcmbmop.getItemCount());
        if (jcmbmop.getItemCount()>0){
        jcmbmop.setSelectedIndex(objd1.getmop()-1);
        }
        jcmbpayment_type.setSelectedIndex(GlobalUtils.CNomorInt(objd1.getpayment_type())-1);
        jtxtpayment_ammount.setText(GlobalUtils.formatnumber(objd1.getpayment_ammount()));
        jtxtpayment_total.setText(GlobalUtils.formatnumber(objd1.getpayment_total()));
        jtxtpayment_balance.setText(GlobalUtils.formatnumber(objd1.getpayment_balance()));

        obj=objd1.getObj();
        
        jtxttotal_payment.setText(GlobalUtils.formatnumber(obj.gettotal_payment()));
        jtxttotal_entry.setText(GlobalUtils.formatnumber(obj.gettotal_entry()));
        showdatadetail2();

        showdatadetail3();

        setToolBardetail1();
    }

    private void showdatadetail2(){
        objd2s=objd1.getObjd2s();
        GlobalModel.clearRow(model_invoice);
        for (int i=0;i<objd2s.size();i++){
            objd2=objd2s.get(i);
            model_invoice.addRow(new Object[model_invoice.getColumnCount()]);
            model_invoice.setValueAt(objd2.getpilih(), i, 0);
            model_invoice.setValueAt(objd2.getdocument_number(), i, 1);
            model_invoice.setValueAt(objd2.getdocument_date(), i, 2);
            model_invoice.setValueAt(objd2.getdocument_duedate(), i, 3);
            model_invoice.setValueAt(objd2.gettotal_aft_tax(), i, 4);
            model_invoice.setValueAt(objd2.gettotalBayar(), i, 5);
            model_invoice.setValueAt(objd2.getsisaFaktur(), i, 6);
            model_invoice.setValueAt(objd2.getjumlah_bayar(), i, 7);
            model_invoice.setValueAt(objd2.getnilaiAkhirFaktur(), i, 8);
        }
    }
    private void showdatadetail3() {
        objd3s=objd1.getObjd3s();
        GlobalModel.clearRow(model_dnote);
        for (int i=0;i<objd3s.size();i++){
            objd3=objd3s.get(i);
            model_dnote.addRow(new Object[model_dnote.getColumnCount()]);
            model_dnote.setValueAt(objd3.getpilih(), i, 0);
            model_dnote.setValueAt(objd3.getdocument_number(), i, 1);
            model_dnote.setValueAt(objd3.getdocument_date(), i, 2);
            model_dnote.setValueAt(objd3.getdocument_duedate(), i, 3);
            model_dnote.setValueAt(objd3.gettotal_aft_tax(), i, 4);
            model_dnote.setValueAt(objd3.gettotalBayar(), i, 5);
            model_dnote.setValueAt(objd3.getsisaFaktur(), i, 6);
            model_dnote.setValueAt(objd3.getjumlah_bayar(), i, 7);
            model_dnote.setValueAt(objd3.getnilaiAkhirFaktur(), i, 8);
        }
    }
    private void savedetail1() throws CodeException{
        objd1.setbatchentry(obj.getbatchentry());
        objd1.setpayment_type(GlobalUtils.churuf(jcmbpayment_type.getSelectedIndex()+1));
        objd1.setpayment_ammount(GlobalUtils.toDbl(jtxtpayment_ammount.getText()));
        objd1.setyop(GlobalUtils.toInt(jcmbyop.getSelectedItem()));
        objd1.setmop(jcmbmop.getSelectedIndex()+1);

        objd1.update();
    }
    public void saveData() throws CodeException {
        setData();
        obj.update();

        savedetail1();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        jtxtdocument_number.setText(obj.getdocument_number());
        jtxtdocument_status.setText(obj.getdocument_status());

        if (obj.getcomplete_status().equalsIgnoreCase("Y")){
        jopt_complete_status_complete.setSelected(true);
        } else {
        jopt_complete_status_draff.setSelected(true);
        }
        
        try {
            kzodocument_date.setDate(GlobalUtils.formatDate(obj.getdocument_date(),"MM/dd/yyyy"));
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmap_payment.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtxtreference.setText(obj.getreference());
        jtxtdscription.setText(obj.getdscription());
        jtxttotal_entry.setText(GlobalUtils.formatnumber(obj.gettotal_entry()));
        jtxttotal_payment.setText(GlobalUtils.formatnumber(obj.gettotal_payment()));
        jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getentrydate()));
        jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getauditdate()));
        jtxtUserID.setText(obj.getaudituser());


        showdatadetail1();

        jtxttotal_payment.setText(GlobalUtils.formatnumber(obj.gettotal_payment_real()));
        jtxttotal_entry.setText(GlobalUtils.formatnumber(obj.gettotal_entry_real()));
        
        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        if (obj.delete()){
            obj.moveNext();
            showData();
        }
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);

        if (istatus==1){
            jbtnBrowse.setEnabled(false);
        } else {
            jbtnBrowse.setEnabled(true);
        }
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }
        obj.setdocument_date(kzodocument_date.getDate());
        obj.setreference(jtxtreference.getText());
        obj.setdscription(jtxtdscription.getText());
        if (jopt_complete_status_complete.isSelected()){
            obj.setcomplete_status("Y");
        } else {
            obj.setcomplete_status("N");
        }

    }

    public void undo() throws CodeException {
        istatus = 0;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    private void setToolBardetail1() {
        btnNew.setEnabled(true);
        btnSave.setEnabled(true);
        btnUndo.setEnabled(false);
        btnDel.setEnabled(true);

        btnFirst.setEnabled(true);
        btnPrev.setEnabled(true);
        btnNext.setEnabled(true);
        btnLast.setEnabled(true);

        if (objd1.insertsts){
            btnNew.setEnabled(false);
            btnUndo.setEnabled(true);
            btnDel.setEnabled(false);
            btnFirst.setEnabled(false);
            btnPrev.setEnabled(false);
            btnNext.setEnabled(false);
            btnLast.setEnabled(false);
        }
    }

    

}
