/*
 * From ap_option
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ap.component;


import classinterface.NavigatorFormInt;
import common.component.FrmMainFrame;
import java.util.HashMap;
import java.util.Map;
import kopkar.ap.objectclasses.ap_optionext;
import kopkar.utils.browsecontroller;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import utils.CodeException;
import utils.GlobalUtils;
import utils.appsettinghandler;

/**
 *
 * @author  Generator
 */

public class Frmap_option extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmap_option";
    
    public FrmMainFrame mf ;

    public ap_optionext obj=new ap_optionext();
    public browsecontroller obrowse=new browsecontroller();
    private JasperReport jasperReport;
    private JasperPrint jasperPrint;
   
    /** Creates new form Area */
    public Frmap_option() throws CodeException {
        initComponents();
    }
    
    public Frmap_option(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
    public void doinitcomponen(){
        initComponents();
    }

    public void setJudul(String judul){
        this.setTitle(judul);
        jHeader.setText(" : : "+judul);
    }
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jlblcompany_id = new javax.swing.JLabel();
        jtxtcompany_id = new javax.swing.JTextField();
        jlblcompany_name = new javax.swing.JLabel();
        jtxtcompany_name = new javax.swing.JTextField();
        jlblactive_sts = new javax.swing.JLabel();
        jtxtactive_sts = new javax.swing.JTextField();
        jlbladdress1 = new javax.swing.JLabel();
        jtxtaddress1 = new javax.swing.JTextField();
        jtxtaddress2 = new javax.swing.JTextField();
        jlblcity = new javax.swing.JLabel();
        jtxtcity = new javax.swing.JTextField();
        jlblstate = new javax.swing.JLabel();
        jtxtstate = new javax.swing.JTextField();
        jlblzipcode = new javax.swing.JLabel();
        jtxtzipcode = new javax.swing.JTextField();
        jlblphone = new javax.swing.JLabel();
        jtxtphone = new javax.swing.JTextField();
        jlblfaximale = new javax.swing.JLabel();
        jtxtfaximale = new javax.swing.JTextField();
        jlblemail = new javax.swing.JLabel();
        jtxtemail = new javax.swing.JTextField();
        jlblpic = new javax.swing.JLabel();
        jtxtpic = new javax.swing.JTextField();
        jlblregister_date = new javax.swing.JLabel();
        jtxtregister_date = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jlblterm_code = new javax.swing.JLabel();
        jtxtterm_code = new javax.swing.JTextField();
        jlblsalesman_code = new javax.swing.JLabel();
        jtxtsalesman_code = new javax.swing.JTextField();
        jlblcost_price_code = new javax.swing.JLabel();
        jtxtcost_price_code = new javax.swing.JTextField();
        jlblsales_price_code = new javax.swing.JLabel();
        jtxtsales_price_code = new javax.swing.JTextField();
        jlbldiscount_code = new javax.swing.JLabel();
        jtxtdiscount_code = new javax.swing.JTextField();
        jlblwarehouse_code = new javax.swing.JLabel();
        jtxtwarehouse_code = new javax.swing.JTextField();
        jlblcounter_number = new javax.swing.JLabel();
        jtxtcounter_number = new javax.swing.JTextField();
        jlbltextnotapos = new javax.swing.JLabel();
        jtxttextnotapos = new javax.swing.JTextField();
        jlblaccset_code = new javax.swing.JLabel();
        jlblcash_account = new javax.swing.JLabel();
        jlbltrns_account = new javax.swing.JLabel();
        jlblcrdt_account = new javax.swing.JLabel();
        jtxtcrdt_account = new javax.swing.JTextField();
        jtxttrns_account = new javax.swing.JTextField();
        jtxtcash_account = new javax.swing.JTextField();
        jtxtaccset_code = new javax.swing.JTextField();
        jbtnBrowse = new javax.swing.JButton();
        jtxtterm_code_desc = new javax.swing.JTextField();
        jtxtsalesman_code_desc = new javax.swing.JTextField();
        jtxtcost_price_code_desc = new javax.swing.JTextField();
        jtxtsales_price_code_desc = new javax.swing.JTextField();
        jtxtdiscount_code_desc = new javax.swing.JTextField();
        jtxtwarehouse_code_desc = new javax.swing.JTextField();
        jtxtcrdt_account_desc = new javax.swing.JTextField();
        jtxttrns_account_desc = new javax.swing.JTextField();
        jtxtcash_account_desc = new javax.swing.JTextField();
        jtxtaccset_code_desc = new javax.swing.JTextField();
        jbtnBrowse1 = new javax.swing.JButton();
        jbtnBrowse2 = new javax.swing.JButton();
        jbtnBrowse3 = new javax.swing.JButton();
        jbtnBrowse6 = new javax.swing.JButton();
        jbtnBrowse7 = new javax.swing.JButton();
        jbtnBrowse8 = new javax.swing.JButton();
        jbtnBrowse9 = new javax.swing.JButton();
        jbtnBrowse10 = new javax.swing.JButton();
        jbtnBrowse11 = new javax.swing.JButton();
        jlbltrns_account1 = new javax.swing.JLabel();
        jlblcrdt_account1 = new javax.swing.JLabel();
        jtxtppn_account = new javax.swing.JTextField();
        jtxttemp_account = new javax.swing.JTextField();
        jbtnBrowse12 = new javax.swing.JButton();
        jbtnBrowse13 = new javax.swing.JButton();
        jtxtppn_account_desc = new javax.swing.JTextField();
        jtxttemp_account_desc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AP Option");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : AP Option");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 200, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(360, 30, 170, 20);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(530, 30, 130, 20);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(660, 30, 140, 20);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 0, 10));

        jPanel1.setLayout(null);

        jlblcompany_id.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcompany_id.setText("Kode Instansi");
        jPanel1.add(jlblcompany_id);
        jlblcompany_id.setBounds(20, 10, 140, 13);

        jtxtcompany_id.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcompany_id.setText("company_id");
        jtxtcompany_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcompany_idFocusGained(evt);
            }
        });
        jPanel1.add(jtxtcompany_id);
        jtxtcompany_id.setBounds(210, 10, 150, 23);

        jlblcompany_name.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcompany_name.setText("Nama");
        jPanel1.add(jlblcompany_name);
        jlblcompany_name.setBounds(20, 30, 140, 13);

        jtxtcompany_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcompany_name.setText("company_name");
        jtxtcompany_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcompany_nameFocusGained(evt);
            }
        });
        jPanel1.add(jtxtcompany_name);
        jtxtcompany_name.setBounds(210, 30, 360, 23);

        jlblactive_sts.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblactive_sts.setText("active_sts");
        jPanel1.add(jlblactive_sts);
        jlblactive_sts.setBounds(20, 50, 140, 13);

        jtxtactive_sts.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtactive_sts.setText("active_sts");
        jtxtactive_sts.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtactive_stsFocusGained(evt);
            }
        });
        jPanel1.add(jtxtactive_sts);
        jtxtactive_sts.setBounds(210, 50, 150, 23);

        jlbladdress1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbladdress1.setText("Alamat");
        jPanel1.add(jlbladdress1);
        jlbladdress1.setBounds(20, 70, 140, 13);

        jtxtaddress1.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaddress1.setText("address1");
        jtxtaddress1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtaddress1FocusGained(evt);
            }
        });
        jPanel1.add(jtxtaddress1);
        jtxtaddress1.setBounds(210, 70, 360, 23);

        jtxtaddress2.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaddress2.setText("address2");
        jtxtaddress2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtaddress2FocusGained(evt);
            }
        });
        jPanel1.add(jtxtaddress2);
        jtxtaddress2.setBounds(210, 90, 360, 23);

        jlblcity.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcity.setText("city");
        jPanel1.add(jlblcity);
        jlblcity.setBounds(20, 110, 140, 13);

        jtxtcity.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcity.setText("city");
        jtxtcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcityFocusGained(evt);
            }
        });
        jPanel1.add(jtxtcity);
        jtxtcity.setBounds(210, 110, 360, 23);

        jlblstate.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblstate.setText("Propinsi");
        jPanel1.add(jlblstate);
        jlblstate.setBounds(20, 130, 140, 13);

        jtxtstate.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtstate.setText("state");
        jtxtstate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtstateFocusGained(evt);
            }
        });
        jPanel1.add(jtxtstate);
        jtxtstate.setBounds(210, 130, 360, 23);

        jlblzipcode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblzipcode.setText("zipcode");
        jPanel1.add(jlblzipcode);
        jlblzipcode.setBounds(20, 150, 140, 13);

        jtxtzipcode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtzipcode.setText("zipcode");
        jtxtzipcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtzipcodeFocusGained(evt);
            }
        });
        jPanel1.add(jtxtzipcode);
        jtxtzipcode.setBounds(210, 150, 150, 23);

        jlblphone.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblphone.setText("phone");
        jPanel1.add(jlblphone);
        jlblphone.setBounds(20, 170, 140, 13);

        jtxtphone.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtphone.setText("phone");
        jtxtphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtphoneFocusGained(evt);
            }
        });
        jPanel1.add(jtxtphone);
        jtxtphone.setBounds(210, 170, 150, 23);

        jlblfaximale.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblfaximale.setText("faximale");
        jPanel1.add(jlblfaximale);
        jlblfaximale.setBounds(20, 190, 140, 13);

        jtxtfaximale.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtfaximale.setText("faximale");
        jtxtfaximale.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtfaximaleFocusGained(evt);
            }
        });
        jPanel1.add(jtxtfaximale);
        jtxtfaximale.setBounds(210, 190, 360, 23);

        jlblemail.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblemail.setText("email");
        jPanel1.add(jlblemail);
        jlblemail.setBounds(20, 210, 140, 13);

        jtxtemail.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtemail.setText("email");
        jtxtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtemailFocusGained(evt);
            }
        });
        jPanel1.add(jtxtemail);
        jtxtemail.setBounds(210, 210, 360, 23);

        jlblpic.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblpic.setText("pic");
        jPanel1.add(jlblpic);
        jlblpic.setBounds(20, 230, 140, 13);

        jtxtpic.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtpic.setText("pic");
        jtxtpic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtpicFocusGained(evt);
            }
        });
        jPanel1.add(jtxtpic);
        jtxtpic.setBounds(210, 230, 360, 23);

        jlblregister_date.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblregister_date.setText("Register Date");
        jPanel1.add(jlblregister_date);
        jlblregister_date.setBounds(20, 250, 140, 13);

        jtxtregister_date.setEditable(false);
        jtxtregister_date.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtregister_date.setText("register_date");
        jtxtregister_date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtregister_dateFocusGained(evt);
            }
        });
        jPanel1.add(jtxtregister_date);
        jtxtregister_date.setBounds(210, 250, 150, 23);

        jTabbedPane1.addTab("Informasi Instansi", jPanel1);

        jPanel2.setLayout(null);

        jlblterm_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblterm_code.setText("Term Code");
        jPanel2.add(jlblterm_code);
        jlblterm_code.setBounds(20, 10, 140, 13);

        jtxtterm_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtterm_code.setText("term_code");
        jtxtterm_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtterm_codeFocusGained(evt);
            }
        });
        jPanel2.add(jtxtterm_code);
        jtxtterm_code.setBounds(210, 10, 150, 23);

        jlblsalesman_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsalesman_code.setText("Salesman Code");
        jPanel2.add(jlblsalesman_code);
        jlblsalesman_code.setBounds(20, 30, 140, 13);

        jtxtsalesman_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsalesman_code.setText("salesman_code");
        jtxtsalesman_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsalesman_codeFocusGained(evt);
            }
        });
        jPanel2.add(jtxtsalesman_code);
        jtxtsalesman_code.setBounds(210, 30, 150, 23);

        jlblcost_price_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcost_price_code.setText("Cost Price Code");
        jPanel2.add(jlblcost_price_code);
        jlblcost_price_code.setBounds(20, 50, 140, 13);

        jtxtcost_price_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcost_price_code.setText("cost_price_code");
        jtxtcost_price_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcost_price_codeFocusGained(evt);
            }
        });
        jPanel2.add(jtxtcost_price_code);
        jtxtcost_price_code.setBounds(210, 50, 150, 23);

        jlblsales_price_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsales_price_code.setText("Sales Price Code");
        jPanel2.add(jlblsales_price_code);
        jlblsales_price_code.setBounds(20, 70, 140, 13);

        jtxtsales_price_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsales_price_code.setText("sales_price_code");
        jtxtsales_price_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsales_price_codeFocusGained(evt);
            }
        });
        jPanel2.add(jtxtsales_price_code);
        jtxtsales_price_code.setBounds(210, 70, 150, 23);

        jlbldiscount_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldiscount_code.setText("Discount Code");
        jPanel2.add(jlbldiscount_code);
        jlbldiscount_code.setBounds(20, 90, 140, 13);

        jtxtdiscount_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdiscount_code.setText("discount_code");
        jtxtdiscount_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdiscount_codeFocusGained(evt);
            }
        });
        jPanel2.add(jtxtdiscount_code);
        jtxtdiscount_code.setBounds(210, 90, 150, 23);

        jlblwarehouse_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblwarehouse_code.setText("Warehouse Code");
        jPanel2.add(jlblwarehouse_code);
        jlblwarehouse_code.setBounds(20, 110, 140, 13);

        jtxtwarehouse_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtwarehouse_code.setText("warehouse_code");
        jtxtwarehouse_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtwarehouse_codeFocusGained(evt);
            }
        });
        jPanel2.add(jtxtwarehouse_code);
        jtxtwarehouse_code.setBounds(210, 110, 150, 23);

        jlblcounter_number.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcounter_number.setText("Counter Number");
        jPanel2.add(jlblcounter_number);
        jlblcounter_number.setBounds(20, 130, 140, 13);

        jtxtcounter_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcounter_number.setText("counter_number");
        jtxtcounter_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcounter_numberFocusGained(evt);
            }
        });
        jPanel2.add(jtxtcounter_number);
        jtxtcounter_number.setBounds(210, 130, 150, 23);

        jlbltextnotapos.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltextnotapos.setText("Text Nota Pos");
        jPanel2.add(jlbltextnotapos);
        jlbltextnotapos.setBounds(20, 150, 140, 13);

        jtxttextnotapos.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttextnotapos.setText("textnotapos");
        jtxttextnotapos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttextnotaposFocusGained(evt);
            }
        });
        jPanel2.add(jtxttextnotapos);
        jtxttextnotapos.setBounds(210, 150, 520, 23);

        jlblaccset_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblaccset_code.setText("Acc Set Code");
        jPanel2.add(jlblaccset_code);
        jlblaccset_code.setBounds(20, 190, 140, 13);

        jlblcash_account.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcash_account.setText("Cash Account");
        jPanel2.add(jlblcash_account);
        jlblcash_account.setBounds(20, 210, 140, 13);

        jlbltrns_account.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltrns_account.setText("Trns Account");
        jPanel2.add(jlbltrns_account);
        jlbltrns_account.setBounds(20, 230, 140, 13);

        jlblcrdt_account.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcrdt_account.setText("Crdt Account");
        jPanel2.add(jlblcrdt_account);
        jlblcrdt_account.setBounds(20, 250, 140, 13);

        jtxtcrdt_account.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcrdt_account.setText("crdt_account");
        jtxtcrdt_account.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcrdt_accountFocusGained(evt);
            }
        });
        jPanel2.add(jtxtcrdt_account);
        jtxtcrdt_account.setBounds(210, 250, 150, 23);

        jtxttrns_account.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttrns_account.setText("trns_account");
        jtxttrns_account.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttrns_accountFocusGained(evt);
            }
        });
        jPanel2.add(jtxttrns_account);
        jtxttrns_account.setBounds(210, 230, 150, 23);

        jtxtcash_account.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcash_account.setText("cash_account");
        jtxtcash_account.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcash_accountFocusGained(evt);
            }
        });
        jPanel2.add(jtxtcash_account);
        jtxtcash_account.setBounds(210, 210, 150, 23);

        jtxtaccset_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaccset_code.setText("accset_code");
        jtxtaccset_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtaccset_codeFocusGained(evt);
            }
        });
        jPanel2.add(jtxtaccset_code);
        jtxtaccset_code.setBounds(210, 190, 150, 23);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowse);
        jbtnBrowse.setBounds(360, 30, 30, 17);

        jtxtterm_code_desc.setEditable(false);
        jtxtterm_code_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtterm_code_desc.setText("term_code");
        jtxtterm_code_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtterm_code_descFocusGained(evt);
            }
        });
        jPanel2.add(jtxtterm_code_desc);
        jtxtterm_code_desc.setBounds(400, 10, 330, 23);

        jtxtsalesman_code_desc.setEditable(false);
        jtxtsalesman_code_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsalesman_code_desc.setText("salesman_code");
        jtxtsalesman_code_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsalesman_code_descFocusGained(evt);
            }
        });
        jPanel2.add(jtxtsalesman_code_desc);
        jtxtsalesman_code_desc.setBounds(400, 30, 330, 23);

        jtxtcost_price_code_desc.setEditable(false);
        jtxtcost_price_code_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcost_price_code_desc.setText("cost_price_code");
        jtxtcost_price_code_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcost_price_code_descFocusGained(evt);
            }
        });
        jPanel2.add(jtxtcost_price_code_desc);
        jtxtcost_price_code_desc.setBounds(400, 50, 330, 23);

        jtxtsales_price_code_desc.setEditable(false);
        jtxtsales_price_code_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsales_price_code_desc.setText("sales_price_code");
        jtxtsales_price_code_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsales_price_code_descFocusGained(evt);
            }
        });
        jPanel2.add(jtxtsales_price_code_desc);
        jtxtsales_price_code_desc.setBounds(400, 70, 330, 23);

        jtxtdiscount_code_desc.setEditable(false);
        jtxtdiscount_code_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdiscount_code_desc.setText("discount_code");
        jtxtdiscount_code_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdiscount_code_descFocusGained(evt);
            }
        });
        jPanel2.add(jtxtdiscount_code_desc);
        jtxtdiscount_code_desc.setBounds(400, 90, 330, 23);

        jtxtwarehouse_code_desc.setEditable(false);
        jtxtwarehouse_code_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtwarehouse_code_desc.setText("warehouse_code");
        jtxtwarehouse_code_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtwarehouse_code_descFocusGained(evt);
            }
        });
        jPanel2.add(jtxtwarehouse_code_desc);
        jtxtwarehouse_code_desc.setBounds(400, 110, 330, 23);

        jtxtcrdt_account_desc.setEditable(false);
        jtxtcrdt_account_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcrdt_account_desc.setText("crdt_account");
        jtxtcrdt_account_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcrdt_account_descFocusGained(evt);
            }
        });
        jPanel2.add(jtxtcrdt_account_desc);
        jtxtcrdt_account_desc.setBounds(400, 250, 330, 23);

        jtxttrns_account_desc.setEditable(false);
        jtxttrns_account_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttrns_account_desc.setText("trns_account");
        jtxttrns_account_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttrns_account_descFocusGained(evt);
            }
        });
        jPanel2.add(jtxttrns_account_desc);
        jtxttrns_account_desc.setBounds(400, 230, 330, 23);

        jtxtcash_account_desc.setEditable(false);
        jtxtcash_account_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcash_account_desc.setText("cash_account");
        jtxtcash_account_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcash_account_descFocusGained(evt);
            }
        });
        jPanel2.add(jtxtcash_account_desc);
        jtxtcash_account_desc.setBounds(400, 210, 330, 23);

        jtxtaccset_code_desc.setEditable(false);
        jtxtaccset_code_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaccset_code_desc.setText("accset_code");
        jtxtaccset_code_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtaccset_code_descFocusGained(evt);
            }
        });
        jPanel2.add(jtxtaccset_code_desc);
        jtxtaccset_code_desc.setBounds(400, 190, 330, 23);

        jbtnBrowse1.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse1.setText("...");
        jbtnBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowse1);
        jbtnBrowse1.setBounds(360, 10, 30, 17);

        jbtnBrowse2.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse2.setText("...");
        jbtnBrowse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowse2);
        jbtnBrowse2.setBounds(360, 70, 30, 17);

        jbtnBrowse3.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse3.setText("...");
        jbtnBrowse3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowse3);
        jbtnBrowse3.setBounds(360, 50, 30, 17);

        jbtnBrowse6.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse6.setText("...");
        jbtnBrowse6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowse6);
        jbtnBrowse6.setBounds(360, 110, 30, 17);

        jbtnBrowse7.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse7.setText("...");
        jbtnBrowse7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowse7);
        jbtnBrowse7.setBounds(360, 90, 30, 17);

        jbtnBrowse8.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse8.setText("...");
        jbtnBrowse8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowse8);
        jbtnBrowse8.setBounds(360, 250, 30, 17);

        jbtnBrowse9.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse9.setText("...");
        jbtnBrowse9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowse9);
        jbtnBrowse9.setBounds(360, 230, 30, 17);

        jbtnBrowse10.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse10.setText("...");
        jbtnBrowse10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse10ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowse10);
        jbtnBrowse10.setBounds(360, 210, 30, 17);

        jbtnBrowse11.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse11.setText("...");
        jbtnBrowse11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse11ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowse11);
        jbtnBrowse11.setBounds(360, 190, 30, 17);

        jlbltrns_account1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltrns_account1.setText("Temp Account");
        jPanel2.add(jlbltrns_account1);
        jlbltrns_account1.setBounds(20, 270, 140, 13);

        jlblcrdt_account1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcrdt_account1.setText("PPN Account");
        jPanel2.add(jlblcrdt_account1);
        jlblcrdt_account1.setBounds(20, 290, 140, 13);

        jtxtppn_account.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtppn_account.setText("ppn_account");
        jtxtppn_account.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtppn_accountFocusGained(evt);
            }
        });
        jPanel2.add(jtxtppn_account);
        jtxtppn_account.setBounds(210, 290, 150, 23);

        jtxttemp_account.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttemp_account.setText("trns_account");
        jtxttemp_account.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttemp_accountFocusGained(evt);
            }
        });
        jPanel2.add(jtxttemp_account);
        jtxttemp_account.setBounds(210, 270, 150, 23);

        jbtnBrowse12.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse12.setText("...");
        jbtnBrowse12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse12ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowse12);
        jbtnBrowse12.setBounds(360, 270, 30, 17);

        jbtnBrowse13.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse13.setText("...");
        jbtnBrowse13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse13ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowse13);
        jbtnBrowse13.setBounds(360, 290, 30, 17);

        jtxtppn_account_desc.setEditable(false);
        jtxtppn_account_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtppn_account_desc.setText("ppn_account");
        jtxtppn_account_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtppn_account_descFocusGained(evt);
            }
        });
        jPanel2.add(jtxtppn_account_desc);
        jtxtppn_account_desc.setBounds(400, 290, 330, 23);

        jtxttemp_account_desc.setEditable(false);
        jtxttemp_account_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttemp_account_desc.setText("trns_account");
        jtxttemp_account_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttemp_account_descFocusGained(evt);
            }
        });
        jPanel2.add(jtxttemp_account_desc);
        jtxttemp_account_desc.setBounds(400, 270, 330, 23);

        jTabbedPane1.addTab("Default Setting", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(50, 80, 750, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jtxtcompany_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtcompany_idFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtcompany_idFocusGained

private void jtxtcompany_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtcompany_nameFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtcompany_nameFocusGained

private void jtxtactive_stsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtactive_stsFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtactive_stsFocusGained

private void jtxtaddress1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtaddress1FocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtaddress1FocusGained

private void jtxtaddress2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtaddress2FocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtaddress2FocusGained

private void jtxtcityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtcityFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtcityFocusGained

private void jtxtstateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtstateFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtstateFocusGained

private void jtxtzipcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtzipcodeFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtzipcodeFocusGained

private void jtxtphoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtphoneFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtphoneFocusGained

private void jtxtfaximaleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtfaximaleFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtfaximaleFocusGained

private void jtxtemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtemailFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtemailFocusGained

private void jtxtpicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtpicFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtpicFocusGained

private void jtxtregister_dateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtregister_dateFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtregister_dateFocusGained

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.op_salesman, "", jtxtsalesman_code,jtxtsalesman_code_desc);
}//GEN-LAST:event_jbtnBrowseActionPerformed

private void jtxtterm_code_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtterm_code_descFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtterm_code_descFocusGained

private void jtxtsalesman_code_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsalesman_code_descFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtsalesman_code_descFocusGained

private void jtxtcost_price_code_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtcost_price_code_descFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtcost_price_code_descFocusGained

private void jtxtsales_price_code_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsales_price_code_descFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtsales_price_code_descFocusGained

private void jtxtdiscount_code_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdiscount_code_descFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdiscount_code_descFocusGained

private void jtxtwarehouse_code_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtwarehouse_code_descFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtwarehouse_code_descFocusGained

private void jtxtcrdt_account_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtcrdt_account_descFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtcrdt_account_descFocusGained

private void jtxttrns_account_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxttrns_account_descFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxttrns_account_descFocusGained

private void jtxtcash_account_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtcash_account_descFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtcash_account_descFocusGained

private void jtxtaccset_code_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtaccset_code_descFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtaccset_code_descFocusGained

private void jbtnBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse1ActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.op_payment_term, "", jtxtterm_code,jtxtterm_code_desc);
}//GEN-LAST:event_jbtnBrowse1ActionPerformed

private void jbtnBrowse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse2ActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.in_price, "", jtxtsales_price_code,jtxtsales_price_code_desc);
}//GEN-LAST:event_jbtnBrowse2ActionPerformed

private void jbtnBrowse3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse3ActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.in_price, "", jtxtcost_price_code,jtxtcost_price_code_desc);
}//GEN-LAST:event_jbtnBrowse3ActionPerformed

private void jbtnBrowse6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse6ActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.in_warehouse, "", jtxtwarehouse_code,jtxtwarehouse_code_desc);
}//GEN-LAST:event_jbtnBrowse6ActionPerformed

private void jbtnBrowse7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse7ActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.in_discount, "", jtxtdiscount_code,jtxtdiscount_code_desc);
}//GEN-LAST:event_jbtnBrowse7ActionPerformed

private void jbtnBrowse8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse8ActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.gl_account, "", jtxtcrdt_account,jtxtcrdt_account_desc);
}//GEN-LAST:event_jbtnBrowse8ActionPerformed

private void jbtnBrowse9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse9ActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.gl_account, "", jtxttrns_account,jtxttrns_account_desc);
}//GEN-LAST:event_jbtnBrowse9ActionPerformed

private void jbtnBrowse10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse10ActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.gl_account, "", jtxtcash_account,jtxtcash_account_desc);
}//GEN-LAST:event_jbtnBrowse10ActionPerformed

private void jbtnBrowse11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse11ActionPerformed
    // TODO add your handling code here:
    dobrowseaccountset();
}//GEN-LAST:event_jbtnBrowse11ActionPerformed

private void jtxtppn_accountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtppn_accountFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtppn_accountFocusGained

private void jtxttemp_accountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxttemp_accountFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxttemp_accountFocusGained

private void jbtnBrowse12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse12ActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.gl_account, "", jtxttemp_account,jtxttemp_account_desc);
}//GEN-LAST:event_jbtnBrowse12ActionPerformed

private void jbtnBrowse13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse13ActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.gl_account, "", jtxtppn_account,jtxtppn_account_desc);
}//GEN-LAST:event_jbtnBrowse13ActionPerformed

private void jtxtppn_account_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtppn_account_descFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtppn_account_descFocusGained

private void jtxttemp_account_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxttemp_account_descFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxttemp_account_descFocusGained

private void jtxtterm_codeFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    jtxtterm_code.setSelectionStart(0);
    jtxtterm_code.setSelectionEnd(jtxtterm_code.getText().length());
}                                         

private void jtxtsalesman_codeFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxtsalesman_code.setSelectionStart(0);
    jtxtsalesman_code.setSelectionEnd(jtxtsalesman_code.getText().length());
}                                             

private void jtxtcost_price_codeFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtcost_price_code.setSelectionStart(0);
    jtxtcost_price_code.setSelectionEnd(jtxtcost_price_code.getText().length());
}                                               

private void jtxtsales_price_codeFocusGained(java.awt.event.FocusEvent evt) {                                              
        // TODO add your handling code here:
    jtxtsales_price_code.setSelectionStart(0);
    jtxtsales_price_code.setSelectionEnd(jtxtsales_price_code.getText().length());
}                                                

private void jtxtdiscount_codeFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxtdiscount_code.setSelectionStart(0);
    jtxtdiscount_code.setSelectionEnd(jtxtdiscount_code.getText().length());
}                                             

private void jtxtwarehouse_codeFocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
    jtxtwarehouse_code.setSelectionStart(0);
    jtxtwarehouse_code.setSelectionEnd(jtxtwarehouse_code.getText().length());
}                                              

private void jtxtcounter_numberFocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
    jtxtcounter_number.setSelectionStart(0);
    jtxtcounter_number.setSelectionEnd(jtxtcounter_number.getText().length());
}                                              

private void jtxttextnotaposFocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    jtxttextnotapos.setSelectionStart(0);
    jtxttextnotapos.setSelectionEnd(jtxttextnotapos.getText().length());
}                                           

private void jtxtaccset_codeFocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    jtxtaccset_code.setSelectionStart(0);
    jtxtaccset_code.setSelectionEnd(jtxtaccset_code.getText().length());
}                                           

private void jtxtcash_accountFocusGained(java.awt.event.FocusEvent evt) {                                          
        // TODO add your handling code here:
    jtxtcash_account.setSelectionStart(0);
    jtxtcash_account.setSelectionEnd(jtxtcash_account.getText().length());
}                                            

private void jtxttrns_accountFocusGained(java.awt.event.FocusEvent evt) {                                          
        // TODO add your handling code here:
    jtxttrns_account.setSelectionStart(0);
    jtxttrns_account.setSelectionEnd(jtxttrns_account.getText().length());
}                                            

private void jtxtcrdt_accountFocusGained(java.awt.event.FocusEvent evt) {                                          
        // TODO add your handling code here:
    jtxtcrdt_account.setSelectionStart(0);
    jtxtcrdt_account.setSelectionEnd(jtxtcrdt_account.getText().length());
}                                            

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);

}                                           


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmap_option().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowse1;
    private javax.swing.JButton jbtnBrowse10;
    private javax.swing.JButton jbtnBrowse11;
    private javax.swing.JButton jbtnBrowse12;
    private javax.swing.JButton jbtnBrowse13;
    private javax.swing.JButton jbtnBrowse2;
    private javax.swing.JButton jbtnBrowse3;
    private javax.swing.JButton jbtnBrowse6;
    private javax.swing.JButton jbtnBrowse7;
    private javax.swing.JButton jbtnBrowse8;
    private javax.swing.JButton jbtnBrowse9;
    private javax.swing.JLabel jlblaccset_code;
    private javax.swing.JLabel jlblactive_sts;
    private javax.swing.JLabel jlbladdress1;
    private javax.swing.JLabel jlblcash_account;
    private javax.swing.JLabel jlblcity;
    private javax.swing.JLabel jlblcompany_id;
    private javax.swing.JLabel jlblcompany_name;
    private javax.swing.JLabel jlblcost_price_code;
    private javax.swing.JLabel jlblcounter_number;
    private javax.swing.JLabel jlblcrdt_account;
    private javax.swing.JLabel jlblcrdt_account1;
    private javax.swing.JLabel jlbldiscount_code;
    private javax.swing.JLabel jlblemail;
    private javax.swing.JLabel jlblfaximale;
    private javax.swing.JLabel jlblphone;
    private javax.swing.JLabel jlblpic;
    private javax.swing.JLabel jlblregister_date;
    private javax.swing.JLabel jlblsales_price_code;
    private javax.swing.JLabel jlblsalesman_code;
    private javax.swing.JLabel jlblstate;
    private javax.swing.JLabel jlblterm_code;
    private javax.swing.JLabel jlbltextnotapos;
    private javax.swing.JLabel jlbltrns_account;
    private javax.swing.JLabel jlbltrns_account1;
    private javax.swing.JLabel jlblwarehouse_code;
    private javax.swing.JLabel jlblzipcode;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtaccset_code;
    private javax.swing.JTextField jtxtaccset_code_desc;
    private javax.swing.JTextField jtxtactive_sts;
    private javax.swing.JTextField jtxtaddress1;
    private javax.swing.JTextField jtxtaddress2;
    private javax.swing.JTextField jtxtcash_account;
    private javax.swing.JTextField jtxtcash_account_desc;
    private javax.swing.JTextField jtxtcity;
    private javax.swing.JTextField jtxtcompany_id;
    private javax.swing.JTextField jtxtcompany_name;
    private javax.swing.JTextField jtxtcost_price_code;
    private javax.swing.JTextField jtxtcost_price_code_desc;
    private javax.swing.JTextField jtxtcounter_number;
    private javax.swing.JTextField jtxtcrdt_account;
    private javax.swing.JTextField jtxtcrdt_account_desc;
    private javax.swing.JTextField jtxtdiscount_code;
    private javax.swing.JTextField jtxtdiscount_code_desc;
    private javax.swing.JTextField jtxtemail;
    private javax.swing.JTextField jtxtfaximale;
    private javax.swing.JTextField jtxtphone;
    private javax.swing.JTextField jtxtpic;
    private javax.swing.JTextField jtxtppn_account;
    private javax.swing.JTextField jtxtppn_account_desc;
    private javax.swing.JTextField jtxtregister_date;
    private javax.swing.JTextField jtxtsales_price_code;
    private javax.swing.JTextField jtxtsales_price_code_desc;
    private javax.swing.JTextField jtxtsalesman_code;
    private javax.swing.JTextField jtxtsalesman_code_desc;
    private javax.swing.JTextField jtxtstate;
    private javax.swing.JTextField jtxttemp_account;
    private javax.swing.JTextField jtxttemp_account_desc;
    private javax.swing.JTextField jtxtterm_code;
    private javax.swing.JTextField jtxtterm_code_desc;
    private javax.swing.JTextField jtxttextnotapos;
    private javax.swing.JTextField jtxttrns_account;
    private javax.swing.JTextField jtxttrns_account_desc;
    private javax.swing.JTextField jtxtwarehouse_code;
    private javax.swing.JTextField jtxtwarehouse_code_desc;
    private javax.swing.JTextField jtxtzipcode;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jtxtcompany_id.setText("");
        jtxtcompany_name.setText("");
        jtxtactive_sts.setText("");
        jtxtaddress1.setText("");
        jtxtaddress2.setText("");
        jtxtcity.setText("");
        jtxtstate.setText("");
        jtxtzipcode.setText("");
        jtxtphone.setText("");
        jtxtfaximale.setText("");
        jtxtemail.setText("");
        jtxtpic.setText("");
        jtxtregister_date.setText("");
        jtxtterm_code.setText("");
        jtxtsalesman_code.setText("");
        jtxtcost_price_code.setText("");
        jtxtsales_price_code.setText("");
        jtxtdiscount_code.setText("");
        jtxtwarehouse_code.setText("");
        jtxtcounter_number.setText("");
        jtxttextnotapos.setText("");
        jtxtaccset_code.setText("");
        jtxtcash_account.setText("");
        jtxttrns_account.setText("");
        jtxtcrdt_account.setText("");

        jtxtterm_code_desc.setText("");
        jtxtsalesman_code_desc.setText("");
        jtxtcost_price_code_desc.setText("");
        jtxtsales_price_code_desc.setText("");
        jtxtdiscount_code_desc.setText("");
        jtxtwarehouse_code_desc.setText("");
        jtxtaccset_code_desc.setText("");
        jtxtcash_account_desc.setText("");
        jtxttrns_account_desc.setText("");
        jtxtcrdt_account_desc.setText("");

        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");
    }

    public void newData() throws CodeException {
        istatus=1;
        clearfield();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.update();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        
        jtxtcompany_id.setText(obj.getcompany_id());
        jtxtcompany_name.setText(obj.getcompany_name());
        jtxtactive_sts.setText(obj.getactive_sts());
        jtxtaddress1.setText(obj.getaddress1());
        jtxtaddress2.setText(obj.getaddress2());
        jtxtcity.setText(obj.getcity());
        jtxtstate.setText(obj.getstate());
        jtxtzipcode.setText(obj.getzipcode());
        jtxtphone.setText(obj.getphone());
        jtxtfaximale.setText(obj.getfaximale());
        jtxtemail.setText(obj.getemail());
        jtxtpic.setText(obj.getpic());
        jtxtregister_date.setText(obj.getregister_date());
        jtxtterm_code.setText(obj.getterm_code());
        jtxtsalesman_code.setText(obj.getsalesman_code());
        jtxtcost_price_code.setText(obj.getcost_price_code());
        jtxtsales_price_code.setText(obj.getsales_price_code());
        jtxtdiscount_code.setText(obj.getdiscount_code());
        jtxtwarehouse_code.setText(obj.getwarehouse_code());
        jtxtcounter_number.setText(obj.getcounter_number());
        jtxttextnotapos.setText(obj.gettextnotapos());

        jtxtaccset_code.setText(obj.getaccset_code());
        jtxtcash_account.setText(obj.getcash_account());
        jtxttrns_account.setText(obj.gettrns_account());
        jtxtcrdt_account.setText(obj.getcrdt_account());

        jtxttemp_account.setText(obj.gettemp_account());
        jtxtppn_account.setText(obj.getppn_account());

        jtxtterm_code_desc.setText(obj.getTerm_code_desc());
        jtxtsalesman_code_desc.setText(obj.getSalesman_code_desc());
        jtxtcost_price_code_desc.setText(obj.getCost_price_code_desc());
        jtxtsales_price_code_desc.setText(obj.getSales_price_code_desc());
        jtxtdiscount_code_desc.setText(obj.getDiscount_code_desc());
        jtxtwarehouse_code_desc.setText(obj.getWarehouse_code_desc());
        
        jtxtaccset_code_desc.setText(obj.getAccset_code_desc());
        jtxtcash_account_desc.setText(obj.getCash_account_desc());
        jtxttrns_account_desc.setText(obj.getTrns_account_desc());
        jtxtcrdt_account_desc.setText(obj.getCrdt_account_desc());

        jtxttemp_account_desc.setText(obj.gettemp_account_desc());
        jtxtppn_account_desc.setText(obj.getppn_account_desc());

        jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getentrydate()));
        jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getauditdate()));
        jtxtUserID.setText(obj.getaudituser());

        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        if (obj.delete()){
            obj.moveNext();
            showData();
        }
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);
        mf.btnNew.setEnabled(false);
        mf.btnDel.setEnabled(false);
        mf.btnUndo.setEnabled(false);
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }

        obj.setcompany_id(jtxtcompany_id.getText());
        obj.setcompany_name(jtxtcompany_name.getText());
        obj.setactive_sts(jtxtactive_sts.getText());
        obj.setaddress1(jtxtaddress1.getText());
        obj.setaddress2(jtxtaddress2.getText());
        obj.setcity(jtxtcity.getText());
        obj.setstate(jtxtstate.getText());
        obj.setzipcode(jtxtzipcode.getText());
        obj.setphone(jtxtphone.getText());
        obj.setfaximale(jtxtfaximale.getText());
        obj.setemail(jtxtemail.getText());
        obj.setpic(jtxtpic.getText());
        obj.setregister_date(jtxtregister_date.getText());
        obj.setterm_code(jtxtterm_code.getText());
        obj.setsalesman_code(jtxtsalesman_code.getText());
        obj.setcost_price_code(jtxtcost_price_code.getText());
        obj.setsales_price_code(jtxtsales_price_code.getText());
        obj.setdiscount_code(jtxtdiscount_code.getText());
        obj.setwarehouse_code(jtxtwarehouse_code.getText());
        obj.setcounter_number(jtxtcounter_number.getText());
        obj.settextnotapos(jtxttextnotapos.getText());

        obj.setaccset_code(jtxtaccset_code.getText());
        obj.setcash_account(jtxtcash_account.getText());
        obj.settrns_account(jtxttrns_account.getText());
        obj.setcrdt_account(jtxtcrdt_account.getText());
        obj.settemp_account(jtxttemp_account.getText());
        obj.setppn_account(jtxtppn_account.getText());

    }

    public void undo() throws CodeException {
        istatus = 0;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
        Map parameter = new HashMap();

        parameter.put("scompanyid", GlobalUtils.company);
        
        // Versi 1
        String file ="";
        if(GlobalUtils.getAppDir()){
            try{
            file = GlobalUtils.getCurrentDir() +"/Reports/FMOP-01.jrxml";
            jasperReport = JasperCompileManager.compileReport(file);
            //System.out.println("file: "+file);
            System.out.println("isi parameter Daftar Customer:"+parameter);
            jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, appsettinghandler.db.getConnection());
            JasperViewer.viewReport(jasperPrint, false);
            }catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    public void browseaccountset(String what) {
        obrowse.showbrowser(what, "", jtxtaccset_code,jtxtaccset_code_desc);
    }

    public void dobrowseaccountset() {
        browseaccountset(obrowse.ap_account_set);
    }
    
}
