/*
 * From ko_transaksi_setuju
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ko.component;


import classinterface.NavigatorFormInt;
import common.component.FrmMainFrame;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import kopkar.ko.objectclasses.ko_anggotaext;
import kopkar.ko.objectclasses.ko_departemenext;
import kopkar.ko.objectclasses.ko_jabatanext;
import kopkar.ko.objectclasses.ko_pinjamanext;
import kopkar.ko.objectclasses.ko_transaksi_mohonext;
import kopkar.ko.objectclasses.ko_transaksi_setuju_detailext;
import kopkar.ko.objectclasses.ko_transaksi_setujuext;
import kopkar.utils.browsecontroller;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.kazao.calendar.KazaoCalendarDateTimeException;
import utils.CodeException;
import utils.GlobalUtils;
import utils.appsettinghandler;

/**
 *
 * @author  Generator
 */

public class Frmko_transaksi_setuju extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmko_transaksi_setuju";
    
    FrmMainFrame mf ;

    ko_transaksi_setujuext obj=new ko_transaksi_setujuext();
    private browsecontroller obrowse;
    private ko_anggotaext oagt;
    private DefaultTableModel model;
    private ko_transaksi_setujuext objtmp;
    private int status_data=0;
   
    /** Creates new form Area */
    public Frmko_transaksi_setuju() throws CodeException {
        initComponents();
    }
    
    public Frmko_transaksi_setuju(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
        filldop_tagih();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jlblyop = new javax.swing.JLabel();
        jtxtyop = new javax.swing.JTextField();
        jlblmop = new javax.swing.JLabel();
        jlblmasa_kerja = new javax.swing.JLabel();
        jtxtmasa_kerja = new javax.swing.JTextField();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();
        jlbldocument_number = new javax.swing.JLabel();
        jtxtdocument_number = new javax.swing.JTextField();
        jlbldocument_status = new javax.swing.JLabel();
        jtxtdocument_status = new javax.swing.JTextField();
        jlbldocument_date = new javax.swing.JLabel();
        kzodocument_date = new org.kazao.calendar.KazaoCalendarDate();
        jbtnBrowse = new javax.swing.JButton();
        jtxtmember_number = new javax.swing.JTextField();
        jbtnBrowse_anggota = new javax.swing.JButton();
        jlblmember_number1 = new javax.swing.JLabel();
        jlblmember_number2 = new javax.swing.JLabel();
        jtxtmember_name = new javax.swing.JTextField();
        jlblmember_number3 = new javax.swing.JLabel();
        jtxtmember_number2 = new javax.swing.JTextField();
        jlblmember_number4 = new javax.swing.JLabel();
        jtxtnama_departemen = new javax.swing.JTextField();
        jlblmember_number5 = new javax.swing.JLabel();
        jtxtnama_jabatan = new javax.swing.JTextField();
        jlblmasa_kerja1 = new javax.swing.JLabel();
        jchck_registrasi_sts = new javax.swing.JCheckBox();
        jlbldocument_date1 = new javax.swing.JLabel();
        jopt_complete_status_draff = new javax.swing.JRadioButton();
        jopt_complete_status_complete = new javax.swing.JRadioButton();
        jcmbmop = new javax.swing.JComboBox();
        jtxttanggal_masuk = new javax.swing.JTextField();
        jbtn_cetak_table_angsuran = new javax.swing.JButton();
        jlbldscription = new javax.swing.JLabel();
        jlblreference = new javax.swing.JLabel();
        jlblauto_sts = new javax.swing.JLabel();
        jlblyop_start = new javax.swing.JLabel();
        jlbljumlah_angsuran = new javax.swing.JLabel();
        jlbljangka_waktu = new javax.swing.JLabel();
        jlblsuku_bunga = new javax.swing.JLabel();
        jlbljumlah_pinjaman = new javax.swing.JLabel();
        jlblkode_pinjaman1 = new javax.swing.JLabel();
        jlblkode_pinjaman = new javax.swing.JLabel();
        jtxtkode_pinjaman = new javax.swing.JTextField();
        jtxtnama_pinjaman = new javax.swing.JTextField();
        jtxtjumlah_pinjaman = new javax.swing.JTextField();
        jtxtsuku_bunga = new javax.swing.JTextField();
        jtxtjangka_waktu = new javax.swing.JTextField();
        jtxtjumlah_angsuran = new javax.swing.JTextField();
        jcmbmop_start = new javax.swing.JComboBox();
        jtxtyop_start = new javax.swing.JTextField();
        joptauto_sts_manual = new javax.swing.JRadioButton();
        joptauto_sts_auto = new javax.swing.JRadioButton();
        jtxtreference = new javax.swing.JTextField();
        jtxtdscription = new javax.swing.JTextField();
        joptsatuan_waktu_harian = new javax.swing.JRadioButton();
        joptsatuan_waktu_mingguan = new javax.swing.JRadioButton();
        joptsatuan_waktu_bulanan = new javax.swing.JRadioButton();
        jlblkode_pinjaman2 = new javax.swing.JLabel();
        jtxtreference_number = new javax.swing.JTextField();
        jbtnBrowse_pinjaman1 = new javax.swing.JButton();
        jlbljumlah_pinjaman1 = new javax.swing.JLabel();
        jtxtjumlah_pinjaman1 = new javax.swing.JTextField();
        jlblsuku_bunga1 = new javax.swing.JLabel();
        jtxtjumlah_bunga = new javax.swing.JTextField();
        jlblsuku_bunga2 = new javax.swing.JLabel();
        jtxtjumlah_pokok_bunga = new javax.swing.JTextField();
        jlblsuku_bunga3 = new javax.swing.JLabel();
        jtxtangsuranke = new javax.swing.JTextField();
        jlblsuku_bunga4 = new javax.swing.JLabel();
        jtxtsisa_angsuranke = new javax.swing.JTextField();
        jlblsuku_bunga5 = new javax.swing.JLabel();
        jtxtlast_payment_number = new javax.swing.JTextField();
        jlblsuku_bunga6 = new javax.swing.JLabel();
        jtxttotal_angsuran = new javax.swing.JTextField();
        jtxtpotongan = new javax.swing.JTextField();
        jlblsuku_bunga7 = new javax.swing.JLabel();
        jtxtsisa_angsuran = new javax.swing.JTextField();
        jlblsuku_bunga8 = new javax.swing.JLabel();
        jlbldocument_date2 = new javax.swing.JLabel();
        jcmbdop_tagih = new javax.swing.JComboBox();
        jlbldocument_date3 = new javax.swing.JLabel();
        kzotgl_cair = new org.kazao.calendar.KazaoCalendarDate();
        jopthitung_bunga_flat_khusus = new javax.swing.JRadioButton();
        jopthitung_bunga_mix = new javax.swing.JRadioButton();
        jopthitung_bunga_efektif = new javax.swing.JRadioButton();
        jopthitung_bunga_menurun = new javax.swing.JRadioButton();
        jopthitung_bunga_flat = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Persetujuan Pinjaman");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Persetujuan Pinjaman");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 200, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 12);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 12, 400);

        jlblyop.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblyop.setText("Tahun");
        getContentPane().add(jlblyop);
        jlblyop.setBounds(70, 80, 140, 13);

        jtxtyop.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtyop.setText("yop");
        jtxtyop.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtyopFocusGained(evt);
            }
        });
        getContentPane().add(jtxtyop);
        jtxtyop.setBounds(160, 80, 50, 25);

        jlblmop.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmop.setText("Periode");
        getContentPane().add(jlblmop);
        jlblmop.setBounds(250, 80, 110, 13);

        jlblmasa_kerja.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmasa_kerja.setText("Status Pegawai");
        getContentPane().add(jlblmasa_kerja);
        jlblmasa_kerja.setBounds(520, 180, 140, 13);

        jtxtmasa_kerja.setEditable(false);
        jtxtmasa_kerja.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmasa_kerja.setText("masa_kerja");
        jtxtmasa_kerja.setFocusable(false);
        jtxtmasa_kerja.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmasa_kerjaFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmasa_kerja);
        jtxtmasa_kerja.setBounds(710, 200, 150, 25);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(360, 30, 170, 22);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(530, 30, 130, 22);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(660, 30, 140, 22);

        jlbldocument_number.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_number.setText("No. Registrasi");
        getContentPane().add(jlbldocument_number);
        jlbldocument_number.setBounds(520, 100, 110, 13);

        jtxtdocument_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdocument_number.setText("document_number");
        jtxtdocument_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocument_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdocument_number);
        jtxtdocument_number.setBounds(710, 100, 120, 25);

        jlbldocument_status.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_status.setText("Status");
        getContentPane().add(jlbldocument_status);
        jlbldocument_status.setBounds(520, 80, 140, 13);

        jtxtdocument_status.setEditable(false);
        jtxtdocument_status.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdocument_status.setText("document_status");
        jtxtdocument_status.setFocusable(false);
        jtxtdocument_status.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocument_statusFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdocument_status);
        jtxtdocument_status.setBounds(710, 80, 150, 25);

        jlbldocument_date.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_date.setText("Tgl. Dokumen");
        getContentPane().add(jlbldocument_date);
        jlbldocument_date.setBounds(520, 120, 140, 13);

        kzodocument_date.setFont(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date.setOpaque(false);
        getContentPane().add(kzodocument_date);
        kzodocument_date.setBounds(710, 120, 100, 20);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(830, 100, 30, 17);

        jtxtmember_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_number.setText("member_number");
        jtxtmember_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_number);
        jtxtmember_number.setBounds(260, 120, 150, 25);

        jbtnBrowse_anggota.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse_anggota.setText("...");
        jbtnBrowse_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_anggotaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse_anggota);
        jbtnBrowse_anggota.setBounds(410, 120, 30, 17);

        jlblmember_number1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmember_number1.setText("No. Anggota");
        getContentPane().add(jlblmember_number1);
        jlblmember_number1.setBounds(70, 120, 140, 13);

        jlblmember_number2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmember_number2.setText("Nama Anggota");
        getContentPane().add(jlblmember_number2);
        jlblmember_number2.setBounds(70, 140, 140, 13);

        jtxtmember_name.setEditable(false);
        jtxtmember_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_name.setText("member_number");
        jtxtmember_name.setFocusable(false);
        jtxtmember_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_nameFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_name);
        jtxtmember_name.setBounds(260, 140, 350, 25);

        jlblmember_number3.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmember_number3.setText("N.I.K");
        getContentPane().add(jlblmember_number3);
        jlblmember_number3.setBounds(70, 160, 140, 13);

        jtxtmember_number2.setEditable(false);
        jtxtmember_number2.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_number2.setText("member_number");
        jtxtmember_number2.setFocusable(false);
        jtxtmember_number2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_number2FocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_number2);
        jtxtmember_number2.setBounds(260, 160, 150, 25);

        jlblmember_number4.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmember_number4.setText("Departemen");
        getContentPane().add(jlblmember_number4);
        jlblmember_number4.setBounds(70, 180, 140, 13);

        jtxtnama_departemen.setEditable(false);
        jtxtnama_departemen.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtnama_departemen.setText("member_number");
        jtxtnama_departemen.setFocusable(false);
        jtxtnama_departemen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtnama_departemenFocusGained(evt);
            }
        });
        getContentPane().add(jtxtnama_departemen);
        jtxtnama_departemen.setBounds(260, 180, 260, 25);

        jlblmember_number5.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmember_number5.setText("Jabatan");
        getContentPane().add(jlblmember_number5);
        jlblmember_number5.setBounds(70, 200, 140, 13);

        jtxtnama_jabatan.setEditable(false);
        jtxtnama_jabatan.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtnama_jabatan.setText("member_number");
        jtxtnama_jabatan.setFocusable(false);
        jtxtnama_jabatan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtnama_jabatanFocusGained(evt);
            }
        });
        getContentPane().add(jtxtnama_jabatan);
        jtxtnama_jabatan.setBounds(260, 200, 260, 25);

        jlblmasa_kerja1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmasa_kerja1.setText("masa_kerja");
        getContentPane().add(jlblmasa_kerja1);
        jlblmasa_kerja1.setBounds(520, 200, 140, 13);

        jchck_registrasi_sts.setFont(new java.awt.Font("Dialog", 0, 10));
        jchck_registrasi_sts.setText("Karyawan Tetap");
        jchck_registrasi_sts.setFocusable(false);
        getContentPane().add(jchck_registrasi_sts);
        jchck_registrasi_sts.setBounds(710, 180, 160, 23);

        jlbldocument_date1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_date1.setText("Tgl. Masuk");
        getContentPane().add(jlbldocument_date1);
        jlbldocument_date1.setBounds(520, 160, 140, 13);

        buttonGroup4.add(jopt_complete_status_draff);
        jopt_complete_status_draff.setFont(new java.awt.Font("Dialog", 0, 10));
        jopt_complete_status_draff.setSelected(true);
        jopt_complete_status_draff.setText("Draff");
        getContentPane().add(jopt_complete_status_draff);
        jopt_complete_status_draff.setBounds(70, 550, 57, 23);

        buttonGroup4.add(jopt_complete_status_complete);
        jopt_complete_status_complete.setFont(new java.awt.Font("Dialog", 0, 10));
        jopt_complete_status_complete.setText("Complete");
        getContentPane().add(jopt_complete_status_complete);
        jopt_complete_status_complete.setBounds(150, 550, 123, 23);

        jcmbmop.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbmop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        getContentPane().add(jcmbmop);
        jcmbmop.setBounds(310, 80, 90, 20);

        jtxttanggal_masuk.setEditable(false);
        jtxttanggal_masuk.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttanggal_masuk.setText("tanggal_masuk");
        jtxttanggal_masuk.setFocusable(false);
        jtxttanggal_masuk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttanggal_masukFocusGained(evt);
            }
        });
        getContentPane().add(jtxttanggal_masuk);
        jtxttanggal_masuk.setBounds(710, 160, 150, 25);

        jbtn_cetak_table_angsuran.setFont(new java.awt.Font("Dialog", 1, 10));
        jbtn_cetak_table_angsuran.setText("Cetak Table Angsuran");
        jbtn_cetak_table_angsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cetak_table_angsuranActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_cetak_table_angsuran);
        jbtn_cetak_table_angsuran.setBounds(630, 550, 220, 20);

        jlbldscription.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldscription.setText("Keterangan");
        getContentPane().add(jlbldscription);
        jlbldscription.setBounds(70, 530, 140, 13);

        jlblreference.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblreference.setText("Referensi");
        getContentPane().add(jlblreference);
        jlblreference.setBounds(70, 510, 140, 13);

        jlblauto_sts.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblauto_sts.setText("Pembayaran");
        getContentPane().add(jlblauto_sts);
        jlblauto_sts.setBounds(70, 380, 140, 13);

        jlblyop_start.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblyop_start.setText("Periode Mulai Angsuran");
        getContentPane().add(jlblyop_start);
        jlblyop_start.setBounds(70, 360, 140, 13);

        jlbljumlah_angsuran.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbljumlah_angsuran.setText("Jumlah Angsuran");
        getContentPane().add(jlbljumlah_angsuran);
        jlbljumlah_angsuran.setBounds(70, 340, 140, 13);

        jlbljangka_waktu.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbljangka_waktu.setText("Jangka Waktu");
        getContentPane().add(jlbljangka_waktu);
        jlbljangka_waktu.setBounds(70, 320, 140, 13);

        jlblsuku_bunga.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsuku_bunga.setText("Suku Bunga");
        getContentPane().add(jlblsuku_bunga);
        jlblsuku_bunga.setBounds(70, 300, 140, 13);

        jlbljumlah_pinjaman.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbljumlah_pinjaman.setText("Jumlah pinjaman");
        getContentPane().add(jlbljumlah_pinjaman);
        jlbljumlah_pinjaman.setBounds(70, 280, 140, 13);

        jlblkode_pinjaman1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblkode_pinjaman1.setText("Nama Pinjaman");
        getContentPane().add(jlblkode_pinjaman1);
        jlblkode_pinjaman1.setBounds(70, 260, 140, 13);

        jlblkode_pinjaman.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblkode_pinjaman.setText("Kode Pinjaman");
        getContentPane().add(jlblkode_pinjaman);
        jlblkode_pinjaman.setBounds(70, 240, 140, 13);

        jtxtkode_pinjaman.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtkode_pinjaman.setText("kode_pinjaman");
        jtxtkode_pinjaman.setFocusable(false);
        jtxtkode_pinjaman.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtkode_pinjamanFocusGained(evt);
            }
        });
        getContentPane().add(jtxtkode_pinjaman);
        jtxtkode_pinjaman.setBounds(260, 240, 150, 25);

        jtxtnama_pinjaman.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtnama_pinjaman.setText("kode_pinjaman");
        jtxtnama_pinjaman.setFocusable(false);
        jtxtnama_pinjaman.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtnama_pinjamanFocusGained(evt);
            }
        });
        getContentPane().add(jtxtnama_pinjaman);
        jtxtnama_pinjaman.setBounds(260, 260, 340, 25);

        jtxtjumlah_pinjaman.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtjumlah_pinjaman.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtjumlah_pinjaman.setText("jumlah_pinjaman");
        jtxtjumlah_pinjaman.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtjumlah_pinjamanFocusGained(evt);
            }
        });
        jtxtjumlah_pinjaman.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtjumlah_pinjamanKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtjumlah_pinjaman);
        jtxtjumlah_pinjaman.setBounds(260, 280, 150, 25);

        jtxtsuku_bunga.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsuku_bunga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsuku_bunga.setText("suku_bunga");
        jtxtsuku_bunga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsuku_bungaFocusGained(evt);
            }
        });
        jtxtsuku_bunga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsuku_bungaKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtsuku_bunga);
        jtxtsuku_bunga.setBounds(260, 300, 150, 25);

        jtxtjangka_waktu.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtjangka_waktu.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtjangka_waktu.setText("jangka_waktu");
        jtxtjangka_waktu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtjangka_waktuFocusGained(evt);
            }
        });
        jtxtjangka_waktu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtjangka_waktuKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtjangka_waktu);
        jtxtjangka_waktu.setBounds(260, 320, 150, 25);

        jtxtjumlah_angsuran.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtjumlah_angsuran.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtjumlah_angsuran.setText("jumlah_angsuran");
        jtxtjumlah_angsuran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtjumlah_angsuranFocusGained(evt);
            }
        });
        getContentPane().add(jtxtjumlah_angsuran);
        jtxtjumlah_angsuran.setBounds(260, 340, 150, 25);

        jcmbmop_start.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbmop_start.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        getContentPane().add(jcmbmop_start);
        jcmbmop_start.setBounds(260, 360, 90, 20);

        jtxtyop_start.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtyop_start.setText("yop_start");
        jtxtyop_start.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtyop_startFocusGained(evt);
            }
        });
        getContentPane().add(jtxtyop_start);
        jtxtyop_start.setBounds(350, 360, 60, 25);

        buttonGroup3.add(joptauto_sts_manual);
        joptauto_sts_manual.setFont(new java.awt.Font("Dialog", 1, 10));
        joptauto_sts_manual.setSelected(true);
        joptauto_sts_manual.setText("Manual");
        joptauto_sts_manual.setFocusable(false);
        getContentPane().add(joptauto_sts_manual);
        joptauto_sts_manual.setBounds(260, 380, 70, 23);

        buttonGroup3.add(joptauto_sts_auto);
        joptauto_sts_auto.setFont(new java.awt.Font("Dialog", 1, 10));
        joptauto_sts_auto.setText("Otomatis");
        joptauto_sts_auto.setFocusable(false);
        getContentPane().add(joptauto_sts_auto);
        joptauto_sts_auto.setBounds(350, 380, 123, 23);

        jtxtreference.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtreference.setText("reference");
        jtxtreference.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtreferenceFocusGained(evt);
            }
        });
        getContentPane().add(jtxtreference);
        jtxtreference.setBounds(260, 510, 340, 25);

        jtxtdscription.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdscription.setText("dscription");
        jtxtdscription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdscriptionFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdscription);
        jtxtdscription.setBounds(260, 530, 340, 25);

        buttonGroup2.add(joptsatuan_waktu_harian);
        joptsatuan_waktu_harian.setFont(new java.awt.Font("Dialog", 1, 10));
        joptsatuan_waktu_harian.setText("Harian");
        joptsatuan_waktu_harian.setFocusable(false);
        getContentPane().add(joptsatuan_waktu_harian);
        joptsatuan_waktu_harian.setBounds(410, 320, 71, 23);

        buttonGroup2.add(joptsatuan_waktu_mingguan);
        joptsatuan_waktu_mingguan.setFont(new java.awt.Font("Dialog", 1, 10));
        joptsatuan_waktu_mingguan.setText("Mingguan");
        joptsatuan_waktu_mingguan.setFocusable(false);
        getContentPane().add(joptsatuan_waktu_mingguan);
        joptsatuan_waktu_mingguan.setBounds(490, 320, 100, 23);

        buttonGroup2.add(joptsatuan_waktu_bulanan);
        joptsatuan_waktu_bulanan.setFont(new java.awt.Font("Dialog", 1, 10));
        joptsatuan_waktu_bulanan.setSelected(true);
        joptsatuan_waktu_bulanan.setText("Bulanan");
        joptsatuan_waktu_bulanan.setFocusable(false);
        getContentPane().add(joptsatuan_waktu_bulanan);
        joptsatuan_waktu_bulanan.setBounds(590, 320, 123, 23);

        jlblkode_pinjaman2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblkode_pinjaman2.setText("No. Referensi");
        getContentPane().add(jlblkode_pinjaman2);
        jlblkode_pinjaman2.setBounds(70, 220, 140, 13);

        jtxtreference_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtreference_number.setText("reference_number");
        jtxtreference_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtreference_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtreference_number);
        jtxtreference_number.setBounds(260, 220, 150, 25);

        jbtnBrowse_pinjaman1.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse_pinjaman1.setText("...");
        jbtnBrowse_pinjaman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_pinjaman1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse_pinjaman1);
        jbtnBrowse_pinjaman1.setBounds(410, 220, 30, 17);

        jlbljumlah_pinjaman1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbljumlah_pinjaman1.setText("Jumlah pinjaman di setujui");
        jlbljumlah_pinjaman1.setFocusable(false);
        getContentPane().add(jlbljumlah_pinjaman1);
        jlbljumlah_pinjaman1.setBounds(70, 400, 180, 13);

        jtxtjumlah_pinjaman1.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtjumlah_pinjaman1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtjumlah_pinjaman1.setText("jumlah_pinjaman");
        jtxtjumlah_pinjaman1.setFocusable(false);
        jtxtjumlah_pinjaman1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtjumlah_pinjaman1FocusGained(evt);
            }
        });
        jtxtjumlah_pinjaman1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtjumlah_pinjaman1KeyReleased(evt);
            }
        });
        getContentPane().add(jtxtjumlah_pinjaman1);
        jtxtjumlah_pinjaman1.setBounds(260, 400, 150, 25);

        jlblsuku_bunga1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsuku_bunga1.setText("Total Bunga");
        jlblsuku_bunga1.setFocusable(false);
        getContentPane().add(jlblsuku_bunga1);
        jlblsuku_bunga1.setBounds(70, 420, 140, 13);

        jtxtjumlah_bunga.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtjumlah_bunga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtjumlah_bunga.setText("jumlah_bunga");
        jtxtjumlah_bunga.setFocusable(false);
        jtxtjumlah_bunga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtjumlah_bungaFocusGained(evt);
            }
        });
        jtxtjumlah_bunga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtjumlah_bungaKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtjumlah_bunga);
        jtxtjumlah_bunga.setBounds(260, 420, 150, 25);

        jlblsuku_bunga2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsuku_bunga2.setText("Pinjaman + Bunga");
        getContentPane().add(jlblsuku_bunga2);
        jlblsuku_bunga2.setBounds(520, 400, 140, 13);

        jtxtjumlah_pokok_bunga.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtjumlah_pokok_bunga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtjumlah_pokok_bunga.setText("jumlah_pokok_bunga");
        jtxtjumlah_pokok_bunga.setFocusable(false);
        jtxtjumlah_pokok_bunga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtjumlah_pokok_bungaFocusGained(evt);
            }
        });
        jtxtjumlah_pokok_bunga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtjumlah_pokok_bungaKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtjumlah_pokok_bunga);
        jtxtjumlah_pokok_bunga.setBounds(710, 400, 150, 25);

        jlblsuku_bunga3.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsuku_bunga3.setText("Angsuran ke");
        jlblsuku_bunga3.setFocusable(false);
        getContentPane().add(jlblsuku_bunga3);
        jlblsuku_bunga3.setBounds(70, 440, 140, 13);

        jtxtangsuranke.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtangsuranke.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtangsuranke.setText("angsuranke");
        jtxtangsuranke.setFocusable(false);
        jtxtangsuranke.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtangsurankeFocusGained(evt);
            }
        });
        jtxtangsuranke.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtangsurankeKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtangsuranke);
        jtxtangsuranke.setBounds(260, 440, 150, 25);

        jlblsuku_bunga4.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsuku_bunga4.setText("Sisa Angsuran");
        jlblsuku_bunga4.setFocusable(false);
        getContentPane().add(jlblsuku_bunga4);
        jlblsuku_bunga4.setBounds(70, 460, 140, 13);

        jtxtsisa_angsuranke.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsisa_angsuranke.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsisa_angsuranke.setText("sisa_angsuranke");
        jtxtsisa_angsuranke.setFocusable(false);
        jtxtsisa_angsuranke.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsisa_angsurankeFocusGained(evt);
            }
        });
        jtxtsisa_angsuranke.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsisa_angsurankeKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtsisa_angsuranke);
        jtxtsisa_angsuranke.setBounds(260, 460, 150, 25);

        jlblsuku_bunga5.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsuku_bunga5.setText("No. Pembayaran Terakhir");
        getContentPane().add(jlblsuku_bunga5);
        jlblsuku_bunga5.setBounds(520, 420, 180, 13);

        jtxtlast_payment_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtlast_payment_number.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtlast_payment_number.setText("suku_bunga");
        jtxtlast_payment_number.setFocusable(false);
        jtxtlast_payment_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtlast_payment_numberFocusGained(evt);
            }
        });
        jtxtlast_payment_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtlast_payment_numberKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtlast_payment_number);
        jtxtlast_payment_number.setBounds(710, 420, 150, 25);

        jlblsuku_bunga6.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsuku_bunga6.setText("Total Angsuran");
        getContentPane().add(jlblsuku_bunga6);
        jlblsuku_bunga6.setBounds(520, 440, 140, 13);

        jtxttotal_angsuran.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttotal_angsuran.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxttotal_angsuran.setText("TotalAngsuran");
        jtxttotal_angsuran.setFocusable(false);
        jtxttotal_angsuran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttotal_angsuranFocusGained(evt);
            }
        });
        jtxttotal_angsuran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxttotal_angsuranKeyReleased(evt);
            }
        });
        getContentPane().add(jtxttotal_angsuran);
        jtxttotal_angsuran.setBounds(710, 440, 150, 25);

        jtxtpotongan.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtpotongan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtpotongan.setText("potongan");
        jtxtpotongan.setFocusable(false);
        jtxtpotongan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtpotonganFocusGained(evt);
            }
        });
        jtxtpotongan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtpotonganKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtpotongan);
        jtxtpotongan.setBounds(710, 460, 150, 25);

        jlblsuku_bunga7.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsuku_bunga7.setText("Potongan");
        getContentPane().add(jlblsuku_bunga7);
        jlblsuku_bunga7.setBounds(520, 460, 140, 13);

        jtxtsisa_angsuran.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsisa_angsuran.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsisa_angsuran.setText("angsuranke");
        jtxtsisa_angsuran.setFocusable(false);
        jtxtsisa_angsuran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsisa_angsuranFocusGained(evt);
            }
        });
        jtxtsisa_angsuran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsisa_angsuranKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtsisa_angsuran);
        jtxtsisa_angsuran.setBounds(710, 480, 150, 25);

        jlblsuku_bunga8.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsuku_bunga8.setText("Sisa Jumlah Angsuran");
        getContentPane().add(jlblsuku_bunga8);
        jlblsuku_bunga8.setBounds(520, 480, 140, 13);

        jlbldocument_date2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_date2.setText("Tanggal Penagihan");
        getContentPane().add(jlbldocument_date2);
        jlbldocument_date2.setBounds(410, 360, 140, 13);

        jcmbdop_tagih.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbdop_tagih.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcmbdop_tagih);
        jcmbdop_tagih.setBounds(520, 360, 87, 20);

        jlbldocument_date3.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_date3.setText("Tgl. Pencairan Dana");
        getContentPane().add(jlbldocument_date3);
        jlbldocument_date3.setBounds(70, 480, 140, 13);

        kzotgl_cair.setFont(new java.awt.Font("Dialog", 0, 10));
        kzotgl_cair.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzotgl_cair.setOpaque(false);
        getContentPane().add(kzotgl_cair);
        kzotgl_cair.setBounds(260, 480, 100, 20);

        buttonGroup1.add(jopthitung_bunga_flat_khusus);
        jopthitung_bunga_flat_khusus.setFont(new java.awt.Font("Dialog", 1, 10));
        jopthitung_bunga_flat_khusus.setText("Flat Khusus");
        jopthitung_bunga_flat_khusus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jopthitung_bunga_flat_khususItemStateChanged(evt);
            }
        });
        jopthitung_bunga_flat_khusus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jopthitung_bunga_flat_khususActionPerformed(evt);
            }
        });
        getContentPane().add(jopthitung_bunga_flat_khusus);
        jopthitung_bunga_flat_khusus.setBounds(710, 300, 120, 23);

        buttonGroup1.add(jopthitung_bunga_mix);
        jopthitung_bunga_mix.setFont(new java.awt.Font("Dialog", 1, 10));
        jopthitung_bunga_mix.setText("Menurun");
        jopthitung_bunga_mix.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jopthitung_bunga_mixItemStateChanged(evt);
            }
        });
        getContentPane().add(jopthitung_bunga_mix);
        jopthitung_bunga_mix.setBounds(620, 300, 90, 23);

        buttonGroup1.add(jopthitung_bunga_efektif);
        jopthitung_bunga_efektif.setFont(new java.awt.Font("Dialog", 1, 10));
        jopthitung_bunga_efektif.setText("Efektif");
        jopthitung_bunga_efektif.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jopthitung_bunga_efektifItemStateChanged(evt);
            }
        });
        getContentPane().add(jopthitung_bunga_efektif);
        jopthitung_bunga_efektif.setBounds(550, 300, 70, 23);

        buttonGroup1.add(jopthitung_bunga_menurun);
        jopthitung_bunga_menurun.setFont(new java.awt.Font("Dialog", 1, 10));
        jopthitung_bunga_menurun.setText("Anuitas");
        jopthitung_bunga_menurun.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jopthitung_bunga_menurunItemStateChanged(evt);
            }
        });
        getContentPane().add(jopthitung_bunga_menurun);
        jopthitung_bunga_menurun.setBounds(470, 300, 80, 23);

        buttonGroup1.add(jopthitung_bunga_flat);
        jopthitung_bunga_flat.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jopthitung_bunga_flat.setSelected(true);
        jopthitung_bunga_flat.setText("Flat");
        jopthitung_bunga_flat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jopthitung_bunga_flatItemStateChanged(evt);
            }
        });
        getContentPane().add(jopthitung_bunga_flat);
        jopthitung_bunga_flat.setBounds(410, 300, 51, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jtxtdocument_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdocument_numberFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdocument_numberFocusGained

private void jtxtdocument_statusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdocument_statusFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdocument_statusFocusGained

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_transaksi_setuju, "", jtxtdocument_number);
    if (!jtxtdocument_number.getText().equalsIgnoreCase("")){
        try {
            if (obj.initdata(jtxtdocument_number.getText())) {
                showData();
            }
        } catch (CodeException ex) {
            Logger.getLogger(Frmko_transaksi_setor_simpanan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}//GEN-LAST:event_jbtnBrowseActionPerformed

private void jtxtmember_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtmember_numberFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtmember_numberFocusGained

private void jbtnBrowse_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_anggotaActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_anggota, "", jtxtmember_number);

    if (!jtxtmember_number.getText().equalsIgnoreCase("")){
        showanggota();
    }
}//GEN-LAST:event_jbtnBrowse_anggotaActionPerformed
private void showanggota() {
        oagt=new ko_anggotaext();
        
            if (oagt.initdata_mohon(jtxtmember_number.getText())) {
                jtxtmember_name.setText(oagt.getmember_name());
                jtxtmember_number2.setText(oagt.getemployee_number());
                ko_departemenext odept=oagt.getdepinfo();
                ko_jabatanext ojbt=oagt.getjbtinfo();
                jtxtnama_departemen.setText(odept.getnama_departemen());
                jtxtnama_jabatan.setText(ojbt.getnama_jabatan());
                jtxttanggal_masuk.setText(GlobalUtils.formatDate(oagt.gettanggal_masuk(),"MM/dd/yyyy"));
                jtxtmasa_kerja.setText(oagt.getmasakerja());
                if (oagt.getemployee_sts().equalsIgnoreCase("Y")){
                jchck_registrasi_sts.setSelected(true);
                } else {
                jchck_registrasi_sts.setSelected(false);
                }
                jtxtmasa_kerja.setText(oagt.getmasakerja());
            }
        

    }

private void jtxtmember_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtmember_nameFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtmember_nameFocusGained

private void jtxtmember_number2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtmember_number2FocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtmember_number2FocusGained

private void jtxtnama_departemenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtnama_departemenFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtnama_departemenFocusGained

private void jtxtnama_jabatanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtnama_jabatanFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtnama_jabatanFocusGained

private void jtxtnama_pinjamanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtnama_pinjamanFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtnama_pinjamanFocusGained

private void jtxtjumlah_pinjamanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtjumlah_pinjamanKeyReleased
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtjumlah_pinjaman);
    calculateangsuran();
}//GEN-LAST:event_jtxtjumlah_pinjamanKeyReleased

private void jtxtjangka_waktuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtjangka_waktuKeyReleased
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtjangka_waktu);
    calculateangsuran();
}//GEN-LAST:event_jtxtjangka_waktuKeyReleased

private void jtxtsuku_bungaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsuku_bungaKeyReleased
    // TODO add your handling code here:
    calculateangsuran();
}//GEN-LAST:event_jtxtsuku_bungaKeyReleased

private void jtxttanggal_masukFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxttanggal_masukFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxttanggal_masukFocusGained

private void jtxtreference_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtreference_numberFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtreference_numberFocusGained

private void jbtnBrowse_pinjaman1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_pinjaman1ActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_transaksi_mohon, "member_number='"+jtxtmember_number.getText()+"' and document_status='O'", jtxtreference_number);

    if (!jtxtreference_number.getText().equalsIgnoreCase("")){
        showpermohonan(jtxtreference_number.getText());
    }
}//GEN-LAST:event_jbtnBrowse_pinjaman1ActionPerformed

private void jtxtjumlah_pinjaman1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtjumlah_pinjaman1FocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtjumlah_pinjaman1FocusGained

private void jtxtjumlah_pinjaman1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtjumlah_pinjaman1KeyReleased
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtjumlah_pinjaman1KeyReleased

private void jtxtjumlah_bungaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtjumlah_bungaFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtjumlah_bungaFocusGained

private void jtxtjumlah_bungaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtjumlah_bungaKeyReleased
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtjumlah_bungaKeyReleased

private void jtxtjumlah_pokok_bungaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtjumlah_pokok_bungaFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtjumlah_pokok_bungaFocusGained

private void jtxtjumlah_pokok_bungaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtjumlah_pokok_bungaKeyReleased
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtjumlah_pokok_bungaKeyReleased

private void jtxtangsurankeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtangsurankeFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtangsurankeFocusGained

private void jtxtangsurankeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtangsurankeKeyReleased
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtangsurankeKeyReleased

private void jtxtsisa_angsurankeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsisa_angsurankeFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtsisa_angsurankeFocusGained

private void jtxtsisa_angsurankeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsisa_angsurankeKeyReleased
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtsisa_angsurankeKeyReleased

private void jtxtlast_payment_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtlast_payment_numberFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtlast_payment_numberFocusGained

private void jtxtlast_payment_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtlast_payment_numberKeyReleased
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtlast_payment_numberKeyReleased

private void jtxttotal_angsuranFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxttotal_angsuranFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxttotal_angsuranFocusGained

private void jtxttotal_angsuranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxttotal_angsuranKeyReleased
    // TODO add your handling code here:
}//GEN-LAST:event_jtxttotal_angsuranKeyReleased

private void jtxtpotonganFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtpotonganFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtpotonganFocusGained

private void jtxtpotonganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpotonganKeyReleased
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtpotonganKeyReleased

private void jtxtsisa_angsuranFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsisa_angsuranFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtsisa_angsuranFocusGained

private void jtxtsisa_angsuranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsisa_angsuranKeyReleased
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtsisa_angsuranKeyReleased

private void jbtn_cetak_table_angsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cetak_table_angsuranActionPerformed
    // TODO add your handling code here:
    if (obj.run_sp_ko_pinjaman_calculate()){
        showreport();
    }
}//GEN-LAST:event_jbtn_cetak_table_angsuranActionPerformed

private void jopthitung_bunga_flat_khususItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jopthitung_bunga_flat_khususItemStateChanged
    // TODO add your handling code here:
    calculateangsuran();
}//GEN-LAST:event_jopthitung_bunga_flat_khususItemStateChanged

private void jopthitung_bunga_mixItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jopthitung_bunga_mixItemStateChanged
    // TODO add your handling code here:
    calculateangsuran();
}//GEN-LAST:event_jopthitung_bunga_mixItemStateChanged

private void jopthitung_bunga_efektifItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jopthitung_bunga_efektifItemStateChanged
    // TODO add your handling code here:
    calculateangsuran();
}//GEN-LAST:event_jopthitung_bunga_efektifItemStateChanged

private void jopthitung_bunga_menurunItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jopthitung_bunga_menurunItemStateChanged
    // TODO add your handling code here:
    calculateangsuran();
}//GEN-LAST:event_jopthitung_bunga_menurunItemStateChanged

private void jopthitung_bunga_flatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jopthitung_bunga_flatItemStateChanged
    // TODO add your handling code here:
    calculateangsuran();
}//GEN-LAST:event_jopthitung_bunga_flatItemStateChanged

private void jopthitung_bunga_flat_khususActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jopthitung_bunga_flat_khususActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jopthitung_bunga_flat_khususActionPerformed



private void jtxtyopFocusGained(java.awt.event.FocusEvent evt) {                                 
        // TODO add your handling code here:
    jtxtyop.setSelectionStart(0);
    jtxtyop.setSelectionEnd(jtxtyop.getText().length());
}                                   

private void jtxtreferenceFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    jtxtreference.setSelectionStart(0);
    jtxtreference.setSelectionEnd(jtxtreference.getText().length());
}                                         

private void jtxtdscriptionFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
    jtxtdscription.setSelectionStart(0);
    jtxtdscription.setSelectionEnd(jtxtdscription.getText().length());
}                                          


private void jtxtmasa_kerjaFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
    jtxtmasa_kerja.setSelectionStart(0);
    jtxtmasa_kerja.setSelectionEnd(jtxtmasa_kerja.getText().length());
}                                          

private void jtxtkode_pinjamanFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxtkode_pinjaman.setSelectionStart(0);
    jtxtkode_pinjaman.setSelectionEnd(jtxtkode_pinjaman.getText().length());
}                                             

private void jtxtjumlah_pinjamanFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtjumlah_pinjaman.setSelectionStart(0);
    jtxtjumlah_pinjaman.setSelectionEnd(jtxtjumlah_pinjaman.getText().length());
}                                               

private void jtxtsuku_bungaFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
    jtxtsuku_bunga.setSelectionStart(0);
    jtxtsuku_bunga.setSelectionEnd(jtxtsuku_bunga.getText().length());
}                                          

private void jtxtjangka_waktuFocusGained(java.awt.event.FocusEvent evt) {                                          
        // TODO add your handling code here:
    jtxtjangka_waktu.setSelectionStart(0);
    jtxtjangka_waktu.setSelectionEnd(jtxtjangka_waktu.getText().length());
}                                            

private void jtxtjumlah_angsuranFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtjumlah_angsuran.setSelectionStart(0);
    jtxtjumlah_angsuran.setSelectionEnd(jtxtjumlah_angsuran.getText().length());
}                                               

private void jtxtyop_startFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    jtxtyop_start.setSelectionStart(0);
    jtxtyop_start.setSelectionEnd(jtxtyop_start.getText().length());
}                                         

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           
                                                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmko_transaksi_setuju().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowse_anggota;
    private javax.swing.JButton jbtnBrowse_pinjaman1;
    private javax.swing.JButton jbtn_cetak_table_angsuran;
    private javax.swing.JCheckBox jchck_registrasi_sts;
    private javax.swing.JComboBox jcmbdop_tagih;
    private javax.swing.JComboBox jcmbmop;
    private javax.swing.JComboBox jcmbmop_start;
    private javax.swing.JLabel jlblauto_sts;
    private javax.swing.JLabel jlbldocument_date;
    private javax.swing.JLabel jlbldocument_date1;
    private javax.swing.JLabel jlbldocument_date2;
    private javax.swing.JLabel jlbldocument_date3;
    private javax.swing.JLabel jlbldocument_number;
    private javax.swing.JLabel jlbldocument_status;
    private javax.swing.JLabel jlbldscription;
    private javax.swing.JLabel jlbljangka_waktu;
    private javax.swing.JLabel jlbljumlah_angsuran;
    private javax.swing.JLabel jlbljumlah_pinjaman;
    private javax.swing.JLabel jlbljumlah_pinjaman1;
    private javax.swing.JLabel jlblkode_pinjaman;
    private javax.swing.JLabel jlblkode_pinjaman1;
    private javax.swing.JLabel jlblkode_pinjaman2;
    private javax.swing.JLabel jlblmasa_kerja;
    private javax.swing.JLabel jlblmasa_kerja1;
    private javax.swing.JLabel jlblmember_number1;
    private javax.swing.JLabel jlblmember_number2;
    private javax.swing.JLabel jlblmember_number3;
    private javax.swing.JLabel jlblmember_number4;
    private javax.swing.JLabel jlblmember_number5;
    private javax.swing.JLabel jlblmop;
    private javax.swing.JLabel jlblreference;
    private javax.swing.JLabel jlblsuku_bunga;
    private javax.swing.JLabel jlblsuku_bunga1;
    private javax.swing.JLabel jlblsuku_bunga2;
    private javax.swing.JLabel jlblsuku_bunga3;
    private javax.swing.JLabel jlblsuku_bunga4;
    private javax.swing.JLabel jlblsuku_bunga5;
    private javax.swing.JLabel jlblsuku_bunga6;
    private javax.swing.JLabel jlblsuku_bunga7;
    private javax.swing.JLabel jlblsuku_bunga8;
    private javax.swing.JLabel jlblyop;
    private javax.swing.JLabel jlblyop_start;
    private javax.swing.JRadioButton jopt_complete_status_complete;
    private javax.swing.JRadioButton jopt_complete_status_draff;
    private javax.swing.JRadioButton joptauto_sts_auto;
    private javax.swing.JRadioButton joptauto_sts_manual;
    private javax.swing.JRadioButton jopthitung_bunga_efektif;
    private javax.swing.JRadioButton jopthitung_bunga_flat;
    private javax.swing.JRadioButton jopthitung_bunga_flat_khusus;
    private javax.swing.JRadioButton jopthitung_bunga_menurun;
    private javax.swing.JRadioButton jopthitung_bunga_mix;
    private javax.swing.JRadioButton joptsatuan_waktu_bulanan;
    private javax.swing.JRadioButton joptsatuan_waktu_harian;
    private javax.swing.JRadioButton joptsatuan_waktu_mingguan;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtangsuranke;
    private javax.swing.JTextField jtxtdocument_number;
    private javax.swing.JTextField jtxtdocument_status;
    private javax.swing.JTextField jtxtdscription;
    private javax.swing.JTextField jtxtjangka_waktu;
    private javax.swing.JTextField jtxtjumlah_angsuran;
    private javax.swing.JTextField jtxtjumlah_bunga;
    private javax.swing.JTextField jtxtjumlah_pinjaman;
    private javax.swing.JTextField jtxtjumlah_pinjaman1;
    private javax.swing.JTextField jtxtjumlah_pokok_bunga;
    private javax.swing.JTextField jtxtkode_pinjaman;
    private javax.swing.JTextField jtxtlast_payment_number;
    private javax.swing.JTextField jtxtmasa_kerja;
    private javax.swing.JTextField jtxtmember_name;
    private javax.swing.JTextField jtxtmember_number;
    private javax.swing.JTextField jtxtmember_number2;
    private javax.swing.JTextField jtxtnama_departemen;
    private javax.swing.JTextField jtxtnama_jabatan;
    private javax.swing.JTextField jtxtnama_pinjaman;
    private javax.swing.JTextField jtxtpotongan;
    private javax.swing.JTextField jtxtreference;
    private javax.swing.JTextField jtxtreference_number;
    private javax.swing.JTextField jtxtsisa_angsuran;
    private javax.swing.JTextField jtxtsisa_angsuranke;
    private javax.swing.JTextField jtxtsuku_bunga;
    private javax.swing.JTextField jtxttanggal_masuk;
    private javax.swing.JTextField jtxttotal_angsuran;
    private javax.swing.JTextField jtxtyop;
    private javax.swing.JTextField jtxtyop_start;
    private org.kazao.calendar.KazaoCalendarDate kzodocument_date;
    private org.kazao.calendar.KazaoCalendarDate kzotgl_cair;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        if (obj.getdocentry()==null){
            newData();
        }
        showData();
        
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        status_data=1;
        jtxtdocument_number.setText("");
        jtxtdocument_status.setText("");
        jopt_complete_status_draff.setSelected(true);
        try {
            kzodocument_date.setDate(GlobalUtils.getCurrentDate());
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmko_transaksi_setuju.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtxtyop.setText(GlobalUtils.getCurrentYear());
        jcmbmop.setSelectedIndex(GlobalUtils.toInt(GlobalUtils.getCurrentMonth())-1);
        jtxtreference.setText("");
        jtxtdscription.setText("");
        jtxtmember_number.setText("");
        jtxtmasa_kerja.setText("");
        jtxtkode_pinjaman.setText("");
        jtxtjumlah_pinjaman.setText("");
        jtxtsuku_bunga.setText("");
        jtxtjangka_waktu.setText("");
        jopthitung_bunga_flat.setSelected(true);
        joptsatuan_waktu_harian.setSelected(true);
        jtxtjumlah_angsuran.setText("");
        jtxtyop_start.setText(GlobalUtils.getCurrentYear());
        jcmbmop_start.setSelectedIndex(GlobalUtils.toInt(GlobalUtils.getCurrentMonth())-1);
        joptauto_sts_manual.setSelected(true);
        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");

        jtxtmember_name.setText("");
        jtxtmember_number2.setText("");
        jtxtnama_departemen.setText("");
        jtxtnama_jabatan.setText("");
        jtxtmasa_kerja.setText("");
        jtxttanggal_masuk.setText("");
        jtxtnama_pinjaman.setText("");
        jchck_registrasi_sts.setSelected(false);

        jtxtreference_number.setText("");
        jtxtjumlah_pinjaman1.setText("0");
        jtxtjumlah_bunga.setText("0");
        jtxtjumlah_pokok_bunga.setText("0");
        jtxtangsuranke.setText("0");
        jtxtsisa_angsuranke.setText("0");
        jtxtlast_payment_number.setText("0");

        jtxttotal_angsuran.setText("0");
        jtxtpotongan.setText("0");
        jtxtsisa_angsuran.setText("0");

        status_data=0;
    }

    public void newData() throws CodeException {
        istatus=1;
        objtmp=obj;
        obj=new ko_transaksi_setujuext();
        showData();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.update();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        clearfield();
        
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        jtxtdocument_status.setText(obj.getdocument_status_description());
        jtxtdocument_number.setText(obj.getdocument_number());
        if (obj.getcomplete_status().equalsIgnoreCase("Y")){
        jopt_complete_status_complete.setSelected(true);
        } else {
        jopt_complete_status_draff.setSelected(true);
        }
        try {
            kzodocument_date.setDate(GlobalUtils.formatDate(obj.getdocument_date(), "MM/dd/yyyy"));
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmko_transaksi_setuju.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtxtyop.setText(GlobalUtils.churuf(obj.getyop()));
        jcmbmop.setSelectedIndex(obj.getmop()-1);
        jcmbdop_tagih.setSelectedItem(obj.getdop_tagih());
        try {
            kzotgl_cair.setDate(GlobalUtils.formatDate(obj.gettgl_cair(), "MM/dd/yyyy"));
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmko_transaksi_setuju.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtxtreference.setText(obj.getreference());
        jtxtdscription.setText(obj.getdscription());
        jtxtmember_number.setText(obj.getmember_number());
        showanggota();
        jtxtreference_number.setText(obj.getreference_number());
        jtxtmasa_kerja.setText(obj.getmasa_kerja());
        jtxtkode_pinjaman.setText(obj.getkode_pinjaman());
        System.out.println("Nama Pinjaman"+obj.getNama_pinjaman());
        jtxtnama_pinjaman.setText(obj.getNama_pinjaman());
        jtxtjumlah_pinjaman.setText(GlobalUtils.formatnumber(obj.getjumlah_pinjaman()));
        jtxtsuku_bunga.setText(GlobalUtils.formatnumber(obj.getsuku_bunga()));
        jtxtjangka_waktu.setText(GlobalUtils.formatnumber(obj.getjangka_waktu()));
        if (obj.getsatuan_waktu().equals("1")){
            joptsatuan_waktu_harian.setSelected(true);
        } else if (obj.getsatuan_waktu().equals("2")){
            joptsatuan_waktu_mingguan.setSelected(true);
        } else {
            joptsatuan_waktu_bulanan.setSelected(true);
        }
        if (obj.gethitung_bunga().equalsIgnoreCase("1")){
            jopthitung_bunga_flat.setSelected(true);
        }
        if (obj.gethitung_bunga().equalsIgnoreCase("2")){
            jopthitung_bunga_menurun.setSelected(true);
        }
        if (obj.gethitung_bunga().equalsIgnoreCase("3")){
            jopthitung_bunga_efektif.setSelected(true);
        }
        if (obj.gethitung_bunga().equalsIgnoreCase("4")){
            jopthitung_bunga_mix.setSelected(true);
        }
        if (obj.gethitung_bunga().equalsIgnoreCase("5")){
            jopthitung_bunga_flat_khusus.setSelected(true);
        }
        jtxtjumlah_angsuran.setText(GlobalUtils.formatnumber(obj.getjumlah_angsuran()));
        jtxtyop_start.setText(GlobalUtils.churuf(obj.getyop_start()));
        jcmbmop_start.setSelectedIndex(obj.getmop_start()-1);
        if (obj.getauto_sts().equalsIgnoreCase("Y")){
            joptauto_sts_auto.setSelected(true);
        } else {
            joptauto_sts_manual.setSelected(true);
        }
        jtxtjumlah_pinjaman1.setText(GlobalUtils.formatnumber(obj.getjumlah_pinjaman()));
        jtxtjumlah_bunga.setText(GlobalUtils.formatnumber(obj.getjumlah_bunga()));
        jtxtjumlah_pokok_bunga.setText(GlobalUtils.formatnumber(obj.getjumlah_pokok_bunga()));
        jtxtangsuranke.setText(GlobalUtils.churuf(obj.getangsuranke()));
        jtxtsisa_angsuranke.setText(GlobalUtils.formatnumber(obj.getsisa_angsuranke()));
        jtxtlast_payment_number.setText(obj.getlast_payment_number());

        jtxttotal_angsuran.setText(GlobalUtils.formatnumber(obj.gettotal_angsuran()));
        jtxtpotongan.setText(GlobalUtils.formatnumber(obj.gettotal_potongan()));
        jtxtsisa_angsuran.setText(GlobalUtils.formatnumber(obj.gettotal_pokok_bunga_akhir()));

        jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getentrydate()));
        jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getauditdate()));
        jtxtUserID.setText(obj.getaudituser());
        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        if (obj.delete()){
            obj.moveNext();
            showData();
        }
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);
        if (obj.getdocument_status().equalsIgnoreCase("C")){
            mf.setToolBar(iformtype,7);
        }
        if (istatus==1){
            jbtnBrowse.setEnabled(false);
        } else {
            jbtnBrowse.setEnabled(true);
        }
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }
        obj.setdocument_number(jtxtdocument_number.getText());
        obj.setdocument_status(jtxtdocument_status.getText());
        if (jopt_complete_status_complete.isSelected()){
            obj.setcomplete_status("Y");
        } else {
            obj.setcomplete_status("N");
        }
        obj.setdocument_date(kzodocument_date.getDate());
        obj.setyop(GlobalUtils.toInt(jtxtyop.getText()));
        obj.setmop(jcmbmop.getSelectedIndex()+1);
        obj.setdop_tagih((Integer) jcmbdop_tagih.getSelectedItem());
        obj.settgl_cair(kzotgl_cair.getDate());
        obj.setreference(jtxtreference.getText());
        obj.setdscription(jtxtdscription.getText());
        obj.setmember_number(jtxtmember_number.getText());
        obj.setmasa_kerja(jtxtmasa_kerja.getText());
        obj.setreference_number(jtxtreference_number.getText());
        obj.setkode_pinjaman(jtxtkode_pinjaman.getText());
        obj.setjumlah_pinjaman(GlobalUtils.toDbl(jtxtjumlah_pinjaman.getText()));
        obj.setsuku_bunga(GlobalUtils.toDbl(jtxtsuku_bunga.getText()));
        obj.setjangka_waktu(GlobalUtils.toInt(jtxtjangka_waktu.getText()));
        int isatuan_waktu=0;
        if (joptsatuan_waktu_harian.isSelected()){
            isatuan_waktu = 1;
        }
        if (joptsatuan_waktu_mingguan.isSelected()){
            isatuan_waktu = 2;
        }
        if (joptsatuan_waktu_bulanan.isSelected()){
            isatuan_waktu = 3;
        }
        if (jopthitung_bunga_flat.isSelected()){
            obj.sethitung_bunga("1");
        }
        if (jopthitung_bunga_menurun.isSelected()){
            obj.sethitung_bunga("2");
        }
        if (jopthitung_bunga_efektif.isSelected()){
            obj.sethitung_bunga("3");
        }
        if (jopthitung_bunga_mix.isSelected()){
            obj.sethitung_bunga("4");
        }
        if (jopthitung_bunga_flat_khusus.isSelected()){
            obj.sethitung_bunga("5");
        }
        obj.setsatuan_waktu(GlobalUtils.churuf(isatuan_waktu));
        obj.setjumlah_angsuran(GlobalUtils.toDbl(jtxtjumlah_angsuran.getText()));
        obj.setyop_start(GlobalUtils.toInt(jtxtyop_start.getText()));
        obj.setmop_start(jcmbmop_start.getSelectedIndex()+1);
        if (joptauto_sts_auto.isSelected()){
            obj.setauto_sts("Y");
        } else {
            obj.setauto_sts("N");
        }

        obj.setjumlah_bunga(GlobalUtils.toDbl(jtxtjumlah_bunga.getText()));
        obj.setjumlah_pokok_bunga(GlobalUtils.toDbl(jtxtjumlah_pokok_bunga.getText()));
        obj.setangsuranke(GlobalUtils.toInt(jtxtangsuranke.getText()));
        obj.setsisa_angsuranke(GlobalUtils.toInt(jtxtsisa_angsuranke.getText()));
        obj.setlast_payment_number(jtxtlast_payment_number.getText());

        obj.settotal_angsuran(GlobalUtils.toDbl(jtxttotal_angsuran.getText()));
        obj.settotal_potongan(GlobalUtils.toDbl(jtxtpotongan.getText()));
        obj.settotal_pokok_bunga_akhir(GlobalUtils.toDbl(jtxtsisa_angsuran.getText()));

        
    }

    public void undo() throws CodeException {
        istatus = 0;
        obj=objtmp;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
        JasperPrint jasperPrint;

        Map parameter = new HashMap();
        parameter.put("document_date_fr", GlobalUtils.formatDate(obj.getdocument_date(),"yyyy-MM-dd"));
        parameter.put("document_date_to", GlobalUtils.formatDate(obj.getdocument_date(),"yyyy-MM-dd"));
        parameter.put("document_number_fr", obj.getdocument_number());
        parameter.put("document_number_to", obj.getdocument_number());
        parameter.put("audituser", GlobalUtils.audituser);

        // Versi 1
        String file ="";
        JasperReport jasperReport;
        if(GlobalUtils.getAppDir()){
            try{
                    file = GlobalUtils.getCurrentDir() +"/Reports/form_setuju.jrxml";
                    jasperReport = JasperCompileManager.compileReport(file);
                    System.out.println("isi parameter form_setuju.jrxml:"+parameter);
                    jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, appsettinghandler.db.getConnection());
                    JasperViewer.viewReport(jasperPrint, false);
            }catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    private void calculateangsuran() {
        if (status_data!=1){

            Double jumlahangsuran = new Double(0);
            Double jumlahpinjaman=GlobalUtils.toDbl(jtxtjumlah_pinjaman.getText());
            Double sukubunga=GlobalUtils.toDbl(jtxtsuku_bunga.getText());
            Double jangkawaktu=GlobalUtils.toDbl(jtxtjangka_waktu.getText());

            if(istatus==1){
                jtxtsisa_angsuranke.setText(jtxtjangka_waktu.getText());
            }

            jumlahangsuran=(jumlahpinjaman+((sukubunga/100)*jumlahpinjaman))/jangkawaktu;
            jumlahangsuran=Math.ceil(jumlahangsuran);
            jtxtjumlah_angsuran.setText(GlobalUtils.formatnumber(jumlahangsuran));

            Integer modelhitung=1;
            if (jopthitung_bunga_menurun.isSelected()){
                modelhitung=2;
            }
            if (jopthitung_bunga_efektif.isSelected()){
                modelhitung=3;
            }
            if (jopthitung_bunga_mix.isSelected()){
                modelhitung=4;
            }
            if (jopthitung_bunga_flat_khusus.isSelected()){
                modelhitung=5;
            }

            if (obj.runsp_ko_transaksi_setuju_get_rincian_pinjaman(jumlahpinjaman,sukubunga,jangkawaktu,modelhitung)){
                jtxtangsuranke.setText(GlobalUtils.churuf(obj.getangsuranke()));
                jtxtsisa_angsuranke.setText(GlobalUtils.churuf(obj.getsisa_angsuranke()));
                jtxtjumlah_pinjaman1.setText(GlobalUtils.formatnumber(obj.getjumlah_pinjaman()));
                jtxtjumlah_bunga.setText(GlobalUtils.formatnumber(obj.getjumlah_bunga()));
                jtxtjumlah_pokok_bunga.setText(GlobalUtils.formatnumber(obj.getjumlah_pokok_bunga()));
                jtxttotal_angsuran.setText(GlobalUtils.formatnumber(obj.gettotal_angsuran()));
                jtxtpotongan.setText(GlobalUtils.formatnumber(obj.getpotongan()));
                jtxtsisa_angsuran.setText(GlobalUtils.formatnumber(obj.getsisa_angsuran()));

                jtxtjumlah_angsuran.setText(GlobalUtils.formatnumber(obj.getjumlah_angsuran()));
            }
        }
    }

    private void showpinjaman() {
        ko_pinjamanext okopinj=new ko_pinjamanext();
        try {
            if (okopinj.initdata(jtxtkode_pinjaman.getText())) {
                jtxtkode_pinjaman.setText(okopinj.getkode_pinjaman());
                jtxtnama_pinjaman.setText(okopinj.getnama_pinjaman());
                if (okopinj.getcara_bayar().equalsIgnoreCase("1")){
                    joptsatuan_waktu_harian.setSelected(true);
                }
                if (okopinj.getcara_bayar().equalsIgnoreCase("2")){
                    joptsatuan_waktu_mingguan.setSelected(true);
                }
                if (okopinj.getcara_bayar().equalsIgnoreCase("3")){
                    joptsatuan_waktu_bulanan.setSelected(true);
                }
                if (okopinj.gettipe_bunga().equalsIgnoreCase("1")){
                    jopthitung_bunga_flat.setSelected(true);
                } else {
                    jopthitung_bunga_menurun.setSelected(true);
                }
                jtxtjangka_waktu.setText(GlobalUtils.churuf(okopinj.getjumlah_cicilan()));
                jtxtsuku_bunga.setText(GlobalUtils.churuf(okopinj.getbunga()));
            }
        } catch (CodeException ex) {
            Logger.getLogger(Frmko_transaksi_setuju.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void showpermohonan(String document_number) {
        ko_transaksi_mohonext omohon=new ko_transaksi_mohonext();
        try {
            if (omohon.initdata(document_number)) {
                jtxtkode_pinjaman.setText(omohon.getkode_pinjaman());
                jtxtnama_pinjaman.setText(omohon.getnama_pinjaman());
                jtxtjumlah_pinjaman.setText(GlobalUtils.formatnumber(omohon.getjumlah_pinjaman()));
                jtxtsuku_bunga.setText(GlobalUtils.formatnumber(omohon.getsuku_bunga()));
                jtxtjangka_waktu.setText(GlobalUtils.formatnumber(omohon.getjangka_waktu()));
                if (omohon.getsatuan_waktu().equals("1")){
                    joptsatuan_waktu_harian.setSelected(true);
                } else if (omohon.getsatuan_waktu().equals("2")){
                    joptsatuan_waktu_mingguan.setSelected(true);
                } else {
                    joptsatuan_waktu_bulanan.setSelected(true);
                }
                if (omohon.gethitung_bunga().equalsIgnoreCase("1")){
                    jopthitung_bunga_flat.setSelected(true);
                }
                if (omohon.gethitung_bunga().equalsIgnoreCase("2")){
                    jopthitung_bunga_menurun.setSelected(true);
                }
                if (omohon.gethitung_bunga().equalsIgnoreCase("3")){
                    jopthitung_bunga_efektif.setSelected(true);
                }
                if (omohon.gethitung_bunga().equalsIgnoreCase("4")){
                    jopthitung_bunga_mix.setSelected(true);
                }
                if (omohon.gethitung_bunga().equalsIgnoreCase("5")){
                    jopthitung_bunga_flat_khusus.setSelected(true);
                }
                jtxtjumlah_angsuran.setText(GlobalUtils.formatnumber(omohon.getjumlah_angsuran()));
                jtxtyop_start.setText(GlobalUtils.churuf(omohon.getyop_start()));
                jcmbmop_start.setSelectedIndex(omohon.getmop_start()-1);
                try {
                    kzotgl_cair.setDate(GlobalUtils.formatDate(omohon.gettgl_cair(), "MM/dd/yyyy"));
                } catch (KazaoCalendarDateTimeException ex) {
                    Logger.getLogger(Frmko_transaksi_setuju.class.getName()).log(Level.SEVERE, null, ex);
                }
                jcmbdop_tagih.setSelectedItem(omohon.getdop_tagih());
                if (omohon.getauto_sts().equalsIgnoreCase("Y")){
                    joptauto_sts_auto.setSelected(true);
                } else {
                    joptauto_sts_manual.setSelected(true);
                }

                jtxtjumlah_pinjaman1.setText(GlobalUtils.formatnumber(omohon.getjumlah_pinjaman()));
                jtxtjumlah_bunga.setText(GlobalUtils.formatnumber(omohon.getcaljumlahbunga()));
                jtxtjumlah_pokok_bunga.setText(GlobalUtils.formatnumber(omohon.getcaljtxtjumlah_pokok_bunga()));

                jtxtsisa_angsuranke.setText(jtxtjangka_waktu.getText());

                calculateangsuran();
            }
        } catch (CodeException ex) {
            Logger.getLogger(Frmko_transaksi_setuju.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void showreport() {
        JasperPrint jasperPrint;

            Map parameter = new HashMap();
            parameter.put("puser", (GlobalUtils.getUserId()));
            parameter.put("document_number", obj.getdocument_number());
            parameter.put("get", "2");
            parameter.put("audituser", GlobalUtils.audituser);

            // Versi 1
            String file ="";
            JasperReport jasperReport;
            if(GlobalUtils.getAppDir()){
                try{
                        file = GlobalUtils.getCurrentDir() +"/Reports/ko_angsuran_ilustrasi_rpt.jrxml";
                        jasperReport = JasperCompileManager.compileReport(file);
                        System.out.println("isi parameter ko_angsuran_ilustrasi_rpt.jrxml:"+parameter);
                        jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, appsettinghandler.db.getConnection());
                        JasperViewer.viewReport(jasperPrint, false);
                }catch (Exception e) {
                    e.printStackTrace();
                }
            }
    }

    private void filldop_tagih() {
        jcmbdop_tagih.removeAllItems();
        for (int i=1;i<32;i++){
            jcmbdop_tagih.addItem(i);
        }
    }
}
