/*
 * From ko_member_deposit
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ko.component;


import classinterface.NavigatorFormInt;
import common.component.FrmBrowseData;
import common.component.FrmMainFrame;
import kopkar.ko.objectclasses.ko_member_depositext;
import java.util.logging.Level;
import java.util.logging.Logger;
import utils.CodeException;
import utils.GlobalUtils;

/**
 *
 * @author  Generator
 */

public class Frmko_member_deposit extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmko_member_deposit";
    
    FrmMainFrame mf ;

    ko_member_depositext obj=new ko_member_depositext();
   
    /** Creates new form Area */
    public Frmko_member_deposit() throws CodeException {
        initComponents();
    }
    
    public Frmko_member_deposit(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();
        jlblmember_number = new javax.swing.JLabel();
        jtxtmember_number = new javax.swing.JTextField();
        jlblsimpanan_wajib = new javax.swing.JLabel();
        jtxtsimpanan_wajib = new javax.swing.JTextField();
        jlblsimpanan_pokok = new javax.swing.JLabel();
        jtxtsimpanan_pokok = new javax.swing.JTextField();
        jlblsimpanan_sukarela = new javax.swing.JLabel();
        jtxtsimpanan_sukarela = new javax.swing.JTextField();
        jlblsimpanan_khusus = new javax.swing.JLabel();
        jtxtsimpanan_khusus = new javax.swing.JTextField();
        jlblpinjaman = new javax.swing.JLabel();
        jtxtpinjaman = new javax.swing.JTextField();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ko_member_deposit");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : ko_member_deposit");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 200, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(420, 100, 30, 17);

        jlblmember_number.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmember_number.setText("member_number");
        getContentPane().add(jlblmember_number);
        jlblmember_number.setBounds(70, 100, 140, 13);

        jtxtmember_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_number.setText("member_number");
        jtxtmember_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_number);
        jtxtmember_number.setBounds(260, 100, 150, 23);

        jlblsimpanan_wajib.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsimpanan_wajib.setText("simpanan_wajib");
        getContentPane().add(jlblsimpanan_wajib);
        jlblsimpanan_wajib.setBounds(70, 120, 140, 13);

        jtxtsimpanan_wajib.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsimpanan_wajib.setText("simpanan_wajib");
        jtxtsimpanan_wajib.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsimpanan_wajibFocusGained(evt);
            }
        });
        getContentPane().add(jtxtsimpanan_wajib);
        jtxtsimpanan_wajib.setBounds(260, 120, 150, 23);

        jlblsimpanan_pokok.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsimpanan_pokok.setText("simpanan_pokok");
        getContentPane().add(jlblsimpanan_pokok);
        jlblsimpanan_pokok.setBounds(70, 140, 140, 13);

        jtxtsimpanan_pokok.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsimpanan_pokok.setText("simpanan_pokok");
        jtxtsimpanan_pokok.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsimpanan_pokokFocusGained(evt);
            }
        });
        getContentPane().add(jtxtsimpanan_pokok);
        jtxtsimpanan_pokok.setBounds(260, 140, 150, 23);

        jlblsimpanan_sukarela.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsimpanan_sukarela.setText("simpanan_sukarela");
        getContentPane().add(jlblsimpanan_sukarela);
        jlblsimpanan_sukarela.setBounds(70, 160, 140, 13);

        jtxtsimpanan_sukarela.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsimpanan_sukarela.setText("simpanan_sukarela");
        jtxtsimpanan_sukarela.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsimpanan_sukarelaFocusGained(evt);
            }
        });
        getContentPane().add(jtxtsimpanan_sukarela);
        jtxtsimpanan_sukarela.setBounds(260, 160, 150, 23);

        jlblsimpanan_khusus.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsimpanan_khusus.setText("simpanan_khusus");
        getContentPane().add(jlblsimpanan_khusus);
        jlblsimpanan_khusus.setBounds(70, 180, 140, 13);

        jtxtsimpanan_khusus.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsimpanan_khusus.setText("simpanan_khusus");
        jtxtsimpanan_khusus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsimpanan_khususFocusGained(evt);
            }
        });
        getContentPane().add(jtxtsimpanan_khusus);
        jtxtsimpanan_khusus.setBounds(260, 180, 150, 23);

        jlblpinjaman.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblpinjaman.setText("pinjaman");
        getContentPane().add(jlblpinjaman);
        jlblpinjaman.setBounds(70, 200, 140, 13);

        jtxtpinjaman.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtpinjaman.setText("pinjaman");
        jtxtpinjaman.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtpinjamanFocusGained(evt);
            }
        });
        getContentPane().add(jtxtpinjaman);
        jtxtpinjaman.setBounds(260, 200, 150, 23);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(360, 30, 170, 20);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(530, 30, 130, 20);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(660, 30, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jtxtmember_numberFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxtmember_number.setSelectionStart(0);
    jtxtmember_number.setSelectionEnd(jtxtmember_number.getText().length());
}                                             

private void jtxtsimpanan_wajibFocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
    jtxtsimpanan_wajib.setSelectionStart(0);
    jtxtsimpanan_wajib.setSelectionEnd(jtxtsimpanan_wajib.getText().length());
}                                              

private void jtxtsimpanan_pokokFocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
    jtxtsimpanan_pokok.setSelectionStart(0);
    jtxtsimpanan_pokok.setSelectionEnd(jtxtsimpanan_pokok.getText().length());
}                                              

private void jtxtsimpanan_sukarelaFocusGained(java.awt.event.FocusEvent evt) {                                               
        // TODO add your handling code here:
    jtxtsimpanan_sukarela.setSelectionStart(0);
    jtxtsimpanan_sukarela.setSelectionEnd(jtxtsimpanan_sukarela.getText().length());
}                                                 

private void jtxtsimpanan_khususFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtsimpanan_khusus.setSelectionStart(0);
    jtxtsimpanan_khusus.setSelectionEnd(jtxtsimpanan_khusus.getText().length());
}                                               

private void jtxtpinjamanFocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtpinjaman.setSelectionStart(0);
    jtxtpinjaman.setSelectionEnd(jtxtpinjaman.getText().length());
}                                        

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
    FrmBrowseData frmbrowse=new FrmBrowseData("ko_member_deposit", "");
    frmbrowse.setModal(true);
    frmbrowse.setVisible(true);
    try {
        //obj.initdata(frmbrowse.getValue());
        showData();
    } catch (CodeException ex) {
        Logger.getLogger(Frmko_member_deposit.class.getName()).log(Level.SEVERE, null, ex);
    }
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmko_member_deposit().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JLabel jlblmember_number;
    private javax.swing.JLabel jlblpinjaman;
    private javax.swing.JLabel jlblsimpanan_khusus;
    private javax.swing.JLabel jlblsimpanan_pokok;
    private javax.swing.JLabel jlblsimpanan_sukarela;
    private javax.swing.JLabel jlblsimpanan_wajib;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtmember_number;
    private javax.swing.JTextField jtxtpinjaman;
    private javax.swing.JTextField jtxtsimpanan_khusus;
    private javax.swing.JTextField jtxtsimpanan_pokok;
    private javax.swing.JTextField jtxtsimpanan_sukarela;
    private javax.swing.JTextField jtxtsimpanan_wajib;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jtxtmember_number.setText("");
        jtxtsimpanan_wajib.setText("");
        jtxtsimpanan_pokok.setText("");
        jtxtsimpanan_sukarela.setText("");
        jtxtsimpanan_khusus.setText("");
        jtxtpinjaman.setText("");

        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");
    }

    public void newData() throws CodeException {
        istatus=1;
        clearfield();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.update();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        jtxtmember_number.setText(obj.getmember_number());
        jtxtsimpanan_wajib.setText(GlobalUtils.formatnumber(obj.getsimpanan_wajib()));
        jtxtsimpanan_pokok.setText(GlobalUtils.formatnumber(obj.getsimpanan_pokok()));
        jtxtsimpanan_sukarela.setText(GlobalUtils.formatnumber(obj.getsimpanan_sukarela()));
        jtxtsimpanan_khusus.setText(GlobalUtils.formatnumber(obj.getsimpanan_khusus()));
        jtxtpinjaman.setText(GlobalUtils.formatnumber(obj.getpinjaman()));

        jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getentrydate()));
        jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getauditdate()));
        jtxtUserID.setText(obj.getaudituser());

        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        if (obj.delete()){
            obj.moveNext();
            showData();
        }
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);

        if (istatus==1){
            jbtnBrowse.setEnabled(false);
        } else {
            jbtnBrowse.setEnabled(true);
        }
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }
        obj.setmember_number(jtxtmember_number.getText());
        obj.setsimpanan_wajib(GlobalUtils.toDbl(jtxtsimpanan_wajib.getText()));
        obj.setsimpanan_pokok(GlobalUtils.toDbl(jtxtsimpanan_pokok.getText()));
        obj.setsimpanan_sukarela(GlobalUtils.toDbl(jtxtsimpanan_sukarela.getText()));
        obj.setsimpanan_khusus(GlobalUtils.toDbl(jtxtsimpanan_khusus.getText()));
        obj.setpinjaman(GlobalUtils.toDbl(jtxtpinjaman.getText()));
        
    }

    public void undo() throws CodeException {
        istatus = 0;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    
}
