/*
 * From ko_transaksi_bayar
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ko.component;


import classinterface.NavigatorFormInt;
import common.component.FrmBrowseData;
import common.component.FrmMainFrame;
import kopkar.ko.objectclasses.ko_transaksi_bayarext;
import java.util.logging.Level;
import java.util.logging.Logger;
import kopkar.ko.objectclasses.ko_anggotaext;
import kopkar.ko.objectclasses.ko_departemenext;
import kopkar.ko.objectclasses.ko_jabatanext;
import kopkar.ko.objectclasses.ko_transaksi_setuju_detailext;
import kopkar.ko.objectclasses.ko_transaksi_setujuext;
import kopkar.utils.browsecontroller;
import org.kazao.calendar.KazaoCalendarDateTimeException;
import utils.CodeException;
import utils.GlobalUtils;

/**
 *
 * @author  Generator
 */

public class Frmko_transaksi_bayar extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmko_transaksi_bayar";
    
    FrmMainFrame mf ;

    ko_transaksi_bayarext obj=new ko_transaksi_bayarext();
    private browsecontroller obrowse;
    private ko_anggotaext oagt;
    private ko_transaksi_bayarext objtmp;
   
    /** Creates new form Area */
    public Frmko_transaksi_bayar() throws CodeException {
        initComponents();
    }
    
    public Frmko_transaksi_bayar(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
        filldop_tagih();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jlblpelunasan = new javax.swing.JLabel();
        jlblauto_sts = new javax.swing.JLabel();
        jlblcash_sts = new javax.swing.JLabel();
        jlblbayar_angsuran = new javax.swing.JLabel();
        jtxtbayar_angsuran = new javax.swing.JTextField();
        jlblbayar_potongan = new javax.swing.JLabel();
        jtxtbayar_potongan = new javax.swing.JTextField();
        jlblangsuranke = new javax.swing.JLabel();
        jtxtangsuranke = new javax.swing.JTextField();
        jlblsisa_angsuranke = new javax.swing.JLabel();
        jtxtsisa_angsuranke = new javax.swing.JTextField();
        jtxtsaldo_pokok_bunga_awal = new javax.swing.JTextField();
        jtxtsaldo_pokok_awal = new javax.swing.JTextField();
        jtxtsaldo_bunga_awal = new javax.swing.JTextField();
        jtxtangsuran_pokok_bunga = new javax.swing.JTextField();
        jtxtangsuran_pokok = new javax.swing.JTextField();
        jtxtangsuran_bunga = new javax.swing.JTextField();
        jlblsaldo_pokok_bunga_akhir = new javax.swing.JLabel();
        jtxtsaldo_pokok_bunga_akhir = new javax.swing.JTextField();
        jlblsaldo_pokok_akhir = new javax.swing.JLabel();
        jtxtsaldo_pokok_akhir = new javax.swing.JTextField();
        jlblsaldo_bunga_akhir = new javax.swing.JLabel();
        jtxtsaldo_bunga_akhir = new javax.swing.JTextField();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();
        jHeader1 = new javax.swing.JLabel();
        jHeader2 = new javax.swing.JLabel();
        jHeader3 = new javax.swing.JLabel();
        joptauto_sts_manual = new javax.swing.JRadioButton();
        joptauto_sts_auto = new javax.swing.JRadioButton();
        joptcash_sts_tunai = new javax.swing.JRadioButton();
        joptcash_sts_potong_gaji = new javax.swing.JRadioButton();
        joptpelunasan_ya = new javax.swing.JRadioButton();
        joptpelunasan_tidak = new javax.swing.JRadioButton();
        jlblyop = new javax.swing.JLabel();
        jtxtyop = new javax.swing.JTextField();
        jlblmop = new javax.swing.JLabel();
        jlbldocument_number = new javax.swing.JLabel();
        jtxtdocument_number = new javax.swing.JTextField();
        jlbldocument_status = new javax.swing.JLabel();
        jtxtdocument_status = new javax.swing.JTextField();
        jlbldocument_date = new javax.swing.JLabel();
        kzodocument_date = new org.kazao.calendar.KazaoCalendarDate();
        jtxtmember_number = new javax.swing.JTextField();
        jbtnBrowse_anggota = new javax.swing.JButton();
        jlblmember_number1 = new javax.swing.JLabel();
        jlblmember_number2 = new javax.swing.JLabel();
        jtxtmember_name = new javax.swing.JTextField();
        jlblmember_number3 = new javax.swing.JLabel();
        jtxtmember_number2 = new javax.swing.JTextField();
        jlblmember_number4 = new javax.swing.JLabel();
        jtxtnama_departemen = new javax.swing.JTextField();
        jlblmember_number5 = new javax.swing.JLabel();
        jtxtnama_jabatan = new javax.swing.JTextField();
        jcmbmop = new javax.swing.JComboBox();
        jlblyop_start = new javax.swing.JLabel();
        jlbljumlah_angsuran = new javax.swing.JLabel();
        jlbljangka_waktu = new javax.swing.JLabel();
        jlblsuku_bunga = new javax.swing.JLabel();
        jlbljumlah_pinjaman = new javax.swing.JLabel();
        jlblkode_pinjaman1 = new javax.swing.JLabel();
        jtxtnama_pinjaman = new javax.swing.JTextField();
        jtxtjumlah_pinjaman = new javax.swing.JTextField();
        jtxtsuku_bunga = new javax.swing.JTextField();
        jtxtjangka_waktu = new javax.swing.JTextField();
        jtxtjumlah_angsuran = new javax.swing.JTextField();
        jcmbmop_start = new javax.swing.JComboBox();
        jtxtyop_start = new javax.swing.JTextField();
        jopthitung_bunga_flat = new javax.swing.JRadioButton();
        joptsatuan_waktu_harian = new javax.swing.JRadioButton();
        jopthitung_bunga_menurun = new javax.swing.JRadioButton();
        joptsatuan_waktu_mingguan = new javax.swing.JRadioButton();
        joptsatuan_waktu_bulanan = new javax.swing.JRadioButton();
        jlblkode_pinjaman2 = new javax.swing.JLabel();
        jtxtreference_number = new javax.swing.JTextField();
        jbtnBrowse_pinjaman1 = new javax.swing.JButton();
        jopt_complete_status_draff = new javax.swing.JRadioButton();
        jopt_complete_status_complete = new javax.swing.JRadioButton();
        jlblreference = new javax.swing.JLabel();
        jlbldscription = new javax.swing.JLabel();
        jtxtreference = new javax.swing.JTextField();
        jtxtdscription = new javax.swing.JTextField();
        jbtnBrowse = new javax.swing.JButton();
        jlbldocument_date1 = new javax.swing.JLabel();
        jcmbdop_tagih = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bayar Pinjaman");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHeader.setText("Saldo Akhir");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(560, 420, 150, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jlblpelunasan.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblpelunasan.setText("Pelunasan");
        getContentPane().add(jlblpelunasan);
        jlblpelunasan.setBounds(70, 280, 140, 13);

        jlblauto_sts.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblauto_sts.setText("Proses ");
        getContentPane().add(jlblauto_sts);
        jlblauto_sts.setBounds(70, 300, 140, 13);

        jlblcash_sts.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcash_sts.setText("Metode Pembayaran");
        getContentPane().add(jlblcash_sts);
        jlblcash_sts.setBounds(70, 320, 140, 13);

        jlblbayar_angsuran.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblbayar_angsuran.setText("Jumlah Bayar Angsuran");
        getContentPane().add(jlblbayar_angsuran);
        jlblbayar_angsuran.setBounds(70, 370, 140, 13);

        jtxtbayar_angsuran.setEditable(false);
        jtxtbayar_angsuran.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtbayar_angsuran.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtbayar_angsuran.setText("bayar_angsuran");
        jtxtbayar_angsuran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtbayar_angsuranFocusGained(evt);
            }
        });
        getContentPane().add(jtxtbayar_angsuran);
        jtxtbayar_angsuran.setBounds(260, 370, 150, 23);

        jlblbayar_potongan.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblbayar_potongan.setText("Jumlah Bayar Potongan");
        getContentPane().add(jlblbayar_potongan);
        jlblbayar_potongan.setBounds(70, 390, 140, 13);

        jtxtbayar_potongan.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtbayar_potongan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtbayar_potongan.setText("bayar_potongan");
        jtxtbayar_potongan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtbayar_potonganFocusGained(evt);
            }
        });
        jtxtbayar_potongan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtbayar_potonganKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtbayar_potongan);
        jtxtbayar_potongan.setBounds(260, 390, 150, 23);

        jlblangsuranke.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblangsuranke.setText("Angsuran ke");
        getContentPane().add(jlblangsuranke);
        jlblangsuranke.setBounds(70, 350, 140, 13);

        jtxtangsuranke.setEditable(false);
        jtxtangsuranke.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtangsuranke.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtangsuranke.setText("angsuranke");
        jtxtangsuranke.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtangsurankeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtangsuranke);
        jtxtangsuranke.setBounds(260, 350, 150, 23);

        jlblsisa_angsuranke.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsisa_angsuranke.setText("Sisa Angsuran");
        getContentPane().add(jlblsisa_angsuranke);
        jlblsisa_angsuranke.setBounds(420, 350, 140, 13);

        jtxtsisa_angsuranke.setEditable(false);
        jtxtsisa_angsuranke.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsisa_angsuranke.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsisa_angsuranke.setText("sisa_angsuranke");
        jtxtsisa_angsuranke.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsisa_angsurankeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtsisa_angsuranke);
        jtxtsisa_angsuranke.setBounds(610, 350, 150, 23);

        jtxtsaldo_pokok_bunga_awal.setEditable(false);
        jtxtsaldo_pokok_bunga_awal.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsaldo_pokok_bunga_awal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsaldo_pokok_bunga_awal.setText("saldo_pokok_bunga_awal");
        jtxtsaldo_pokok_bunga_awal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsaldo_pokok_bunga_awalFocusGained(evt);
            }
        });
        getContentPane().add(jtxtsaldo_pokok_bunga_awal);
        jtxtsaldo_pokok_bunga_awal.setBounds(260, 480, 150, 23);

        jtxtsaldo_pokok_awal.setEditable(false);
        jtxtsaldo_pokok_awal.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsaldo_pokok_awal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsaldo_pokok_awal.setText("saldo_pokok_awal");
        jtxtsaldo_pokok_awal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsaldo_pokok_awalFocusGained(evt);
            }
        });
        getContentPane().add(jtxtsaldo_pokok_awal);
        jtxtsaldo_pokok_awal.setBounds(260, 440, 150, 23);

        jtxtsaldo_bunga_awal.setEditable(false);
        jtxtsaldo_bunga_awal.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsaldo_bunga_awal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsaldo_bunga_awal.setText("saldo_bunga_awal");
        jtxtsaldo_bunga_awal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsaldo_bunga_awalFocusGained(evt);
            }
        });
        getContentPane().add(jtxtsaldo_bunga_awal);
        jtxtsaldo_bunga_awal.setBounds(260, 460, 150, 23);

        jtxtangsuran_pokok_bunga.setEditable(false);
        jtxtangsuran_pokok_bunga.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtangsuran_pokok_bunga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtangsuran_pokok_bunga.setText("angsuran_pokok_bunga");
        jtxtangsuran_pokok_bunga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtangsuran_pokok_bungaFocusGained(evt);
            }
        });
        getContentPane().add(jtxtangsuran_pokok_bunga);
        jtxtangsuran_pokok_bunga.setBounds(410, 480, 150, 23);

        jtxtangsuran_pokok.setEditable(false);
        jtxtangsuran_pokok.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtangsuran_pokok.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtangsuran_pokok.setText("angsuran_pokok");
        jtxtangsuran_pokok.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtangsuran_pokokFocusGained(evt);
            }
        });
        jtxtangsuran_pokok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtangsuran_pokokKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtangsuran_pokok);
        jtxtangsuran_pokok.setBounds(410, 440, 150, 23);

        jtxtangsuran_bunga.setEditable(false);
        jtxtangsuran_bunga.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtangsuran_bunga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtangsuran_bunga.setText("angsuran_bunga");
        jtxtangsuran_bunga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtangsuran_bungaFocusGained(evt);
            }
        });
        jtxtangsuran_bunga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtangsuran_bungaKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtangsuran_bunga);
        jtxtangsuran_bunga.setBounds(410, 460, 150, 23);

        jlblsaldo_pokok_bunga_akhir.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsaldo_pokok_bunga_akhir.setText("Pokok");
        getContentPane().add(jlblsaldo_pokok_bunga_akhir);
        jlblsaldo_pokok_bunga_akhir.setBounds(70, 440, 140, 13);

        jtxtsaldo_pokok_bunga_akhir.setEditable(false);
        jtxtsaldo_pokok_bunga_akhir.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsaldo_pokok_bunga_akhir.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsaldo_pokok_bunga_akhir.setText("saldo_pokok_bunga_akhir");
        jtxtsaldo_pokok_bunga_akhir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsaldo_pokok_bunga_akhirFocusGained(evt);
            }
        });
        getContentPane().add(jtxtsaldo_pokok_bunga_akhir);
        jtxtsaldo_pokok_bunga_akhir.setBounds(560, 480, 150, 23);

        jlblsaldo_pokok_akhir.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsaldo_pokok_akhir.setText("Bunga");
        getContentPane().add(jlblsaldo_pokok_akhir);
        jlblsaldo_pokok_akhir.setBounds(70, 460, 140, 13);

        jtxtsaldo_pokok_akhir.setEditable(false);
        jtxtsaldo_pokok_akhir.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsaldo_pokok_akhir.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsaldo_pokok_akhir.setText("saldo_pokok_akhir");
        jtxtsaldo_pokok_akhir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsaldo_pokok_akhirFocusGained(evt);
            }
        });
        getContentPane().add(jtxtsaldo_pokok_akhir);
        jtxtsaldo_pokok_akhir.setBounds(560, 440, 150, 23);

        jlblsaldo_bunga_akhir.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsaldo_bunga_akhir.setText("Sisa Jumlah Angsuran");
        getContentPane().add(jlblsaldo_bunga_akhir);
        jlblsaldo_bunga_akhir.setBounds(70, 480, 140, 13);

        jtxtsaldo_bunga_akhir.setEditable(false);
        jtxtsaldo_bunga_akhir.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsaldo_bunga_akhir.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsaldo_bunga_akhir.setText("saldo_bunga_akhir");
        jtxtsaldo_bunga_akhir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsaldo_bunga_akhirFocusGained(evt);
            }
        });
        getContentPane().add(jtxtsaldo_bunga_akhir);
        jtxtsaldo_bunga_akhir.setBounds(560, 460, 150, 23);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(360, 30, 170, 20);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(530, 30, 130, 20);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(660, 30, 140, 20);

        jHeader1.setBackground(new java.awt.Color(102, 102, 102));
        jHeader1.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader1.setForeground(new java.awt.Color(255, 255, 255));
        jHeader1.setText(" : : Bayar Pinjaman");
        jHeader1.setAlignmentY(0.0F);
        jHeader1.setOpaque(true);
        getContentPane().add(jHeader1);
        jHeader1.setBounds(30, 30, 200, 20);

        jHeader2.setBackground(new java.awt.Color(102, 102, 102));
        jHeader2.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader2.setForeground(new java.awt.Color(255, 255, 255));
        jHeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHeader2.setText("Saldo Awal");
        jHeader2.setAlignmentY(0.0F);
        jHeader2.setOpaque(true);
        getContentPane().add(jHeader2);
        jHeader2.setBounds(260, 420, 150, 20);

        jHeader3.setBackground(new java.awt.Color(102, 102, 102));
        jHeader3.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader3.setForeground(new java.awt.Color(255, 255, 255));
        jHeader3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHeader3.setText("Angsuran");
        jHeader3.setAlignmentY(0.0F);
        jHeader3.setOpaque(true);
        getContentPane().add(jHeader3);
        jHeader3.setBounds(410, 420, 150, 20);

        buttonGroup1.add(joptauto_sts_manual);
        joptauto_sts_manual.setFont(new java.awt.Font("Dialog", 1, 10));
        joptauto_sts_manual.setSelected(true);
        joptauto_sts_manual.setText("Manual");
        getContentPane().add(joptauto_sts_manual);
        joptauto_sts_manual.setBounds(260, 300, 66, 24);

        buttonGroup1.add(joptauto_sts_auto);
        joptauto_sts_auto.setFont(new java.awt.Font("Dialog", 1, 10));
        joptauto_sts_auto.setText("Otomatis");
        getContentPane().add(joptauto_sts_auto);
        joptauto_sts_auto.setBounds(350, 300, 123, 24);

        buttonGroup2.add(joptcash_sts_tunai);
        joptcash_sts_tunai.setFont(new java.awt.Font("Dialog", 1, 10));
        joptcash_sts_tunai.setSelected(true);
        joptcash_sts_tunai.setText("Tunai");
        getContentPane().add(joptcash_sts_tunai);
        joptcash_sts_tunai.setBounds(260, 320, 57, 24);

        buttonGroup2.add(joptcash_sts_potong_gaji);
        joptcash_sts_potong_gaji.setFont(new java.awt.Font("Dialog", 1, 10));
        joptcash_sts_potong_gaji.setText("Potong Gaji");
        getContentPane().add(joptcash_sts_potong_gaji);
        joptcash_sts_potong_gaji.setBounds(350, 320, 130, 24);

        buttonGroup5.add(joptpelunasan_ya);
        joptpelunasan_ya.setFont(new java.awt.Font("Dialog", 1, 10));
        joptpelunasan_ya.setText("Ya");
        joptpelunasan_ya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joptpelunasan_yaActionPerformed(evt);
            }
        });
        getContentPane().add(joptpelunasan_ya);
        joptpelunasan_ya.setBounds(260, 280, 40, 24);

        buttonGroup5.add(joptpelunasan_tidak);
        joptpelunasan_tidak.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        joptpelunasan_tidak.setSelected(true);
        joptpelunasan_tidak.setText("Tidak");
        joptpelunasan_tidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joptpelunasan_tidakActionPerformed(evt);
            }
        });
        getContentPane().add(joptpelunasan_tidak);
        joptpelunasan_tidak.setBounds(350, 280, 123, 24);

        jlblyop.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblyop.setText("Tahun");
        getContentPane().add(jlblyop);
        jlblyop.setBounds(70, 80, 140, 13);

        jtxtyop.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtyop.setText("yop");
        jtxtyop.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtyopFocusGained(evt);
            }
        });
        getContentPane().add(jtxtyop);
        jtxtyop.setBounds(160, 80, 50, 23);

        jlblmop.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmop.setText("Periode");
        getContentPane().add(jlblmop);
        jlblmop.setBounds(250, 80, 110, 13);

        jlbldocument_number.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_number.setText("No. Registrasi");
        getContentPane().add(jlbldocument_number);
        jlbldocument_number.setBounds(520, 100, 110, 13);

        jtxtdocument_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdocument_number.setText("document_number");
        jtxtdocument_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocument_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdocument_number);
        jtxtdocument_number.setBounds(710, 100, 120, 23);

        jlbldocument_status.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_status.setText("Status");
        getContentPane().add(jlbldocument_status);
        jlbldocument_status.setBounds(520, 80, 140, 13);

        jtxtdocument_status.setEditable(false);
        jtxtdocument_status.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdocument_status.setText("document_status");
        jtxtdocument_status.setFocusable(false);
        jtxtdocument_status.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocument_statusFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdocument_status);
        jtxtdocument_status.setBounds(710, 80, 150, 23);

        jlbldocument_date.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_date.setText("Tgl. Dokumen");
        getContentPane().add(jlbldocument_date);
        jlbldocument_date.setBounds(520, 120, 140, 13);

        kzodocument_date.setFont(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date.setOpaque(false);
        getContentPane().add(kzodocument_date);
        kzodocument_date.setBounds(710, 120, 100, 20);

        jtxtmember_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_number.setText("member_number");
        jtxtmember_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_number);
        jtxtmember_number.setBounds(260, 120, 150, 23);

        jbtnBrowse_anggota.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse_anggota.setText("...");
        jbtnBrowse_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_anggotaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse_anggota);
        jbtnBrowse_anggota.setBounds(410, 120, 30, 17);

        jlblmember_number1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmember_number1.setText("No. Anggota");
        getContentPane().add(jlblmember_number1);
        jlblmember_number1.setBounds(70, 120, 140, 13);

        jlblmember_number2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmember_number2.setText("Nama Anggota");
        getContentPane().add(jlblmember_number2);
        jlblmember_number2.setBounds(70, 140, 140, 13);

        jtxtmember_name.setEditable(false);
        jtxtmember_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_name.setText("member_number");
        jtxtmember_name.setFocusable(false);
        jtxtmember_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_nameFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_name);
        jtxtmember_name.setBounds(260, 140, 260, 23);

        jlblmember_number3.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmember_number3.setText("N.I.K");
        getContentPane().add(jlblmember_number3);
        jlblmember_number3.setBounds(70, 160, 140, 13);

        jtxtmember_number2.setEditable(false);
        jtxtmember_number2.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_number2.setText("member_number");
        jtxtmember_number2.setFocusable(false);
        jtxtmember_number2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_number2FocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_number2);
        jtxtmember_number2.setBounds(260, 160, 150, 23);

        jlblmember_number4.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmember_number4.setText("Departemen");
        getContentPane().add(jlblmember_number4);
        jlblmember_number4.setBounds(520, 140, 140, 13);

        jtxtnama_departemen.setEditable(false);
        jtxtnama_departemen.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtnama_departemen.setText("member_number");
        jtxtnama_departemen.setFocusable(false);
        jtxtnama_departemen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtnama_departemenFocusGained(evt);
            }
        });
        getContentPane().add(jtxtnama_departemen);
        jtxtnama_departemen.setBounds(710, 140, 150, 23);

        jlblmember_number5.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmember_number5.setText("Jabatan");
        getContentPane().add(jlblmember_number5);
        jlblmember_number5.setBounds(520, 160, 140, 13);

        jtxtnama_jabatan.setEditable(false);
        jtxtnama_jabatan.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtnama_jabatan.setText("member_number");
        jtxtnama_jabatan.setFocusable(false);
        jtxtnama_jabatan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtnama_jabatanFocusGained(evt);
            }
        });
        getContentPane().add(jtxtnama_jabatan);
        jtxtnama_jabatan.setBounds(710, 160, 150, 23);

        jcmbmop.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbmop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        getContentPane().add(jcmbmop);
        jcmbmop.setBounds(310, 80, 90, 20);

        jlblyop_start.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblyop_start.setText("Periode Mulai Angsuran");
        getContentPane().add(jlblyop_start);
        jlblyop_start.setBounds(70, 260, 140, 13);

        jlbljumlah_angsuran.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbljumlah_angsuran.setText("Jumlah Angsuran");
        getContentPane().add(jlbljumlah_angsuran);
        jlbljumlah_angsuran.setBounds(70, 240, 140, 13);

        jlbljangka_waktu.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbljangka_waktu.setText("Jangka Waktu");
        getContentPane().add(jlbljangka_waktu);
        jlbljangka_waktu.setBounds(70, 220, 140, 13);

        jlblsuku_bunga.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsuku_bunga.setText("Suku Bunga");
        getContentPane().add(jlblsuku_bunga);
        jlblsuku_bunga.setBounds(520, 200, 140, 13);

        jlbljumlah_pinjaman.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbljumlah_pinjaman.setText("Jumlah pinjaman");
        getContentPane().add(jlbljumlah_pinjaman);
        jlbljumlah_pinjaman.setBounds(70, 200, 140, 13);

        jlblkode_pinjaman1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblkode_pinjaman1.setText("Nama Pinjaman");
        getContentPane().add(jlblkode_pinjaman1);
        jlblkode_pinjaman1.setBounds(520, 180, 140, 13);

        jtxtnama_pinjaman.setEditable(false);
        jtxtnama_pinjaman.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtnama_pinjaman.setFocusable(false);
        getContentPane().add(jtxtnama_pinjaman);
        jtxtnama_pinjaman.setBounds(710, 180, 270, 23);

        jtxtjumlah_pinjaman.setEditable(false);
        jtxtjumlah_pinjaman.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtjumlah_pinjaman.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtjumlah_pinjaman.setText("jumlah_pinjaman");
        jtxtjumlah_pinjaman.setFocusable(false);
        jtxtjumlah_pinjaman.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtjumlah_pinjamanFocusGained(evt);
            }
        });
        jtxtjumlah_pinjaman.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtjumlah_pinjamanKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtjumlah_pinjaman);
        jtxtjumlah_pinjaman.setBounds(260, 200, 150, 23);

        jtxtsuku_bunga.setEditable(false);
        jtxtsuku_bunga.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsuku_bunga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsuku_bunga.setText("suku_bunga");
        jtxtsuku_bunga.setFocusable(false);
        jtxtsuku_bunga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsuku_bungaFocusGained(evt);
            }
        });
        jtxtsuku_bunga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsuku_bungaKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtsuku_bunga);
        jtxtsuku_bunga.setBounds(710, 200, 150, 23);

        jtxtjangka_waktu.setEditable(false);
        jtxtjangka_waktu.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtjangka_waktu.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtjangka_waktu.setText("jangka_waktu");
        jtxtjangka_waktu.setFocusable(false);
        jtxtjangka_waktu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtjangka_waktuFocusGained(evt);
            }
        });
        jtxtjangka_waktu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtjangka_waktuKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtjangka_waktu);
        jtxtjangka_waktu.setBounds(260, 220, 150, 23);

        jtxtjumlah_angsuran.setEditable(false);
        jtxtjumlah_angsuran.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtjumlah_angsuran.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtjumlah_angsuran.setText("jumlah_angsuran");
        jtxtjumlah_angsuran.setFocusable(false);
        jtxtjumlah_angsuran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtjumlah_angsuranFocusGained(evt);
            }
        });
        getContentPane().add(jtxtjumlah_angsuran);
        jtxtjumlah_angsuran.setBounds(260, 240, 150, 23);

        jcmbmop_start.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbmop_start.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        jcmbmop_start.setEnabled(false);
        jcmbmop_start.setFocusable(false);
        getContentPane().add(jcmbmop_start);
        jcmbmop_start.setBounds(260, 260, 90, 20);

        jtxtyop_start.setEditable(false);
        jtxtyop_start.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtyop_start.setText("yop_start");
        jtxtyop_start.setFocusable(false);
        jtxtyop_start.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtyop_startFocusGained(evt);
            }
        });
        getContentPane().add(jtxtyop_start);
        jtxtyop_start.setBounds(350, 260, 60, 23);

        jopthitung_bunga_flat.setFont(new java.awt.Font("Dialog", 1, 10));
        jopthitung_bunga_flat.setSelected(true);
        jopthitung_bunga_flat.setText("Flat");
        jopthitung_bunga_flat.setEnabled(false);
        jopthitung_bunga_flat.setFocusable(false);
        getContentPane().add(jopthitung_bunga_flat);
        jopthitung_bunga_flat.setBounds(520, 220, 47, 24);

        joptsatuan_waktu_harian.setFont(new java.awt.Font("Dialog", 1, 10));
        joptsatuan_waktu_harian.setSelected(true);
        joptsatuan_waktu_harian.setText("Harian");
        joptsatuan_waktu_harian.setEnabled(false);
        joptsatuan_waktu_harian.setFocusable(false);
        getContentPane().add(joptsatuan_waktu_harian);
        joptsatuan_waktu_harian.setBounds(520, 240, 71, 24);

        jopthitung_bunga_menurun.setFont(new java.awt.Font("Dialog", 1, 10));
        jopthitung_bunga_menurun.setText("Bunga Menurun");
        jopthitung_bunga_menurun.setEnabled(false);
        jopthitung_bunga_menurun.setFocusable(false);
        getContentPane().add(jopthitung_bunga_menurun);
        jopthitung_bunga_menurun.setBounds(580, 220, 123, 24);

        joptsatuan_waktu_mingguan.setFont(new java.awt.Font("Dialog", 1, 10));
        joptsatuan_waktu_mingguan.setText("Mingguan");
        joptsatuan_waktu_mingguan.setEnabled(false);
        joptsatuan_waktu_mingguan.setFocusable(false);
        getContentPane().add(joptsatuan_waktu_mingguan);
        joptsatuan_waktu_mingguan.setBounds(600, 240, 100, 24);

        joptsatuan_waktu_bulanan.setFont(new java.awt.Font("Dialog", 1, 10));
        joptsatuan_waktu_bulanan.setText("Bulanan");
        joptsatuan_waktu_bulanan.setEnabled(false);
        joptsatuan_waktu_bulanan.setFocusable(false);
        getContentPane().add(joptsatuan_waktu_bulanan);
        joptsatuan_waktu_bulanan.setBounds(700, 240, 123, 24);

        jlblkode_pinjaman2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblkode_pinjaman2.setText("No. Referensi");
        getContentPane().add(jlblkode_pinjaman2);
        jlblkode_pinjaman2.setBounds(70, 180, 140, 13);

        jtxtreference_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtreference_number.setText("kode_pinjaman");
        jtxtreference_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtreference_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtreference_number);
        jtxtreference_number.setBounds(260, 180, 150, 23);

        jbtnBrowse_pinjaman1.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse_pinjaman1.setText("...");
        jbtnBrowse_pinjaman1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_pinjaman1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse_pinjaman1);
        jbtnBrowse_pinjaman1.setBounds(410, 180, 30, 17);

        buttonGroup4.add(jopt_complete_status_draff);
        jopt_complete_status_draff.setFont(new java.awt.Font("Dialog", 0, 10));
        jopt_complete_status_draff.setSelected(true);
        jopt_complete_status_draff.setText("Draff");
        jopt_complete_status_draff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jopt_complete_status_draffActionPerformed(evt);
            }
        });
        getContentPane().add(jopt_complete_status_draff);
        jopt_complete_status_draff.setBounds(70, 570, 52, 24);

        buttonGroup4.add(jopt_complete_status_complete);
        jopt_complete_status_complete.setFont(new java.awt.Font("Dialog", 0, 10));
        jopt_complete_status_complete.setText("Complete");
        jopt_complete_status_complete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jopt_complete_status_completeActionPerformed(evt);
            }
        });
        getContentPane().add(jopt_complete_status_complete);
        jopt_complete_status_complete.setBounds(150, 570, 123, 24);

        jlblreference.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblreference.setText("Referensi");
        getContentPane().add(jlblreference);
        jlblreference.setBounds(70, 510, 140, 13);

        jlbldscription.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldscription.setText("Keterangan");
        getContentPane().add(jlbldscription);
        jlbldscription.setBounds(70, 530, 140, 13);

        jtxtreference.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtreference.setText("reference");
        jtxtreference.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtreferenceFocusGained(evt);
            }
        });
        getContentPane().add(jtxtreference);
        jtxtreference.setBounds(260, 510, 340, 23);

        jtxtdscription.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdscription.setText("dscription");
        jtxtdscription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdscriptionFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdscription);
        jtxtdscription.setBounds(260, 530, 340, 23);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(830, 100, 30, 17);

        jlbldocument_date1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_date1.setText("Tanggal Penagihan");
        getContentPane().add(jlbldocument_date1);
        jlbldocument_date1.setBounds(520, 260, 140, 13);

        jcmbdop_tagih.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbdop_tagih.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcmbdop_tagih);
        jcmbdop_tagih.setBounds(710, 260, 65, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jtxtyopFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtyopFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtyopFocusGained

private void jtxtdocument_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdocument_numberFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdocument_numberFocusGained

private void jtxtdocument_statusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdocument_statusFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdocument_statusFocusGained

private void jtxtmember_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtmember_numberFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtmember_numberFocusGained

private void jbtnBrowse_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_anggotaActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_anggota, "", jtxtmember_number);

    if (!jtxtmember_number.getText().equalsIgnoreCase("")){
        showanggota();
    }
}//GEN-LAST:event_jbtnBrowse_anggotaActionPerformed

private void showanggota() {
        oagt=new ko_anggotaext();
        try {
            oagt.initdata(jtxtmember_number.getText());
            jtxtmember_name.setText(oagt.getmember_name());
            jtxtmember_number2.setText(oagt.getemployee_number());
            ko_departemenext odept=oagt.getdepinfo();
            ko_jabatanext ojbt=oagt.getjbtinfo();
            jtxtnama_departemen.setText(odept.getnama_departemen());
            jtxtnama_jabatan.setText(ojbt.getnama_jabatan());
            
        } catch (CodeException ex) {
            Logger.getLogger(Frmko_transaksi_bayar.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


private void jtxtmember_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtmember_nameFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtmember_nameFocusGained

private void jtxtmember_number2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtmember_number2FocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtmember_number2FocusGained

private void jtxtnama_departemenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtnama_departemenFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtnama_departemenFocusGained

private void jtxtnama_jabatanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtnama_jabatanFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtnama_jabatanFocusGained

private void jtxtnama_pinjamanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtnama_pinjamanFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtnama_pinjamanFocusGained

private void jtxtjumlah_pinjamanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtjumlah_pinjamanFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtjumlah_pinjamanFocusGained

private void jtxtjumlah_pinjamanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtjumlah_pinjamanKeyReleased
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtjumlah_pinjaman);

}//GEN-LAST:event_jtxtjumlah_pinjamanKeyReleased

private void jtxtsuku_bungaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsuku_bungaFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtsuku_bungaFocusGained

private void jtxtsuku_bungaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsuku_bungaKeyReleased
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtsuku_bungaKeyReleased

private void jtxtjangka_waktuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtjangka_waktuFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtjangka_waktuFocusGained

private void jtxtjangka_waktuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtjangka_waktuKeyReleased
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtjangka_waktu);
}//GEN-LAST:event_jtxtjangka_waktuKeyReleased

private void jtxtjumlah_angsuranFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtjumlah_angsuranFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtjumlah_angsuranFocusGained

private void jtxtyop_startFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtyop_startFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtyop_startFocusGained

private void jtxtreference_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtreference_numberFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtreference_numberFocusGained

private void jbtnBrowse_pinjaman1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_pinjaman1ActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_transaksi_setuju, "member_number='"+jtxtmember_number.getText()+"' and document_status='C' and angsur_sts='Y'", jtxtreference_number);

    if (!jtxtreference_number.getText().equalsIgnoreCase("")){
        showpermohonan_detail(jtxtreference_number.getText());
    }
}//GEN-LAST:event_jbtnBrowse_pinjaman1ActionPerformed

private void jtxtreferenceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtreferenceFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtreferenceFocusGained

private void jtxtdscriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdscriptionFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdscriptionFocusGained

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_transaksi_bayar, "", jtxtdocument_number);
    if (!jtxtdocument_number.getText().equalsIgnoreCase("")){
        try {
            if (obj.initdata(jtxtdocument_number.getText())) {
                showData();
            }
        } catch (CodeException ex) {
            Logger.getLogger(Frmko_transaksi_setor_simpanan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}//GEN-LAST:event_jbtnBrowseActionPerformed

private void joptpelunasan_yaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joptpelunasan_yaActionPerformed
    // TODO add your handling code here:
        showpermohonan_detail(jtxtreference_number.getText());
}//GEN-LAST:event_joptpelunasan_yaActionPerformed

private void joptpelunasan_tidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joptpelunasan_tidakActionPerformed
    // TODO add your handling code here:
        showpermohonan_detail(jtxtreference_number.getText());
}//GEN-LAST:event_joptpelunasan_tidakActionPerformed

private void jtxtangsuran_pokokKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtangsuran_pokokKeyReleased
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtangsuran_pokok);
}//GEN-LAST:event_jtxtangsuran_pokokKeyReleased

private void jtxtangsuran_bungaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtangsuran_bungaKeyReleased
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtangsuran_bunga);
}//GEN-LAST:event_jtxtangsuran_bungaKeyReleased

private void jtxtbayar_potonganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbayar_potonganKeyReleased
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtbayar_potongan);

    Double bayar_potongan=GlobalUtils.toDbl(jtxtbayar_potongan.getText());
    Double angsuran_bunga=GlobalUtils.toDbl(jtxtangsuran_bunga.getText());

    if (bayar_potongan>angsuran_bunga){
        bayar_potongan=angsuran_bunga;

        jtxtbayar_potongan.setText(GlobalUtils.formatnumber(bayar_potongan));
    }
}//GEN-LAST:event_jtxtbayar_potonganKeyReleased

private void jopt_complete_status_draffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jopt_complete_status_draffActionPerformed
    // TODO add your handling code here:
    disable_when_complete(jopt_complete_status_draff.isSelected());
}//GEN-LAST:event_jopt_complete_status_draffActionPerformed

private void jopt_complete_status_completeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jopt_complete_status_completeActionPerformed
    // TODO add your handling code here:
    disable_when_complete(jopt_complete_status_draff.isSelected());
}//GEN-LAST:event_jopt_complete_status_completeActionPerformed

private void showpermohonan(String document_number) {
    ko_transaksi_setujuext omohon=new ko_transaksi_setujuext();
    try {
        omohon.initdata(document_number);
        jtxtnama_pinjaman.setText(omohon.getnama_pinjaman());
        jtxtjumlah_pinjaman.setText(GlobalUtils.formatnumber(omohon.getjumlah_pinjaman()));
        jtxtsuku_bunga.setText(GlobalUtils.formatnumber(omohon.getsuku_bunga()));
        jtxtjangka_waktu.setText(GlobalUtils.formatnumber(omohon.getjangka_waktu()));
        if (omohon.getsatuan_waktu().equals("1")){
            joptsatuan_waktu_harian.setSelected(true);
        } else if (omohon.getsatuan_waktu().equals("2")){
            joptsatuan_waktu_mingguan.setSelected(true);
        } else {
            joptsatuan_waktu_bulanan.setSelected(true);
        }
        if (omohon.gethitung_bunga().equalsIgnoreCase("1")){
            jopthitung_bunga_flat.setSelected(true);
        } else {
            jopthitung_bunga_menurun.setSelected(true);
        }
        jtxtjumlah_angsuran.setText(GlobalUtils.formatnumber(omohon.getjumlah_angsuran()));
        jtxtyop_start.setText(GlobalUtils.churuf(omohon.getyop_start()));
        jcmbmop_start.setSelectedIndex(omohon.getmop_start()-1);
        if (omohon.getauto_sts().equalsIgnoreCase("Y")){
            joptauto_sts_auto.setSelected(true);
        } else {
            joptauto_sts_manual.setSelected(true);
        }

    } catch (CodeException ex) {
        Logger.getLogger(Frmko_transaksi_bayar.class.getName()).log(Level.SEVERE, null, ex);
    }
}

private void jtxtbayar_angsuranFocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
    jtxtbayar_angsuran.setSelectionStart(0);
    jtxtbayar_angsuran.setSelectionEnd(jtxtbayar_angsuran.getText().length());
}                                              

private void jtxtbayar_potonganFocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
    jtxtbayar_potongan.setSelectionStart(0);
    jtxtbayar_potongan.setSelectionEnd(jtxtbayar_potongan.getText().length());
}                                              

private void jtxtangsurankeFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
    jtxtangsuranke.setSelectionStart(0);
    jtxtangsuranke.setSelectionEnd(jtxtangsuranke.getText().length());
}                                          

private void jtxtsisa_angsurankeFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtsisa_angsuranke.setSelectionStart(0);
    jtxtsisa_angsuranke.setSelectionEnd(jtxtsisa_angsuranke.getText().length());
}                                               

private void jtxtsaldo_pokok_bunga_awalFocusGained(java.awt.event.FocusEvent evt) {                                                    
        // TODO add your handling code here:
    jtxtsaldo_pokok_bunga_awal.setSelectionStart(0);
    jtxtsaldo_pokok_bunga_awal.setSelectionEnd(jtxtsaldo_pokok_bunga_awal.getText().length());
}                                                      

private void jtxtsaldo_pokok_awalFocusGained(java.awt.event.FocusEvent evt) {                                              
        // TODO add your handling code here:
    jtxtsaldo_pokok_awal.setSelectionStart(0);
    jtxtsaldo_pokok_awal.setSelectionEnd(jtxtsaldo_pokok_awal.getText().length());
}                                                

private void jtxtsaldo_bunga_awalFocusGained(java.awt.event.FocusEvent evt) {                                              
        // TODO add your handling code here:
    jtxtsaldo_bunga_awal.setSelectionStart(0);
    jtxtsaldo_bunga_awal.setSelectionEnd(jtxtsaldo_bunga_awal.getText().length());
}                                                

private void jtxtangsuran_pokok_bungaFocusGained(java.awt.event.FocusEvent evt) {                                                  
        // TODO add your handling code here:
    jtxtangsuran_pokok_bunga.setSelectionStart(0);
    jtxtangsuran_pokok_bunga.setSelectionEnd(jtxtangsuran_pokok_bunga.getText().length());
}                                                    

private void jtxtangsuran_pokokFocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
    jtxtangsuran_pokok.setSelectionStart(0);
    jtxtangsuran_pokok.setSelectionEnd(jtxtangsuran_pokok.getText().length());
}                                              

private void jtxtangsuran_bungaFocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
    jtxtangsuran_bunga.setSelectionStart(0);
    jtxtangsuran_bunga.setSelectionEnd(jtxtangsuran_bunga.getText().length());
}                                              

private void jtxtsaldo_pokok_bunga_akhirFocusGained(java.awt.event.FocusEvent evt) {                                                     
        // TODO add your handling code here:
    jtxtsaldo_pokok_bunga_akhir.setSelectionStart(0);
    jtxtsaldo_pokok_bunga_akhir.setSelectionEnd(jtxtsaldo_pokok_bunga_akhir.getText().length());
}                                                       

private void jtxtsaldo_pokok_akhirFocusGained(java.awt.event.FocusEvent evt) {                                               
        // TODO add your handling code here:
    jtxtsaldo_pokok_akhir.setSelectionStart(0);
    jtxtsaldo_pokok_akhir.setSelectionEnd(jtxtsaldo_pokok_akhir.getText().length());
}                                                 

private void jtxtsaldo_bunga_akhirFocusGained(java.awt.event.FocusEvent evt) {                                               
        // TODO add your handling code here:
    jtxtsaldo_bunga_akhir.setSelectionStart(0);
    jtxtsaldo_bunga_akhir.setSelectionEnd(jtxtsaldo_bunga_akhir.getText().length());
}                                                 

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmko_transaksi_bayar().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jHeader;
    private javax.swing.JLabel jHeader1;
    private javax.swing.JLabel jHeader2;
    private javax.swing.JLabel jHeader3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowse_anggota;
    private javax.swing.JButton jbtnBrowse_pinjaman1;
    private javax.swing.JComboBox jcmbdop_tagih;
    private javax.swing.JComboBox jcmbmop;
    private javax.swing.JComboBox jcmbmop_start;
    private javax.swing.JLabel jlblangsuranke;
    private javax.swing.JLabel jlblauto_sts;
    private javax.swing.JLabel jlblbayar_angsuran;
    private javax.swing.JLabel jlblbayar_potongan;
    private javax.swing.JLabel jlblcash_sts;
    private javax.swing.JLabel jlbldocument_date;
    private javax.swing.JLabel jlbldocument_date1;
    private javax.swing.JLabel jlbldocument_number;
    private javax.swing.JLabel jlbldocument_status;
    private javax.swing.JLabel jlbldscription;
    private javax.swing.JLabel jlbljangka_waktu;
    private javax.swing.JLabel jlbljumlah_angsuran;
    private javax.swing.JLabel jlbljumlah_pinjaman;
    private javax.swing.JLabel jlblkode_pinjaman1;
    private javax.swing.JLabel jlblkode_pinjaman2;
    private javax.swing.JLabel jlblmember_number1;
    private javax.swing.JLabel jlblmember_number2;
    private javax.swing.JLabel jlblmember_number3;
    private javax.swing.JLabel jlblmember_number4;
    private javax.swing.JLabel jlblmember_number5;
    private javax.swing.JLabel jlblmop;
    private javax.swing.JLabel jlblpelunasan;
    private javax.swing.JLabel jlblreference;
    private javax.swing.JLabel jlblsaldo_bunga_akhir;
    private javax.swing.JLabel jlblsaldo_pokok_akhir;
    private javax.swing.JLabel jlblsaldo_pokok_bunga_akhir;
    private javax.swing.JLabel jlblsisa_angsuranke;
    private javax.swing.JLabel jlblsuku_bunga;
    private javax.swing.JLabel jlblyop;
    private javax.swing.JLabel jlblyop_start;
    private javax.swing.JRadioButton jopt_complete_status_complete;
    private javax.swing.JRadioButton jopt_complete_status_draff;
    private javax.swing.JRadioButton joptauto_sts_auto;
    private javax.swing.JRadioButton joptauto_sts_manual;
    private javax.swing.JRadioButton joptcash_sts_potong_gaji;
    private javax.swing.JRadioButton joptcash_sts_tunai;
    private javax.swing.JRadioButton jopthitung_bunga_flat;
    private javax.swing.JRadioButton jopthitung_bunga_menurun;
    private javax.swing.JRadioButton joptpelunasan_tidak;
    private javax.swing.JRadioButton joptpelunasan_ya;
    private javax.swing.JRadioButton joptsatuan_waktu_bulanan;
    private javax.swing.JRadioButton joptsatuan_waktu_harian;
    private javax.swing.JRadioButton joptsatuan_waktu_mingguan;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtangsuran_bunga;
    private javax.swing.JTextField jtxtangsuran_pokok;
    private javax.swing.JTextField jtxtangsuran_pokok_bunga;
    private javax.swing.JTextField jtxtangsuranke;
    private javax.swing.JTextField jtxtbayar_angsuran;
    private javax.swing.JTextField jtxtbayar_potongan;
    private javax.swing.JTextField jtxtdocument_number;
    private javax.swing.JTextField jtxtdocument_status;
    private javax.swing.JTextField jtxtdscription;
    private javax.swing.JTextField jtxtjangka_waktu;
    private javax.swing.JTextField jtxtjumlah_angsuran;
    private javax.swing.JTextField jtxtjumlah_pinjaman;
    private javax.swing.JTextField jtxtmember_name;
    private javax.swing.JTextField jtxtmember_number;
    private javax.swing.JTextField jtxtmember_number2;
    private javax.swing.JTextField jtxtnama_departemen;
    private javax.swing.JTextField jtxtnama_jabatan;
    private javax.swing.JTextField jtxtnama_pinjaman;
    private javax.swing.JTextField jtxtreference;
    private javax.swing.JTextField jtxtreference_number;
    private javax.swing.JTextField jtxtsaldo_bunga_akhir;
    private javax.swing.JTextField jtxtsaldo_bunga_awal;
    private javax.swing.JTextField jtxtsaldo_pokok_akhir;
    private javax.swing.JTextField jtxtsaldo_pokok_awal;
    private javax.swing.JTextField jtxtsaldo_pokok_bunga_akhir;
    private javax.swing.JTextField jtxtsaldo_pokok_bunga_awal;
    private javax.swing.JTextField jtxtsisa_angsuranke;
    private javax.swing.JTextField jtxtsuku_bunga;
    private javax.swing.JTextField jtxtyop;
    private javax.swing.JTextField jtxtyop_start;
    private org.kazao.calendar.KazaoCalendarDate kzodocument_date;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        if (obj.getdocentry()==0){
            newData();
        }
        showData();
        if (istatus==1){
            try {
                kzodocument_date.setDate(GlobalUtils.getCurrentDate());
            } catch (KazaoCalendarDateTimeException ex) {
                Logger.getLogger(Frmko_transaksi_bayar.class.getName()).log(Level.SEVERE, null, ex);
            }
            jtxtyop.setText(GlobalUtils.getCurrentYear());
            jcmbmop.setSelectedIndex(GlobalUtils.toInt(GlobalUtils.getCurrentMonth())-1);

            jopthitung_bunga_flat.setSelected(true);
            joptsatuan_waktu_harian.setSelected(true);
            jtxtyop_start.setText(GlobalUtils.getCurrentYear());
            jcmbmop_start.setSelectedIndex(GlobalUtils.toInt(GlobalUtils.getCurrentMonth())-1);
            joptauto_sts_manual.setSelected(true);
            jcmbmop_start.setSelectedIndex(-1);
        }
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jtxtdocument_number.setText("");
        jtxtdocument_status.setText("");
        jopt_complete_status_draff.setSelected(true);
        try {
            kzodocument_date.setDate(GlobalUtils.getCurrentDate());
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmko_transaksi_bayar.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtxtyop.setText(GlobalUtils.getCurrentYear());
        jcmbmop.setSelectedIndex(GlobalUtils.toInt(GlobalUtils.getCurrentMonth())-1);
        jtxtreference.setText("");
        jtxtdscription.setText("");
        jtxtmember_number.setText("");
        jtxtjumlah_pinjaman.setText("0");
        jtxtsuku_bunga.setText("0");
        jtxtjangka_waktu.setText("0");
        jopthitung_bunga_flat.setSelected(true);
        joptsatuan_waktu_bulanan.setSelected(true);
        jtxtjumlah_angsuran.setText("0");
        jtxtyop_start.setText(GlobalUtils.getCurrentYear());
        jcmbmop_start.setSelectedIndex(GlobalUtils.toInt(GlobalUtils.getCurrentMonth())-1);
        joptauto_sts_manual.setSelected(true);

        jtxtreference_number.setText("");
        jtxtmember_name.setText("");
        jtxtnama_pinjaman.setText("");
        jtxtmember_number2.setText("");
        jtxtnama_departemen.setText("");
        jtxtnama_jabatan.setText("");
        jtxtyop_start.setText("");
        jcmbmop_start.setSelectedIndex(-1);

        jtxtbayar_angsuran.setText("0");
        jtxtbayar_potongan.setText("0");
        jtxtangsuranke.setText("0");
        jtxtsisa_angsuranke.setText("0");
        jtxtsaldo_pokok_bunga_awal.setText("0");
        jtxtsaldo_pokok_awal.setText("0");
        jtxtsaldo_bunga_awal.setText("0");
        jtxtangsuran_pokok_bunga.setText("0");
        jtxtangsuran_pokok.setText("0");
        jtxtangsuran_bunga.setText("0");
        jtxtsaldo_pokok_bunga_akhir.setText("0");
        jtxtsaldo_pokok_akhir.setText("0");
        jtxtsaldo_bunga_akhir.setText("0");
        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");
    }

    public void newData() throws CodeException {
        istatus=1;
        objtmp=obj;
        obj=new ko_transaksi_bayarext();
        showData();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.update();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        jtxtdocument_status.setText(obj.getdocument_status_description());
        jtxtdocument_number.setText(obj.getdocument_number());
        if (obj.getcomplete_status().equalsIgnoreCase("Y")){
        jopt_complete_status_complete.setSelected(true);
        } else {
        jopt_complete_status_draff.setSelected(true);
        }
        try {
            kzodocument_date.setDate(GlobalUtils.formatDate(obj.getdocument_date(), "MM/dd/yyyy"));
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmko_transaksi_bayar.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtxtyop.setText(GlobalUtils.churuf(obj.getyop()));
        jcmbmop.setSelectedIndex(obj.getmop()-1);
        jcmbdop_tagih.setSelectedItem(obj.getdop_tagih());
        if (obj.getpelunasan().equalsIgnoreCase("Y")){
        joptpelunasan_ya.setSelected(true);
        }  else {
            joptpelunasan_tidak.setSelected(false);
        }

        jtxtreference.setText(obj.getreference());
        jtxtdscription.setText(obj.getdscription());
        jtxtmember_number.setText(obj.getmember_number());
        showanggota();
        jtxtreference_number.setText(obj.getreference_number());
        showpermohonan(obj.getreference_number());
        if (obj.getauto_sts().equalsIgnoreCase("Y")){
            joptauto_sts_auto.setSelected(true);
        } else {
            joptauto_sts_manual.setSelected(true);
        }
        jtxtnama_pinjaman.setText(obj.getNama_pinjaman());
        jtxtbayar_angsuran.setText(GlobalUtils.formatnumber(obj.getbayar_angsuran()));
        jtxtbayar_potongan.setText(GlobalUtils.formatnumber(obj.getbayar_potongan()));
        jtxtangsuranke.setText(GlobalUtils.formatnumber(obj.getangsuranke()));
        jtxtsisa_angsuranke.setText(GlobalUtils.formatnumber(obj.getsisa_angsuranke()));
        jtxtsaldo_pokok_bunga_awal.setText(GlobalUtils.formatnumber(obj.getsaldo_pokok_bunga_awal()));
        jtxtsaldo_pokok_awal.setText(GlobalUtils.formatnumber(obj.getsaldo_pokok_awal()));
        jtxtsaldo_bunga_awal.setText(GlobalUtils.formatnumber(obj.getsaldo_bunga_awal()));
        jtxtangsuran_pokok_bunga.setText(GlobalUtils.formatnumber(obj.getangsuran_pokok_bunga()));
        jtxtangsuran_pokok.setText(GlobalUtils.formatnumber(obj.getangsuran_pokok()));
        jtxtangsuran_bunga.setText(GlobalUtils.formatnumber(obj.getangsuran_bunga()));
        jtxtsaldo_pokok_bunga_akhir.setText(GlobalUtils.formatnumber(obj.getsaldo_pokok_bunga_akhir()));
        jtxtsaldo_pokok_akhir.setText(GlobalUtils.formatnumber(obj.getsaldo_pokok_akhir()));
        jtxtsaldo_bunga_akhir.setText(GlobalUtils.formatnumber(obj.getsaldo_bunga_akhir()));
        
        jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getentrydate()));
        jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getauditdate()));
        jtxtUserID.setText(obj.getaudituser());

        setCursor(GlobalUtils.NORMALCURSOR);

        disable_when_complete(!obj.getcomplete_status().equalsIgnoreCase("Y"));
    }

    public void delete() throws CodeException {
        if (obj.delete()){
            obj.moveNext();
            showData();
        }
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);
        if (obj.getdocument_status().equalsIgnoreCase("C")){
            mf.setToolBar(iformtype,7);
        }
        if (istatus==1){
            jbtnBrowse.setEnabled(false);
        } else {
            jbtnBrowse.setEnabled(true);
        }
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }
        obj.setdocument_number(jtxtdocument_number.getText());
        if (jopt_complete_status_complete.isSelected()){
            obj.setcomplete_status("Y");
        } else {
            obj.setcomplete_status("N");
        }
        obj.setdocument_date(kzodocument_date.getDate());
        obj.setyop(GlobalUtils.toInt(jtxtyop.getText()));
        obj.setmop(jcmbmop.getSelectedIndex()+1);
        obj.setdop_tagih((Integer) jcmbdop_tagih.getSelectedItem());
        if (joptpelunasan_ya.isSelected()){
            obj.setpelunasan("Y");
        } else {
            obj.setpelunasan("N");
        }
        obj.setreference(jtxtreference.getText());
        obj.setdscription(jtxtdscription.getText());
        obj.setmember_number(jtxtmember_number.getText());
        obj.setreference_number(jtxtreference_number.getText());
        int isatuan_waktu=0;
        if (joptsatuan_waktu_harian.isSelected()){
            isatuan_waktu = 1;
        }
        if (joptsatuan_waktu_mingguan.isSelected()){
            isatuan_waktu = 2;
        }
        if (joptsatuan_waktu_bulanan.isSelected()){
            isatuan_waktu = 3;
        }
        if (joptauto_sts_auto.isSelected()){
            obj.setauto_sts("Y");
        } else {
            obj.setauto_sts("N");
        }
        obj.setbayar_angsuran(GlobalUtils.toDbl(jtxtbayar_angsuran.getText()));
        obj.setbayar_potongan(GlobalUtils.toDbl(jtxtbayar_potongan.getText()));
        obj.setangsuranke(GlobalUtils.toInt(jtxtangsuranke.getText()));
        obj.setsisa_angsuranke(GlobalUtils.toInt(jtxtsisa_angsuranke.getText()));
        obj.setsaldo_pokok_bunga_awal(GlobalUtils.toDbl(jtxtsaldo_pokok_bunga_awal.getText()));
        obj.setsaldo_pokok_awal(GlobalUtils.toDbl(jtxtsaldo_pokok_awal.getText()));
        obj.setsaldo_bunga_awal(GlobalUtils.toDbl(jtxtsaldo_bunga_awal.getText()));
        obj.setangsuran_pokok_bunga(GlobalUtils.toDbl(jtxtangsuran_pokok_bunga.getText()));
        obj.setangsuran_pokok(GlobalUtils.toDbl(jtxtangsuran_pokok.getText()));
        obj.setangsuran_bunga(GlobalUtils.toDbl(jtxtangsuran_bunga.getText()));
        obj.setsaldo_pokok_bunga_akhir(GlobalUtils.toDbl(jtxtsaldo_pokok_bunga_akhir.getText()));
        obj.setsaldo_pokok_akhir(GlobalUtils.toDbl(jtxtsaldo_pokok_akhir.getText()));
        obj.setsaldo_bunga_akhir(GlobalUtils.toDbl(jtxtsaldo_bunga_akhir.getText()));

    }

    public void undo() throws CodeException {
        istatus = 0;
        obj=objtmp;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    private void showpermohonan_detail(String reference_number) {
        ko_transaksi_setuju_detailext osetuju=new ko_transaksi_setuju_detailext();
        String spelunasan="N";
        try {
            jtxtbayar_potongan.setEnabled(false);
            if (joptpelunasan_ya.isSelected()){
                spelunasan="Y";
                jtxtbayar_potongan.setEnabled(true);
            }
            if (osetuju.initdata(reference_number,spelunasan)) {
                obj.setkode_pinjaman(osetuju.getkode_pinjaman());
                jtxtnama_pinjaman.setText(osetuju.getnama_pinjaman());
                jtxtsuku_bunga.setText(GlobalUtils.formatnumber(osetuju.getsuku_bunga()));
                if (osetuju.gethitung_bunga().equalsIgnoreCase("1")){
                    jopthitung_bunga_flat.setSelected(true);
                } else {
                    jopthitung_bunga_menurun.setSelected(true);
                }
                jtxtjumlah_angsuran.setText(GlobalUtils.formatnumber(osetuju.getjumlah_angsuran()));
                jtxtjangka_waktu.setText(GlobalUtils.formatnumber(osetuju.getjangka_waktu()));
                if (osetuju.getsatuan_waktu().equals("1")){
                    joptsatuan_waktu_harian.setSelected(true);
                } else if (osetuju.getsatuan_waktu().equals("2")){
                    joptsatuan_waktu_mingguan.setSelected(true);
                } else {
                    joptsatuan_waktu_bulanan.setSelected(true);
                }
                jtxtyop_start.setText(GlobalUtils.formatnumber(osetuju.getyop_start()));
                jcmbmop_start.setSelectedIndex(osetuju.getmop_start()-1);
                jcmbdop_tagih.setSelectedItem(osetuju.getdop_tagih());
                jtxtjumlah_pinjaman.setText(GlobalUtils.formatnumber(osetuju.getjumlah_pinjaman()));
                jtxtangsuranke.setText(GlobalUtils.formatnumber(osetuju.getangsuranke()));
                jtxtsisa_angsuranke.setText(GlobalUtils.formatnumber(osetuju.getsisa_angsuranke()));
                jtxtbayar_angsuran.setText(GlobalUtils.formatnumber(osetuju.getJml_bayar_angsuran()));
                jtxtbayar_potongan.setText(GlobalUtils.formatnumber(osetuju.getJml_bayar_potongan()));
                jtxtsaldo_pokok_awal.setText(GlobalUtils.formatnumber(osetuju.getSaldo_awal_pokok()));
                jtxtsaldo_bunga_awal.setText(GlobalUtils.formatnumber(osetuju.getSaldo_awal_bunga()));
                jtxtsaldo_pokok_bunga_awal.setText(GlobalUtils.formatnumber(osetuju.getSaldo_awal_pokok_bunga()));
                jtxtangsuran_pokok.setText(GlobalUtils.formatnumber(osetuju.getAngsuran_pokok()));
                jtxtangsuran_bunga.setText(GlobalUtils.formatnumber(osetuju.getAngsuran_bunga()));
                jtxtangsuran_pokok_bunga.setText(GlobalUtils.formatnumber(osetuju.getAngsuran_pokok_bunga()));
                jtxtsaldo_pokok_akhir.setText(GlobalUtils.formatnumber(osetuju.getSaldo_akhir_pokok()));
                jtxtsaldo_bunga_akhir.setText(GlobalUtils.formatnumber(osetuju.getSaldo_akhir_bunga()));
                jtxtsaldo_pokok_bunga_akhir.setText(GlobalUtils.formatnumber(osetuju.getSaldo_akhir_pokok_bunga()));

            }
        } catch (CodeException ex) {
            Logger.getLogger(Frmko_transaksi_bayar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void filldop_tagih() {
        jcmbdop_tagih.removeAllItems();
        for (int i=1;i<32;i++){
            jcmbdop_tagih.addItem(i);
        }
    }

    private void disable_when_complete(Boolean b){
        jtxtbayar_angsuran.setEnabled(b);
        jtxtbayar_potongan.setEnabled(b);
        jtxtangsuranke.setEnabled(b);
        jtxtsisa_angsuranke.setEnabled(b);
        jtxtsaldo_pokok_bunga_awal.setEnabled(b);
        jtxtsaldo_pokok_awal.setEnabled(b);
        jtxtsaldo_bunga_awal.setEnabled(b);
        jtxtangsuran_pokok_bunga.setEnabled(b);
        jtxtangsuran_pokok.setEnabled(b);
        jtxtangsuran_bunga.setEnabled(b);
        jtxtsaldo_pokok_bunga_akhir.setEnabled(b);
        jtxtsaldo_pokok_akhir.setEnabled(b);
        jtxtsaldo_bunga_akhir.setEnabled(b);
        jtxtTanggalEntry.setEnabled(b);
        jtxtTanggalUpdate.setEnabled(b);
        jtxtUserID.setEnabled(b);
        joptauto_sts_manual.setEnabled(b);
        joptauto_sts_auto.setEnabled(b);
        joptcash_sts_tunai.setEnabled(b);
        joptcash_sts_potong_gaji.setEnabled(b);
        joptpelunasan_ya.setEnabled(b);
        joptpelunasan_tidak.setEnabled(b);
        jtxtyop.setEnabled(b);
        jtxtdocument_number.setEnabled(b);
        jtxtdocument_status.setEnabled(b);
        jtxtmember_number.setEnabled(b);
        jtxtmember_name.setEnabled(b);
        jtxtmember_number2.setEnabled(b);
        jtxtnama_departemen.setEnabled(b);
        jtxtnama_jabatan.setEnabled(b);
        jcmbmop.setEnabled(b);
        jtxtnama_pinjaman.setEnabled(b);
        jtxtjumlah_pinjaman.setEnabled(b);
        jtxtsuku_bunga.setEnabled(b);
        jtxtjangka_waktu.setEnabled(b);
        jtxtjumlah_angsuran.setEnabled(b);
        jcmbmop_start.setEnabled(b);
        jtxtyop_start.setEnabled(b);
        jopthitung_bunga_flat.setEnabled(b);
        joptsatuan_waktu_harian.setEnabled(b);
        jopthitung_bunga_menurun.setEnabled(b);
        joptsatuan_waktu_mingguan.setEnabled(b);
        joptsatuan_waktu_bulanan.setEnabled(b);
        jtxtreference_number.setEnabled(b);
        jbtnBrowse_pinjaman1.setEnabled(b);
        jopt_complete_status_draff.setEnabled(true);
        jopt_complete_status_complete.setEnabled(true);
        jtxtreference.setEnabled(b);
        jtxtdscription.setEnabled(b);
        jbtnBrowse.setEnabled(true);
        jbtnBrowse_anggota.setEnabled(b);
        jcmbdop_tagih.setEnabled(b);
    }

    
}
