/*
 * From ap_purchase_order
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ko.component;


import classinterface.NavigatorFormInt;
import common.component.FrmMainFrame;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

import kopkar.gl.objectclasses.gl_kalender_detail1ext;
import kopkar.gl.objectclasses.gl_kalenderext;
import kopkar.gl.objectclasses.gl_kalenderextcol;
import kopkar.ko.objectclasses.ko_anggotaext;
import kopkar.ko.objectclasses.ko_transaksi_tagihan_detail1ext;
import kopkar.ko.objectclasses.ko_transaksi_tagihan_detail1extcol;
import kopkar.ko.objectclasses.ko_transaksi_tagihanext;
import kopkar.utils.browsecontroller;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.kazao.calendar.KazaoCalendarDateTimeException;
import utils.CodeException;
import utils.GlobalModel;
import utils.GlobalUtils;
import utils.appsettinghandler;
import utils.selectallJTable;

/**
 *
 * @author  Generator
 */

public class Frmko_transaksi_tagihan extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmap_purchase_order";
    
    FrmMainFrame mf ;

    ko_transaksi_tagihanext obj=new ko_transaksi_tagihanext();
    ko_transaksi_tagihan_detail1extcol appods;
    browsecontroller obrowse=new browsecontroller();
    
    DefaultTableModel model=null;
    private ko_transaksi_tagihanext objtmp;
   
    /** Creates new form Area */
    public Frmko_transaksi_tagihan() throws CodeException {
        initComponents();
    }
    
    public Frmko_transaksi_tagihan(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();

        model=(DefaultTableModel) jtbldetail.getModel();

        showtahun(jcmbyop);
        showtahun(jcmbyop_tagihan);
        showbulan(jcmbmop);
        showbulan(jcmbmop_tagihan);
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowseDocument_Number = new javax.swing.JButton();
        HorizontalLine = new javax.swing.JSeparator();
        jlbldocument_number = new javax.swing.JLabel();
        jtxtdocument_number = new javax.swing.JTextField();
        jlbldocument_status = new javax.swing.JLabel();
        jtxtdocument_status = new javax.swing.JTextField();
        jlbldocument_date = new javax.swing.JLabel();
        jlblprice_code = new javax.swing.JLabel();
        jtxtterima_bayar = new javax.swing.JTextField();
        jlblreference = new javax.swing.JLabel();
        jtxtcari = new javax.swing.JTextField();
        jtxtreference = new javax.swing.JTextField();
        jlbldscription = new javax.swing.JLabel();
        jtxtdscription = new javax.swing.JTextField();
        jlbltotal_bfr_discount = new javax.swing.JLabel();
        jtxttotal_tagihan = new javax.swing.JTextField();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();
        jlblsupplier_code1 = new javax.swing.JLabel();
        jlblsupplier_code2 = new javax.swing.JLabel();
        kzodocument_date = new org.kazao.calendar.KazaoCalendarDate();
        jbtnprice_code = new javax.swing.JButton();
        jlbltotal_bfr_discount1 = new javax.swing.JLabel();
        jtxttotal_bayar = new javax.swing.JTextField();
        jlblsupplier_code3 = new javax.swing.JLabel();
        jcmbmop = new javax.swing.JComboBox();
        jcmbyop = new javax.swing.JComboBox();
        jopt_complete_status_draff = new javax.swing.JRadioButton();
        jopt_complete_status_complete = new javax.swing.JRadioButton();
        jlbltotal_bfr_discount2 = new javax.swing.JLabel();
        jtxtsisa_tagihan = new javax.swing.JTextField();
        jlbltotal_bfr_discount3 = new javax.swing.JLabel();
        jtxtsisa_bayar = new javax.swing.JTextField();
        jlblprice_code1 = new javax.swing.JLabel();
        joptCariBy_NoAnggota = new javax.swing.JRadioButton();
        joptCariBy_Nama = new javax.swing.JRadioButton();
        jlblsupplier_code4 = new javax.swing.JLabel();
        jlblsupplier_code5 = new javax.swing.JLabel();
        jlblsupplier_code6 = new javax.swing.JLabel();
        jcmbmop_tagihan = new javax.swing.JComboBox();
        jcmbyop_tagihan = new javax.swing.JComboBox();
        jHeader1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbldetail = new selectallJTable(model);
        jHeader2 = new javax.swing.JLabel();
        jHeader3 = new javax.swing.JLabel();
        jHeader4 = new javax.swing.JLabel();
        jHeader5 = new javax.swing.JLabel();
        jHeader6 = new javax.swing.JLabel();
        jHeader7 = new javax.swing.JLabel();
        jlblsisa_tagihan_info = new javax.swing.JLabel();
        jlbltotal_simpanan_info = new javax.swing.JLabel();
        jlbltotal_pinjaman_info = new javax.swing.JLabel();
        jlbltoko_info = new javax.swing.JLabel();
        jlblsisa_tagihan_bln_seb_info = new javax.swing.JLabel();
        jlbltotal_tagihan_info = new javax.swing.JLabel();
        jlbltotal_bayar_info = new javax.swing.JLabel();
        joptTunai = new javax.swing.JRadioButton();
        joptTransfer = new javax.swing.JRadioButton();
        jchkpilih_semua = new javax.swing.JCheckBox();
        lblnama_departemen = new javax.swing.JLabel();
        jtxtkode_departemen = new javax.swing.JTextField();
        jbtnkode_departemen = new javax.swing.JButton();
        jtxtnama_departemen = new javax.swing.JTextField();
        lblkode_departemen = new javax.swing.JLabel();
        jchkall_departemen = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Penerimaan Tagihan");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHeader.setText("Jumlah Tagihan");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(850, 440, 130, 20);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jbtnBrowseDocument_Number.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseDocument_Number.setText("...");
        jbtnBrowseDocument_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseDocument_NumberActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowseDocument_Number);
        jbtnBrowseDocument_Number.setBounds(1030, 80, 30, 17);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(230, 46, 830, 10);

        jlbldocument_number.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_number.setText("No. Dokumen");
        getContentPane().add(jlbldocument_number);
        jlbldocument_number.setBounds(690, 80, 140, 13);

        jtxtdocument_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdocument_number.setText("document_number");
        jtxtdocument_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocument_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdocument_number);
        jtxtdocument_number.setBounds(880, 80, 150, 23);

        jlbldocument_status.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_status.setText("Status");
        getContentPane().add(jlbldocument_status);
        jlbldocument_status.setBounds(690, 60, 140, 13);

        jtxtdocument_status.setEditable(false);
        jtxtdocument_status.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdocument_status.setText("document_status");
        jtxtdocument_status.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocument_statusFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdocument_status);
        jtxtdocument_status.setBounds(880, 60, 150, 23);

        jlbldocument_date.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_date.setText("Tgl. Dokumen");
        getContentPane().add(jlbldocument_date);
        jlbldocument_date.setBounds(690, 100, 140, 13);

        jlblprice_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblprice_code.setText("Cari berdasarkan");
        getContentPane().add(jlblprice_code);
        jlblprice_code.setBounds(70, 200, 120, 13);

        jtxtterima_bayar.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtterima_bayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtterima_bayar.setText("terima_bayar");
        jtxtterima_bayar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtterima_bayarFocusGained(evt);
            }
        });
        jtxtterima_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtterima_bayarKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtterima_bayar);
        jtxtterima_bayar.setBounds(260, 180, 160, 23);

        jlblreference.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblreference.setText("Referensi");
        getContentPane().add(jlblreference);
        jlblreference.setBounds(70, 490, 140, 13);

        jtxtcari.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcariKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtcari);
        jtxtcari.setBounds(370, 200, 140, 23);

        jtxtreference.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtreference.setText("reference");
        jtxtreference.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtreferenceFocusGained(evt);
            }
        });
        getContentPane().add(jtxtreference);
        jtxtreference.setBounds(260, 490, 270, 23);

        jlbldscription.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldscription.setText("Keterangan");
        getContentPane().add(jlbldscription);
        jlbldscription.setBounds(70, 510, 140, 13);

        jtxtdscription.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdscription.setText("dscription");
        jtxtdscription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdscriptionFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdscription);
        jtxtdscription.setBounds(260, 510, 270, 23);

        jlbltotal_bfr_discount.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltotal_bfr_discount.setText("Total Tagihan");
        getContentPane().add(jlbltotal_bfr_discount);
        jlbltotal_bfr_discount.setBounds(690, 140, 140, 13);

        jtxttotal_tagihan.setEditable(false);
        jtxttotal_tagihan.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttotal_tagihan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxttotal_tagihan.setText("total_tagihan");
        jtxttotal_tagihan.setFocusable(false);
        getContentPane().add(jtxttotal_tagihan);
        jtxttotal_tagihan.setBounds(880, 140, 150, 23);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(620, 30, 170, 20);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(790, 30, 130, 20);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(920, 30, 140, 20);

        jlblsupplier_code1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsupplier_code1.setText("Periode");
        getContentPane().add(jlblsupplier_code1);
        jlblsupplier_code1.setBounds(70, 60, 140, 13);

        jlblsupplier_code2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsupplier_code2.setText("Bulan");
        getContentPane().add(jlblsupplier_code2);
        jlblsupplier_code2.setBounds(70, 100, 140, 13);

        kzodocument_date.setFont(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date.setOpaque(false);
        getContentPane().add(kzodocument_date);
        kzodocument_date.setBounds(880, 100, 100, 20);

        jbtnprice_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnprice_code.setText("Cari");
        jbtnprice_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnprice_codeActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnprice_code);
        jbtnprice_code.setBounds(510, 200, 70, 20);

        jlbltotal_bfr_discount1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltotal_bfr_discount1.setText("Total Bayar");
        getContentPane().add(jlbltotal_bfr_discount1);
        jlbltotal_bfr_discount1.setBounds(690, 160, 140, 13);

        jtxttotal_bayar.setEditable(false);
        jtxttotal_bayar.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttotal_bayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxttotal_bayar.setText("total_bayar");
        jtxttotal_bayar.setFocusable(false);
        jtxttotal_bayar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttotal_bayarFocusGained(evt);
            }
        });
        getContentPane().add(jtxttotal_bayar);
        jtxttotal_bayar.setBounds(880, 160, 150, 23);

        jlblsupplier_code3.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsupplier_code3.setText("Tahun");
        getContentPane().add(jlblsupplier_code3);
        jlblsupplier_code3.setBounds(70, 80, 140, 13);

        jcmbmop.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbmop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcmbmop);
        jcmbmop.setBounds(260, 90, 160, 20);

        jcmbyop.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbyop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmbyop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbyopItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbyop);
        jcmbyop.setBounds(260, 70, 80, 20);

        buttonGroup1.add(jopt_complete_status_draff);
        jopt_complete_status_draff.setFont(new java.awt.Font("Dialog", 0, 10));
        jopt_complete_status_draff.setSelected(true);
        jopt_complete_status_draff.setText("Draff");
        getContentPane().add(jopt_complete_status_draff);
        jopt_complete_status_draff.setBounds(70, 540, 52, 24);

        buttonGroup1.add(jopt_complete_status_complete);
        jopt_complete_status_complete.setFont(new java.awt.Font("Dialog", 0, 10));
        jopt_complete_status_complete.setText("Complete");
        getContentPane().add(jopt_complete_status_complete);
        jopt_complete_status_complete.setBounds(150, 540, 123, 24);

        jlbltotal_bfr_discount2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltotal_bfr_discount2.setText("Total Sisa Tagihan");
        getContentPane().add(jlbltotal_bfr_discount2);
        jlbltotal_bfr_discount2.setBounds(690, 180, 140, 13);

        jtxtsisa_tagihan.setEditable(false);
        jtxtsisa_tagihan.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsisa_tagihan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsisa_tagihan.setText("sisa_tagihan");
        jtxtsisa_tagihan.setFocusable(false);
        getContentPane().add(jtxtsisa_tagihan);
        jtxtsisa_tagihan.setBounds(880, 180, 150, 23);

        jlbltotal_bfr_discount3.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltotal_bfr_discount3.setText("Sisa Belum Dibayar");
        getContentPane().add(jlbltotal_bfr_discount3);
        jlbltotal_bfr_discount3.setBounds(690, 200, 140, 13);

        jtxtsisa_bayar.setEditable(false);
        jtxtsisa_bayar.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsisa_bayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsisa_bayar.setText("sisa_bayar");
        jtxtsisa_bayar.setFocusable(false);
        jtxtsisa_bayar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsisa_bayarFocusGained(evt);
            }
        });
        getContentPane().add(jtxtsisa_bayar);
        jtxtsisa_bayar.setBounds(880, 200, 150, 23);

        jlblprice_code1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblprice_code1.setText("Penerimaan Pembayaran");
        getContentPane().add(jlblprice_code1);
        jlblprice_code1.setBounds(70, 180, 180, 13);

        buttonGroup2.add(joptCariBy_NoAnggota);
        joptCariBy_NoAnggota.setFont(new java.awt.Font("Dialog", 1, 10));
        joptCariBy_NoAnggota.setText("No.Anggota");
        getContentPane().add(joptCariBy_NoAnggota);
        joptCariBy_NoAnggota.setBounds(260, 200, 110, 24);

        buttonGroup2.add(joptCariBy_Nama);
        joptCariBy_Nama.setFont(new java.awt.Font("Dialog", 1, 10));
        joptCariBy_Nama.setSelected(true);
        joptCariBy_Nama.setText("Nama");
        getContentPane().add(joptCariBy_Nama);
        joptCariBy_Nama.setBounds(190, 200, 59, 24);

        jlblsupplier_code4.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsupplier_code4.setText("Tagihan");
        getContentPane().add(jlblsupplier_code4);
        jlblsupplier_code4.setBounds(70, 120, 140, 13);

        jlblsupplier_code5.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsupplier_code5.setText("Bulan");
        getContentPane().add(jlblsupplier_code5);
        jlblsupplier_code5.setBounds(70, 160, 140, 13);

        jlblsupplier_code6.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsupplier_code6.setText("Tahun");
        getContentPane().add(jlblsupplier_code6);
        jlblsupplier_code6.setBounds(70, 140, 140, 13);

        jcmbmop_tagihan.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbmop_tagihan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmbmop_tagihan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbmop_tagihanItemStateChanged1(evt);
            }
        });
        getContentPane().add(jcmbmop_tagihan);
        jcmbmop_tagihan.setBounds(260, 160, 160, 20);

        jcmbyop_tagihan.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbyop_tagihan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmbyop_tagihan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbyop_tagihanItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbyop_tagihan);
        jcmbyop_tagihan.setBounds(260, 140, 80, 20);

        jHeader1.setBackground(new java.awt.Color(102, 102, 102));
        jHeader1.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader1.setForeground(new java.awt.Color(255, 255, 255));
        jHeader1.setText(" : : Penerimaan Tagihan");
        jHeader1.setAlignmentY(0.0F);
        jHeader1.setOpaque(true);
        getContentPane().add(jHeader1);
        jHeader1.setBounds(30, 30, 200, 20);

        jtbldetail.setFont(new java.awt.Font("Dialog", 0, 10));
        jtbldetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "No.Anggota", "NIK", "Nama", "Bagian", "Departemen", "Jumlah Tagihan", "Jumlah Bayar", "Sisa Tagihan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbldetail.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtbldetail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtbldetail.setSurrendersFocusOnKeystroke(true);
        jtbldetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbldetailMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtbldetailMouseReleased(evt);
            }
        });
        jtbldetail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtbldetailFocusGained(evt);
            }
        });
        jtbldetail.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtbldetailPropertyChange(evt);
            }
        });
        jtbldetail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbldetailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtbldetailKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtbldetail);
        jtbldetail.getColumnModel().getColumn(0).setMinWidth(30);
        jtbldetail.getColumnModel().getColumn(0).setMaxWidth(30);
        jtbldetail.getColumnModel().getColumn(1).setMinWidth(100);
        jtbldetail.getColumnModel().getColumn(2).setMinWidth(90);
        jtbldetail.getColumnModel().getColumn(3).setMinWidth(150);
        jtbldetail.getColumnModel().getColumn(4).setMinWidth(150);
        jtbldetail.getColumnModel().getColumn(5).setMinWidth(150);
        jtbldetail.getColumnModel().getColumn(6).setMinWidth(100);
        jtbldetail.getColumnModel().getColumn(7).setMinWidth(100);
        jtbldetail.getColumnModel().getColumn(8).setMinWidth(100);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 230, 990, 200);

        jHeader2.setBackground(new java.awt.Color(102, 102, 102));
        jHeader2.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader2.setForeground(new java.awt.Color(255, 255, 255));
        jHeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHeader2.setText("Simpan");
        jHeader2.setAlignmentY(0.0F);
        jHeader2.setOpaque(true);
        getContentPane().add(jHeader2);
        jHeader2.setBounds(70, 440, 130, 20);

        jHeader3.setBackground(new java.awt.Color(102, 102, 102));
        jHeader3.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader3.setForeground(new java.awt.Color(255, 255, 255));
        jHeader3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHeader3.setText("Pinjam");
        jHeader3.setAlignmentY(0.0F);
        jHeader3.setOpaque(true);
        getContentPane().add(jHeader3);
        jHeader3.setBounds(200, 440, 130, 20);

        jHeader4.setBackground(new java.awt.Color(102, 102, 102));
        jHeader4.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader4.setForeground(new java.awt.Color(255, 255, 255));
        jHeader4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHeader4.setText("Toko");
        jHeader4.setAlignmentY(0.0F);
        jHeader4.setOpaque(true);
        getContentPane().add(jHeader4);
        jHeader4.setBounds(330, 440, 130, 20);

        jHeader5.setBackground(new java.awt.Color(102, 102, 102));
        jHeader5.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader5.setForeground(new java.awt.Color(255, 255, 255));
        jHeader5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHeader5.setText("Tagihan Bulan Lalu");
        jHeader5.setAlignmentY(0.0F);
        jHeader5.setOpaque(true);
        getContentPane().add(jHeader5);
        jHeader5.setBounds(460, 440, 130, 20);

        jHeader6.setBackground(new java.awt.Color(102, 102, 102));
        jHeader6.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader6.setForeground(new java.awt.Color(255, 255, 255));
        jHeader6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHeader6.setText("Total Tagihan");
        jHeader6.setAlignmentY(0.0F);
        jHeader6.setOpaque(true);
        getContentPane().add(jHeader6);
        jHeader6.setBounds(590, 440, 130, 20);

        jHeader7.setBackground(new java.awt.Color(102, 102, 102));
        jHeader7.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader7.setForeground(new java.awt.Color(255, 255, 255));
        jHeader7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHeader7.setText("Total Terima");
        jHeader7.setAlignmentY(0.0F);
        jHeader7.setOpaque(true);
        getContentPane().add(jHeader7);
        jHeader7.setBounds(720, 440, 130, 20);

        jlblsisa_tagihan_info.setBackground(new java.awt.Color(250, 243, 243));
        jlblsisa_tagihan_info.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsisa_tagihan_info.setForeground(new java.awt.Color(12, 5, 5));
        jlblsisa_tagihan_info.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblsisa_tagihan_info.setText("0");
        jlblsisa_tagihan_info.setAlignmentY(0.0F);
        jlblsisa_tagihan_info.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlblsisa_tagihan_info.setOpaque(true);
        getContentPane().add(jlblsisa_tagihan_info);
        jlblsisa_tagihan_info.setBounds(850, 460, 130, 20);

        jlbltotal_simpanan_info.setBackground(new java.awt.Color(250, 243, 243));
        jlbltotal_simpanan_info.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltotal_simpanan_info.setForeground(new java.awt.Color(12, 5, 5));
        jlbltotal_simpanan_info.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbltotal_simpanan_info.setText("0");
        jlbltotal_simpanan_info.setAlignmentY(0.0F);
        jlbltotal_simpanan_info.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbltotal_simpanan_info.setOpaque(true);
        getContentPane().add(jlbltotal_simpanan_info);
        jlbltotal_simpanan_info.setBounds(70, 460, 130, 20);

        jlbltotal_pinjaman_info.setBackground(new java.awt.Color(250, 243, 243));
        jlbltotal_pinjaman_info.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltotal_pinjaman_info.setForeground(new java.awt.Color(12, 5, 5));
        jlbltotal_pinjaman_info.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbltotal_pinjaman_info.setText("0");
        jlbltotal_pinjaman_info.setAlignmentY(0.0F);
        jlbltotal_pinjaman_info.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbltotal_pinjaman_info.setOpaque(true);
        getContentPane().add(jlbltotal_pinjaman_info);
        jlbltotal_pinjaman_info.setBounds(200, 460, 130, 20);

        jlbltoko_info.setBackground(new java.awt.Color(250, 243, 243));
        jlbltoko_info.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltoko_info.setForeground(new java.awt.Color(12, 5, 5));
        jlbltoko_info.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbltoko_info.setText("0");
        jlbltoko_info.setAlignmentY(0.0F);
        jlbltoko_info.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbltoko_info.setOpaque(true);
        getContentPane().add(jlbltoko_info);
        jlbltoko_info.setBounds(330, 460, 130, 20);

        jlblsisa_tagihan_bln_seb_info.setBackground(new java.awt.Color(250, 243, 243));
        jlblsisa_tagihan_bln_seb_info.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsisa_tagihan_bln_seb_info.setForeground(new java.awt.Color(12, 5, 5));
        jlblsisa_tagihan_bln_seb_info.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblsisa_tagihan_bln_seb_info.setText("0");
        jlblsisa_tagihan_bln_seb_info.setAlignmentY(0.0F);
        jlblsisa_tagihan_bln_seb_info.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlblsisa_tagihan_bln_seb_info.setOpaque(true);
        getContentPane().add(jlblsisa_tagihan_bln_seb_info);
        jlblsisa_tagihan_bln_seb_info.setBounds(460, 460, 130, 20);

        jlbltotal_tagihan_info.setBackground(new java.awt.Color(250, 243, 243));
        jlbltotal_tagihan_info.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltotal_tagihan_info.setForeground(new java.awt.Color(12, 5, 5));
        jlbltotal_tagihan_info.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbltotal_tagihan_info.setText("0");
        jlbltotal_tagihan_info.setAlignmentY(0.0F);
        jlbltotal_tagihan_info.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbltotal_tagihan_info.setOpaque(true);
        getContentPane().add(jlbltotal_tagihan_info);
        jlbltotal_tagihan_info.setBounds(590, 460, 130, 20);

        jlbltotal_bayar_info.setBackground(new java.awt.Color(250, 243, 243));
        jlbltotal_bayar_info.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltotal_bayar_info.setForeground(new java.awt.Color(12, 5, 5));
        jlbltotal_bayar_info.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlbltotal_bayar_info.setText("0");
        jlbltotal_bayar_info.setAlignmentY(0.0F);
        jlbltotal_bayar_info.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlbltotal_bayar_info.setOpaque(true);
        getContentPane().add(jlbltotal_bayar_info);
        jlbltotal_bayar_info.setBounds(720, 460, 130, 20);

        buttonGroup3.add(joptTunai);
        joptTunai.setFont(new java.awt.Font("Dialog", 1, 10));
        joptTunai.setSelected(true);
        joptTunai.setText("Tunai");
        getContentPane().add(joptTunai);
        joptTunai.setBounds(260, 110, 80, 24);

        buttonGroup3.add(joptTransfer);
        joptTransfer.setFont(new java.awt.Font("Dialog", 1, 10));
        joptTransfer.setText("Transfer");
        getContentPane().add(joptTransfer);
        joptTransfer.setBounds(340, 110, 110, 24);

        jchkpilih_semua.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkpilih_semua.setText("Pilih / Tidak Pilih Semua");
        jchkpilih_semua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkpilih_semuaActionPerformed(evt);
            }
        });
        getContentPane().add(jchkpilih_semua);
        jchkpilih_semua.setBounds(590, 490, 200, 24);

        lblnama_departemen.setFont(new java.awt.Font("Dialog", 1, 10));
        lblnama_departemen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblnama_departemen.setText("Nama Dept.");
        getContentPane().add(lblnama_departemen);
        lblnama_departemen.setBounds(430, 140, 110, 13);

        jtxtkode_departemen.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtkode_departemen.setText("simpanan_wajib_kode_akun");
        jtxtkode_departemen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtkode_departemenFocusGained(evt);
            }
        });
        getContentPane().add(jtxtkode_departemen);
        jtxtkode_departemen.setBounds(510, 120, 140, 23);

        jbtnkode_departemen.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnkode_departemen.setText("...");
        jbtnkode_departemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnkode_departemenActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnkode_departemen);
        jbtnkode_departemen.setBounds(650, 120, 30, 17);

        jtxtnama_departemen.setEditable(false);
        jtxtnama_departemen.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtnama_departemen.setText("simpanan_wajib_kode_akun");
        jtxtnama_departemen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtnama_departemenFocusGained(evt);
            }
        });
        getContentPane().add(jtxtnama_departemen);
        jtxtnama_departemen.setBounds(510, 140, 170, 23);

        lblkode_departemen.setFont(new java.awt.Font("Dialog", 1, 10));
        lblkode_departemen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblkode_departemen.setText("Kd. Dept");
        getContentPane().add(lblkode_departemen);
        lblkode_departemen.setBounds(430, 120, 110, 13);

        jchkall_departemen.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkall_departemen.setText("All Departemen");
        jchkall_departemen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jchkall_departemenItemStateChanged(evt);
            }
        });
        jchkall_departemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkall_departemenActionPerformed(evt);
            }
        });
        getContentPane().add(jchkall_departemen);
        jchkall_departemen.setBounds(430, 90, 150, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jbtnBrowseDocument_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseDocument_NumberActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.ko_transaksi_tagihan, "", jtxtdocument_number);
        try {
            if (!jtxtdocument_number.getText().equalsIgnoreCase("")){
                obj.initdata(jtxtdocument_number.getText());
                showData();
            }
        } catch (CodeException ex) {
            Logger.getLogger(Frmko_transaksi_tagihan.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}//GEN-LAST:event_jbtnBrowseDocument_NumberActionPerformed

private void jtbldetailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtbldetailFocusGained
    // TODO add your handling code here:
    if (jtbldetail.getRowCount()==0){
        insertnewlastrow();
    }
}//GEN-LAST:event_jtbldetailFocusGained

private void jtbldetailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbldetailKeyPressed
    // TODO add your handling code here:
    int col=jtbldetail.getSelectedColumn();
    int row=jtbldetail.getSelectedRow();
    switch (evt.getKeyCode()){
        case KeyEvent.VK_F5:
            switch (jtbldetail.getSelectedColumn()){
                case 1:
                    obrowse.showbrowser(obrowse.ko_anggota, "", jtbldetail);
                    showanggota((Integer)jtbldetail.getSelectedRow());
                    jtbldetailPropertyChange(null);
                    GlobalUtils.selectCellTable(jtbldetail, row, 3);
                    break;
            }
            break;
        case KeyEvent.VK_INSERT:
            evt.consume();
            insertnewlastrow();
            break;
        case KeyEvent.VK_DELETE:
            evt.consume();
            if (jtbldetail.getSelectedRow()<appods.size()){
            ko_transaksi_tagihan_detail1ext o = appods.get(jtbldetail.getSelectedRow());
                o.setstatus(ko_transaksi_tagihan_detail1ext.Status_delete);
            }
            jtbldetailPropertyChange(null);
            break;
        case KeyEvent.VK_ENTER:
            evt.consume();
            break;
    }
}//GEN-LAST:event_jtbldetailKeyPressed

private void jtbldetailPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtbldetailPropertyChange
    // TODO add your handling code here:
    int irow=jtbldetail.getSelectedRow();
    int icol=jtbldetail.getSelectedColumn();

    if (irow>-1){
        switch (icol){
            case 0:
//                set_pilih(irow);
                break;
            case 1:
                break;
            case 7:
                set_bayar(irow);
                break;
        }
        if (appods.size()>0){
        cekdetail();
        }
        tampil_total();
    }
}//GEN-LAST:event_jtbldetailPropertyChange
private void set_pilih(int irow){
    ko_transaksi_tagihan_detail1ext o = obj.getDetail1().get(irow);
    if (Boolean.parseBoolean(GlobalUtils.churuf(jtbldetail.getValueAt(irow, 0)))){
        if (o.gettotal_tagihan()>obj.getSisa_belum_dibayar()){
            o.settotal_bayar(obj.getSisa_belum_dibayar());
        } else {
            o.settotal_bayar(o.gettotal_tagihan());
        }
    } else {
        o.settotal_bayar(new Double(0));
    }
    if (o.gettotal_bayar()<=0){
        jtbldetail.setValueAt(false,irow, 0);
    }
    jtbldetail.setValueAt(o.gettotal_bayar(), irow, 7);
    jtbldetail.setValueAt(o.getsisa_tagihan(), irow, 8);
}
private void set_bayar(int irow){
    ko_transaksi_tagihan_detail1ext o = obj.getDetail1().get(irow);
    o.settotal_bayar(GlobalUtils.toDbl(GlobalUtils.churuf(model.getValueAt(irow, 7))));
    if (o.gettotal_bayar()>obj.getSisa_belum_dibayar()){
        o.settotal_bayar(obj.getSisa_belum_dibayar());
    }
    if (o.gettotal_bayar()<=0){
        jtbldetail.setValueAt(false,irow, 0);
    } else {
        jtbldetail.setValueAt(true,irow, 0);
    }
    jtbldetail.setValueAt(o.gettotal_bayar(), irow, 7);
    jtbldetail.setValueAt(o.getsisa_tagihan(), irow, 8);
    
}
private void tampil_total(){
    obj.calculatetotal();
    jtxttotal_tagihan.setText(GlobalUtils.formatnumber(obj.gettotal_tagihan()));
    jtxttotal_bayar.setText(GlobalUtils.formatnumber(obj.gettotal_bayar()));
    jtxtsisa_tagihan.setText(GlobalUtils.formatnumber(obj.getsisa_tagihan()));
    jtxtsisa_bayar.setText(GlobalUtils.formatnumber(obj.getSisa_belum_dibayar()));
}
private void jbtnprice_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnprice_codeActionPerformed
    // TODO add your handling code here:
    docari();
}//GEN-LAST:event_jbtnprice_codeActionPerformed

private void jtbldetailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbldetailKeyReleased
        int col=jtbldetail.getSelectedColumn();
        int row=jtbldetail.getSelectedRow();
    // TODO add your handling code here:
        if (evt.getKeyCode()==evt.VK_ENTER&&row>-1){
            switch (col){
                case 1:
                    showanggota(row);
                    jtbldetailPropertyChange(null);
                    GlobalUtils.selectCellTable(jtbldetail, row, 4);
                    break;
                case 6:
                    insertnewlastrow();
                    break;
            }
        }
}//GEN-LAST:event_jtbldetailKeyReleased

private void jtxttotal_bayarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxttotal_bayarFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxttotal_bayarFocusGained

private void jcmbyopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbyopItemStateChanged
    // TODO add your handling code here:
    showbulan(jcmbmop);
}//GEN-LAST:event_jcmbyopItemStateChanged

private void jtxtsisa_bayarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsisa_bayarFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtsisa_bayarFocusGained

private void jcmbyop_tagihanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbyop_tagihanItemStateChanged
    // TODO add your handling code here:
    showbulan(jcmbmop_tagihan);
}//GEN-LAST:event_jcmbyop_tagihanItemStateChanged

private void jtbldetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbldetailMouseClicked
    // TODO add your handling code here:
    
}//GEN-LAST:event_jtbldetailMouseClicked

private void jtxtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcariKeyReleased
    int ifind;
    // TODO add your handling code here:
    if (evt.getKeyCode()==evt.VK_ENTER){
        docari();
    }    
    
}//GEN-LAST:event_jtxtcariKeyReleased

private void jtxtterima_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtterima_bayarKeyReleased
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtterima_bayar);
    obj.setterima_bayar(GlobalUtils.toDbl(jtxtterima_bayar.getText()));
    jtxtsisa_bayar.setText(GlobalUtils.formatnumber(obj.getSisa_belum_dibayar()));
}//GEN-LAST:event_jtxtterima_bayarKeyReleased

private void jcmbmop_tagihanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbmop_tagihanItemStateChanged
    // TODO add your handling code here:
    if (jcmbyop_tagihan.getItemCount()>0&&jcmbmop_tagihan.getItemCount()>0){
    obj.setyop_tagihan(GlobalUtils.toInt(jcmbyop_tagihan.getSelectedItem().toString()));
    obj.setmop_tagihan(jcmbmop_tagihan.getSelectedIndex()+1);
    obj.loaddetail();
    appods=obj.getDetail1();
        
    GlobalModel.clearRow(model);

    if (jtbldetail.getRowCount()==0){
        insertnewlastrow();
    }
    int i=0;
    for (i=0;i<appods.size();i++){
        ko_transaksi_tagihan_detail1ext appod = appods.get(i);
        model.setValueAt(appod.getselected(), i, 0);
        model.setValueAt(appod.getmember_number(), i, 1);

        model.setValueAt(appod.getEmployee_number(), i, 2);


        model.setValueAt(appod.getMember_name(), i, 3);
        model.setValueAt(appod.getNama_jabatan(), i, 4);

        model.setValueAt(appod.getNama_departemen(), i, 5);
        model.setValueAt(appod.gettotal_tagihan(), i, 6);
        model.setValueAt(appod.gettotal_bayar(), i, 7);
        model.setValueAt(appod.getsisa_tagihan(), i, 8);

        insertnewlastrow();
    }
    }
}//GEN-LAST:event_jcmbmop_tagihanItemStateChanged

private void jtxtterima_bayarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtterima_bayarFocusGained
    // TODO add your handling code here:
    GlobalUtils.highlighttext(jtxtterima_bayar);
}//GEN-LAST:event_jtxtterima_bayarFocusGained

private void jchkpilih_semuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkpilih_semuaActionPerformed
    // TODO add your handling code here:
    if (jchkpilih_semua.isSelected()){
        pilihsemua(true);
    } else {
        pilihsemua(false);
    }
}//GEN-LAST:event_jchkpilih_semuaActionPerformed

private void jcmbmop_tagihanItemStateChanged1(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbmop_tagihanItemStateChanged1
    // TODO add your handling code here:
    initdata_detail();
}//GEN-LAST:event_jcmbmop_tagihanItemStateChanged1

private void initdata_detail(){
    if (istatus==1){
        if (jcmbmop_tagihan.getSelectedIndex()>-1){
            obj.setmop_tagihan(jcmbmop_tagihan.getSelectedIndex()+1);
            if (jchkall_departemen.isSelected()){
                obj.setall_departemen("Y");
            } else {
                obj.setall_departemen("N");
            }
            obj.setkode_departemen(jtxtkode_departemen.getText());
            try {
                obj.setDetail1(new ko_transaksi_tagihan_detail1extcol(obj));
                obj.getDetail1().initdata();

                showdata_detail();
            } catch (SQLException ex) {
                Logger.getLogger(Frmko_transaksi_tagihan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
private void jtxtkode_departemenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtkode_departemenFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtkode_departemenFocusGained

private void jbtnkode_departemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnkode_departemenActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.ko_departemen, "", jtxtkode_departemen, jtxtnama_departemen);
    if (!jtxtkode_departemen.getText().equalsIgnoreCase("")){
        initdata_detail();
    }
}//GEN-LAST:event_jbtnkode_departemenActionPerformed

private void jtxtnama_departemenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtnama_departemenFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtnama_departemenFocusGained

private void jchkall_departemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkall_departemenActionPerformed
    // TODO add your handling code here:
//    jtxtkode_departemen.setEnabled(!jchkall_departemen.isSelected());
//    jtxtnama_departemen.setEnabled(!jchkall_departemen.isSelected());
//    jbtnkode_departemen.setEnabled(!jchkall_departemen.isSelected());
}//GEN-LAST:event_jchkall_departemenActionPerformed

private void jchkall_departemenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jchkall_departemenItemStateChanged
    // TODO add your handling code here:
    jtxtkode_departemen.setEnabled(!jchkall_departemen.isSelected());
    jtxtnama_departemen.setEnabled(!jchkall_departemen.isSelected());
    jbtnkode_departemen.setEnabled(!jchkall_departemen.isSelected());
}//GEN-LAST:event_jchkall_departemenItemStateChanged

private void jtbldetailMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbldetailMouseReleased
    // TODO add your handling code here:
    int irow=jtbldetail.getSelectedRow();
    if (irow>-1 && irow<obj.getDetail1().size()){
        showdetail(obj.getDetail1().get(irow));
    }

    int icol=jtbldetail.getSelectedColumn();

    if (irow>-1){
        switch (icol){
            case 0:
                set_pilih(irow);
                break;
            case 1:
                break;
            case 7:
                set_bayar(irow);
                break;
        }
        if (appods.size()>0){
        cekdetail();
        }
        tampil_total();
    }
}//GEN-LAST:event_jtbldetailMouseReleased
                         

private void jtxtdocument_numberFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtdocument_number.setSelectionStart(0);
    jtxtdocument_number.setSelectionEnd(jtxtdocument_number.getText().length());
}                                               

private void jtxtdocument_statusFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtdocument_status.setSelectionStart(0);
    jtxtdocument_status.setSelectionEnd(jtxtdocument_status.getText().length());
}                                                                                           

                                               

private void jtxtprice_codeFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
    jtxtterima_bayar.setSelectionStart(0);
    jtxtterima_bayar.setSelectionEnd(jtxtterima_bayar.getText().length());
}                                          

private void jtxtwarehouse_codeFocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
    jtxtcari.setSelectionStart(0);
    jtxtcari.setSelectionEnd(jtxtcari.getText().length());
}                                              


private void jtxtreferenceFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    jtxtreference.setSelectionStart(0);
    jtxtreference.setSelectionEnd(jtxtreference.getText().length());
}                                         

private void jtxtdscriptionFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
    jtxtdscription.setSelectionStart(0);
    jtxtdscription.setSelectionEnd(jtxtdscription.getText().length());
}                                                                                    

private void jtxttotal_bfr_discountFocusGained(java.awt.event.FocusEvent evt) {                                                
        // TODO add your handling code here:
    jtxttotal_tagihan.setSelectionStart(0);
    jtxttotal_tagihan.setSelectionEnd(jtxttotal_tagihan.getText().length());
}                                                  


private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

                                                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmko_transaksi_tagihan().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jHeader;
    private javax.swing.JLabel jHeader1;
    private javax.swing.JLabel jHeader2;
    private javax.swing.JLabel jHeader3;
    private javax.swing.JLabel jHeader4;
    private javax.swing.JLabel jHeader5;
    private javax.swing.JLabel jHeader6;
    private javax.swing.JLabel jHeader7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowseDocument_Number;
    private javax.swing.JButton jbtnkode_departemen;
    private javax.swing.JButton jbtnprice_code;
    private javax.swing.JCheckBox jchkall_departemen;
    private javax.swing.JCheckBox jchkpilih_semua;
    private javax.swing.JComboBox jcmbmop;
    private javax.swing.JComboBox jcmbmop_tagihan;
    private javax.swing.JComboBox jcmbyop;
    private javax.swing.JComboBox jcmbyop_tagihan;
    private javax.swing.JLabel jlbldocument_date;
    private javax.swing.JLabel jlbldocument_number;
    private javax.swing.JLabel jlbldocument_status;
    private javax.swing.JLabel jlbldscription;
    private javax.swing.JLabel jlblprice_code;
    private javax.swing.JLabel jlblprice_code1;
    private javax.swing.JLabel jlblreference;
    private javax.swing.JLabel jlblsisa_tagihan_bln_seb_info;
    private javax.swing.JLabel jlblsisa_tagihan_info;
    private javax.swing.JLabel jlblsupplier_code1;
    private javax.swing.JLabel jlblsupplier_code2;
    private javax.swing.JLabel jlblsupplier_code3;
    private javax.swing.JLabel jlblsupplier_code4;
    private javax.swing.JLabel jlblsupplier_code5;
    private javax.swing.JLabel jlblsupplier_code6;
    private javax.swing.JLabel jlbltoko_info;
    private javax.swing.JLabel jlbltotal_bayar_info;
    private javax.swing.JLabel jlbltotal_bfr_discount;
    private javax.swing.JLabel jlbltotal_bfr_discount1;
    private javax.swing.JLabel jlbltotal_bfr_discount2;
    private javax.swing.JLabel jlbltotal_bfr_discount3;
    private javax.swing.JLabel jlbltotal_pinjaman_info;
    private javax.swing.JLabel jlbltotal_simpanan_info;
    private javax.swing.JLabel jlbltotal_tagihan_info;
    private javax.swing.JRadioButton joptCariBy_Nama;
    private javax.swing.JRadioButton joptCariBy_NoAnggota;
    private javax.swing.JRadioButton joptTransfer;
    private javax.swing.JRadioButton joptTunai;
    private javax.swing.JRadioButton jopt_complete_status_complete;
    private javax.swing.JRadioButton jopt_complete_status_draff;
    private javax.swing.JTable jtbldetail;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtcari;
    private javax.swing.JTextField jtxtdocument_number;
    private javax.swing.JTextField jtxtdocument_status;
    private javax.swing.JTextField jtxtdscription;
    private javax.swing.JTextField jtxtkode_departemen;
    private javax.swing.JTextField jtxtnama_departemen;
    private javax.swing.JTextField jtxtreference;
    private javax.swing.JTextField jtxtsisa_bayar;
    private javax.swing.JTextField jtxtsisa_tagihan;
    private javax.swing.JTextField jtxtterima_bayar;
    private javax.swing.JTextField jtxttotal_bayar;
    private javax.swing.JTextField jtxttotal_tagihan;
    private org.kazao.calendar.KazaoCalendarDate kzodocument_date;
    private javax.swing.JLabel lblkode_departemen;
    private javax.swing.JLabel lblnama_departemen;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jtxtdocument_number.setText("");
        jtxtdocument_status.setText("Open");
        try {
            kzodocument_date.setDate(GlobalUtils.getCurrentDate());
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmko_transaksi_tagihan.class.getName()).log(Level.SEVERE, null, ex);
        }
        jopt_complete_status_draff.setSelected(true);
        jtxtterima_bayar.setText("");
        jtxtcari.setText("");
        jtxtreference.setText("");
        jtxtdscription.setText("");
        jtxttotal_tagihan.setText("");
        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");

        if (joptTunai.isSelected()){
            obj.setCash_sts("Y");
        } else {
            obj.setCash_sts("N");
        }

        GlobalModel.clearRow(model);

        if (jtbldetail.getRowCount()==0){
            insertnewlastrow();
        }
    }

    public void newData() throws CodeException {
        istatus=1;
        objtmp=obj;
        obj=new ko_transaksi_tagihanext();

        jchkpilih_semua.setSelected(false);

        jcmbyop.setSelectedItem(GlobalUtils.toInt(GlobalUtils.formatDate(GlobalUtils.sessiondate,"yyyy")));
        jcmbyop_tagihan.setSelectedItem(GlobalUtils.toInt(GlobalUtils.formatDate(GlobalUtils.sessiondate,"yyyy")));
        obj.setyop(GlobalUtils.toInt(jcmbyop.getSelectedItem().toString()));
        obj.setyop_tagihan(GlobalUtils.toInt(jcmbyop_tagihan.getSelectedItem().toString()));

        jcmbmop.setSelectedItem(GlobalUtils.getMonthName(GlobalUtils.toInt(GlobalUtils.formatDate(GlobalUtils.sessiondate,"MM"))));
        jcmbmop_tagihan.setSelectedItem(GlobalUtils.getMonthName(GlobalUtils.toInt(GlobalUtils.formatDate(GlobalUtils.sessiondate,"MM"))));
        obj.setmop(jcmbmop.getSelectedIndex()+1);
        obj.setmop_tagihan(jcmbmop_tagihan.getSelectedIndex()+1);
        obj.loaddetail();
        obj.setall_departemen("Y");
        showData();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.update();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        jtxtdocument_number.setText(obj.getdocument_number());
        try {
            kzodocument_date.setDate(GlobalUtils.formatDate(obj.getdocument_date(),"MM/dd/yyyy"));
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmko_transaksi_tagihan.class.getName()).log(Level.SEVERE, null, ex);
        }

        jcmbyop.setSelectedItem(obj.getyop());
        System.out.println(jcmbmop.getItemCount());
        jcmbmop.setSelectedIndex(obj.getmop()-1);

        if (jcmbyop_tagihan.getItemCount()>0){
            jcmbyop_tagihan.setSelectedItem(obj.getyop_tagihan());
        }
        if (jcmbmop_tagihan.getItemCount()>0){
        jcmbmop_tagihan.setSelectedIndex(obj.getmop_tagihan()-1);
        }
        jtxtterima_bayar.setText(GlobalUtils.formatnumber(obj.getterima_bayar()));
        

        jtxtreference.setText(obj.getreference());
        jtxtdscription.setText(obj.getdscription());
        jtxttotal_tagihan.setText(GlobalUtils.formatnumber(obj.gettotal_tagihan()));
        jtxttotal_bayar.setText(GlobalUtils.formatnumber(obj.gettotal_bayar()));
        jtxtsisa_tagihan.setText(GlobalUtils.formatnumber(obj.getsisa_tagihan()));
        jtxtsisa_bayar.setText(GlobalUtils.formatnumber(obj.getSisa_belum_dibayar()));

        jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getentrydate()));
        jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getauditdate()));
        jtxtUserID.setText(obj.getaudituser());

        jtxtdocument_status.setText(obj.getDocument_status_desc());

        if (obj.getcomplete_status().equalsIgnoreCase("Y")){
            jopt_complete_status_complete.setSelected(true);
        } else {
            jopt_complete_status_draff.setSelected(true);
        }

        if (obj.getCash_sts().equalsIgnoreCase("Y")){
            joptTunai.setSelected(true);
        } else {
            joptTransfer.setSelected(true);
        }

        if (obj.getall_departemen().equalsIgnoreCase("Y")){
            jchkall_departemen.setSelected(true);
        } else {
            jchkall_departemen.setSelected(false);
        }

        jtxtkode_departemen.setText(obj.getkode_departemen());
        jtxtnama_departemen.setText(obj.getnama_departemen());

        showdata_detail();
        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void showdata_detail(){
         appods=obj.getDetail1();

        GlobalModel.clearRow(model);

        if (jtbldetail.getRowCount()==0){
            insertnewlastrow();
        }
        int i=0;
        for (i=0;i<appods.size();i++){
            model.addRow(new Object[model.getColumnCount()]);
            ko_transaksi_tagihan_detail1ext appod = appods.get(i);
            model.setValueAt(appod.getselected(), i, 0);
            model.setValueAt(appod.getmember_number(), i, 1);

            model.setValueAt(appod.getEmployee_number(), i, 2);
            model.setValueAt(appod.getMember_name(), i, 3);
            model.setValueAt(appod.getNama_jabatan(), i, 4);

            model.setValueAt(appod.getNama_departemen(), i, 5);
            model.setValueAt(appod.gettotal_tagihan(), i, 6);
            model.setValueAt(appod.gettotal_bayar(), i, 7);
            model.setValueAt(appod.getsisa_tagihan(), i, 8);

            //insertnewlastrow();
        }
    }
    public void delete() throws CodeException {
        if (obj.delete()){
            obj.moveNext();
            showData();
        }
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);
//        if (obj.getdocument_status().equalsIgnoreCase("C")){
//            mf.setToolBar(iformtype,7);
//        }
        if (istatus==1){
            jbtnBrowseDocument_Number.setEnabled(false);
        } else {
            jbtnBrowseDocument_Number.setEnabled(true);
        }
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }
        obj.setyop(GlobalUtils.toInt(jcmbyop.getSelectedItem().toString()));
        obj.setyop_tagihan(GlobalUtils.toInt(jcmbyop_tagihan.getSelectedItem().toString()));

        obj.setmop(jcmbmop.getSelectedIndex()+1);
        obj.setmop_tagihan(jcmbmop_tagihan.getSelectedIndex()+1);

        obj.setdocument_number(jtxtdocument_number.getText());
        
        obj.setdocument_date(kzodocument_date.getDate());
        obj.setterima_bayar(GlobalUtils.toDbl(jtxtterima_bayar.getText()));
        
        obj.setreference(jtxtreference.getText());
        obj.setdscription(jtxtdscription.getText());
        obj.settotal_tagihan(GlobalUtils.toDbl(jtxttotal_tagihan.getText()));
        obj.settotal_bayar(GlobalUtils.toDbl(jtxttotal_bayar.getText()));
        obj.setsisa_bayar(GlobalUtils.toDbl(jtxtsisa_bayar.getText()));
        obj.setsisa_tagihan(GlobalUtils.toDbl(jtxtsisa_tagihan.getText()));

        if (jopt_complete_status_draff.isSelected()){
            obj.setcomplete_status("N");
        } else {
            obj.setcomplete_status("Y");
        }

        if (jchkall_departemen.isSelected()){
            obj.setall_departemen("Y");
        } else {
            obj.setall_departemen("N");
        }

        obj.setkode_departemen(jtxtkode_departemen.getText());
    }

    public void undo() throws CodeException {
        istatus = 0;
        obj=objtmp;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
        JasperPrint jasperPrint;

        Map parameter = new HashMap();
        parameter.put("document_date_fr", GlobalUtils.formatDate(obj.getdocument_date(),"yyyy-MM-dd"));
        parameter.put("document_date_to", GlobalUtils.formatDate(obj.getdocument_date(),"yyyy-MM-dd"));
        parameter.put("document_number_fr", obj.getdocument_number());
        parameter.put("document_number_to", obj.getdocument_number());
        parameter.put("audituser", GlobalUtils.audituser);

        // Versi 1
        String file ="";
        JasperReport jasperReport;
        if(GlobalUtils.getAppDir()){
            try{
                    file = GlobalUtils.getCurrentDir() +"/Reports/ko_tagihan_report.jrxml";
                    jasperReport = JasperCompileManager.compileReport(file);
                    System.out.println("isi parameter form_permohonan.jrxml:"+parameter);
                    jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, appsettinghandler.db.getConnection());
                    JasperViewer.viewReport(jasperPrint, false);
            }catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    private void insertnewlastrow() {
        if (!lastrowisempty()){
        model.addRow(new Object[model.getColumnCount()]);
        model.setValueAt(false, model.getRowCount()-1, 0);
        model.setValueAt(0, model.getRowCount()-1, 6);
        model.setValueAt(0, model.getRowCount()-1, 7);
        model.setValueAt(0, model.getRowCount()-1, 8);
        
        GlobalUtils.selectCellTable(jtbldetail, model.getRowCount()-1, 1);
        }
    }

    private void cekdetail() {
        int row = jtbldetail.getSelectedRow();
        int col = jtbldetail.getSelectedColumn();


        ko_transaksi_tagihan_detail1ext appod=new ko_transaksi_tagihan_detail1ext(0);
        if (row > appods.size() - 1) {
            appod = new ko_transaksi_tagihan_detail1ext(0);
            appod.setstatus(ko_transaksi_tagihan_detail1ext.Status_Insert);
            appods.add(appod);
        } else {
            appod = (ko_transaksi_tagihan_detail1ext) appods.get(row);
            if (!appod.getstatus().equals(ko_transaksi_tagihan_detail1ext.Status_Insert)&&!appod.getstatus().equals(ko_transaksi_tagihan_detail1ext.Status_delete)){
                appod.setstatus(ko_transaksi_tagihan_detail1ext.Status_update);
            }
        }
        switch (appod.getlinenum()){
            case 1:
                appod.setstatus(ko_transaksi_tagihan_detail1ext.Status_Insert);
                break;
            case 2:
                appod.setstatus(ko_transaksi_tagihan_detail1ext.Status_update);
                break;
            case 3:
                break;
        }
        appod.setselected((Boolean)model.getValueAt(row, 0));
        appod.setmember_number(GlobalUtils.churuf(model.getValueAt(row, 1)));
        
        appod.settotal_tagihan(GlobalUtils.toDbl(GlobalUtils.churuf(model.getValueAt(row, 6))));
        appod.settotal_bayar(GlobalUtils.toDbl(GlobalUtils.churuf(model.getValueAt(row, 7))));

        appods.set(row, appod);

    }


    private boolean lastrowisempty() {
        if (model.getRowCount()>0){
            if (GlobalUtils.churuf(model.getValueAt(model.getRowCount()-1, 1)).equalsIgnoreCase("")){
                return true;
            }
        }
        return false;
    }

    private void showtahun(JComboBox jcmb) {
        gl_kalenderextcol okal=new gl_kalenderextcol();
        try {
            okal.initdata();
            jcmb.removeAllItems();
            for (int i=0;i<okal.size();i++){
                gl_kalenderext o = okal.get(i);
                jcmb.addItem(o.getyop());
            }
            jcmb.setSelectedItem(GlobalUtils.toInt(GlobalUtils.formatDate(GlobalUtils.sessiondate,"yyyy")));
        } catch (SQLException ex) {
            Logger.getLogger(Frmko_transaksi_tagihan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void showbulan(JComboBox jcmb) {
        gl_kalenderext okal=new gl_kalenderext();
        gl_kalender_detail1ext o;
        try {
            
                jcmb.removeAllItems();
                if (okal.initdata(GlobalUtils.toInt(GlobalUtils.churuf(jcmbyop.getSelectedItem())))) {
                    for (int i = 0; i < okal.getDetail1().size(); i++) {
                        o=okal.getDetail1().get(i);
                        jcmb.addItem(GlobalUtils.getMonthName(o.getmop()));
                    }
                }
                jcmb.setSelectedItem(GlobalUtils.getMonthName(GlobalUtils.toInt(GlobalUtils.formatDate(GlobalUtils.sessiondate,"MM"))));
            
        } catch (CodeException ex) {
            Logger.getLogger(Frmko_transaksi_tagihan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void showanggota(Integer row) {
        ko_anggotaext oangt=new ko_anggotaext();
        String kodeakun=GlobalUtils.churuf(model.getValueAt(row, 1));
        try {
            if (oangt.initdata(kodeakun)) {
                model.setValueAt(oangt.getmember_number(), row, 1);
                model.setValueAt(oangt.getemployee_number(), row, 2);
                model.setValueAt(oangt.getmember_name(), row, 3);
                model.setValueAt(oangt.getbagian(), row, 4);
                model.setValueAt(oangt.getdepinfo().getnama_departemen(), row, 5);
            }
        } catch (CodeException ex) {
            Logger.getLogger(Frmko_transaksi_tagihan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void showdetail(ko_transaksi_tagihan_detail1ext od) {
        jlbltotal_simpanan_info.setText(GlobalUtils.formatnumber(od.getTotal_simpanan_info()));
        jlbltotal_pinjaman_info.setText(GlobalUtils.formatnumber(od.getTotal_pinjaman_info()));
        jlbltoko_info.setText(GlobalUtils.formatnumber(od.getToko_info()));
        jlblsisa_tagihan_bln_seb_info.setText(GlobalUtils.formatnumber(od.getSisa_tagihan_bln_seb_info()));
        jlbltotal_tagihan_info.setText(GlobalUtils.formatnumber(od.getTotal_tagihan_info()));
        jlbltotal_bayar_info.setText(GlobalUtils.formatnumber(od.getTotal_bayar_info()));
        jlblsisa_tagihan_info.setText(GlobalUtils.formatnumber(od.getSisa_tagihan_info()));

    }

    private int findintable(int searchby,String text) {
        int i=0;
        int start=0;
        if (jtbldetail.getSelectedRow()>-1){
            start=jtbldetail.getSelectedRow();
        }
        if (start==jtbldetail.getRowCount()-1){
            start=0;
        }
        for (i=start;i<obj.getDetail1().size();i++){
            ko_transaksi_tagihan_detail1ext o = obj.getDetail1().get(i);
            if (searchby==1){
                if (o.getMember_name().toLowerCase().contains(text.toLowerCase())){
                    return i;
                }
            } else {
                if (o.getmember_number().toLowerCase().contains(text.toLowerCase())){
                    return i;
                }
            }
        }
        return -1;
    }

    private void docari() {
        int ifind;
        // TODO add your handling code here:
        
            if (joptCariBy_Nama.isSelected()){
                ifind=findintable(1,jtxtcari.getText());
            } else {
                ifind=findintable(2,jtxtcari.getText());
            }
            if (ifind>-1){
                GlobalUtils.selectCellTable(jtbldetail, ifind, 0);

            } else {
                GlobalUtils.selectCellTable(jtbldetail, jtbldetail.getRowCount()-1, 0);
            }
        
    }

    private void pilihsemua(boolean b) {
        Double jml_terima=GlobalUtils.toDbl(jtxtterima_bayar.getText());
        Double jml_dibayar=new Double(0);
        Double jml_sisa=jml_terima;
        Double jml_bayar=new Double(0);
        for (int i=0;i<obj.getDetail1().size()&&jml_sisa>0;i++){
            model.setValueAt(b, i, 0);
            ko_transaksi_tagihan_detail1ext o = obj.getDetail1().get(i);
            if (b){
                if (jml_sisa<GlobalUtils.toDbl(GlobalUtils.churuf(model.getValueAt(i, 6)))){
                    jml_bayar=jml_sisa;
                    model.setValueAt(jml_bayar, i, 7);
                    set_detail(i,o);
                    jtbldetail.setValueAt(o.getsisa_tagihan(), i, 8);
                    break;
                } else {
                    jml_bayar=GlobalUtils.toDbl(GlobalUtils.churuf(model.getValueAt(i, 6)));
                }
                jml_dibayar=jml_dibayar+jml_bayar;
                model.setValueAt(jml_bayar, i, 7);
                jml_sisa=jml_sisa-jml_bayar;
            }
            set_detail(i,o);
            jtbldetail.setValueAt(o.getsisa_tagihan(), i, 8);
        }
        tampil_total();
    }

    private void set_detail(int i,ko_transaksi_tagihan_detail1ext o){
        switch (o.getlinenum()){
            case 1:
                o.setstatus(ko_transaksi_tagihan_detail1ext.Status_Insert);
                break;
            case 2:
                o.setstatus(ko_transaksi_tagihan_detail1ext.Status_update);
                break;
            case 3:
                break;
        }
        o.setselected((Boolean)model.getValueAt(i, 0));
        o.setmember_number(GlobalUtils.churuf(model.getValueAt(i, 1)));

        o.settotal_tagihan(GlobalUtils.toDbl(GlobalUtils.churuf(model.getValueAt(i, 6))));
        o.settotal_bayar(GlobalUtils.toDbl(GlobalUtils.churuf(model.getValueAt(i, 7))));
    }
}
