/*
 * From ko_pinjaman
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ko.component;


import classinterface.NavigatorFormInt;
import common.component.FrmBrowseData;
import common.component.FrmMainFrame;
import java.util.logging.Level;
import java.util.logging.Logger;
import kopkar.ko.objectclasses.ko_pinjamanext;
import kopkar.utils.browsecontroller;
import utils.CodeException;
import utils.GlobalUtils;

/**
 *
 * @author  Generator
 */

public class Frmko_pinjaman extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmko_pinjaman";
    String status="";
    String bunga="";
    String bayar="";
    
    FrmMainFrame mf ;

    ko_pinjamanext obj=new ko_pinjamanext();


    /** Creates new form Area */
    public Frmko_pinjaman() throws CodeException {
        initComponents();
    }
    
    public Frmko_pinjaman(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();
        jlblkode_pinjaman = new javax.swing.JLabel();
        jtxtkode_pinjaman = new javax.swing.JTextField();
        jlblnama_pinjaman = new javax.swing.JLabel();
        jtxtnama_pinjaman = new javax.swing.JTextField();
        jlblbunga = new javax.swing.JLabel();
        jtxtbunga = new javax.swing.JTextField();
        jlbltipe_bunga = new javax.swing.JLabel();
        jlbljumlah_cicilan = new javax.swing.JLabel();
        jtxtjumlah_cicilan = new javax.swing.JTextField();
        jlblcara_bayar = new javax.swing.JLabel();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();
        chck_status = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        bunga2 = new javax.swing.JRadioButton();
        bunga3 = new javax.swing.JRadioButton();
        bunga1 = new javax.swing.JRadioButton();
        satuan3 = new javax.swing.JRadioButton();
        satuan1 = new javax.swing.JRadioButton();
        satuan2 = new javax.swing.JRadioButton();
        jbtnBrowse1 = new javax.swing.JButton();
        jlblkode_pinjaman1 = new javax.swing.JLabel();
        jtxtkode_pinjaman_tipe = new javax.swing.JTextField();
        jlblnama_pinjaman1 = new javax.swing.JLabel();
        jtxtnama_pinjaman_tipe = new javax.swing.JTextField();
        jbtnBrowse2 = new javax.swing.JButton();
        jlblkode_pinjaman2 = new javax.swing.JLabel();
        jtxtaccset_code = new javax.swing.JTextField();
        jlblnama_pinjaman2 = new javax.swing.JLabel();
        jtxtaccset_desc = new javax.swing.JTextField();
        jopthitung_bunga_mix = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Master Pinjaman");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Master Pinjaman");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 200, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(420, 100, 30, 17);

        jlblkode_pinjaman.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblkode_pinjaman.setText("Kode Pinjaman");
        getContentPane().add(jlblkode_pinjaman);
        jlblkode_pinjaman.setBounds(70, 100, 140, 13);

        jtxtkode_pinjaman.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtkode_pinjaman.setText("kode_pinjaman");
        jtxtkode_pinjaman.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtkode_pinjamanFocusGained(evt);
            }
        });
        getContentPane().add(jtxtkode_pinjaman);
        jtxtkode_pinjaman.setBounds(260, 100, 150, 23);

        jlblnama_pinjaman.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_pinjaman.setText("Nama Pinjaman");
        getContentPane().add(jlblnama_pinjaman);
        jlblnama_pinjaman.setBounds(70, 120, 140, 13);

        jtxtnama_pinjaman.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtnama_pinjaman.setText("nama_pinjaman");
        jtxtnama_pinjaman.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtnama_pinjamanFocusGained(evt);
            }
        });
        getContentPane().add(jtxtnama_pinjaman);
        jtxtnama_pinjaman.setBounds(260, 120, 400, 23);

        jlblbunga.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblbunga.setText("Bunga (%)");
        getContentPane().add(jlblbunga);
        jlblbunga.setBounds(70, 180, 140, 13);

        jtxtbunga.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtbunga.setText("bunga");
        jtxtbunga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtbungaFocusGained(evt);
            }
        });
        getContentPane().add(jtxtbunga);
        jtxtbunga.setBounds(260, 180, 40, 23);

        jlbltipe_bunga.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltipe_bunga.setText("Perhitungan");
        getContentPane().add(jlbltipe_bunga);
        jlbltipe_bunga.setBounds(70, 200, 140, 13);

        jlbljumlah_cicilan.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbljumlah_cicilan.setText("Lama Angsuran");
        getContentPane().add(jlbljumlah_cicilan);
        jlbljumlah_cicilan.setBounds(70, 220, 140, 20);

        jtxtjumlah_cicilan.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtjumlah_cicilan.setText("Lama angsuran");
        jtxtjumlah_cicilan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtjumlah_cicilanFocusGained(evt);
            }
        });
        getContentPane().add(jtxtjumlah_cicilan);
        jtxtjumlah_cicilan.setBounds(260, 220, 150, 23);

        jlblcara_bayar.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcara_bayar.setText("Satuan");
        getContentPane().add(jlblcara_bayar);
        jlblcara_bayar.setBounds(70, 240, 140, 20);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(360, 30, 170, 20);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(530, 30, 130, 20);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(660, 30, 140, 20);

        chck_status.setFont(new java.awt.Font("Dialog", 1, 10));
        chck_status.setText("Aktif");
        chck_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chck_statusActionPerformed(evt);
            }
        });
        getContentPane().add(chck_status);
        chck_status.setBounds(260, 73, 54, 20);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel1.setText("% per Tahun");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 180, 100, 20);

        buttonGroup1.add(bunga2);
        bunga2.setFont(new java.awt.Font("Dialog", 1, 10));
        bunga2.setText("Anuitas");
        bunga2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bunga2ActionPerformed(evt);
            }
        });
        getContentPane().add(bunga2);
        bunga2.setBounds(320, 200, 120, 24);

        buttonGroup1.add(bunga3);
        bunga3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        bunga3.setText("Bunga Efektif");
        bunga3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bunga3ActionPerformed(evt);
            }
        });
        getContentPane().add(bunga3);
        bunga3.setBounds(440, 200, 120, 20);

        buttonGroup1.add(bunga1);
        bunga1.setFont(new java.awt.Font("Dialog", 1, 10));
        bunga1.setSelected(true);
        bunga1.setText("Flat");
        bunga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bunga1ActionPerformed(evt);
            }
        });
        getContentPane().add(bunga1);
        bunga1.setBounds(260, 200, 50, 24);

        buttonGroup2.add(satuan3);
        satuan3.setFont(new java.awt.Font("Dialog", 1, 10));
        satuan3.setSelected(true);
        satuan3.setText("Bulanan");
        satuan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuan3ActionPerformed(evt);
            }
        });
        getContentPane().add(satuan3);
        satuan3.setBounds(430, 240, 80, 24);

        buttonGroup2.add(satuan1);
        satuan1.setFont(new java.awt.Font("Dialog", 1, 10));
        satuan1.setText("Harian");
        satuan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuan1ActionPerformed(evt);
            }
        });
        getContentPane().add(satuan1);
        satuan1.setBounds(260, 240, 70, 24);

        buttonGroup2.add(satuan2);
        satuan2.setFont(new java.awt.Font("Dialog", 1, 10));
        satuan2.setText("Mingguan");
        satuan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuan2ActionPerformed(evt);
            }
        });
        getContentPane().add(satuan2);
        satuan2.setBounds(340, 240, 80, 24);

        jbtnBrowse1.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse1.setText("...");
        jbtnBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse1);
        jbtnBrowse1.setBounds(420, 140, 30, 17);

        jlblkode_pinjaman1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblkode_pinjaman1.setText("Tipe Pinjaman");
        getContentPane().add(jlblkode_pinjaman1);
        jlblkode_pinjaman1.setBounds(70, 140, 140, 13);

        jtxtkode_pinjaman_tipe.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtkode_pinjaman_tipe.setText("kode_pinjaman");
        jtxtkode_pinjaman_tipe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtkode_pinjaman_tipeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtkode_pinjaman_tipe);
        jtxtkode_pinjaman_tipe.setBounds(260, 140, 150, 23);

        jlblnama_pinjaman1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_pinjaman1.setText("Nama Tipe Pinjaman");
        getContentPane().add(jlblnama_pinjaman1);
        jlblnama_pinjaman1.setBounds(70, 160, 140, 13);

        jtxtnama_pinjaman_tipe.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtnama_pinjaman_tipe.setText("nama_pinjaman");
        jtxtnama_pinjaman_tipe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtnama_pinjaman_tipeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtnama_pinjaman_tipe);
        jtxtnama_pinjaman_tipe.setBounds(260, 160, 400, 23);

        jbtnBrowse2.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse2.setText("...");
        jbtnBrowse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse2);
        jbtnBrowse2.setBounds(420, 270, 30, 17);

        jlblkode_pinjaman2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblkode_pinjaman2.setText("Setting Akun");
        getContentPane().add(jlblkode_pinjaman2);
        jlblkode_pinjaman2.setBounds(70, 270, 140, 13);

        jtxtaccset_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaccset_code.setText("accset_code");
        jtxtaccset_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtaccset_codeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtaccset_code);
        jtxtaccset_code.setBounds(260, 270, 150, 23);

        jlblnama_pinjaman2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_pinjaman2.setText("Nama Setting Akun");
        getContentPane().add(jlblnama_pinjaman2);
        jlblnama_pinjaman2.setBounds(70, 290, 140, 13);

        jtxtaccset_desc.setEditable(false);
        jtxtaccset_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaccset_desc.setText("nama_pinjaman");
        jtxtaccset_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtaccset_descFocusGained(evt);
            }
        });
        getContentPane().add(jtxtaccset_desc);
        jtxtaccset_desc.setBounds(260, 290, 400, 23);

        buttonGroup1.add(jopthitung_bunga_mix);
        jopthitung_bunga_mix.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jopthitung_bunga_mix.setText("Bunga Menurun");
        jopthitung_bunga_mix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jopthitung_bunga_mixActionPerformed(evt);
            }
        });
        getContentPane().add(jopthitung_bunga_mix);
        jopthitung_bunga_mix.setBounds(570, 200, 150, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void bunga2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bunga2ActionPerformed
    // TODO add your handling code here:
        if(bunga2.isSelected()){
        bunga = "2";
    }
}//GEN-LAST:event_bunga2ActionPerformed

private void chck_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chck_statusActionPerformed
    // TODO add your handling code here:
    if(chck_status.isSelected()){
        status="Y";
    }else{
        status="N";
    }
}//GEN-LAST:event_chck_statusActionPerformed

private void bunga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bunga1ActionPerformed
    // TODO add your handling code here:
    if(bunga1.isSelected()){
        bunga = "1";
    }
}//GEN-LAST:event_bunga1ActionPerformed

private void bunga3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bunga3ActionPerformed
    // TODO add your handling code here:
    if(bunga3.isSelected()){
        bunga = "3";
    }
}//GEN-LAST:event_bunga3ActionPerformed

private void satuan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuan1ActionPerformed
    // TODO add your handling code here:
    if(satuan1.isSelected()){
        bayar="1";
    }
}//GEN-LAST:event_satuan1ActionPerformed

private void satuan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuan2ActionPerformed
    // TODO add your handling code here:
    if(satuan2.isSelected()){
        bayar="2";
    }
}//GEN-LAST:event_satuan2ActionPerformed

private void satuan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuan3ActionPerformed
    // TODO add your handling code here:
    if(satuan3.isSelected()){
        bayar="3";
    }
}//GEN-LAST:event_satuan3ActionPerformed

private void jbtnBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse1ActionPerformed
    // TODO add your handling code here:
    browsecontroller obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_pinjaman_tipe, "", jtxtkode_pinjaman_tipe,jtxtnama_pinjaman_tipe);
}//GEN-LAST:event_jbtnBrowse1ActionPerformed

private void jtxtkode_pinjaman_tipeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtkode_pinjaman_tipeFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtkode_pinjaman_tipeFocusGained

private void jtxtnama_pinjaman_tipeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtnama_pinjaman_tipeFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtnama_pinjaman_tipeFocusGained

private void jbtnBrowse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse2ActionPerformed
    // TODO add your handling code here:
    browsecontroller obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_account_set, "", jtxtaccset_code,jtxtaccset_desc);
}//GEN-LAST:event_jbtnBrowse2ActionPerformed

private void jtxtaccset_codeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtaccset_codeFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtaccset_codeFocusGained

private void jtxtaccset_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtaccset_descFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtaccset_descFocusGained

private void jopthitung_bunga_mixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jopthitung_bunga_mixActionPerformed
    // TODO add your handling code here:
    if(jopthitung_bunga_mix.isSelected()){
        bunga = "4";
    }
}//GEN-LAST:event_jopthitung_bunga_mixActionPerformed

private void jtxtkode_pinjamanFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxtkode_pinjaman.setSelectionStart(0);
    jtxtkode_pinjaman.setSelectionEnd(jtxtkode_pinjaman.getText().length());
}                                             

private void jtxtnama_pinjamanFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxtnama_pinjaman.setSelectionStart(0);
    jtxtnama_pinjaman.setSelectionEnd(jtxtnama_pinjaman.getText().length());
}                                             

                                        

private void jtxtbungaFocusGained(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    jtxtbunga.setSelectionStart(0);
    jtxtbunga.setSelectionEnd(jtxtbunga.getText().length());
}                                     
                                   

private void jtxtjumlah_cicilanFocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
    jtxtjumlah_cicilan.setSelectionStart(0);
    jtxtjumlah_cicilan.setSelectionEnd(jtxtjumlah_cicilan.getText().length());
}                                              
                                       

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
    FrmBrowseData frmbrowse=new FrmBrowseData("ko_pinjaman", "");
    frmbrowse.setModal(true);
    frmbrowse.setVisible(true);
    try {
        obj.initdata(frmbrowse.getValue());
        showData();
    } catch (CodeException ex) {
        Logger.getLogger(Frmko_pinjaman.class.getName()).log(Level.SEVERE, null, ex);
    }
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmko_pinjaman().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JRadioButton bunga1;
    private javax.swing.JRadioButton bunga2;
    private javax.swing.JRadioButton bunga3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chck_status;
    private javax.swing.JLabel jHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowse1;
    private javax.swing.JButton jbtnBrowse2;
    private javax.swing.JLabel jlblbunga;
    private javax.swing.JLabel jlblcara_bayar;
    private javax.swing.JLabel jlbljumlah_cicilan;
    private javax.swing.JLabel jlblkode_pinjaman;
    private javax.swing.JLabel jlblkode_pinjaman1;
    private javax.swing.JLabel jlblkode_pinjaman2;
    private javax.swing.JLabel jlblnama_pinjaman;
    private javax.swing.JLabel jlblnama_pinjaman1;
    private javax.swing.JLabel jlblnama_pinjaman2;
    private javax.swing.JLabel jlbltipe_bunga;
    private javax.swing.JRadioButton jopthitung_bunga_mix;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtaccset_code;
    private javax.swing.JTextField jtxtaccset_desc;
    private javax.swing.JTextField jtxtbunga;
    private javax.swing.JTextField jtxtjumlah_cicilan;
    private javax.swing.JTextField jtxtkode_pinjaman;
    private javax.swing.JTextField jtxtkode_pinjaman_tipe;
    private javax.swing.JTextField jtxtnama_pinjaman;
    private javax.swing.JTextField jtxtnama_pinjaman_tipe;
    private javax.swing.JRadioButton satuan1;
    private javax.swing.JRadioButton satuan2;
    private javax.swing.JRadioButton satuan3;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jtxtkode_pinjaman.setText("");
        jtxtnama_pinjaman.setText("");

        jtxtkode_pinjaman_tipe.setText("");
        jtxtnama_pinjaman_tipe.setText("");

        jtxtaccset_code.setText("");
        jtxtaccset_desc.setText("");

        chck_status.setSelected(false);
        jtxtbunga.setText("");
        jtxtjumlah_cicilan.setText("");
        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");
    }

    public void newData() throws CodeException {
        istatus=1;
        clearfield();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.update();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        jtxtkode_pinjaman.setText(obj.getkode_pinjaman());
        jtxtnama_pinjaman.setText(obj.getnama_pinjaman());

        jtxtkode_pinjaman_tipe.setText(obj.getkode_pinjaman_tipe());
        jtxtnama_pinjaman_tipe.setText(obj.getnama_pinjaman_tipe());

        if(obj.getaktif_sts().equalsIgnoreCase("Y")){
            chck_status.setSelected(true);
        }else{
            chck_status.setSelected(false);
        }
        jtxtbunga.setText(GlobalUtils.churuf(obj.getbunga()));
        jtxtjumlah_cicilan.setText(GlobalUtils.churuf(obj.getjumlah_cicilan()));

        jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getentrydate()));
        jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getauditdate()));
        jtxtUserID.setText(obj.getaudituser());
        switch (GlobalUtils.toInt(obj.gettipe_bunga())){
                case 1:
                    bunga1.setSelected(true);
                    break;
                case 2:
                    bunga2.setSelected(true);
                    break;
                case 3:
                    bunga3.setSelected(true);
                    break;
                case 4:
                    jopthitung_bunga_mix.setSelected(true);
                    break;
            }
        switch (GlobalUtils.toInt(obj.getcara_bayar())){
                case 1:
                    satuan1.setSelected(true);
                    break;
                case 2:
                    satuan2.setSelected(true);
                    break;
                case 3:
                    satuan3.setSelected(true);
                    break;
            }

        jtxtaccset_code.setText(obj.getaccset_code());
        jtxtaccset_desc.setText(obj.getaccset_desc());
        
        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        if (obj.delete()){
            obj.moveNext();
            showData();
        }
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);

        if (istatus==1){
            jbtnBrowse.setEnabled(false);
        } else {
            jbtnBrowse.setEnabled(true);
        }
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }
        obj.setkode_pinjaman(jtxtkode_pinjaman.getText());
        obj.setnama_pinjaman(jtxtnama_pinjaman.getText());
        obj.setkode_pinjaman_tipe(jtxtkode_pinjaman_tipe.getText());
        obj.setaktif_sts(status);
        obj.setbunga(GlobalUtils.toDbl(jtxtbunga.getText()));
        obj.setjumlah_cicilan(GlobalUtils.toInt(jtxtjumlah_cicilan.getText()));
        obj.settipe_bunga(bunga);
        obj.setcara_bayar(bayar);

        obj.setaccset_code(jtxtaccset_code.getText());
        
    }

    public void undo() throws CodeException {
        istatus = 0;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    
}
