/*
 * From ko_transaksi_mohon_detail1
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ko.component;


import classinterface.NavigatorFormInt;
import common.component.FrmBrowseData;
import common.component.FrmMainFrame;
import java.util.logging.Level;
import java.util.logging.Logger;
import kopkar.ko.objectclasses.ko_transaksi_mohon_detail1ext;
import utils.CodeException;
import utils.GlobalUtils;

/**
 *
 * @author  Generator
 */

public class Frmko_transaksi_mohon_detail1 extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmko_transaksi_mohon_detail1";
    
    FrmMainFrame mf ;

    ko_transaksi_mohon_detail1ext obj=new ko_transaksi_mohon_detail1ext();
   
    /** Creates new form Area */
    public Frmko_transaksi_mohon_detail1() throws CodeException {
        initComponents();
    }
    
    public Frmko_transaksi_mohon_detail1(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();
        jlbldocentry = new javax.swing.JLabel();
        jtxtdocentry = new javax.swing.JTextField();
        jlblline_number = new javax.swing.JLabel();
        jtxtline_number = new javax.swing.JTextField();
        jlblkode_pinjaman_tipe = new javax.swing.JLabel();
        jtxtkode_pinjaman_tipe = new javax.swing.JTextField();
        jlbljumlah_pinjaman = new javax.swing.JLabel();
        jtxtjumlah_pinjaman = new javax.swing.JTextField();
        jlblsisa_pinjaman = new javax.swing.JLabel();
        jtxtsisa_pinjaman = new javax.swing.JTextField();
        jlbljumlah_angsuran = new javax.swing.JLabel();
        jtxtjumlah_angsuran = new javax.swing.JTextField();
        jlblsisa_angsuran = new javax.swing.JLabel();
        jtxtsisa_angsuran = new javax.swing.JTextField();
        jlblentrydate = new javax.swing.JLabel();
        jtxtentrydate = new javax.swing.JTextField();
        jlblauditdate = new javax.swing.JLabel();
        jtxtauditdate = new javax.swing.JTextField();
        jlblaudituser = new javax.swing.JLabel();
        jtxtaudituser = new javax.swing.JTextField();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ko_transaksi_mohon_detail1");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : ko_transaksi_mohon_detail1");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 200, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(420, 100, 30, 17);

        jlbldocentry.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocentry.setText("docentry");
        getContentPane().add(jlbldocentry);
        jlbldocentry.setBounds(70, 100, 140, 13);

        jtxtdocentry.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdocentry.setText("docentry");
        jtxtdocentry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocentryFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdocentry);
        jtxtdocentry.setBounds(260, 100, 150, 23);

        jlblline_number.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblline_number.setText("line_number");
        getContentPane().add(jlblline_number);
        jlblline_number.setBounds(70, 117, 140, 13);

        jtxtline_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtline_number.setText("line_number");
        jtxtline_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtline_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtline_number);
        jtxtline_number.setBounds(260, 117, 150, 23);

        jlblkode_pinjaman_tipe.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblkode_pinjaman_tipe.setText("kode_pinjaman_tipe");
        getContentPane().add(jlblkode_pinjaman_tipe);
        jlblkode_pinjaman_tipe.setBounds(70, 134, 140, 13);

        jtxtkode_pinjaman_tipe.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtkode_pinjaman_tipe.setText("kode_pinjaman_tipe");
        jtxtkode_pinjaman_tipe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtkode_pinjaman_tipeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtkode_pinjaman_tipe);
        jtxtkode_pinjaman_tipe.setBounds(260, 134, 150, 23);

        jlbljumlah_pinjaman.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbljumlah_pinjaman.setText("jumlah_pinjaman");
        getContentPane().add(jlbljumlah_pinjaman);
        jlbljumlah_pinjaman.setBounds(70, 151, 140, 13);

        jtxtjumlah_pinjaman.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtjumlah_pinjaman.setText("jumlah_pinjaman");
        jtxtjumlah_pinjaman.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtjumlah_pinjamanFocusGained(evt);
            }
        });
        getContentPane().add(jtxtjumlah_pinjaman);
        jtxtjumlah_pinjaman.setBounds(260, 151, 150, 23);

        jlblsisa_pinjaman.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsisa_pinjaman.setText("sisa_pinjaman");
        getContentPane().add(jlblsisa_pinjaman);
        jlblsisa_pinjaman.setBounds(70, 168, 140, 13);

        jtxtsisa_pinjaman.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsisa_pinjaman.setText("sisa_pinjaman");
        jtxtsisa_pinjaman.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsisa_pinjamanFocusGained(evt);
            }
        });
        getContentPane().add(jtxtsisa_pinjaman);
        jtxtsisa_pinjaman.setBounds(260, 168, 150, 23);

        jlbljumlah_angsuran.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbljumlah_angsuran.setText("jumlah_angsuran");
        getContentPane().add(jlbljumlah_angsuran);
        jlbljumlah_angsuran.setBounds(70, 185, 140, 13);

        jtxtjumlah_angsuran.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtjumlah_angsuran.setText("jumlah_angsuran");
        jtxtjumlah_angsuran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtjumlah_angsuranFocusGained(evt);
            }
        });
        getContentPane().add(jtxtjumlah_angsuran);
        jtxtjumlah_angsuran.setBounds(260, 185, 150, 23);

        jlblsisa_angsuran.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsisa_angsuran.setText("sisa_angsuran");
        getContentPane().add(jlblsisa_angsuran);
        jlblsisa_angsuran.setBounds(70, 202, 140, 13);

        jtxtsisa_angsuran.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsisa_angsuran.setText("sisa_angsuran");
        jtxtsisa_angsuran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsisa_angsuranFocusGained(evt);
            }
        });
        getContentPane().add(jtxtsisa_angsuran);
        jtxtsisa_angsuran.setBounds(260, 202, 150, 23);

        jlblentrydate.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblentrydate.setText("entrydate");
        getContentPane().add(jlblentrydate);
        jlblentrydate.setBounds(70, 219, 140, 13);

        jtxtentrydate.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtentrydate.setText("entrydate");
        jtxtentrydate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtentrydateFocusGained(evt);
            }
        });
        getContentPane().add(jtxtentrydate);
        jtxtentrydate.setBounds(260, 219, 150, 23);

        jlblauditdate.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblauditdate.setText("auditdate");
        getContentPane().add(jlblauditdate);
        jlblauditdate.setBounds(70, 236, 140, 13);

        jtxtauditdate.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtauditdate.setText("auditdate");
        jtxtauditdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtauditdateFocusGained(evt);
            }
        });
        getContentPane().add(jtxtauditdate);
        jtxtauditdate.setBounds(260, 236, 150, 23);

        jlblaudituser.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblaudituser.setText("audituser");
        getContentPane().add(jlblaudituser);
        jlblaudituser.setBounds(70, 253, 140, 13);

        jtxtaudituser.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaudituser.setText("audituser");
        jtxtaudituser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtaudituserFocusGained(evt);
            }
        });
        getContentPane().add(jtxtaudituser);
        jtxtaudituser.setBounds(260, 253, 150, 23);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(360, 30, 170, 20);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(530, 30, 130, 20);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(660, 30, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jtxtdocentryFocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtdocentry.setSelectionStart(0);
    jtxtdocentry.setSelectionEnd(jtxtdocentry.getText().length());
}                                        

private void jtxtline_numberFocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    jtxtline_number.setSelectionStart(0);
    jtxtline_number.setSelectionEnd(jtxtline_number.getText().length());
}                                           

private void jtxtkode_pinjaman_tipeFocusGained(java.awt.event.FocusEvent evt) {                                                
        // TODO add your handling code here:
    jtxtkode_pinjaman_tipe.setSelectionStart(0);
    jtxtkode_pinjaman_tipe.setSelectionEnd(jtxtkode_pinjaman_tipe.getText().length());
}                                                  

private void jtxtjumlah_pinjamanFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtjumlah_pinjaman.setSelectionStart(0);
    jtxtjumlah_pinjaman.setSelectionEnd(jtxtjumlah_pinjaman.getText().length());
}                                               

private void jtxtsisa_pinjamanFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxtsisa_pinjaman.setSelectionStart(0);
    jtxtsisa_pinjaman.setSelectionEnd(jtxtsisa_pinjaman.getText().length());
}                                             

private void jtxtjumlah_angsuranFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtjumlah_angsuran.setSelectionStart(0);
    jtxtjumlah_angsuran.setSelectionEnd(jtxtjumlah_angsuran.getText().length());
}                                               

private void jtxtsisa_angsuranFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxtsisa_angsuran.setSelectionStart(0);
    jtxtsisa_angsuran.setSelectionEnd(jtxtsisa_angsuran.getText().length());
}                                             

private void jtxtentrydateFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    jtxtentrydate.setSelectionStart(0);
    jtxtentrydate.setSelectionEnd(jtxtentrydate.getText().length());
}                                         

private void jtxtauditdateFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    jtxtauditdate.setSelectionStart(0);
    jtxtauditdate.setSelectionEnd(jtxtauditdate.getText().length());
}                                         

private void jtxtaudituserFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    jtxtaudituser.setSelectionStart(0);
    jtxtaudituser.setSelectionEnd(jtxtaudituser.getText().length());
}                                         

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
    FrmBrowseData frmbrowse=new FrmBrowseData("ko_transaksi_mohon_detail1", "");
    frmbrowse.setModal(true);
    frmbrowse.setVisible(true);
    try {
        obj.initdata(frmbrowse.getValue());
        showData();
    } catch (CodeException ex) {
        Logger.getLogger(Frmko_transaksi_mohon_detail1.class.getName()).log(Level.SEVERE, null, ex);
    }
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmko_transaksi_mohon_detail1().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JLabel jlblauditdate;
    private javax.swing.JLabel jlblaudituser;
    private javax.swing.JLabel jlbldocentry;
    private javax.swing.JLabel jlblentrydate;
    private javax.swing.JLabel jlbljumlah_angsuran;
    private javax.swing.JLabel jlbljumlah_pinjaman;
    private javax.swing.JLabel jlblkode_pinjaman_tipe;
    private javax.swing.JLabel jlblline_number;
    private javax.swing.JLabel jlblsisa_angsuran;
    private javax.swing.JLabel jlblsisa_pinjaman;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtauditdate;
    private javax.swing.JTextField jtxtaudituser;
    private javax.swing.JTextField jtxtdocentry;
    private javax.swing.JTextField jtxtentrydate;
    private javax.swing.JTextField jtxtjumlah_angsuran;
    private javax.swing.JTextField jtxtjumlah_pinjaman;
    private javax.swing.JTextField jtxtkode_pinjaman_tipe;
    private javax.swing.JTextField jtxtline_number;
    private javax.swing.JTextField jtxtsisa_angsuran;
    private javax.swing.JTextField jtxtsisa_pinjaman;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jtxtdocentry.setText("");
        jtxtline_number.setText("");
        jtxtkode_pinjaman_tipe.setText("");
        jtxtjumlah_pinjaman.setText("");
        jtxtsisa_pinjaman.setText("");
        jtxtjumlah_angsuran.setText("");
        jtxtsisa_angsuran.setText("");
        jtxtentrydate.setText("");
        jtxtauditdate.setText("");
        jtxtaudituser.setText("");
        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");
    }

    public void newData() throws CodeException {
        istatus=1;
        clearfield();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.update();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

//        jtxtdocentry.setText(GlobalUtils.churuf(obj.getdocentry()));
//        jtxtline_number.setText(obj.getline_number());
//        jtxtkode_pinjaman_tipe.setText(obj.getkode_pinjaman_tipe());
//        jtxtjumlah_pinjaman.setText(obj.getjumlah_pinjaman());
//        jtxtsisa_pinjaman.setText(obj.getsisa_pinjaman());
//        jtxtjumlah_angsuran.setText(obj.getjumlah_angsuran());
//        jtxtsisa_angsuran.setText(obj.getsisa_angsuran());
        jtxtentrydate.setText(obj.getentrydate());
        jtxtauditdate.setText(obj.getauditdate());
        jtxtaudituser.setText(obj.getaudituser());
//        jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getEntrydate()));
//        jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getAuditdate()));
//        jtxtUserID.setText(obj.getAudituser());

        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        if (obj.delete()){
            obj.moveNext();
            showData();
        }
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);

        if (istatus==1){
            jbtnBrowse.setEnabled(false);
        } else {
            jbtnBrowse.setEnabled(true);
        }
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }
//        obj.setdocentry(jtxtdocentry.getText());
//        obj.setline_number(jtxtline_number.getText());
//        obj.setkode_pinjaman_tipe(jtxtkode_pinjaman_tipe.getText());
//        obj.setjumlah_pinjaman(jtxtjumlah_pinjaman.getText());
//        obj.setsisa_pinjaman(jtxtsisa_pinjaman.getText());
//        obj.setjumlah_angsuran(jtxtjumlah_angsuran.getText());
//        obj.setsisa_angsuran(jtxtsisa_angsuran.getText());
        obj.setentrydate(jtxtentrydate.getText());
        obj.setauditdate(jtxtauditdate.getText());
        obj.setaudituser(jtxtaudituser.getText());

    }

    public void undo() throws CodeException {
        istatus = 0;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    
}
