/*
 * From ko_transaksi_registrasi
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ko.component;


import classinterface.NavigatorFormInt;
import common.component.FrmBrowseData;
import common.component.FrmMainFrame;
import kopkar.ko.objectclasses.ko_transaksi_registrasiext;
import java.util.logging.Level;
import java.util.logging.Logger;
import kopkar.utils.browsecontroller;
import kopkar.utils.findcontroller;
import org.kazao.calendar.KazaoCalendarDateTimeException;
import utils.CodeException;
import utils.GlobalUtils;

/**
 *
 * @author  Generator
 */

public class Frmko_transaksi_registrasi extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmko_transaksi_registrasi";
    
    FrmMainFrame mf ;

    ko_transaksi_registrasiext obj=new ko_transaksi_registrasiext();
    private browsecontroller obrowse;
    private ko_transaksi_registrasiext objtmp;
   
    /** Creates new form Area */
    public Frmko_transaksi_registrasi() throws CodeException {
        initComponents();
    }
    
    public Frmko_transaksi_registrasi(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrp_Complete_Status = new javax.swing.ButtonGroup();
        btngrp_sex = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();
        jlbldocument_number = new javax.swing.JLabel();
        jtxtdocument_number = new javax.swing.JTextField();
        jlbldocument_status = new javax.swing.JLabel();
        jtxtdocument_status = new javax.swing.JTextField();
        jlblcomplete_status = new javax.swing.JLabel();
        jlbldocument_date = new javax.swing.JLabel();
        jlblreference = new javax.swing.JLabel();
        jtxtreference = new javax.swing.JTextField();
        jlbldscription = new javax.swing.JLabel();
        jtxtdscription = new javax.swing.JTextField();
        jlblmember_number = new javax.swing.JLabel();
        jtxtmember_number = new javax.swing.JTextField();
        jlblmember_name = new javax.swing.JLabel();
        jtxtmember_name = new javax.swing.JTextField();
        jlbladdress1 = new javax.swing.JLabel();
        jtxtaddress1 = new javax.swing.JTextField();
        jtxtaddress2 = new javax.swing.JTextField();
        jlblcity = new javax.swing.JLabel();
        jtxtcity = new javax.swing.JTextField();
        jlblstate = new javax.swing.JLabel();
        jtxtstate = new javax.swing.JTextField();
        jlblzipcode = new javax.swing.JLabel();
        jtxtzipcode = new javax.swing.JTextField();
        jlblphone = new javax.swing.JLabel();
        jtxtphone = new javax.swing.JTextField();
        jlblfaximale = new javax.swing.JLabel();
        jtxtfaximale = new javax.swing.JTextField();
        jlblemail = new javax.swing.JLabel();
        jtxtemail = new javax.swing.JTextField();
        jlblemployee_sts = new javax.swing.JLabel();
        jlblemployee_number = new javax.swing.JLabel();
        jtxtemployee_number = new javax.swing.JTextField();
        jlbltanggal_masuk = new javax.swing.JLabel();
        jlblsex = new javax.swing.JLabel();
        jlblreligion = new javax.swing.JLabel();
        jlbldepartment_code = new javax.swing.JLabel();
        jtxtdepartment_code = new javax.swing.JTextField();
        jlblposition_code = new javax.swing.JLabel();
        jtxtposition_code = new javax.swing.JTextField();
        jlblregister_date = new javax.swing.JLabel();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();
        jtxtdepartment_name = new javax.swing.JTextField();
        jbtnBrowse_department_name = new javax.swing.JButton();
        jtxtposition_name = new javax.swing.JTextField();
        jbtnBrowse_position_name = new javax.swing.JButton();
        jopt_complete_status_draff = new javax.swing.JRadioButton();
        jopt_sex_perempuan = new javax.swing.JRadioButton();
        jlblregister_date1 = new javax.swing.JLabel();
        jtxtsimpanan_wajib = new javax.swing.JTextField();
        jHeader1 = new javax.swing.JLabel();
        jlblregister_date2 = new javax.swing.JLabel();
        jtxtsimpanan_pokok = new javax.swing.JTextField();
        jlblregister_date3 = new javax.swing.JLabel();
        jtxtsimpanan_sukarela = new javax.swing.JTextField();
        jlblregister_date4 = new javax.swing.JLabel();
        jcmbreligion = new javax.swing.JComboBox();
        jtxtsimpanan_khusus = new javax.swing.JTextField();
        jopt_complete_status_complete = new javax.swing.JRadioButton();
        jopt_sex_laki = new javax.swing.JRadioButton();
        jchck_employee_sts = new javax.swing.JCheckBox();
        kzodocument_date = new org.kazao.calendar.KazaoCalendarDate();
        kzoregister_date = new org.kazao.calendar.KazaoCalendarDate();
        kzotanggal_masuk = new org.kazao.calendar.KazaoCalendarDate();
        jlblfaximale1 = new javax.swing.JLabel();
        jtxthp = new javax.swing.JTextField();
        jlblsex1 = new javax.swing.JLabel();
        joptmember_sts_biasa = new javax.swing.JRadioButton();
        joptmember_sts_luar_biasa = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrasi Anggota");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText("Simpanan");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(70, 440, 340, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 10, 540);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(830, 100, 30, 17);

        jlbldocument_number.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_number.setText("No. Registrasi");
        getContentPane().add(jlbldocument_number);
        jlbldocument_number.setBounds(520, 100, 110, 13);

        jtxtdocument_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdocument_number.setText("document_number");
        jtxtdocument_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocument_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdocument_number);
        jtxtdocument_number.setBounds(710, 100, 120, 23);

        jlbldocument_status.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_status.setText("Status");
        getContentPane().add(jlbldocument_status);
        jlbldocument_status.setBounds(520, 80, 140, 13);

        jtxtdocument_status.setEditable(false);
        jtxtdocument_status.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdocument_status.setText("document_status");
        jtxtdocument_status.setFocusable(false);
        jtxtdocument_status.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocument_statusFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdocument_status);
        jtxtdocument_status.setBounds(710, 80, 150, 23);

        jlblcomplete_status.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcomplete_status.setText("Status Complete");
        getContentPane().add(jlblcomplete_status);
        jlblcomplete_status.setBounds(70, 530, 140, 13);

        jlbldocument_date.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_date.setText("Tgl. Dokumen");
        getContentPane().add(jlbldocument_date);
        jlbldocument_date.setBounds(520, 120, 140, 13);

        jlblreference.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblreference.setText("Referensi");
        getContentPane().add(jlblreference);
        jlblreference.setBounds(70, 550, 140, 13);

        jtxtreference.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtreference.setText("reference");
        jtxtreference.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtreferenceFocusGained(evt);
            }
        });
        getContentPane().add(jtxtreference);
        jtxtreference.setBounds(260, 550, 600, 23);

        jlbldscription.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldscription.setText("Keterangan");
        getContentPane().add(jlbldscription);
        jlbldscription.setBounds(70, 570, 140, 13);

        jtxtdscription.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdscription.setText("dscription");
        jtxtdscription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdscriptionFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdscription);
        jtxtdscription.setBounds(260, 570, 600, 23);

        jlblmember_number.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmember_number.setText("No. Anggota");
        getContentPane().add(jlblmember_number);
        jlblmember_number.setBounds(70, 100, 140, 13);

        jtxtmember_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_number.setText("member_number");
        jtxtmember_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_number);
        jtxtmember_number.setBounds(260, 100, 150, 23);

        jlblmember_name.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmember_name.setText("Nama Anggota");
        getContentPane().add(jlblmember_name);
        jlblmember_name.setBounds(70, 120, 140, 13);

        jtxtmember_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_name.setText("member_name");
        jtxtmember_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_nameFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_name);
        jtxtmember_name.setBounds(260, 120, 150, 23);

        jlbladdress1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbladdress1.setText("Alamat");
        getContentPane().add(jlbladdress1);
        jlbladdress1.setBounds(70, 140, 140, 13);

        jtxtaddress1.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaddress1.setText("address1");
        jtxtaddress1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtaddress1FocusGained(evt);
            }
        });
        getContentPane().add(jtxtaddress1);
        jtxtaddress1.setBounds(260, 140, 600, 23);

        jtxtaddress2.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaddress2.setText("address2");
        jtxtaddress2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtaddress2FocusGained(evt);
            }
        });
        getContentPane().add(jtxtaddress2);
        jtxtaddress2.setBounds(260, 160, 600, 23);

        jlblcity.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcity.setText("Kota");
        getContentPane().add(jlblcity);
        jlblcity.setBounds(70, 180, 140, 13);

        jtxtcity.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcity.setText("city");
        jtxtcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcityFocusGained(evt);
            }
        });
        getContentPane().add(jtxtcity);
        jtxtcity.setBounds(260, 180, 260, 23);

        jlblstate.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblstate.setText("Propinsi");
        getContentPane().add(jlblstate);
        jlblstate.setBounds(70, 200, 140, 13);

        jtxtstate.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtstate.setText("state");
        jtxtstate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtstateFocusGained(evt);
            }
        });
        getContentPane().add(jtxtstate);
        jtxtstate.setBounds(260, 200, 260, 23);

        jlblzipcode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblzipcode.setText("Kode Pos");
        getContentPane().add(jlblzipcode);
        jlblzipcode.setBounds(520, 180, 140, 13);

        jtxtzipcode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtzipcode.setText("zipcode");
        jtxtzipcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtzipcodeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtzipcode);
        jtxtzipcode.setBounds(710, 180, 150, 23);

        jlblphone.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblphone.setText("Telepon");
        getContentPane().add(jlblphone);
        jlblphone.setBounds(70, 220, 140, 13);

        jtxtphone.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtphone.setText("phone");
        jtxtphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtphoneFocusGained(evt);
            }
        });
        getContentPane().add(jtxtphone);
        jtxtphone.setBounds(260, 220, 150, 23);

        jlblfaximale.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblfaximale.setText("Faximale");
        getContentPane().add(jlblfaximale);
        jlblfaximale.setBounds(520, 230, 140, 13);

        jtxtfaximale.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtfaximale.setText("faximale");
        jtxtfaximale.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtfaximaleFocusGained(evt);
            }
        });
        getContentPane().add(jtxtfaximale);
        jtxtfaximale.setBounds(710, 230, 150, 23);

        jlblemail.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblemail.setText("Email");
        getContentPane().add(jlblemail);
        jlblemail.setBounds(70, 240, 140, 13);

        jtxtemail.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtemail.setText("email");
        jtxtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtemailFocusGained(evt);
            }
        });
        getContentPane().add(jtxtemail);
        jtxtemail.setBounds(260, 240, 150, 23);

        jlblemployee_sts.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblemployee_sts.setText("Status Karyawan");
        getContentPane().add(jlblemployee_sts);
        jlblemployee_sts.setBounds(70, 280, 140, 13);

        jlblemployee_number.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblemployee_number.setText("N.I.K.");
        getContentPane().add(jlblemployee_number);
        jlblemployee_number.setBounds(520, 280, 140, 13);

        jtxtemployee_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtemployee_number.setText("employee_number");
        jtxtemployee_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtemployee_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtemployee_number);
        jtxtemployee_number.setBounds(710, 280, 150, 23);

        jlbltanggal_masuk.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltanggal_masuk.setText("Tanggal Masuk");
        getContentPane().add(jlbltanggal_masuk);
        jlbltanggal_masuk.setBounds(70, 300, 140, 13);

        jlblsex.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsex.setText("Jenis Kelamin");
        getContentPane().add(jlblsex);
        jlblsex.setBounds(70, 320, 140, 13);

        jlblreligion.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblreligion.setText("Agama");
        getContentPane().add(jlblreligion);
        jlblreligion.setBounds(70, 350, 140, 13);

        jlbldepartment_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldepartment_code.setText("Departemen");
        getContentPane().add(jlbldepartment_code);
        jlbldepartment_code.setBounds(70, 370, 140, 13);

        jtxtdepartment_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdepartment_code.setText("department_code");
        jtxtdepartment_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdepartment_codeFocusGained(evt);
            }
        });
        jtxtdepartment_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtdepartment_codeKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtdepartment_code);
        jtxtdepartment_code.setBounds(260, 370, 150, 23);

        jlblposition_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblposition_code.setText("Jabatan");
        getContentPane().add(jlblposition_code);
        jlblposition_code.setBounds(70, 390, 140, 13);

        jtxtposition_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtposition_code.setText("position_code");
        jtxtposition_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtposition_codeFocusGained(evt);
            }
        });
        jtxtposition_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtposition_codeKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtposition_code);
        jtxtposition_code.setBounds(260, 390, 150, 23);

        jlblregister_date.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblregister_date.setText("Tgl Register");
        getContentPane().add(jlblregister_date);
        jlblregister_date.setBounds(70, 410, 140, 13);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(360, 30, 170, 20);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(530, 30, 130, 20);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(660, 30, 140, 20);

        jtxtdepartment_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdepartment_name.setText("department_name");
        jtxtdepartment_name.setFocusable(false);
        jtxtdepartment_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdepartment_nameFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdepartment_name);
        jtxtdepartment_name.setBounds(450, 370, 150, 23);

        jbtnBrowse_department_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse_department_name.setText("...");
        jbtnBrowse_department_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_department_nameActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse_department_name);
        jbtnBrowse_department_name.setBounds(410, 370, 30, 17);

        jtxtposition_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtposition_name.setText("position_name");
        jtxtposition_name.setFocusable(false);
        jtxtposition_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtposition_nameFocusGained(evt);
            }
        });
        getContentPane().add(jtxtposition_name);
        jtxtposition_name.setBounds(450, 390, 150, 23);

        jbtnBrowse_position_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse_position_name.setText("...");
        jbtnBrowse_position_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_position_nameActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse_position_name);
        jbtnBrowse_position_name.setBounds(410, 390, 30, 17);

        btnGrp_Complete_Status.add(jopt_complete_status_draff);
        jopt_complete_status_draff.setFont(new java.awt.Font("Dialog", 0, 10));
        jopt_complete_status_draff.setSelected(true);
        jopt_complete_status_draff.setText("Draff");
        jopt_complete_status_draff.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jopt_complete_status_draffItemStateChanged(evt);
            }
        });
        getContentPane().add(jopt_complete_status_draff);
        jopt_complete_status_draff.setBounds(260, 530, 52, 24);

        btngrp_sex.add(jopt_sex_perempuan);
        jopt_sex_perempuan.setFont(new java.awt.Font("Dialog", 0, 10));
        jopt_sex_perempuan.setText("Perempuan");
        getContentPane().add(jopt_sex_perempuan);
        jopt_sex_perempuan.setBounds(360, 320, 123, 24);

        jlblregister_date1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblregister_date1.setText("Wajib");
        getContentPane().add(jlblregister_date1);
        jlblregister_date1.setBounds(70, 470, 140, 13);

        jtxtsimpanan_wajib.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsimpanan_wajib.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsimpanan_wajib.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsimpanan_wajibKeyReleased1(evt);
            }
        });
        getContentPane().add(jtxtsimpanan_wajib);
        jtxtsimpanan_wajib.setBounds(260, 470, 150, 23);

        jHeader1.setBackground(new java.awt.Color(102, 102, 102));
        jHeader1.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader1.setForeground(new java.awt.Color(255, 255, 255));
        jHeader1.setText(" : : Registrasi Anggota");
        jHeader1.setAlignmentY(0.0F);
        jHeader1.setOpaque(true);
        getContentPane().add(jHeader1);
        jHeader1.setBounds(30, 30, 200, 20);

        jlblregister_date2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblregister_date2.setText("Pokok");
        getContentPane().add(jlblregister_date2);
        jlblregister_date2.setBounds(70, 490, 140, 13);

        jtxtsimpanan_pokok.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsimpanan_pokok.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsimpanan_pokok.setText("simpanan_pokok");
        jtxtsimpanan_pokok.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsimpanan_pokokFocusGained(evt);
            }
        });
        jtxtsimpanan_pokok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsimpanan_pokokKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtsimpanan_pokok);
        jtxtsimpanan_pokok.setBounds(260, 490, 150, 23);

        jlblregister_date3.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblregister_date3.setText("Sukarela");
        getContentPane().add(jlblregister_date3);
        jlblregister_date3.setBounds(510, 470, 140, 13);

        jtxtsimpanan_sukarela.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsimpanan_sukarela.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsimpanan_sukarela.setText("simpanan_pokok");
        jtxtsimpanan_sukarela.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsimpanan_sukarelaFocusGained(evt);
            }
        });
        jtxtsimpanan_sukarela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsimpanan_sukarelaKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtsimpanan_sukarela);
        jtxtsimpanan_sukarela.setBounds(700, 470, 150, 23);

        jlblregister_date4.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblregister_date4.setText("Khusus");
        getContentPane().add(jlblregister_date4);
        jlblregister_date4.setBounds(510, 490, 140, 13);

        jcmbreligion.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbreligion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Islam", "Kristen", "Katholik", "Hindu", "Budha" }));
        getContentPane().add(jcmbreligion);
        jcmbreligion.setBounds(260, 350, 150, 23);

        jtxtsimpanan_khusus.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsimpanan_khusus.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsimpanan_khusus.setText("simpanan_pokok");
        jtxtsimpanan_khusus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsimpanan_khususFocusGained(evt);
            }
        });
        jtxtsimpanan_khusus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsimpanan_khususKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtsimpanan_khusus);
        jtxtsimpanan_khusus.setBounds(700, 490, 150, 23);

        btnGrp_Complete_Status.add(jopt_complete_status_complete);
        jopt_complete_status_complete.setFont(new java.awt.Font("Dialog", 0, 10));
        jopt_complete_status_complete.setText("Complete");
        jopt_complete_status_complete.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jopt_complete_status_completeItemStateChanged(evt);
            }
        });
        getContentPane().add(jopt_complete_status_complete);
        jopt_complete_status_complete.setBounds(340, 530, 123, 24);

        btngrp_sex.add(jopt_sex_laki);
        jopt_sex_laki.setFont(new java.awt.Font("Dialog", 0, 10));
        jopt_sex_laki.setSelected(true);
        jopt_sex_laki.setText("Laki-laki");
        getContentPane().add(jopt_sex_laki);
        jopt_sex_laki.setBounds(260, 320, 100, 24);

        jchck_employee_sts.setFont(new java.awt.Font("Dialog", 1, 10));
        jchck_employee_sts.setText("PNS");
        getContentPane().add(jchck_employee_sts);
        jchck_employee_sts.setBounds(260, 280, 108, 24);

        kzodocument_date.setFont(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date.setOpaque(false);
        getContentPane().add(kzodocument_date);
        kzodocument_date.setBounds(710, 120, 100, 20);

        kzoregister_date.setFont(new java.awt.Font("Dialog", 0, 10));
        kzoregister_date.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzoregister_date.setOpaque(false);
        getContentPane().add(kzoregister_date);
        kzoregister_date.setBounds(260, 410, 100, 20);

        kzotanggal_masuk.setFont(new java.awt.Font("Dialog", 0, 10));
        kzotanggal_masuk.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzotanggal_masuk.setOpaque(false);
        getContentPane().add(kzotanggal_masuk);
        kzotanggal_masuk.setBounds(260, 300, 100, 20);

        jlblfaximale1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblfaximale1.setText("Handphone");
        getContentPane().add(jlblfaximale1);
        jlblfaximale1.setBounds(520, 250, 140, 13);

        jtxthp.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxthp.setText("faximale");
        jtxthp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxthpFocusGained(evt);
            }
        });
        getContentPane().add(jtxthp);
        jtxthp.setBounds(710, 250, 150, 23);

        jlblsex1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsex1.setText("Status Anggota");
        getContentPane().add(jlblsex1);
        jlblsex1.setBounds(520, 310, 140, 13);

        buttonGroup1.add(joptmember_sts_biasa);
        joptmember_sts_biasa.setFont(new java.awt.Font("Dialog", 1, 10));
        joptmember_sts_biasa.setSelected(true);
        joptmember_sts_biasa.setText("Biasa");
        getContentPane().add(joptmember_sts_biasa);
        joptmember_sts_biasa.setBounds(630, 310, 94, 24);

        buttonGroup1.add(joptmember_sts_luar_biasa);
        joptmember_sts_luar_biasa.setFont(new java.awt.Font("Dialog", 1, 10));
        joptmember_sts_luar_biasa.setText("Luar Biasa");
        getContentPane().add(joptmember_sts_luar_biasa);
        joptmember_sts_luar_biasa.setBounds(730, 310, 130, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jtxtdepartment_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdepartment_nameFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdepartment_nameFocusGained

private void jbtnBrowse_department_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_department_nameActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_departemen, "", jtxtdepartment_code, jtxtdepartment_name);
}//GEN-LAST:event_jbtnBrowse_department_nameActionPerformed

private void jtxtposition_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtposition_nameFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtposition_nameFocusGained

private void jbtnBrowse_position_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_position_nameActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_jabatan, "", jtxtposition_code, jtxtposition_name);
}//GEN-LAST:event_jbtnBrowse_position_nameActionPerformed

private void jtxtsimpanan_wajibFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsimpanan_wajibFocusGained
    // TODO add your handling code here:
    GlobalUtils.highlighttext(jtxtsimpanan_wajib);
}//GEN-LAST:event_jtxtsimpanan_wajibFocusGained

private void jtxtsimpanan_pokokFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsimpanan_pokokFocusGained
    // TODO add your handling code here:
    GlobalUtils.highlighttext(jtxtsimpanan_pokok);
}//GEN-LAST:event_jtxtsimpanan_pokokFocusGained

private void jtxtsimpanan_sukarelaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsimpanan_sukarelaFocusGained
    // TODO add your handling code here:
    GlobalUtils.highlighttext(jtxtsimpanan_sukarela);
}//GEN-LAST:event_jtxtsimpanan_sukarelaFocusGained

private void jtxtsimpanan_khususFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsimpanan_khususFocusGained
    // TODO add your handling code here:
    GlobalUtils.highlighttext(jtxtsimpanan_khusus);
}//GEN-LAST:event_jtxtsimpanan_khususFocusGained

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_transaksi_registrasi, "", jtxtdocument_number);
        try {
            if (obj.initdata(jtxtdocument_number.getText())) {
                showData();
            }
        } catch (CodeException ex) {
            Logger.getLogger(Frmko_transaksi_registrasi.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jbtnBrowseActionPerformed

private void jtxtsimpanan_wajibKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsimpanan_wajibKeyReleased
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtsimpanan_wajib);
}//GEN-LAST:event_jtxtsimpanan_wajibKeyReleased

private void jtxtsimpanan_pokokKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsimpanan_pokokKeyReleased
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtsimpanan_pokok);
}//GEN-LAST:event_jtxtsimpanan_pokokKeyReleased

private void jtxtsimpanan_sukarelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsimpanan_sukarelaKeyReleased
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtsimpanan_sukarela);
}//GEN-LAST:event_jtxtsimpanan_sukarelaKeyReleased

private void jtxtsimpanan_khususKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsimpanan_khususKeyReleased
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtsimpanan_khusus);
}//GEN-LAST:event_jtxtsimpanan_khususKeyReleased

private void jtxtdepartment_codeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtdepartment_codeKeyReleased
    // TODO add your handling code here:
    findcontroller ofind=new findcontroller();
    ofind.find(ofind.ko_departemen, jtxtdepartment_code, jtxtdepartment_name);
}//GEN-LAST:event_jtxtdepartment_codeKeyReleased

private void jtxtposition_codeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtposition_codeKeyReleased
    // TODO add your handling code here:
    findcontroller ofind=new findcontroller();
    ofind.find(ofind.ko_jabatan, jtxtposition_code, jtxtposition_name);
}//GEN-LAST:event_jtxtposition_codeKeyReleased

private void jtxthpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxthpFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxthpFocusGained

private void jtxtsimpanan_wajibKeyReleased1(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsimpanan_wajibKeyReleased1
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtsimpanan_wajib);
}//GEN-LAST:event_jtxtsimpanan_wajibKeyReleased1

private void jopt_complete_status_draffItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jopt_complete_status_draffItemStateChanged
    // TODO add your handling code here:
    enable_complete(jopt_complete_status_draff.isSelected());
}//GEN-LAST:event_jopt_complete_status_draffItemStateChanged

private void jopt_complete_status_completeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jopt_complete_status_completeItemStateChanged
    // TODO add your handling code here:
    enable_complete(jopt_complete_status_draff.isSelected());
}//GEN-LAST:event_jopt_complete_status_completeItemStateChanged

private void jtxtdocument_numberFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtdocument_number.setSelectionStart(0);
    jtxtdocument_number.setSelectionEnd(jtxtdocument_number.getText().length());
}                                               

private void jtxtdocument_statusFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtdocument_status.setSelectionStart(0);
    jtxtdocument_status.setSelectionEnd(jtxtdocument_status.getText().length());
}                                               

private void jtxtreferenceFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    jtxtreference.setSelectionStart(0);
    jtxtreference.setSelectionEnd(jtxtreference.getText().length());
}                                         

private void jtxtdscriptionFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
    jtxtdscription.setSelectionStart(0);
    jtxtdscription.setSelectionEnd(jtxtdscription.getText().length());
}                                          

private void jtxtmember_numberFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxtmember_number.setSelectionStart(0);
    jtxtmember_number.setSelectionEnd(jtxtmember_number.getText().length());
}                                             

private void jtxtmember_nameFocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    jtxtmember_name.setSelectionStart(0);
    jtxtmember_name.setSelectionEnd(jtxtmember_name.getText().length());
}                                           

private void jtxtaddress1FocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtaddress1.setSelectionStart(0);
    jtxtaddress1.setSelectionEnd(jtxtaddress1.getText().length());
}                                        

private void jtxtaddress2FocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtaddress2.setSelectionStart(0);
    jtxtaddress2.setSelectionEnd(jtxtaddress2.getText().length());
}                                        

private void jtxtcityFocusGained(java.awt.event.FocusEvent evt) {                                  
        // TODO add your handling code here:
    jtxtcity.setSelectionStart(0);
    jtxtcity.setSelectionEnd(jtxtcity.getText().length());
}                                    

private void jtxtstateFocusGained(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    jtxtstate.setSelectionStart(0);
    jtxtstate.setSelectionEnd(jtxtstate.getText().length());
}                                     

private void jtxtzipcodeFocusGained(java.awt.event.FocusEvent evt) {                                     
        // TODO add your handling code here:
    jtxtzipcode.setSelectionStart(0);
    jtxtzipcode.setSelectionEnd(jtxtzipcode.getText().length());
}                                       

private void jtxtphoneFocusGained(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    jtxtphone.setSelectionStart(0);
    jtxtphone.setSelectionEnd(jtxtphone.getText().length());
}                                     

private void jtxtfaximaleFocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtfaximale.setSelectionStart(0);
    jtxtfaximale.setSelectionEnd(jtxtfaximale.getText().length());
}                                        

private void jtxtemailFocusGained(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    jtxtemail.setSelectionStart(0);
    jtxtemail.setSelectionEnd(jtxtemail.getText().length());
}                                     

private void jtxtemployee_numberFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtemployee_number.setSelectionStart(0);
    jtxtemployee_number.setSelectionEnd(jtxtemployee_number.getText().length());
}                                               

private void jtxtdepartment_codeFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtdepartment_code.setSelectionStart(0);
    jtxtdepartment_code.setSelectionEnd(jtxtdepartment_code.getText().length());
}                                               

private void jtxtposition_codeFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxtposition_code.setSelectionStart(0);
    jtxtposition_code.setSelectionEnd(jtxtposition_code.getText().length());
}                                             

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmko_transaksi_registrasi().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.ButtonGroup btnGrp_Complete_Status;
    private javax.swing.ButtonGroup btngrp_sex;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jHeader;
    private javax.swing.JLabel jHeader1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowse_department_name;
    private javax.swing.JButton jbtnBrowse_position_name;
    private javax.swing.JCheckBox jchck_employee_sts;
    private javax.swing.JComboBox jcmbreligion;
    private javax.swing.JLabel jlbladdress1;
    private javax.swing.JLabel jlblcity;
    private javax.swing.JLabel jlblcomplete_status;
    private javax.swing.JLabel jlbldepartment_code;
    private javax.swing.JLabel jlbldocument_date;
    private javax.swing.JLabel jlbldocument_number;
    private javax.swing.JLabel jlbldocument_status;
    private javax.swing.JLabel jlbldscription;
    private javax.swing.JLabel jlblemail;
    private javax.swing.JLabel jlblemployee_number;
    private javax.swing.JLabel jlblemployee_sts;
    private javax.swing.JLabel jlblfaximale;
    private javax.swing.JLabel jlblfaximale1;
    private javax.swing.JLabel jlblmember_name;
    private javax.swing.JLabel jlblmember_number;
    private javax.swing.JLabel jlblphone;
    private javax.swing.JLabel jlblposition_code;
    private javax.swing.JLabel jlblreference;
    private javax.swing.JLabel jlblregister_date;
    private javax.swing.JLabel jlblregister_date1;
    private javax.swing.JLabel jlblregister_date2;
    private javax.swing.JLabel jlblregister_date3;
    private javax.swing.JLabel jlblregister_date4;
    private javax.swing.JLabel jlblreligion;
    private javax.swing.JLabel jlblsex;
    private javax.swing.JLabel jlblsex1;
    private javax.swing.JLabel jlblstate;
    private javax.swing.JLabel jlbltanggal_masuk;
    private javax.swing.JLabel jlblzipcode;
    private javax.swing.JRadioButton jopt_complete_status_complete;
    private javax.swing.JRadioButton jopt_complete_status_draff;
    private javax.swing.JRadioButton jopt_sex_laki;
    private javax.swing.JRadioButton jopt_sex_perempuan;
    private javax.swing.JRadioButton joptmember_sts_biasa;
    private javax.swing.JRadioButton joptmember_sts_luar_biasa;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtaddress1;
    private javax.swing.JTextField jtxtaddress2;
    private javax.swing.JTextField jtxtcity;
    private javax.swing.JTextField jtxtdepartment_code;
    private javax.swing.JTextField jtxtdepartment_name;
    private javax.swing.JTextField jtxtdocument_number;
    private javax.swing.JTextField jtxtdocument_status;
    private javax.swing.JTextField jtxtdscription;
    private javax.swing.JTextField jtxtemail;
    private javax.swing.JTextField jtxtemployee_number;
    private javax.swing.JTextField jtxtfaximale;
    private javax.swing.JTextField jtxthp;
    private javax.swing.JTextField jtxtmember_name;
    private javax.swing.JTextField jtxtmember_number;
    private javax.swing.JTextField jtxtphone;
    private javax.swing.JTextField jtxtposition_code;
    private javax.swing.JTextField jtxtposition_name;
    private javax.swing.JTextField jtxtreference;
    private javax.swing.JTextField jtxtsimpanan_khusus;
    private javax.swing.JTextField jtxtsimpanan_pokok;
    private javax.swing.JTextField jtxtsimpanan_sukarela;
    private javax.swing.JTextField jtxtsimpanan_wajib;
    private javax.swing.JTextField jtxtstate;
    private javax.swing.JTextField jtxtzipcode;
    private org.kazao.calendar.KazaoCalendarDate kzodocument_date;
    private org.kazao.calendar.KazaoCalendarDate kzoregister_date;
    private org.kazao.calendar.KazaoCalendarDate kzotanggal_masuk;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        if (obj.getdocentry()==0){
            newData();
        }
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jtxtdocument_number.setText("");
        jtxtdocument_status.setText("");
        jopt_complete_status_draff.setSelected(true);
        try {
            kzodocument_date.setDate(GlobalUtils.getCurrentDate());
            kzoregister_date.setDate(GlobalUtils.getCurrentDate());
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmko_transaksi_registrasi.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtxtreference.setText("");
        jtxtdscription.setText("");
        jtxtmember_number.setText("");
        jtxtmember_name.setText("");
        jtxtaddress1.setText("");
        jtxtaddress2.setText("");
        jtxtcity.setText("");
        jtxtstate.setText("");
        jtxtzipcode.setText("");
        jtxtphone.setText("");
        jtxtfaximale.setText("");
        jtxtemail.setText("");
        jchck_employee_sts.setSelected(false);
        jtxtemployee_number.setText("");
        try {
            kzotanggal_masuk.setDate(GlobalUtils.getCurrentDate());
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmko_transaksi_registrasi.class.getName()).log(Level.SEVERE, null, ex);
        }
        jopt_sex_laki.setSelected(true);
        jcmbreligion.setSelectedIndex(0);
        jtxtdepartment_code.setText("");
        jtxtposition_code.setText("");
        jtxtsimpanan_wajib.setText("0");
        jtxtsimpanan_pokok.setText("0");
        jtxtsimpanan_sukarela.setText("0");
        jtxtsimpanan_khusus.setText("0");

        jtxtdepartment_name.setText("");
        jtxtposition_name.setText("");

        jtxthp.setText("");
        joptmember_sts_biasa.setSelected(true);
        
        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");
    }

    public void newData() throws CodeException {
        istatus=1;
        objtmp=obj;
        obj=new ko_transaksi_registrasiext();
        showData();

        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.update();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        try {
            if (obj.getcomplete_status().equalsIgnoreCase("Y")){
                enable_complete(false);
            } else {
                enable_complete(true);
            }
            if (obj.getmember_number().equalsIgnoreCase("")){
                jopt_complete_status_complete.setEnabled(false);
            } else {
                jopt_complete_status_complete.setEnabled(true);
            }
            
            setToolBar(iformtype, istatus);
            setCursor(GlobalUtils.HOURGLASSCURSOR);
            jtxtdocument_number.setText(obj.getdocument_number());
            jtxtdocument_status.setText(obj.getdocument_status_desc());
            if (obj.getcomplete_status().equalsIgnoreCase("N")) {
                jopt_complete_status_draff.setSelected(true);
            } else {
                jopt_complete_status_complete.setSelected(true);
            }
            kzodocument_date.setDate(GlobalUtils.formatDate(obj.getdocument_date(),"MM/dd/yyyy"));
            jtxtreference.setText(obj.getreference());
            jtxtdscription.setText(obj.getdscription());
            jtxtmember_number.setText(obj.getmember_number());
            jtxtmember_name.setText(obj.getmember_name());
            jtxtaddress1.setText(obj.getaddress1());
            jtxtaddress2.setText(obj.getaddress2());
            jtxtcity.setText(obj.getcity());
            jtxtstate.setText(obj.getstate());
            jtxtzipcode.setText(obj.getzipcode());
            jtxtphone.setText(obj.getphone());
            jtxtfaximale.setText(obj.getfaximale());
            jtxtemail.setText(obj.getemail());
            if (obj.getemployee_sts().equalsIgnoreCase("Y")) {
                jchck_employee_sts.setSelected(true);
            }
            jtxtemployee_number.setText(obj.getemployee_number());
            kzotanggal_masuk.setDate(GlobalUtils.formatDate(obj.gettanggal_masuk(),"MM/dd/yyyy"));
            if (obj.getsex().equalsIgnoreCase("L")) {
                jopt_sex_laki.setSelected(true);
            } else {
                jopt_sex_perempuan.setSelected(true);
            }
            jcmbreligion.setSelectedIndex(GlobalUtils.toInt(obj.getreligion()) - 1);
            jtxtdepartment_code.setText(obj.getdepartment_code());
            jtxtdepartment_name.setText(obj.getDept_info().getnama_departemen());
            jtxtposition_code.setText(obj.getposition_code());
            jtxtposition_name.setText(obj.getJabt_info().getnama_jabatan());

            kzoregister_date.setDate(GlobalUtils.formatDate(obj.getregister_date(),"MM/dd/yyyy"));

            jtxtsimpanan_wajib.setText(GlobalUtils.formatnumber(obj.getsimpanan_wajib()));
            jtxtsimpanan_pokok.setText(GlobalUtils.formatnumber(obj.getsimpanan_pokok()));
            jtxtsimpanan_sukarela.setText(GlobalUtils.formatnumber(obj.getsimpanan_sukarela()));
            jtxtsimpanan_khusus.setText(GlobalUtils.formatnumber(obj.getsimpanan_khusus()));

            jtxthp.setText(obj.gethp());
            if (obj.getmember_sts().equalsIgnoreCase("Y")){
                joptmember_sts_luar_biasa.setSelected(true);
            } else {
                joptmember_sts_biasa.setSelected(true);
            }

            jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getentrydate()));
            jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getauditdate()));
            jtxtUserID.setText(obj.getaudituser());
            setCursor(GlobalUtils.NORMALCURSOR);
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmko_transaksi_registrasi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void delete() throws CodeException {
        obj.delete();
        obj.moveNext();
        showData();

        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);
        if (obj.getdocument_status().equalsIgnoreCase("C")){
            mf.setToolBar(iformtype,7);
        }

        if (istatus==1){
            jbtnBrowse.setEnabled(false);
        } else {
            jbtnBrowse.setEnabled(true);
        }
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }
        obj.setdocument_number(jtxtdocument_number.getText());
        obj.setdocument_status(jtxtdocument_status.getText());
        if (jopt_complete_status_draff.isSelected()){
            obj.setcomplete_status("N");
        } else {
            obj.setcomplete_status("Y");
        }
        obj.setdocument_date(kzodocument_date.getDate());
        obj.setreference(jtxtreference.getText());
        obj.setdscription(jtxtdscription.getText());
        obj.setmember_number(jtxtmember_number.getText());
        obj.setmember_name(jtxtmember_name.getText());
        obj.setaddress1(jtxtaddress1.getText());
        obj.setaddress2(jtxtaddress2.getText());
        obj.setcity(jtxtcity.getText());
        obj.setstate(jtxtstate.getText());
        obj.setzipcode(jtxtzipcode.getText());
        obj.setphone(jtxtphone.getText());
        obj.setfaximale(jtxtfaximale.getText());
        obj.setemail(jtxtemail.getText());
        if (jchck_employee_sts.isSelected()){
            obj.setemployee_sts("Y");
        } else {
            obj.setemployee_sts("N");
        }
        obj.setemployee_number(jtxtemployee_number.getText());
        obj.settanggal_masuk(kzotanggal_masuk.getDate());
        if (jopt_sex_laki.isSelected()){
            obj.setsex("L");
        } else {
            obj.setsex("P");
        }
        obj.setreligion(GlobalUtils.churuf(jcmbreligion.getSelectedIndex()+1));
        obj.setdepartment_code(jtxtdepartment_code.getText());
        obj.setposition_code(jtxtposition_code.getText());
        obj.setregister_date(kzoregister_date.getDate());

        obj.setsimpanan_wajib(GlobalUtils.toDbl(jtxtsimpanan_wajib.getText()));
        obj.setsimpanan_pokok(GlobalUtils.toDbl(jtxtsimpanan_pokok.getText()));
        obj.setsimpanan_sukarela(GlobalUtils.toDbl(jtxtsimpanan_sukarela.getText()));
        obj.setsimpanan_khusus(GlobalUtils.toDbl(jtxtsimpanan_khusus.getText()));

        obj.sethp(jtxthp.getText());
        if (joptmember_sts_luar_biasa.isSelected()){
            obj.setmember_sts("Y");
        } else {
            obj.setmember_sts("N");
        }
    }

    public void undo() throws CodeException {
        istatus = 0;
        obj=objtmp;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    private void enable_complete(boolean b) {
        jbtnBrowse_department_name.setEnabled(b);
        jbtnBrowse_position_name.setEnabled(b);
        jchck_employee_sts.setEnabled(b);
        jcmbreligion.setEditable(b);
        jopt_sex_laki.setEnabled(b);
        jopt_sex_perempuan.setEnabled(b);
        joptmember_sts_biasa.setEnabled(b);
        joptmember_sts_luar_biasa.setEnabled(b);
        jtxtaddress1.setEditable(b);
        jtxtaddress2.setEditable(b);
        jtxtcity.setEditable(b);
        jtxtdepartment_code.setEditable(b);
        jtxtdepartment_name.setEditable(false);
        jtxtdocument_number.setEditable(b);
        jtxtdocument_status.setEditable(b);
        jtxtdscription.setEditable(b);
        jtxtemail.setEditable(b);
        jtxtemployee_number.setEditable(b);
        jtxtfaximale.setEditable(b);
        jtxthp.setEditable(b);
        jtxtmember_name.setEditable(b);
        jtxtmember_number.setEditable(false);
        jtxtphone.setEditable(b);
        jtxtposition_code.setEditable(b);
        jtxtposition_name.setEditable(false);
        jtxtreference.setEditable(b);
        jtxtsimpanan_khusus.setEditable(b);
        jtxtsimpanan_pokok.setEditable(b);
        jtxtsimpanan_sukarela.setEditable(b);
        jtxtsimpanan_wajib.setEditable(b);
        jtxtstate.setEditable(b);
        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalUpdate.setEditable(false);
        jtxtUserID.setEditable(false);
        jtxtzipcode.setEditable(b);
        kzodocument_date.setEditable(b);
        kzoregister_date.setEditable(b);
        kzotanggal_masuk.setEditable(b);
    }

    
}
