/*
 * From ko_loan
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ko.component;


import classinterface.NavigatorFormInt;
import common.component.FrmBrowseData;
import common.component.FrmMainFrame;
import kopkar.ko.objectclasses.ko_loanext;
import java.util.logging.Level;
import java.util.logging.Logger;
import utils.CodeException;
import utils.GlobalUtils;

/**
 *
 * @author  Generator
 */

public class Frmko_loan extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmko_loan";
    
    FrmMainFrame mf ;

    ko_loanext obj=new ko_loanext();
   
    /** Creates new form Area */
    public Frmko_loan() throws CodeException {
        initComponents();
    }
    
    public Frmko_loan(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();
        jlblloan_code = new javax.swing.JLabel();
        jtxtloan_code = new javax.swing.JTextField();
        jlblloan_name = new javax.swing.JLabel();
        jtxtloan_name = new javax.swing.JTextField();
        jlblactive_sts = new javax.swing.JLabel();
        jtxtactive_sts = new javax.swing.JTextField();
        jlblrate = new javax.swing.JLabel();
        jtxtrate = new javax.swing.JTextField();
        jlblmode = new javax.swing.JLabel();
        jtxtmode = new javax.swing.JTextField();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ko_loan");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : ko_loan");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 200, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(420, 100, 30, 17);

        jlblloan_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblloan_code.setText("loan_code");
        getContentPane().add(jlblloan_code);
        jlblloan_code.setBounds(70, 100, 140, 13);

        jtxtloan_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtloan_code.setText("loan_code");
        jtxtloan_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtloan_codeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtloan_code);
        jtxtloan_code.setBounds(260, 100, 150, 23);

        jlblloan_name.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblloan_name.setText("loan_name");
        getContentPane().add(jlblloan_name);
        jlblloan_name.setBounds(70, 120, 140, 13);

        jtxtloan_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtloan_name.setText("loan_name");
        jtxtloan_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtloan_nameFocusGained(evt);
            }
        });
        getContentPane().add(jtxtloan_name);
        jtxtloan_name.setBounds(260, 120, 150, 23);

        jlblactive_sts.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblactive_sts.setText("active_sts");
        getContentPane().add(jlblactive_sts);
        jlblactive_sts.setBounds(70, 140, 140, 13);

        jtxtactive_sts.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtactive_sts.setText("active_sts");
        jtxtactive_sts.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtactive_stsFocusGained(evt);
            }
        });
        getContentPane().add(jtxtactive_sts);
        jtxtactive_sts.setBounds(260, 140, 150, 23);

        jlblrate.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblrate.setText("rate");
        getContentPane().add(jlblrate);
        jlblrate.setBounds(70, 160, 140, 13);

        jtxtrate.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtrate.setText("rate");
        jtxtrate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtrateFocusGained(evt);
            }
        });
        getContentPane().add(jtxtrate);
        jtxtrate.setBounds(260, 160, 150, 23);

        jlblmode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmode.setText("mode");
        getContentPane().add(jlblmode);
        jlblmode.setBounds(70, 180, 140, 13);

        jtxtmode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmode.setText("mode");
        jtxtmode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmodeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmode);
        jtxtmode.setBounds(260, 180, 150, 23);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(360, 30, 170, 20);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(530, 30, 130, 20);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(660, 30, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jtxtloan_codeFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    jtxtloan_code.setSelectionStart(0);
    jtxtloan_code.setSelectionEnd(jtxtloan_code.getText().length());
}                                         

private void jtxtloan_nameFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    jtxtloan_name.setSelectionStart(0);
    jtxtloan_name.setSelectionEnd(jtxtloan_name.getText().length());
}                                         

private void jtxtactive_stsFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
    jtxtactive_sts.setSelectionStart(0);
    jtxtactive_sts.setSelectionEnd(jtxtactive_sts.getText().length());
}                                          

private void jtxtrateFocusGained(java.awt.event.FocusEvent evt) {                                  
        // TODO add your handling code here:
    jtxtrate.setSelectionStart(0);
    jtxtrate.setSelectionEnd(jtxtrate.getText().length());
}                                    

private void jtxtmodeFocusGained(java.awt.event.FocusEvent evt) {                                  
        // TODO add your handling code here:
    jtxtmode.setSelectionStart(0);
    jtxtmode.setSelectionEnd(jtxtmode.getText().length());
}                                    

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
    FrmBrowseData frmbrowse=new FrmBrowseData("ko_loan", "");
    frmbrowse.setModal(true);
    frmbrowse.setVisible(true);
    try {
        obj.initdata(frmbrowse.getValue());
        showData();
    } catch (CodeException ex) {
        Logger.getLogger(Frmko_loan.class.getName()).log(Level.SEVERE, null, ex);
    }
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmko_loan().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JLabel jlblactive_sts;
    private javax.swing.JLabel jlblloan_code;
    private javax.swing.JLabel jlblloan_name;
    private javax.swing.JLabel jlblmode;
    private javax.swing.JLabel jlblrate;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtactive_sts;
    private javax.swing.JTextField jtxtloan_code;
    private javax.swing.JTextField jtxtloan_name;
    private javax.swing.JTextField jtxtmode;
    private javax.swing.JTextField jtxtrate;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jtxtloan_code.setText("");
        jtxtloan_name.setText("");
        jtxtactive_sts.setText("");
        jtxtrate.setText("");
        jtxtmode.setText("");

        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");
    }

    public void newData() throws CodeException {
        istatus=1;
        clearfield();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.update();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        jtxtloan_code.setText(obj.getloan_code());
        jtxtloan_name.setText(obj.getloan_name());
        jtxtactive_sts.setText(obj.getactive_sts());
        jtxtrate.setText(GlobalUtils.churuf(obj.getrate()));
        jtxtmode.setText(obj.getmode());

        jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getentrydate()));
        jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getauditdate()));
        jtxtUserID.setText(obj.getaudituser());

        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        if (obj.delete()){
            obj.moveNext();
            showData();
        }
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);

        if (istatus==1){
            jbtnBrowse.setEnabled(false);
        } else {
            jbtnBrowse.setEnabled(true);
        }
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }
        obj.setloan_code(jtxtloan_code.getText());
        obj.setloan_name(jtxtloan_name.getText());
        obj.setactive_sts(jtxtactive_sts.getText());
        obj.setrate(GlobalUtils.toDbl(jtxtrate.getText()));
        obj.setmode(jtxtmode.getText());

        
    }

    public void undo() throws CodeException {
        istatus = 0;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    
}
