/*
 * From ko_anggota
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ko.component;


import classinterface.NavigatorFormInt;
import common.component.FrmMainFrame;
import javax.swing.table.DefaultTableModel;
import kopkar.ko.objectclasses.ko_anggota_pinjaman;
import java.util.logging.Level;
import java.util.logging.Logger;
import kopkar.ko.objectclasses.ko_anggota_infoext;
import kopkar.ko.objectclasses.ko_anggota_pinjamancol;
import kopkar.utils.browsecontroller;
import kopkar.utils.findcontroller;
import org.kazao.calendar.KazaoCalendarDateTimeException;
import utils.CodeException;
import utils.GlobalModel;
import utils.GlobalUtils;

/**
 *
 * @author  Generator
 */

public class Frmko_anggota extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmko_anggota";
    
    FrmMainFrame mf ;

    ko_anggota_infoext obj=new ko_anggota_infoext();
    private browsecontroller obrowse;
    private findcontroller ofind;
    private DefaultTableModel model;
   
    /** Creates new form Area */
    public Frmko_anggota() throws CodeException {
        initComponents();
    }
    
    public Frmko_anggota(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();

        model=(DefaultTableModel) jTable1.getModel();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();
        jlblmember_number = new javax.swing.JLabel();
        jtxtmember_number = new javax.swing.JTextField();
        jlblmember_name = new javax.swing.JLabel();
        jtxtmember_name = new javax.swing.JTextField();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jlbladdress1 = new javax.swing.JLabel();
        jtxtaddress1 = new javax.swing.JTextField();
        jtxtaddress2 = new javax.swing.JTextField();
        jlblcity = new javax.swing.JLabel();
        jtxtcity = new javax.swing.JTextField();
        jlblstate = new javax.swing.JLabel();
        jtxtstate = new javax.swing.JTextField();
        jlblzipcode = new javax.swing.JLabel();
        jtxtzipcode = new javax.swing.JTextField();
        jlblphone = new javax.swing.JLabel();
        jtxtphone = new javax.swing.JTextField();
        jlblfaximale = new javax.swing.JLabel();
        jtxtfaximale = new javax.swing.JTextField();
        jlblemail = new javax.swing.JLabel();
        jtxtemail = new javax.swing.JTextField();
        jlblemployee_sts = new javax.swing.JLabel();
        jlblemployee_number = new javax.swing.JLabel();
        jtxtemployee_number = new javax.swing.JTextField();
        jlbltanggal_masuk = new javax.swing.JLabel();
        jlblsex = new javax.swing.JLabel();
        jlblreligion = new javax.swing.JLabel();
        jlbldepartment_code = new javax.swing.JLabel();
        jtxtdepartment_code = new javax.swing.JTextField();
        jlblposition_code = new javax.swing.JLabel();
        jtxtposition_code = new javax.swing.JTextField();
        jchkemployee_sts = new javax.swing.JCheckBox();
        kzotanggal_masuk = new org.kazao.calendar.KazaoCalendarDate();
        joptsex_perempuan = new javax.swing.JRadioButton();
        joptsex_laki = new javax.swing.JRadioButton();
        jcmbreligion = new javax.swing.JComboBox();
        jbtnBrowse_Departemen = new javax.swing.JButton();
        jbtnBrowse_Jabatan = new javax.swing.JButton();
        jtxtdepartment_name = new javax.swing.JTextField();
        jtxtposition_name = new javax.swing.JTextField();
        jlblfaximale1 = new javax.swing.JLabel();
        jtxthp = new javax.swing.JTextField();
        jlblsex1 = new javax.swing.JLabel();
        joptmember_sts_biasa = new javax.swing.JRadioButton();
        joptmember_sts_luar_biasa = new javax.swing.JRadioButton();
        jlblposition_code1 = new javax.swing.JLabel();
        jtxtkode_pendidikan = new javax.swing.JTextField();
        jbtnBrowse_Jabatan1 = new javax.swing.JButton();
        jtxtpendidikan_name = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jlblsimpanan_wajib = new javax.swing.JLabel();
        jtxtsimpanan_wajib = new javax.swing.JTextField();
        jlblsimpanan_pokok = new javax.swing.JLabel();
        jtxtsimpanan_pokok = new javax.swing.JTextField();
        jlblsimpanan_sukarela = new javax.swing.JLabel();
        jtxtsimpanan_sukarela = new javax.swing.JTextField();
        jlblsimpanan_khusus = new javax.swing.JLabel();
        jtxtsimpanan_khusus = new javax.swing.JTextField();
        jlblreference_number = new javax.swing.JLabel();
        jtxtreference_number = new javax.swing.JTextField();
        jlbllast_update = new javax.swing.JLabel();
        jtxtlast_update = new javax.swing.JTextField();
        jHeader1 = new javax.swing.JLabel();
        jlblsimpanan_wajib1 = new javax.swing.JLabel();
        jtxtsimpanan_wajib1 = new javax.swing.JTextField();
        jlblsimpanan_pokok1 = new javax.swing.JLabel();
        jtxtsimpanan_pokok1 = new javax.swing.JTextField();
        jlblsimpanan_sukarela1 = new javax.swing.JLabel();
        jtxtsimpanan_sukarela1 = new javax.swing.JTextField();
        jlblsimpanan_khusus1 = new javax.swing.JLabel();
        jtxtsimpanan_khusus1 = new javax.swing.JTextField();
        jHeader2 = new javax.swing.JLabel();
        jlblmember_name1 = new javax.swing.JLabel();
        jtxttotal_simpanan = new javax.swing.JTextField();
        jlbllast_update1 = new javax.swing.JLabel();
        jtxtmaks_penarikan_ss = new javax.swing.JTextField();
        jlbllast_update2 = new javax.swing.JLabel();
        jtxtmaks_pinjaman = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jHeader3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlbldepartment_code1 = new javax.swing.JLabel();
        jtxtbank_code = new javax.swing.JTextField();
        jbtnBrowse_Departemen1 = new javax.swing.JButton();
        jtxtbank_name = new javax.swing.JTextField();
        jlbldepartment_code2 = new javax.swing.JLabel();
        jtxtbank_account = new javax.swing.JTextField();
        jlbldepartment_code3 = new javax.swing.JLabel();
        jtxtbank_branch = new javax.swing.JTextField();
        jchkactive_sts = new javax.swing.JCheckBox();
        jlblregister_date = new javax.swing.JLabel();
        kzoregister_date = new org.kazao.calendar.KazaoCalendarDate();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Anggota");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Anggota");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 200, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 2);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 2, 400);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(420, 100, 30, 17);

        jlblmember_number.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmember_number.setText("No. Anggota");
        getContentPane().add(jlblmember_number);
        jlblmember_number.setBounds(70, 100, 140, 14);

        jtxtmember_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_number.setText("member_number");
        jtxtmember_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_number);
        jtxtmember_number.setBounds(260, 100, 150, 20);

        jlblmember_name.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmember_name.setText("Nama Anggota");
        getContentPane().add(jlblmember_name);
        jlblmember_name.setBounds(70, 120, 140, 14);

        jtxtmember_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_name.setText("member_name");
        jtxtmember_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_nameFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_name);
        jtxtmember_name.setBounds(260, 120, 400, 20);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(360, 30, 170, 16);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(530, 30, 130, 16);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(660, 30, 140, 16);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 0, 10));

        jPanel1.setLayout(null);

        jlbladdress1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbladdress1.setText("Alamat");
        jPanel1.add(jlbladdress1);
        jlbladdress1.setBounds(10, 10, 140, 14);

        jtxtaddress1.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaddress1.setText("address1");
        jtxtaddress1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtaddress1FocusGained(evt);
            }
        });
        jPanel1.add(jtxtaddress1);
        jtxtaddress1.setBounds(200, 10, 540, 20);

        jtxtaddress2.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaddress2.setText("address2");
        jtxtaddress2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtaddress2FocusGained(evt);
            }
        });
        jPanel1.add(jtxtaddress2);
        jtxtaddress2.setBounds(200, 30, 540, 20);

        jlblcity.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcity.setText("Kota");
        jPanel1.add(jlblcity);
        jlblcity.setBounds(10, 50, 140, 14);

        jtxtcity.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcity.setText("city");
        jtxtcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcityFocusGained(evt);
            }
        });
        jPanel1.add(jtxtcity);
        jtxtcity.setBounds(200, 50, 150, 20);

        jlblstate.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblstate.setText("Propinsi");
        jPanel1.add(jlblstate);
        jlblstate.setBounds(10, 70, 140, 14);

        jtxtstate.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtstate.setText("state");
        jtxtstate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtstateFocusGained(evt);
            }
        });
        jPanel1.add(jtxtstate);
        jtxtstate.setBounds(200, 70, 150, 20);

        jlblzipcode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblzipcode.setText("Kode Pos");
        jPanel1.add(jlblzipcode);
        jlblzipcode.setBounds(400, 50, 140, 14);

        jtxtzipcode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtzipcode.setText("zipcode");
        jtxtzipcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtzipcodeFocusGained(evt);
            }
        });
        jPanel1.add(jtxtzipcode);
        jtxtzipcode.setBounds(590, 50, 150, 20);

        jlblphone.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblphone.setText("Telepon");
        jPanel1.add(jlblphone);
        jlblphone.setBounds(10, 90, 140, 14);

        jtxtphone.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtphone.setText("phone");
        jtxtphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtphoneFocusGained(evt);
            }
        });
        jPanel1.add(jtxtphone);
        jtxtphone.setBounds(200, 90, 150, 20);

        jlblfaximale.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblfaximale.setText("Faximale");
        jPanel1.add(jlblfaximale);
        jlblfaximale.setBounds(400, 90, 140, 14);

        jtxtfaximale.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtfaximale.setText("faximale");
        jtxtfaximale.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtfaximaleFocusGained(evt);
            }
        });
        jPanel1.add(jtxtfaximale);
        jtxtfaximale.setBounds(590, 90, 150, 20);

        jlblemail.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblemail.setText("Email");
        jPanel1.add(jlblemail);
        jlblemail.setBounds(10, 110, 140, 14);

        jtxtemail.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtemail.setText("email");
        jtxtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtemailFocusGained(evt);
            }
        });
        jPanel1.add(jtxtemail);
        jtxtemail.setBounds(200, 110, 150, 20);

        jlblemployee_sts.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblemployee_sts.setText("Status Karyawan");
        jPanel1.add(jlblemployee_sts);
        jlblemployee_sts.setBounds(10, 140, 140, 14);

        jlblemployee_number.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblemployee_number.setText("NIK");
        jPanel1.add(jlblemployee_number);
        jlblemployee_number.setBounds(400, 140, 140, 14);

        jtxtemployee_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtemployee_number.setText("employee_number");
        jtxtemployee_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtemployee_numberFocusGained(evt);
            }
        });
        jPanel1.add(jtxtemployee_number);
        jtxtemployee_number.setBounds(590, 140, 150, 20);

        jlbltanggal_masuk.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltanggal_masuk.setText("Tanggal Masuk");
        jPanel1.add(jlbltanggal_masuk);
        jlbltanggal_masuk.setBounds(10, 160, 140, 14);

        jlblsex.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsex.setText("Jenis Kelamin");
        jPanel1.add(jlblsex);
        jlblsex.setBounds(10, 180, 140, 14);

        jlblreligion.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblreligion.setText("Agama");
        jPanel1.add(jlblreligion);
        jlblreligion.setBounds(10, 200, 140, 14);

        jlbldepartment_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldepartment_code.setText("Departemen");
        jPanel1.add(jlbldepartment_code);
        jlbldepartment_code.setBounds(10, 220, 140, 14);

        jtxtdepartment_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdepartment_code.setText("department_code");
        jtxtdepartment_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdepartment_codeFocusGained(evt);
            }
        });
        jtxtdepartment_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtdepartment_codeKeyReleased(evt);
            }
        });
        jPanel1.add(jtxtdepartment_code);
        jtxtdepartment_code.setBounds(200, 220, 150, 20);

        jlblposition_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblposition_code.setText("Jabatan");
        jPanel1.add(jlblposition_code);
        jlblposition_code.setBounds(10, 240, 140, 14);

        jtxtposition_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtposition_code.setText("position_code");
        jtxtposition_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtposition_codeFocusGained(evt);
            }
        });
        jtxtposition_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtposition_codeKeyReleased(evt);
            }
        });
        jPanel1.add(jtxtposition_code);
        jtxtposition_code.setBounds(200, 240, 150, 20);

        jchkemployee_sts.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkemployee_sts.setText("PNS");
        jPanel1.add(jchkemployee_sts);
        jchkemployee_sts.setBounds(200, 140, 108, 29);

        kzotanggal_masuk.setFont(new java.awt.Font("Dialog", 0, 10));
        kzotanggal_masuk.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzotanggal_masuk.setOpaque(false);
        jPanel1.add(kzotanggal_masuk);
        kzotanggal_masuk.setBounds(200, 160, 100, 20);

        buttonGroup1.add(joptsex_perempuan);
        joptsex_perempuan.setFont(new java.awt.Font("Dialog", 1, 10));
        joptsex_perempuan.setText("Permpuan");
        jPanel1.add(joptsex_perempuan);
        joptsex_perempuan.setBounds(300, 180, 123, 29);

        buttonGroup1.add(joptsex_laki);
        joptsex_laki.setFont(new java.awt.Font("Dialog", 1, 10));
        joptsex_laki.setText("Laki-laki");
        jPanel1.add(joptsex_laki);
        joptsex_laki.setBounds(200, 180, 94, 29);

        jcmbreligion.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbreligion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Islam", "Kristen", "Katholik", "Hindu", "Budha" }));
        jPanel1.add(jcmbreligion);
        jcmbreligion.setBounds(200, 200, 63, 20);

        jbtnBrowse_Departemen.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse_Departemen.setText("...");
        jbtnBrowse_Departemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_DepartemenActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBrowse_Departemen);
        jbtnBrowse_Departemen.setBounds(350, 220, 30, 17);

        jbtnBrowse_Jabatan.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse_Jabatan.setText("...");
        jbtnBrowse_Jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_JabatanActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBrowse_Jabatan);
        jbtnBrowse_Jabatan.setBounds(350, 240, 30, 17);

        jtxtdepartment_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdepartment_name.setText("department_code");
        jtxtdepartment_name.setFocusable(false);
        jtxtdepartment_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdepartment_nameFocusGained(evt);
            }
        });
        jPanel1.add(jtxtdepartment_name);
        jtxtdepartment_name.setBounds(400, 220, 340, 20);

        jtxtposition_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtposition_name.setText("position_code");
        jtxtposition_name.setFocusable(false);
        jtxtposition_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtposition_nameFocusGained(evt);
            }
        });
        jPanel1.add(jtxtposition_name);
        jtxtposition_name.setBounds(400, 240, 340, 20);

        jlblfaximale1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblfaximale1.setText("Handphone");
        jPanel1.add(jlblfaximale1);
        jlblfaximale1.setBounds(400, 110, 140, 14);

        jtxthp.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxthp.setText("faximale");
        jtxthp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxthpFocusGained(evt);
            }
        });
        jPanel1.add(jtxthp);
        jtxthp.setBounds(590, 110, 150, 20);

        jlblsex1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsex1.setText("Status Anggota");
        jPanel1.add(jlblsex1);
        jlblsex1.setBounds(400, 160, 140, 14);

        buttonGroup2.add(joptmember_sts_biasa);
        joptmember_sts_biasa.setFont(new java.awt.Font("Dialog", 1, 10));
        joptmember_sts_biasa.setSelected(true);
        joptmember_sts_biasa.setText("Biasa");
        jPanel1.add(joptmember_sts_biasa);
        joptmember_sts_biasa.setBounds(510, 160, 94, 29);

        buttonGroup2.add(joptmember_sts_luar_biasa);
        joptmember_sts_luar_biasa.setFont(new java.awt.Font("Dialog", 1, 10));
        joptmember_sts_luar_biasa.setText("Luar Biasa");
        jPanel1.add(joptmember_sts_luar_biasa);
        joptmember_sts_luar_biasa.setBounds(610, 160, 130, 29);

        jlblposition_code1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblposition_code1.setText("Pendidikan");
        jPanel1.add(jlblposition_code1);
        jlblposition_code1.setBounds(10, 260, 140, 14);

        jtxtkode_pendidikan.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtkode_pendidikan.setText("kode_pendidikan");
        jtxtkode_pendidikan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtkode_pendidikanFocusGained(evt);
            }
        });
        jtxtkode_pendidikan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtkode_pendidikanKeyReleased(evt);
            }
        });
        jPanel1.add(jtxtkode_pendidikan);
        jtxtkode_pendidikan.setBounds(200, 260, 150, 20);

        jbtnBrowse_Jabatan1.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse_Jabatan1.setText("...");
        jbtnBrowse_Jabatan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_Jabatan1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBrowse_Jabatan1);
        jbtnBrowse_Jabatan1.setBounds(350, 260, 30, 17);

        jtxtpendidikan_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtpendidikan_name.setText("kode_pendidikan");
        jtxtpendidikan_name.setFocusable(false);
        jtxtpendidikan_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtpendidikan_nameFocusGained(evt);
            }
        });
        jPanel1.add(jtxtpendidikan_name);
        jtxtpendidikan_name.setBounds(400, 260, 340, 20);

        jTabbedPane1.addTab("Utama", jPanel1);

        jPanel2.setLayout(null);

        jlblsimpanan_wajib.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsimpanan_wajib.setText("Wajib");
        jPanel2.add(jlblsimpanan_wajib);
        jlblsimpanan_wajib.setBounds(10, 160, 140, 14);

        jtxtsimpanan_wajib.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsimpanan_wajib.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsimpanan_wajib.setText("simpanan_wajib");
        jtxtsimpanan_wajib.setFocusable(false);
        jtxtsimpanan_wajib.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsimpanan_wajibFocusGained(evt);
            }
        });
        jtxtsimpanan_wajib.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsimpanan_wajibKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtsimpanan_wajib);
        jtxtsimpanan_wajib.setBounds(200, 40, 150, 20);

        jlblsimpanan_pokok.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsimpanan_pokok.setText("Pokok");
        jPanel2.add(jlblsimpanan_pokok);
        jlblsimpanan_pokok.setBounds(10, 180, 140, 14);

        jtxtsimpanan_pokok.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsimpanan_pokok.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsimpanan_pokok.setText("simpanan_pokok");
        jtxtsimpanan_pokok.setFocusable(false);
        jtxtsimpanan_pokok.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsimpanan_pokokFocusGained(evt);
            }
        });
        jtxtsimpanan_pokok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsimpanan_pokokKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtsimpanan_pokok);
        jtxtsimpanan_pokok.setBounds(200, 60, 150, 20);

        jlblsimpanan_sukarela.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsimpanan_sukarela.setText("Sukarela");
        jPanel2.add(jlblsimpanan_sukarela);
        jlblsimpanan_sukarela.setBounds(10, 200, 140, 14);

        jtxtsimpanan_sukarela.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsimpanan_sukarela.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsimpanan_sukarela.setText("simpanan_sukarela");
        jtxtsimpanan_sukarela.setFocusable(false);
        jtxtsimpanan_sukarela.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsimpanan_sukarelaFocusGained(evt);
            }
        });
        jtxtsimpanan_sukarela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsimpanan_sukarelaKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtsimpanan_sukarela);
        jtxtsimpanan_sukarela.setBounds(200, 80, 150, 20);

        jlblsimpanan_khusus.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsimpanan_khusus.setText("Khusus");
        jPanel2.add(jlblsimpanan_khusus);
        jlblsimpanan_khusus.setBounds(10, 220, 140, 14);

        jtxtsimpanan_khusus.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsimpanan_khusus.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsimpanan_khusus.setText("simpanan_khusus");
        jtxtsimpanan_khusus.setFocusable(false);
        jtxtsimpanan_khusus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsimpanan_khususFocusGained(evt);
            }
        });
        jtxtsimpanan_khusus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtsimpanan_khususKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtsimpanan_khusus);
        jtxtsimpanan_khusus.setBounds(200, 100, 150, 20);

        jlblreference_number.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblreference_number.setText("No. Referensi");
        jPanel2.add(jlblreference_number);
        jlblreference_number.setBounds(390, 40, 140, 14);

        jtxtreference_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtreference_number.setText("reference_number");
        jtxtreference_number.setFocusable(false);
        jtxtreference_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtreference_numberFocusGained(evt);
            }
        });
        jPanel2.add(jtxtreference_number);
        jtxtreference_number.setBounds(580, 40, 150, 20);

        jlbllast_update.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbllast_update.setText("Terakhir Revisi");
        jPanel2.add(jlbllast_update);
        jlbllast_update.setBounds(390, 60, 140, 14);

        jtxtlast_update.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtlast_update.setText("last_update");
        jtxtlast_update.setFocusable(false);
        jtxtlast_update.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtlast_updateFocusGained(evt);
            }
        });
        jPanel2.add(jtxtlast_update);
        jtxtlast_update.setBounds(580, 60, 150, 20);

        jHeader1.setBackground(new java.awt.Color(102, 102, 102));
        jHeader1.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader1.setForeground(new java.awt.Color(255, 255, 255));
        jHeader1.setText("Total Simpanan");
        jHeader1.setAlignmentY(0.0F);
        jHeader1.setOpaque(true);
        jPanel2.add(jHeader1);
        jHeader1.setBounds(10, 130, 200, 20);

        jlblsimpanan_wajib1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsimpanan_wajib1.setText("Wajib");
        jPanel2.add(jlblsimpanan_wajib1);
        jlblsimpanan_wajib1.setBounds(10, 40, 140, 14);

        jtxtsimpanan_wajib1.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsimpanan_wajib1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsimpanan_wajib1.setText("simpanan_wajib");
        jtxtsimpanan_wajib1.setFocusable(false);
        jtxtsimpanan_wajib1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsimpanan_wajib1FocusGained(evt);
            }
        });
        jPanel2.add(jtxtsimpanan_wajib1);
        jtxtsimpanan_wajib1.setBounds(200, 160, 150, 20);

        jlblsimpanan_pokok1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsimpanan_pokok1.setText("Pokok");
        jPanel2.add(jlblsimpanan_pokok1);
        jlblsimpanan_pokok1.setBounds(10, 60, 140, 14);

        jtxtsimpanan_pokok1.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsimpanan_pokok1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsimpanan_pokok1.setText("simpanan_pokok");
        jtxtsimpanan_pokok1.setFocusable(false);
        jtxtsimpanan_pokok1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsimpanan_pokok1FocusGained(evt);
            }
        });
        jPanel2.add(jtxtsimpanan_pokok1);
        jtxtsimpanan_pokok1.setBounds(200, 180, 150, 20);

        jlblsimpanan_sukarela1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsimpanan_sukarela1.setText("Sukarela");
        jPanel2.add(jlblsimpanan_sukarela1);
        jlblsimpanan_sukarela1.setBounds(10, 80, 140, 14);

        jtxtsimpanan_sukarela1.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsimpanan_sukarela1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsimpanan_sukarela1.setText("simpanan_sukarela");
        jtxtsimpanan_sukarela1.setFocusable(false);
        jtxtsimpanan_sukarela1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsimpanan_sukarela1FocusGained(evt);
            }
        });
        jPanel2.add(jtxtsimpanan_sukarela1);
        jtxtsimpanan_sukarela1.setBounds(200, 200, 150, 20);

        jlblsimpanan_khusus1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsimpanan_khusus1.setText("Khusus");
        jPanel2.add(jlblsimpanan_khusus1);
        jlblsimpanan_khusus1.setBounds(10, 100, 140, 14);

        jtxtsimpanan_khusus1.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtsimpanan_khusus1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtsimpanan_khusus1.setText("simpanan_khusus");
        jtxtsimpanan_khusus1.setFocusable(false);
        jtxtsimpanan_khusus1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtsimpanan_khusus1FocusGained(evt);
            }
        });
        jPanel2.add(jtxtsimpanan_khusus1);
        jtxtsimpanan_khusus1.setBounds(200, 220, 150, 20);

        jHeader2.setBackground(new java.awt.Color(102, 102, 102));
        jHeader2.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader2.setForeground(new java.awt.Color(255, 255, 255));
        jHeader2.setText("Default Simpanan");
        jHeader2.setAlignmentY(0.0F);
        jHeader2.setOpaque(true);
        jPanel2.add(jHeader2);
        jHeader2.setBounds(10, 10, 200, 20);

        jlblmember_name1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblmember_name1.setText("Total Simpanan");
        jPanel2.add(jlblmember_name1);
        jlblmember_name1.setBounds(10, 250, 140, 14);

        jtxttotal_simpanan.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttotal_simpanan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxttotal_simpanan.setText("member_name");
        jtxttotal_simpanan.setFocusable(false);
        jtxttotal_simpanan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttotal_simpananFocusGained(evt);
            }
        });
        jPanel2.add(jtxttotal_simpanan);
        jtxttotal_simpanan.setBounds(200, 250, 150, 20);

        jlbllast_update1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbllast_update1.setText("Penarikan SS Maksimal");
        jPanel2.add(jlbllast_update1);
        jlbllast_update1.setBounds(390, 170, 140, 14);

        jtxtmaks_penarikan_ss.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmaks_penarikan_ss.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtmaks_penarikan_ss.setText("last_update");
        jtxtmaks_penarikan_ss.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmaks_penarikan_ssFocusGained(evt);
            }
        });
        jPanel2.add(jtxtmaks_penarikan_ss);
        jtxtmaks_penarikan_ss.setBounds(580, 170, 150, 20);

        jlbllast_update2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbllast_update2.setText("Pengajuan Pinjaman Maksimal");
        jPanel2.add(jlbllast_update2);
        jlbllast_update2.setBounds(390, 190, 180, 14);

        jtxtmaks_pinjaman.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmaks_pinjaman.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtmaks_pinjaman.setText("last_update");
        jtxtmaks_pinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtmaks_pinjamanActionPerformed(evt);
            }
        });
        jtxtmaks_pinjaman.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmaks_pinjamanFocusGained(evt);
            }
        });
        jPanel2.add(jtxtmaks_pinjaman);
        jtxtmaks_pinjaman.setBounds(580, 190, 150, 20);

        jTabbedPane1.addTab("Simpanan", jPanel2);

        jPanel3.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No.Pinjaman", "Jml.Pinjaman", "Jml.Angsuran", "Saldo Pokok", "Saldo Bunga", "Saldo Pinjaman", "Angsuran Ke", "Sisa Angsuran"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 720, 240);

        jHeader3.setBackground(new java.awt.Color(102, 102, 102));
        jHeader3.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader3.setForeground(new java.awt.Color(255, 255, 255));
        jHeader3.setText("Pinjaman");
        jHeader3.setAlignmentY(0.0F);
        jHeader3.setOpaque(true);
        jPanel3.add(jHeader3);
        jHeader3.setBounds(10, 10, 200, 20);

        jTabbedPane1.addTab("Pinjaman", jPanel3);

        jPanel4.setLayout(null);

        jlbldepartment_code1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldepartment_code1.setText("Bank");
        jPanel4.add(jlbldepartment_code1);
        jlbldepartment_code1.setBounds(10, 20, 170, 14);

        jtxtbank_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtbank_code.setText("bank_code");
        jtxtbank_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtbank_codeFocusGained(evt);
            }
        });
        jtxtbank_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtbank_codeKeyReleased(evt);
            }
        });
        jPanel4.add(jtxtbank_code);
        jtxtbank_code.setBounds(200, 20, 150, 20);

        jbtnBrowse_Departemen1.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse_Departemen1.setText("...");
        jbtnBrowse_Departemen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_Departemen1ActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnBrowse_Departemen1);
        jbtnBrowse_Departemen1.setBounds(350, 20, 30, 17);

        jtxtbank_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtbank_name.setText("bank_name");
        jtxtbank_name.setFocusable(false);
        jtxtbank_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtbank_nameFocusGained(evt);
            }
        });
        jPanel4.add(jtxtbank_name);
        jtxtbank_name.setBounds(390, 20, 340, 20);

        jlbldepartment_code2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldepartment_code2.setText("Nomor Rekening");
        jPanel4.add(jlbldepartment_code2);
        jlbldepartment_code2.setBounds(10, 60, 170, 14);

        jtxtbank_account.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtbank_account.setText("bank_code");
        jtxtbank_account.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtbank_accountFocusGained(evt);
            }
        });
        jtxtbank_account.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtbank_accountKeyReleased(evt);
            }
        });
        jPanel4.add(jtxtbank_account);
        jtxtbank_account.setBounds(200, 60, 150, 20);

        jlbldepartment_code3.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldepartment_code3.setText("Cabang");
        jPanel4.add(jlbldepartment_code3);
        jlbldepartment_code3.setBounds(10, 40, 170, 14);

        jtxtbank_branch.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtbank_branch.setText("bank_branch");
        jtxtbank_branch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtbank_branchFocusGained(evt);
            }
        });
        jtxtbank_branch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtbank_branchKeyReleased(evt);
            }
        });
        jPanel4.add(jtxtbank_branch);
        jtxtbank_branch.setBounds(200, 40, 290, 20);

        jTabbedPane1.addTab("Rekening", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(60, 150, 750, 320);

        jchkactive_sts.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkactive_sts.setText("Aktif");
        getContentPane().add(jchkactive_sts);
        jchkactive_sts.setBounds(650, 70, 108, 29);

        jlblregister_date.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblregister_date.setText("Tgl Register");
        getContentPane().add(jlblregister_date);
        jlblregister_date.setBounds(510, 100, 140, 14);

        kzoregister_date.setFont(new java.awt.Font("Dialog", 0, 10));
        kzoregister_date.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzoregister_date.setOpaque(false);
        getContentPane().add(kzoregister_date);
        kzoregister_date.setBounds(700, 100, 100, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jtxtdepartment_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdepartment_nameFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdepartment_nameFocusGained

private void jtxtposition_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtposition_nameFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtposition_nameFocusGained

private void jbtnBrowse_DepartemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_DepartemenActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_departemen, "", jtxtdepartment_code,jtxtdepartment_name);
}//GEN-LAST:event_jbtnBrowse_DepartemenActionPerformed

private void jbtnBrowse_JabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_JabatanActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_jabatan, "", jtxtposition_code,jtxtposition_name);
}//GEN-LAST:event_jbtnBrowse_JabatanActionPerformed

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_anggota, "", jtxtmember_number);

    if (!jtxtmember_number.getText().equalsIgnoreCase("")){
        try {
            if (obj.initdata(jtxtmember_number.getText())) {
                showData();
            }
        } catch (CodeException ex) {
            Logger.getLogger(Frmko_anggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}//GEN-LAST:event_jbtnBrowseActionPerformed

private void jtxtdepartment_codeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtdepartment_codeKeyReleased
    // TODO add your handling code here:
    ofind=new findcontroller();
    ofind.find(ofind.ko_departemen, jtxtdepartment_code, jtxtdepartment_name);
}//GEN-LAST:event_jtxtdepartment_codeKeyReleased

private void jtxtposition_codeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtposition_codeKeyReleased
    // TODO add your handling code here:
    ofind=new findcontroller();
    ofind.find(ofind.ko_jabatan, jtxtposition_code, jtxtposition_name);
}//GEN-LAST:event_jtxtposition_codeKeyReleased

private void jtxtsimpanan_wajibFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsimpanan_wajibFocusGained
    // TODO add your handling code here:
    GlobalUtils.highlighttext(jtxtsimpanan_wajib);
}//GEN-LAST:event_jtxtsimpanan_wajibFocusGained

private void jtxtsimpanan_pokokFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsimpanan_pokokFocusGained
    // TODO add your handling code here:
    GlobalUtils.highlighttext(jtxtsimpanan_pokok);
}//GEN-LAST:event_jtxtsimpanan_pokokFocusGained

private void jtxtsimpanan_sukarelaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsimpanan_sukarelaFocusGained
    // TODO add your handling code here:
    GlobalUtils.highlighttext(jtxtsimpanan_sukarela);
}//GEN-LAST:event_jtxtsimpanan_sukarelaFocusGained

private void jtxtsimpanan_khususFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsimpanan_khususFocusGained
    // TODO add your handling code here:
    GlobalUtils.highlighttext(jtxtsimpanan_khusus);
}//GEN-LAST:event_jtxtsimpanan_khususFocusGained

private void jtxtreference_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtreference_numberFocusGained
    // TODO add your handling code here:
    GlobalUtils.highlighttext(jtxtreference_number);
}//GEN-LAST:event_jtxtreference_numberFocusGained

private void jtxtlast_updateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtlast_updateFocusGained
    // TODO add your handling code here:
    GlobalUtils.highlighttext(jtxtlast_update);
}//GEN-LAST:event_jtxtlast_updateFocusGained

private void jtxtsimpanan_wajib1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsimpanan_wajib1FocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtsimpanan_wajib1FocusGained

private void jtxtsimpanan_pokok1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsimpanan_pokok1FocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtsimpanan_pokok1FocusGained

private void jtxtsimpanan_sukarela1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsimpanan_sukarela1FocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtsimpanan_sukarela1FocusGained

private void jtxtsimpanan_khusus1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtsimpanan_khusus1FocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtsimpanan_khusus1FocusGained

private void jtxttotal_simpananFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxttotal_simpananFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxttotal_simpananFocusGained

private void jtxtsimpanan_wajibKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsimpanan_wajibKeyReleased
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtsimpanan_wajib);
}//GEN-LAST:event_jtxtsimpanan_wajibKeyReleased

private void jtxtsimpanan_pokokKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsimpanan_pokokKeyReleased
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtsimpanan_pokok);
}//GEN-LAST:event_jtxtsimpanan_pokokKeyReleased

private void jtxtsimpanan_sukarelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsimpanan_sukarelaKeyReleased
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtsimpanan_sukarela);
}//GEN-LAST:event_jtxtsimpanan_sukarelaKeyReleased

private void jtxtsimpanan_khususKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtsimpanan_khususKeyReleased
    // TODO add your handling code here:
    GlobalUtils.domasking(jtxtsimpanan_khusus);
}//GEN-LAST:event_jtxtsimpanan_khususKeyReleased

private void jtxthpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxthpFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxthpFocusGained

private void jtxtbank_codeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtbank_codeFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtbank_codeFocusGained

private void jtxtbank_codeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbank_codeKeyReleased
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtbank_codeKeyReleased

private void jbtnBrowse_Departemen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_Departemen1ActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.op_bank, "", jtxtbank_code,jtxtbank_name);
}//GEN-LAST:event_jbtnBrowse_Departemen1ActionPerformed

private void jtxtbank_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtbank_nameFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtbank_nameFocusGained

private void jtxtbank_accountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtbank_accountFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtbank_accountFocusGained

private void jtxtbank_accountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbank_accountKeyReleased
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtbank_accountKeyReleased

private void jtxtbank_branchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtbank_branchFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtbank_branchFocusGained

private void jtxtbank_branchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtbank_branchKeyReleased
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtbank_branchKeyReleased

private void jtxtmaks_penarikan_ssFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtmaks_penarikan_ssFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtmaks_penarikan_ssFocusGained

private void jtxtmaks_pinjamanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtmaks_pinjamanFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtmaks_pinjamanFocusGained

private void jtxtmaks_pinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtmaks_pinjamanActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtmaks_pinjamanActionPerformed

private void jtxtkode_pendidikanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtkode_pendidikanFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtkode_pendidikanFocusGained

private void jtxtkode_pendidikanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtkode_pendidikanKeyReleased
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtkode_pendidikanKeyReleased

private void jbtnBrowse_Jabatan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_Jabatan1ActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_pendidikan, "", jtxtkode_pendidikan,jtxtpendidikan_name);
}//GEN-LAST:event_jbtnBrowse_Jabatan1ActionPerformed

private void jtxtpendidikan_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtpendidikan_nameFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtpendidikan_nameFocusGained

private void jtxtmember_numberFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxtmember_number.setSelectionStart(0);
    jtxtmember_number.setSelectionEnd(jtxtmember_number.getText().length());

    if (!jtxtmember_number.getText().equalsIgnoreCase("")){
        try {
            if (obj.initdata(jtxtmember_number.getText())) {
                showData();
            }
        } catch (CodeException ex) {
            Logger.getLogger(Frmko_anggota.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}                                             

private void jtxtmember_nameFocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    jtxtmember_name.setSelectionStart(0);
    jtxtmember_name.setSelectionEnd(jtxtmember_name.getText().length());
}                                           

private void jtxtaddress1FocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtaddress1.setSelectionStart(0);
    jtxtaddress1.setSelectionEnd(jtxtaddress1.getText().length());
}                                        

private void jtxtaddress2FocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtaddress2.setSelectionStart(0);
    jtxtaddress2.setSelectionEnd(jtxtaddress2.getText().length());
}                                        

private void jtxtcityFocusGained(java.awt.event.FocusEvent evt) {                                  
        // TODO add your handling code here:
    jtxtcity.setSelectionStart(0);
    jtxtcity.setSelectionEnd(jtxtcity.getText().length());
}                                    

private void jtxtstateFocusGained(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    jtxtstate.setSelectionStart(0);
    jtxtstate.setSelectionEnd(jtxtstate.getText().length());
}                                     

private void jtxtzipcodeFocusGained(java.awt.event.FocusEvent evt) {                                     
        // TODO add your handling code here:
    jtxtzipcode.setSelectionStart(0);
    jtxtzipcode.setSelectionEnd(jtxtzipcode.getText().length());
}                                       

private void jtxtphoneFocusGained(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    jtxtphone.setSelectionStart(0);
    jtxtphone.setSelectionEnd(jtxtphone.getText().length());
}                                     

private void jtxtfaximaleFocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtfaximale.setSelectionStart(0);
    jtxtfaximale.setSelectionEnd(jtxtfaximale.getText().length());
}                                        

private void jtxtemailFocusGained(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    jtxtemail.setSelectionStart(0);
    jtxtemail.setSelectionEnd(jtxtemail.getText().length());
}                                     

private void jtxtemployee_numberFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtemployee_number.setSelectionStart(0);
    jtxtemployee_number.setSelectionEnd(jtxtemployee_number.getText().length());
}                                               


private void jtxtdepartment_codeFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtdepartment_code.setSelectionStart(0);
    jtxtdepartment_code.setSelectionEnd(jtxtdepartment_code.getText().length());
}                                               

private void jtxtposition_codeFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxtposition_code.setSelectionStart(0);
    jtxtposition_code.setSelectionEnd(jtxtposition_code.getText().length());
}                                             


private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmko_anggota().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jHeader;
    private javax.swing.JLabel jHeader1;
    private javax.swing.JLabel jHeader2;
    private javax.swing.JLabel jHeader3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowse_Departemen;
    private javax.swing.JButton jbtnBrowse_Departemen1;
    private javax.swing.JButton jbtnBrowse_Jabatan;
    private javax.swing.JButton jbtnBrowse_Jabatan1;
    private javax.swing.JCheckBox jchkactive_sts;
    private javax.swing.JCheckBox jchkemployee_sts;
    private javax.swing.JComboBox jcmbreligion;
    private javax.swing.JLabel jlbladdress1;
    private javax.swing.JLabel jlblcity;
    private javax.swing.JLabel jlbldepartment_code;
    private javax.swing.JLabel jlbldepartment_code1;
    private javax.swing.JLabel jlbldepartment_code2;
    private javax.swing.JLabel jlbldepartment_code3;
    private javax.swing.JLabel jlblemail;
    private javax.swing.JLabel jlblemployee_number;
    private javax.swing.JLabel jlblemployee_sts;
    private javax.swing.JLabel jlblfaximale;
    private javax.swing.JLabel jlblfaximale1;
    private javax.swing.JLabel jlbllast_update;
    private javax.swing.JLabel jlbllast_update1;
    private javax.swing.JLabel jlbllast_update2;
    private javax.swing.JLabel jlblmember_name;
    private javax.swing.JLabel jlblmember_name1;
    private javax.swing.JLabel jlblmember_number;
    private javax.swing.JLabel jlblphone;
    private javax.swing.JLabel jlblposition_code;
    private javax.swing.JLabel jlblposition_code1;
    private javax.swing.JLabel jlblreference_number;
    private javax.swing.JLabel jlblregister_date;
    private javax.swing.JLabel jlblreligion;
    private javax.swing.JLabel jlblsex;
    private javax.swing.JLabel jlblsex1;
    private javax.swing.JLabel jlblsimpanan_khusus;
    private javax.swing.JLabel jlblsimpanan_khusus1;
    private javax.swing.JLabel jlblsimpanan_pokok;
    private javax.swing.JLabel jlblsimpanan_pokok1;
    private javax.swing.JLabel jlblsimpanan_sukarela;
    private javax.swing.JLabel jlblsimpanan_sukarela1;
    private javax.swing.JLabel jlblsimpanan_wajib;
    private javax.swing.JLabel jlblsimpanan_wajib1;
    private javax.swing.JLabel jlblstate;
    private javax.swing.JLabel jlbltanggal_masuk;
    private javax.swing.JLabel jlblzipcode;
    private javax.swing.JRadioButton joptmember_sts_biasa;
    private javax.swing.JRadioButton joptmember_sts_luar_biasa;
    private javax.swing.JRadioButton joptsex_laki;
    private javax.swing.JRadioButton joptsex_perempuan;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtaddress1;
    private javax.swing.JTextField jtxtaddress2;
    private javax.swing.JTextField jtxtbank_account;
    private javax.swing.JTextField jtxtbank_branch;
    private javax.swing.JTextField jtxtbank_code;
    private javax.swing.JTextField jtxtbank_name;
    private javax.swing.JTextField jtxtcity;
    private javax.swing.JTextField jtxtdepartment_code;
    private javax.swing.JTextField jtxtdepartment_name;
    private javax.swing.JTextField jtxtemail;
    private javax.swing.JTextField jtxtemployee_number;
    private javax.swing.JTextField jtxtfaximale;
    private javax.swing.JTextField jtxthp;
    private javax.swing.JTextField jtxtkode_pendidikan;
    private javax.swing.JTextField jtxtlast_update;
    private javax.swing.JTextField jtxtmaks_penarikan_ss;
    private javax.swing.JTextField jtxtmaks_pinjaman;
    private javax.swing.JTextField jtxtmember_name;
    private javax.swing.JTextField jtxtmember_number;
    private javax.swing.JTextField jtxtpendidikan_name;
    private javax.swing.JTextField jtxtphone;
    private javax.swing.JTextField jtxtposition_code;
    private javax.swing.JTextField jtxtposition_name;
    private javax.swing.JTextField jtxtreference_number;
    private javax.swing.JTextField jtxtsimpanan_khusus;
    private javax.swing.JTextField jtxtsimpanan_khusus1;
    private javax.swing.JTextField jtxtsimpanan_pokok;
    private javax.swing.JTextField jtxtsimpanan_pokok1;
    private javax.swing.JTextField jtxtsimpanan_sukarela;
    private javax.swing.JTextField jtxtsimpanan_sukarela1;
    private javax.swing.JTextField jtxtsimpanan_wajib;
    private javax.swing.JTextField jtxtsimpanan_wajib1;
    private javax.swing.JTextField jtxtstate;
    private javax.swing.JTextField jtxttotal_simpanan;
    private javax.swing.JTextField jtxtzipcode;
    private org.kazao.calendar.KazaoCalendarDate kzoregister_date;
    private org.kazao.calendar.KazaoCalendarDate kzotanggal_masuk;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jtxtmember_number.setText("");
        jtxtmember_name.setText("");
        jchkactive_sts.setSelected(true);
        jtxtaddress1.setText("");
        jtxtaddress2.setText("");
        jtxtcity.setText("");
        jtxtstate.setText("");
        jtxtzipcode.setText("");
        jtxtphone.setText("");
        jtxtfaximale.setText("");
        jtxtemail.setText("");
        
        jchkemployee_sts.setSelected(true);
        jtxtemployee_number.setText("");
        try {
            kzotanggal_masuk.setDate(GlobalUtils.getCurrentDate());
            kzoregister_date.setDate(GlobalUtils.getCurrentDate());
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmko_anggota.class.getName()).log(Level.SEVERE, null, ex);
        }
        joptsex_laki.setSelected(true);
        jcmbreligion.setSelectedIndex(0);
        jtxtdepartment_code.setText("");
        jtxtposition_code.setText("");


        jtxtsimpanan_wajib.setText("0");
        jtxtsimpanan_pokok.setText("0");
        jtxtsimpanan_sukarela.setText("0");
        jtxtsimpanan_khusus.setText("0");

        jtxtsimpanan_wajib1.setText("0");
        jtxtsimpanan_pokok1.setText("0");
        jtxtsimpanan_sukarela1.setText("0");
        jtxtsimpanan_khusus1.setText("0");

        jtxttotal_simpanan.setText("0");

        jtxtreference_number.setText("");
        jtxtlast_update.setText("");

        jtxthp.setText("");
        joptmember_sts_biasa.setSelected(true);

        jtxtbank_code.setText("");
        jtxtbank_branch.setText("");
        jtxtbank_account.setText("");
        
        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");
    }

    public void newData() throws CodeException {
        istatus=1;
        clearfield();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.update();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        clearfield();
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        jtxtmember_number.setText(obj.getmember_number());
        jtxtmember_name.setText(obj.getmember_name());
        if (obj.getactive_sts().equalsIgnoreCase("Y")){
        jchkactive_sts.setSelected(true);
        } else {
            jchkactive_sts.setSelected(false);
        }
        jtxtaddress1.setText(obj.getaddress1());
        jtxtaddress2.setText(obj.getaddress2());
        jtxtcity.setText(obj.getcity());
        jtxtstate.setText(obj.getstate());
        jtxtzipcode.setText(obj.getzipcode());
        jtxtphone.setText(obj.getphone());
        jtxtfaximale.setText(obj.getfaximale());
        jtxtemail.setText(obj.getemail());
        if (obj.getemployee_sts().equalsIgnoreCase("Y")){
            jchkemployee_sts.setSelected(true);
        } else {
            jchkemployee_sts.setSelected(false);
        }
        jtxtemployee_number.setText(obj.getemployee_number());
        try {
            kzotanggal_masuk.setDate(GlobalUtils.formatDate(obj.gettanggal_masuk(), "MM/dd/yyyy"));
            kzoregister_date.setDate(GlobalUtils.formatDate(obj.getregister_date(),"MM/dd/yyyy"));
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmko_anggota.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (obj.getsex().equalsIgnoreCase("L")){
            joptsex_laki.setSelected(true);
        } else {
            joptsex_perempuan.setSelected(true);
        }
        jcmbreligion.setSelectedIndex(GlobalUtils.toInt(obj.getreligion())-1);
        jtxtdepartment_code.setText(obj.getdepartment_code());
        jtxtdepartment_name.setText(obj.getdepinfo().getnama_departemen());
        jtxtposition_code.setText(obj.getposition_code());
       jtxtposition_name.setText(obj.getjbtinfo().getnama_jabatan());
       jtxtkode_pendidikan.setText(obj.getkode_pendidikan());
       jtxtpendidikan_name.setText(obj.getpddkinfo().getnama_pendidikan());

        jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getentrydate()));
        jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getauditdate()));
        jtxtUserID.setText(obj.getaudituser());

        jtxtsimpanan_wajib.setText(GlobalUtils.formatnumber(obj.getsimpanan_wajib()));
        jtxtsimpanan_pokok.setText(GlobalUtils.formatnumber(obj.getsimpanan_pokok()));
        jtxtsimpanan_sukarela.setText(GlobalUtils.formatnumber(obj.getsimpanan_sukarela()));
        jtxtsimpanan_khusus.setText(GlobalUtils.formatnumber(obj.getsimpanan_khusus()));

        jtxtsimpanan_wajib1.setText(GlobalUtils.formatnumber(obj.getSimpanan_info_wajib()));
        jtxtsimpanan_pokok1.setText(GlobalUtils.formatnumber(obj.getSimpanan_info_pokok()));
        jtxtsimpanan_sukarela1.setText(GlobalUtils.formatnumber(obj.getSimpanan_info_sukarela()));
        jtxtsimpanan_khusus1.setText(GlobalUtils.formatnumber(obj.getSimpanan_info_khusus()));

        jtxtreference_number.setText(obj.getreference_number());
        jtxtlast_update.setText(obj.getlast_update());

        jtxthp.setText(obj.gethp());
        if (obj.getmember_sts().equalsIgnoreCase("Y")){
            joptmember_sts_luar_biasa.setSelected(true);
        } else {
            joptmember_sts_biasa.setSelected(true);
        }

        jtxtbank_code.setText(obj.getbank_code());
        jtxtbank_name.setText(obj.getbank_name());
        jtxtbank_branch.setText(obj.getbank_branch());
        jtxtbank_account.setText(obj.getbank_account());

        Double total_pinjaman=new Double(0);
        ko_anggota_pinjamancol info_pinjaman=obj.getinfo_pinjaman();
        GlobalModel.clearRow(model);
        for (int i=0;i<info_pinjaman.size();i++){
            ko_anggota_pinjaman o = info_pinjaman.get(i);
            model.addRow(new Object[model.getColumnCount()]);
            model.setValueAt(o.getDocument_number(), i, 0);
            model.setValueAt(o.getJumlah_pinjaman(), i, 1);
            model.setValueAt(o.getJumlah_angsuran(), i, 2);
            model.setValueAt(o.getTotal_pokok_akhir(), i, 3);
            model.setValueAt(o.getTotal_bunga_akhir(), i, 4);
            model.setValueAt(o.getTotal_pokok_bunga_akhir(), i, 5);
            model.setValueAt(o.getAngsuranke(), i, 6);
            model.setValueAt(o.getSisa_angsuranke(), i, 7);

            total_pinjaman=total_pinjaman+o.getJumlah_pinjaman();
        }

        Double max_penarikan=(total_pinjaman/5)-(obj.getSimpanan_info_wajib()+obj.getSimpanan_info_sukarela());
        if (max_penarikan<0){
            max_penarikan=new Double(0);
        }
        jtxtmaks_penarikan_ss.setText(GlobalUtils.formatnumber(max_penarikan));

        Double maks_pinjaman=(obj.getSimpanan_info_wajib()+obj.getSimpanan_info_sukarela())*5;
        if (maks_pinjaman>20000000){
            maks_pinjaman=new Double(20000000);
        }
        jtxtmaks_pinjaman.setText(GlobalUtils.formatnumber(maks_pinjaman));

        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        if (obj.delete()){
            obj.moveNext();
            showData();
        }
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);

        if (istatus==1){
            jbtnBrowse.setEnabled(false);
        } else {
            jbtnBrowse.setEnabled(true);
        }
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }
        obj.setmember_number(jtxtmember_number.getText());
        obj.setmember_name(jtxtmember_name.getText());
        if (jchkactive_sts.isSelected()){
        obj.setactive_sts("Y");
        } else {
        obj.setactive_sts("N");
        }
        obj.setaddress1(jtxtaddress1.getText());
        obj.setaddress2(jtxtaddress2.getText());
        obj.setcity(jtxtcity.getText());
        obj.setstate(jtxtstate.getText());
        obj.setzipcode(jtxtzipcode.getText());
        obj.setphone(jtxtphone.getText());
        obj.setfaximale(jtxtfaximale.getText());
        obj.setemail(jtxtemail.getText());
        if (jchkemployee_sts.isSelected()){
            obj.setemployee_sts("Y");
        } else {
            obj.setemployee_sts("N");
        }
        obj.setemployee_number(jtxtemployee_number.getText());
        obj.settanggal_masuk(kzotanggal_masuk.getDate());
        if (joptsex_laki.isSelected()){
            obj.setsex("L");
        } else {
            obj.setsex("P");
        }
        obj.setreligion(jcmbreligion.getSelectedIndex()+1+"");
        obj.setdepartment_code(jtxtdepartment_code.getText());
        obj.setposition_code(jtxtposition_code.getText());
        obj.setkode_pendidikan(jtxtkode_pendidikan.getText());
        obj.setregister_date(kzoregister_date.getDate());

        obj.setsimpanan_wajib(GlobalUtils.toDbl(jtxtsimpanan_wajib.getText()));
        obj.setsimpanan_pokok(GlobalUtils.toDbl(jtxtsimpanan_pokok.getText()));
        obj.setsimpanan_sukarela(GlobalUtils.toDbl(jtxtsimpanan_sukarela.getText()));
        obj.setsimpanan_khusus(GlobalUtils.toDbl(jtxtsimpanan_khusus.getText()));
        
        obj.sethp(jtxthp.getText());
        if (joptmember_sts_luar_biasa.isSelected()){
            obj.setmember_sts("Y");
        } else {
            obj.setmember_sts("N");
        }

        obj.setbank_code(jtxtbank_code.getText());
        obj.setbank_branch(jtxtbank_branch.getText());
        obj.setbank_account(jtxtbank_account.getText());

    }

    public void undo() throws CodeException {
        istatus = 0;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    
}
