/*
 * From ko_departemen
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ko.component;


import kopkar.ko.objectclasses.ko_monthly_processext;
import classinterface.NavigatorFormInt;
import common.component.FrmMainFrame;
import java.util.HashMap;
import java.util.Map;
import kopkar.utils.browsecontroller;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import utils.CodeException;
import utils.GlobalUtils;
import utils.appsettinghandler;

/**
 *
 * @author  Generator
 */

public class FrmRTKO04 extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 1;
    public static String CLASSNAME="Frmko_Auto_Pot_Pinjaman";
    
    FrmMainFrame mf ;

    ko_monthly_processext opinj;
    private browsecontroller obrowse;
    private JasperReport jasperReport;
    private JasperPrint jasperPrint;

    /** Creates new form Area */
    public FrmRTKO04() throws CodeException {
        initComponents();
    }
    
    public FrmRTKO04(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();

        fillyear();
        jcmbTahun.setSelectedItem(GlobalUtils.toInt(GlobalUtils.getCurrentYear()));

        jcmbBulan.setSelectedIndex(GlobalUtils.toInt(GlobalUtils.getCurrentMonth())-1);
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jlblkode_departemen = new javax.swing.JLabel();
        jcmbTahun = new javax.swing.JComboBox();
        jcmbBulan = new javax.swing.JComboBox();
        jlblnama_departemen1 = new javax.swing.JLabel();
        jlblnama_departemen2 = new javax.swing.JLabel();
        jchksort_by_pelunasan = new javax.swing.JCheckBox();
        jlblnama_departemen8 = new javax.swing.JLabel();
        joptpelunasan_semua = new javax.swing.JRadioButton();
        joptpelunasan = new javax.swing.JRadioButton();
        joptpelunasan_angsuran = new javax.swing.JRadioButton();
        jlbldocument_date = new javax.swing.JLabel();
        jlbldocument_duedate = new javax.swing.JLabel();
        kzodocument_date_to = new org.kazao.calendar.KazaoCalendarDate();
        kzodocument_date_fr = new org.kazao.calendar.KazaoCalendarDate();
        joptcash_sts_potong_gaji = new javax.swing.JRadioButton();
        joptcash_sts_tunai = new javax.swing.JRadioButton();
        joptcash_sts_semua = new javax.swing.JRadioButton();
        jlblnama_departemen9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laporan Bayar Pinjaman");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Laporan Bayar Pinjaman");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 320, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jlblkode_departemen.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblkode_departemen.setText("Tahun");
        getContentPane().add(jlblkode_departemen);
        jlblkode_departemen.setBounds(70, 100, 140, 13);

        jcmbTahun.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbTahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013", "2012" }));
        getContentPane().add(jcmbTahun);
        jcmbTahun.setBounds(260, 100, 80, 20);

        jcmbBulan.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbBulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        getContentPane().add(jcmbBulan);
        jcmbBulan.setBounds(260, 120, 80, 20);

        jlblnama_departemen1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen1.setText("Periode");
        getContentPane().add(jlblnama_departemen1);
        jlblnama_departemen1.setBounds(70, 120, 140, 13);

        jlblnama_departemen2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen2.setText("Tanggal");
        getContentPane().add(jlblnama_departemen2);
        jlblnama_departemen2.setBounds(70, 150, 140, 13);

        jchksort_by_pelunasan.setFont(new java.awt.Font("Dialog", 1, 10));
        jchksort_by_pelunasan.setText("Tampil Berdasarkan Group Bayar");
        getContentPane().add(jchksort_by_pelunasan);
        jchksort_by_pelunasan.setBounds(70, 290, 220, 24);

        jlblnama_departemen8.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen8.setText("Group Bayar");
        getContentPane().add(jlblnama_departemen8);
        jlblnama_departemen8.setBounds(70, 240, 140, 13);

        buttonGroup1.add(joptpelunasan_semua);
        joptpelunasan_semua.setFont(new java.awt.Font("Dialog", 1, 10));
        joptpelunasan_semua.setText("Semua");
        getContentPane().add(joptpelunasan_semua);
        joptpelunasan_semua.setBounds(250, 230, 120, 24);

        buttonGroup1.add(joptpelunasan);
        joptpelunasan.setFont(new java.awt.Font("Dialog", 1, 10));
        joptpelunasan.setText("Pelunasan");
        getContentPane().add(joptpelunasan);
        joptpelunasan.setBounds(370, 230, 123, 24);

        buttonGroup1.add(joptpelunasan_angsuran);
        joptpelunasan_angsuran.setFont(new java.awt.Font("Dialog", 1, 10));
        joptpelunasan_angsuran.setText("Angsuran");
        joptpelunasan_angsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joptpelunasan_angsuranActionPerformed(evt);
            }
        });
        getContentPane().add(joptpelunasan_angsuran);
        joptpelunasan_angsuran.setBounds(490, 230, 123, 24);

        jlbldocument_date.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_date.setText("Dari");
        getContentPane().add(jlbldocument_date);
        jlbldocument_date.setBounds(70, 170, 140, 13);

        jlbldocument_duedate.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_duedate.setText("Sampai");
        getContentPane().add(jlbldocument_duedate);
        jlbldocument_duedate.setBounds(70, 190, 140, 13);

        kzodocument_date_to.setFont(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date_to.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date_to.setOpaque(false);
        getContentPane().add(kzodocument_date_to);
        kzodocument_date_to.setBounds(260, 190, 100, 20);

        kzodocument_date_fr.setFont(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date_fr.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date_fr.setOpaque(false);
        getContentPane().add(kzodocument_date_fr);
        kzodocument_date_fr.setBounds(260, 170, 100, 20);

        buttonGroup2.add(joptcash_sts_potong_gaji);
        joptcash_sts_potong_gaji.setFont(new java.awt.Font("Dialog", 1, 10));
        joptcash_sts_potong_gaji.setText("Angsuran");
        joptcash_sts_potong_gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joptcash_sts_potong_gajiActionPerformed(evt);
            }
        });
        getContentPane().add(joptcash_sts_potong_gaji);
        joptcash_sts_potong_gaji.setBounds(490, 250, 123, 24);

        buttonGroup2.add(joptcash_sts_tunai);
        joptcash_sts_tunai.setFont(new java.awt.Font("Dialog", 1, 10));
        joptcash_sts_tunai.setText("Pelunasan");
        getContentPane().add(joptcash_sts_tunai);
        joptcash_sts_tunai.setBounds(370, 250, 123, 24);

        buttonGroup2.add(joptcash_sts_semua);
        joptcash_sts_semua.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        joptcash_sts_semua.setSelected(true);
        joptcash_sts_semua.setText("Semua");
        getContentPane().add(joptcash_sts_semua);
        joptcash_sts_semua.setBounds(250, 250, 120, 24);

        jlblnama_departemen9.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen9.setText("Cara Bayar");
        getContentPane().add(jlblnama_departemen9);
        jlblnama_departemen9.setBounds(70, 260, 140, 13);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void joptpelunasan_angsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joptpelunasan_angsuranActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_joptpelunasan_angsuranActionPerformed

private void joptcash_sts_potong_gajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joptcash_sts_potong_gajiActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_joptcash_sts_potong_gajiActionPerformed

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmRTKO04().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox jchksort_by_pelunasan;
    private javax.swing.JComboBox jcmbBulan;
    private javax.swing.JComboBox jcmbTahun;
    private javax.swing.JLabel jlbldocument_date;
    private javax.swing.JLabel jlbldocument_duedate;
    private javax.swing.JLabel jlblkode_departemen;
    private javax.swing.JLabel jlblnama_departemen1;
    private javax.swing.JLabel jlblnama_departemen2;
    private javax.swing.JLabel jlblnama_departemen8;
    private javax.swing.JLabel jlblnama_departemen9;
    private javax.swing.JRadioButton joptcash_sts_potong_gaji;
    private javax.swing.JRadioButton joptcash_sts_semua;
    private javax.swing.JRadioButton joptcash_sts_tunai;
    private javax.swing.JRadioButton joptpelunasan;
    private javax.swing.JRadioButton joptpelunasan_angsuran;
    private javax.swing.JRadioButton joptpelunasan_semua;
    private org.kazao.calendar.KazaoCalendarDate kzodocument_date_fr;
    private org.kazao.calendar.KazaoCalendarDate kzodocument_date_to;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jcmbTahun.setSelectedItem(GlobalUtils.getCurrentYear());
        jcmbBulan.setSelectedIndex(GlobalUtils.toInt(GlobalUtils.getCurrentMonth())-1);
    }

    public void newData() throws CodeException {
        istatus=1;
        clearfield();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        Map parameter = new HashMap();

        parameter.put("yop", GlobalUtils.churuf(jcmbTahun.getSelectedItem()));
        parameter.put("mop", GlobalUtils.churuf(jcmbBulan.getSelectedIndex()+1));

        String sort_by_pelunasan="N";
        if (jchksort_by_pelunasan.isSelected()){
            sort_by_pelunasan="Y";
        }
        parameter.put("sort_by_pelunasan", sort_by_pelunasan);
        parameter.put("document_date_fr", GlobalUtils.formatDate(kzodocument_date_fr.getDate(), "yyyy-MM-dd"));
        parameter.put("document_date_to", GlobalUtils.formatDate(kzodocument_date_to.getDate(), "yyyy-MM-dd"));
        String pelunasan="A";
        if (joptpelunasan.isSelected()){
            pelunasan="Y";
        } else if (joptpelunasan_angsuran.isSelected()){
            pelunasan="N";
        }
        parameter.put("pelunasan", pelunasan);

        String cash_sts="A";
        if (joptcash_sts_tunai.isSelected()){
            cash_sts="Y";
        } else if (joptcash_sts_potong_gaji.isSelected()){
            cash_sts="N";
        }
        parameter.put("cash_sts", cash_sts);

        parameter.put("audituser", (GlobalUtils.getUserId()));

        // Versi 1
        String file ="";
        if(GlobalUtils.getAppDir()){
            try{
                file = GlobalUtils.getCurrentDir() +"/Reports/RTKO-04.jrxml";
                jasperReport = JasperCompileManager.compileReport(file);
                //System.out.println("file: "+file);
                System.out.println("isi parameter RTKO-04:"+parameter);
                jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, appsettinghandler.db.getConnection());
                JasperViewer.viewReport(jasperPrint, false);
            }catch (Exception e) {
            e.printStackTrace();
            }
        }
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);
    }

    public void setData() throws CodeException {
        if (istatus==1){
        }
    }

    public void undo() throws CodeException {
        istatus = 0;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    private void fillyear() {
        jcmbTahun.removeAllItems();
        for (int i=2013;i<2020;i++){
            jcmbTahun.addItem(i);
        }
    }

    
}
