/*
 * From ko_departemen
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ko.component;


import kopkar.ko.objectclasses.ko_monthly_processext;
import classinterface.NavigatorFormInt;
import common.component.FrmMainFrame;
import java.util.HashMap;
import java.util.Map;
import kopkar.utils.browsecontroller;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import utils.CodeException;
import utils.GlobalUtils;
import utils.appsettinghandler;

/**
 *
 * @author  Generator
 */

public class FrmRTKO07 extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 1;
    public static String CLASSNAME="Frmko_Auto_Pot_Pinjaman";
    
    FrmMainFrame mf ;

    ko_monthly_processext opinj;
    private browsecontroller obrowse;
    private JasperReport jasperReport;
    private JasperPrint jasperPrint;

    /** Creates new form Area */
    public FrmRTKO07() throws CodeException {
        initComponents();
    }
    
    public FrmRTKO07(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
        clearfield();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jlblnama_departemen2 = new javax.swing.JLabel();
        jlblnama_departemen8 = new javax.swing.JLabel();
        joptcomplete_status = new javax.swing.JRadioButton();
        joptcomplete_status_complete = new javax.swing.JRadioButton();
        joptcomplete_status_draft = new javax.swing.JRadioButton();
        jlbldocument_date = new javax.swing.JLabel();
        jlbldocument_duedate = new javax.swing.JLabel();
        kzodocument_date_to = new org.kazao.calendar.KazaoCalendarDate();
        kzodocument_date_fr = new org.kazao.calendar.KazaoCalendarDate();
        jlblnama_departemen4 = new javax.swing.JLabel();
        jtxtmember_number_fr_desc = new javax.swing.JTextField();
        jtxtmember_number_fr = new javax.swing.JTextField();
        jbtnBrowse2 = new javax.swing.JButton();
        jlblnama_departemen5 = new javax.swing.JLabel();
        jtxtmember_number_to_desc = new javax.swing.JTextField();
        jtxtmember_number_to = new javax.swing.JTextField();
        jbtnBrowse3 = new javax.swing.JButton();
        jlblnama_departemen6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laporan Tarik Pinjaman");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Laporan Tarik Pinjaman");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 320, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jlblnama_departemen2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen2.setText("Tanggal");
        getContentPane().add(jlblnama_departemen2);
        jlblnama_departemen2.setBounds(70, 80, 140, 13);

        jlblnama_departemen8.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen8.setText("Status Dokumen");
        getContentPane().add(jlblnama_departemen8);
        jlblnama_departemen8.setBounds(70, 240, 140, 13);

        buttonGroup1.add(joptcomplete_status);
        joptcomplete_status.setFont(new java.awt.Font("Dialog", 1, 10));
        joptcomplete_status.setSelected(true);
        joptcomplete_status.setText("Semua");
        getContentPane().add(joptcomplete_status);
        joptcomplete_status.setBounds(250, 230, 120, 24);

        buttonGroup1.add(joptcomplete_status_complete);
        joptcomplete_status_complete.setFont(new java.awt.Font("Dialog", 1, 10));
        joptcomplete_status_complete.setText("Complete");
        joptcomplete_status_complete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joptcomplete_status_completeActionPerformed(evt);
            }
        });
        getContentPane().add(joptcomplete_status_complete);
        joptcomplete_status_complete.setBounds(370, 230, 123, 24);

        buttonGroup1.add(joptcomplete_status_draft);
        joptcomplete_status_draft.setFont(new java.awt.Font("Dialog", 1, 10));
        joptcomplete_status_draft.setText("Angsuran");
        joptcomplete_status_draft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joptcomplete_status_draftActionPerformed(evt);
            }
        });
        getContentPane().add(joptcomplete_status_draft);
        joptcomplete_status_draft.setBounds(490, 230, 123, 24);

        jlbldocument_date.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_date.setText("Dari");
        getContentPane().add(jlbldocument_date);
        jlbldocument_date.setBounds(70, 100, 140, 13);

        jlbldocument_duedate.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_duedate.setText("Sampai");
        getContentPane().add(jlbldocument_duedate);
        jlbldocument_duedate.setBounds(70, 120, 140, 13);

        kzodocument_date_to.setFont(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date_to.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date_to.setOpaque(false);
        getContentPane().add(kzodocument_date_to);
        kzodocument_date_to.setBounds(260, 120, 100, 20);

        kzodocument_date_fr.setFont(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date_fr.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date_fr.setOpaque(false);
        getContentPane().add(kzodocument_date_fr);
        kzodocument_date_fr.setBounds(260, 100, 100, 20);

        jlblnama_departemen4.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen4.setText("Kode Anggota");
        getContentPane().add(jlblnama_departemen4);
        jlblnama_departemen4.setBounds(70, 160, 140, 13);

        jtxtmember_number_fr_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_number_fr_desc.setText("nama_member_fr");
        jtxtmember_number_fr_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_number_fr_descFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_number_fr_desc);
        jtxtmember_number_fr_desc.setBounds(460, 180, 400, 23);

        jtxtmember_number_fr.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_number_fr.setText("member_number_fr");
        jtxtmember_number_fr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_number_frFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_number_fr);
        jtxtmember_number_fr.setBounds(260, 180, 150, 23);

        jbtnBrowse2.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse2.setText("...");
        jbtnBrowse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse2);
        jbtnBrowse2.setBounds(420, 180, 30, 17);

        jlblnama_departemen5.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen5.setText("Dari");
        getContentPane().add(jlblnama_departemen5);
        jlblnama_departemen5.setBounds(70, 180, 140, 13);

        jtxtmember_number_to_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_number_to_desc.setText("nama_member_fr");
        jtxtmember_number_to_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_number_to_descFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_number_to_desc);
        jtxtmember_number_to_desc.setBounds(460, 200, 400, 23);

        jtxtmember_number_to.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_number_to.setText("member_number_fr");
        jtxtmember_number_to.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_number_toFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_number_to);
        jtxtmember_number_to.setBounds(260, 200, 150, 23);

        jbtnBrowse3.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse3.setText("...");
        jbtnBrowse3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse3);
        jbtnBrowse3.setBounds(420, 200, 30, 17);

        jlblnama_departemen6.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen6.setText("Sampai");
        getContentPane().add(jlblnama_departemen6);
        jlblnama_departemen6.setBounds(70, 200, 140, 13);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void joptcomplete_status_draftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joptcomplete_status_draftActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_joptcomplete_status_draftActionPerformed

private void joptcomplete_status_completeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joptcomplete_status_completeActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_joptcomplete_status_completeActionPerformed

private void jtxtmember_number_fr_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtmember_number_fr_descFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtmember_number_fr_descFocusGained

private void jtxtmember_number_frFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtmember_number_frFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtmember_number_frFocusGained

private void jbtnBrowse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse2ActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_anggota, "", jtxtmember_number_fr,jtxtmember_number_fr_desc);
}//GEN-LAST:event_jbtnBrowse2ActionPerformed

private void jtxtmember_number_to_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtmember_number_to_descFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtmember_number_to_descFocusGained

private void jtxtmember_number_toFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtmember_number_toFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtmember_number_toFocusGained

private void jbtnBrowse3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse3ActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_anggota, "", jtxtmember_number_to,jtxtmember_number_to_desc);
}//GEN-LAST:event_jbtnBrowse3ActionPerformed

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmRTKO07().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse2;
    private javax.swing.JButton jbtnBrowse3;
    private javax.swing.JLabel jlbldocument_date;
    private javax.swing.JLabel jlbldocument_duedate;
    private javax.swing.JLabel jlblnama_departemen2;
    private javax.swing.JLabel jlblnama_departemen4;
    private javax.swing.JLabel jlblnama_departemen5;
    private javax.swing.JLabel jlblnama_departemen6;
    private javax.swing.JLabel jlblnama_departemen8;
    private javax.swing.JRadioButton joptcomplete_status;
    private javax.swing.JRadioButton joptcomplete_status_complete;
    private javax.swing.JRadioButton joptcomplete_status_draft;
    private javax.swing.JTextField jtxtmember_number_fr;
    private javax.swing.JTextField jtxtmember_number_fr_desc;
    private javax.swing.JTextField jtxtmember_number_to;
    private javax.swing.JTextField jtxtmember_number_to_desc;
    private org.kazao.calendar.KazaoCalendarDate kzodocument_date_fr;
    private org.kazao.calendar.KazaoCalendarDate kzodocument_date_to;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jtxtmember_number_fr.setText("");
        jtxtmember_number_fr_desc.setText("");
        jtxtmember_number_to.setText("");
        jtxtmember_number_to_desc.setText("");
    }

    public void newData() throws CodeException {
        istatus=1;
        clearfield();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        Map parameter = new HashMap();

        parameter.put("document_date_fr", GlobalUtils.formatDate(kzodocument_date_fr.getDate(), "yyyy-MM-dd"));
        parameter.put("document_date_to", GlobalUtils.formatDate(kzodocument_date_to.getDate(), "yyyy-MM-dd"));

        parameter.put("member_number_fr", jtxtmember_number_fr.getText());
        parameter.put("member_number_to", jtxtmember_number_to.getText());

        String complete_status="A";
        if (joptcomplete_status_complete.isSelected()){
            complete_status="Y";
        } else if (joptcomplete_status_draft.isSelected()){
            complete_status="N";
        }
        parameter.put("complete_status", complete_status);

        parameter.put("audituser", (GlobalUtils.getUserId()));

        // Versi 1
        String report_file ="";
        if(GlobalUtils.getAppDir()){
            try{
                report_file = GlobalUtils.getCurrentDir() +"/Reports/RTKO-07.jrxml";
                jasperReport = JasperCompileManager.compileReport(report_file);
                //System.out.println("file: "+file);
                System.out.println("isi parameter "+report_file+":"+parameter);
                jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, appsettinghandler.db.getConnection());
                JasperViewer.viewReport(jasperPrint, false);
            }catch (Exception e) {
            e.printStackTrace();
            }
        }
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);
    }

    public void setData() throws CodeException {
        if (istatus==1){
        }
    }

    public void undo() throws CodeException {
        istatus = 0;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    

    
}
