/*
 * From ko_departemen
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ko.component;


import kopkar.ko.objectclasses.ko_monthly_processext;
import classinterface.NavigatorFormInt;
import common.component.FrmMainFrame;
import java.util.HashMap;
import java.util.Map;
import kopkar.utils.browsecontroller;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import utils.CodeException;
import utils.GlobalUtils;
import utils.appsettinghandler;

/**
 *
 * @author  Generator
 */

public class FrmRTKO02 extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 1;
    public static String CLASSNAME="Frmko_Auto_Pot_Pinjaman";
    
    FrmMainFrame mf ;

    ko_monthly_processext opinj;
    private browsecontroller obrowse;
    private JasperReport jasperReport;
    private JasperPrint jasperPrint;

    /** Creates new form Area */
    public FrmRTKO02() throws CodeException {
        initComponents();
    }
    
    public FrmRTKO02(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();

        fillyear();
        jcmbTahun.setSelectedItem(GlobalUtils.toInt(GlobalUtils.getCurrentYear()));

        jcmbBulan.setSelectedIndex(GlobalUtils.toInt(GlobalUtils.getCurrentMonth())-1);
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jlblkode_departemen = new javax.swing.JLabel();
        jlblnama_departemen = new javax.swing.JLabel();
        jcmbTahun = new javax.swing.JComboBox();
        jcmbBulan = new javax.swing.JComboBox();
        jlblnama_departemen1 = new javax.swing.JLabel();
        jchksort_by_tgl_cair = new javax.swing.JCheckBox();
        kzodocument_date_fr = new org.kazao.calendar.KazaoCalendarDate();
        jHeader1 = new javax.swing.JLabel();
        jlblnama_departemen2 = new javax.swing.JLabel();
        kzodocument_date_to = new org.kazao.calendar.KazaoCalendarDate();
        jchkall_document_status = new javax.swing.JCheckBox();
        jlblnama_departemen3 = new javax.swing.JLabel();
        joptdocument_status_close = new javax.swing.JRadioButton();
        joptdocument_status_open = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laporan Persetujuan Pinjaman");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText("Tanggal Dokumen");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(90, 170, 320, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jlblkode_departemen.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblkode_departemen.setText("Tahun");
        getContentPane().add(jlblkode_departemen);
        jlblkode_departemen.setBounds(70, 100, 140, 13);

        jlblnama_departemen.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen.setText("Mulai");
        getContentPane().add(jlblnama_departemen);
        jlblnama_departemen.setBounds(90, 200, 140, 13);

        jcmbTahun.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbTahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013", "2012" }));
        getContentPane().add(jcmbTahun);
        jcmbTahun.setBounds(260, 100, 80, 20);

        jcmbBulan.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbBulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        getContentPane().add(jcmbBulan);
        jcmbBulan.setBounds(260, 120, 80, 20);

        jlblnama_departemen1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen1.setText("Periode");
        getContentPane().add(jlblnama_departemen1);
        jlblnama_departemen1.setBounds(70, 120, 140, 13);

        jchksort_by_tgl_cair.setFont(new java.awt.Font("Dialog", 1, 10));
        jchksort_by_tgl_cair.setText("Sort By Tanggal Cair Persetujuan");
        getContentPane().add(jchksort_by_tgl_cair);
        jchksort_by_tgl_cair.setBounds(70, 150, 280, 24);

        kzodocument_date_fr.setFont(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date_fr.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date_fr.setOpaque(false);
        getContentPane().add(kzodocument_date_fr);
        kzodocument_date_fr.setBounds(250, 200, 100, 20);

        jHeader1.setBackground(new java.awt.Color(102, 102, 102));
        jHeader1.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader1.setForeground(new java.awt.Color(255, 255, 255));
        jHeader1.setText(" : : Laporan Persetujuan Pinjaman");
        jHeader1.setAlignmentY(0.0F);
        jHeader1.setOpaque(true);
        getContentPane().add(jHeader1);
        jHeader1.setBounds(30, 30, 320, 20);

        jlblnama_departemen2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen2.setText("Status Dokumen");
        getContentPane().add(jlblnama_departemen2);
        jlblnama_departemen2.setBounds(100, 270, 140, 13);

        kzodocument_date_to.setFont(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date_to.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date_to.setOpaque(false);
        getContentPane().add(kzodocument_date_to);
        kzodocument_date_to.setBounds(250, 220, 100, 20);

        jchkall_document_status.setFont(new java.awt.Font("Dialog", 1, 10));
        jchkall_document_status.setText("Semua Status Dokumen");
        getContentPane().add(jchkall_document_status);
        jchkall_document_status.setBounds(70, 240, 280, 24);

        jlblnama_departemen3.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen3.setText("Sampai");
        getContentPane().add(jlblnama_departemen3);
        jlblnama_departemen3.setBounds(90, 220, 140, 13);

        buttonGroup1.add(joptdocument_status_close);
        joptdocument_status_close.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        joptdocument_status_close.setText("Close");
        getContentPane().add(joptdocument_status_close);
        joptdocument_status_close.setBounds(370, 260, 123, 24);

        buttonGroup1.add(joptdocument_status_open);
        joptdocument_status_open.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        joptdocument_status_open.setSelected(true);
        joptdocument_status_open.setText("Open");
        getContentPane().add(joptdocument_status_open);
        joptdocument_status_open.setBounds(250, 260, 55, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmRTKO02().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jHeader;
    private javax.swing.JLabel jHeader1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox jchkall_document_status;
    private javax.swing.JCheckBox jchksort_by_tgl_cair;
    private javax.swing.JComboBox jcmbBulan;
    private javax.swing.JComboBox jcmbTahun;
    private javax.swing.JLabel jlblkode_departemen;
    private javax.swing.JLabel jlblnama_departemen;
    private javax.swing.JLabel jlblnama_departemen1;
    private javax.swing.JLabel jlblnama_departemen2;
    private javax.swing.JLabel jlblnama_departemen3;
    private javax.swing.JRadioButton joptdocument_status_close;
    private javax.swing.JRadioButton joptdocument_status_open;
    private org.kazao.calendar.KazaoCalendarDate kzodocument_date_fr;
    private org.kazao.calendar.KazaoCalendarDate kzodocument_date_to;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jcmbTahun.setSelectedItem(GlobalUtils.getCurrentYear());
        jcmbBulan.setSelectedIndex(GlobalUtils.toInt(GlobalUtils.getCurrentMonth())-1);
    }

    public void newData() throws CodeException {
        istatus=1;
        clearfield();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        Map parameter = new HashMap();

        parameter.put("yop", GlobalUtils.churuf(jcmbTahun.getSelectedItem()));
        parameter.put("mop", GlobalUtils.churuf(jcmbBulan.getSelectedIndex()+1));

        String sort_by_tgl_cair="N";
        if (jchksort_by_tgl_cair.isSelected()){
            sort_by_tgl_cair="Y";
        }
        parameter.put("sort_by_tgl_cair", sort_by_tgl_cair);
        parameter.put("document_date_fr", GlobalUtils.formatDate(kzodocument_date_fr.getDate(),"yyyy-MM-dd"));
        parameter.put("document_date_to", GlobalUtils.formatDate(kzodocument_date_to.getDate(),"yyyy-MM-dd"));

        String all_document_status="N";
        if (jchkall_document_status.isSelected()){
            all_document_status="Y";
        }
        parameter.put("all_document_status", all_document_status);

        String document_status="O";
        if (joptdocument_status_close.isSelected()){
            document_status="C";
        }
        parameter.put("document_status", document_status);

        parameter.put("audituser", (GlobalUtils.getUserId()));

        // Versi 1
        String file ="";
        if(GlobalUtils.getAppDir()){
            try{
                file = GlobalUtils.getCurrentDir() +"/Reports/RTKO-02.jrxml";
                jasperReport = JasperCompileManager.compileReport(file);
                //System.out.println("file: "+file);
                System.out.println("isi parameter potong_gaji_rpt:"+parameter);
                jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, appsettinghandler.db.getConnection());
                JasperViewer.viewReport(jasperPrint, false);
            }catch (Exception e) {
            e.printStackTrace();
            }
        }
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);
    }

    public void setData() throws CodeException {
        if (istatus==1){
        }
    }

    public void undo() throws CodeException {
        istatus = 0;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    private void fillyear() {
        jcmbTahun.removeAllItems();
        for (int i=2013;i<2020;i++){
            jcmbTahun.addItem(i);
        }
    }

    
}
