/*
 * From ko_departemen
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ko.component;


import kopkar.ko.objectclasses.ko_monthly_processext;
import classinterface.NavigatorFormInt;
import common.component.FrmMainFrame;
import java.util.HashMap;
import java.util.Map;
import kopkar.utils.browsecontroller;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import utils.CodeException;
import utils.GlobalUtils;
import utils.appsettinghandler;

/**
 *
 * @author  Generator
 */

public class FrmRTKO05 extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 1;
    public static String CLASSNAME="Frmko_Auto_Pot_Pinjaman";
    
    FrmMainFrame mf ;

    ko_monthly_processext opinj;
    private browsecontroller obrowse=new browsecontroller();
    private JasperReport jasperReport;
    private JasperPrint jasperPrint;

    /** Creates new form Area */
    public FrmRTKO05() throws CodeException {
        initComponents();
    }
    
    public FrmRTKO05(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();

        jtxtmember_number.setText("");
        jtxtnama_member_fr.setText("");
        jtxtdocument_number.setText("");
        
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jlblnama_departemen4 = new javax.swing.JLabel();
        jbtnBrowse2 = new javax.swing.JButton();
        jtxtmember_number = new javax.swing.JTextField();
        jtxtnama_member_fr = new javax.swing.JTextField();
        jlblnama_departemen6 = new javax.swing.JLabel();
        jlblnama_departemen7 = new javax.swing.JLabel();
        jtxtdocument_number = new javax.swing.JTextField();
        jbtnBrowse4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laporan Angsuran Pinjaman");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Laporan Angsuran Pinjaman");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 320, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jlblnama_departemen4.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen4.setText("Nomor Anggota");
        getContentPane().add(jlblnama_departemen4);
        jlblnama_departemen4.setBounds(70, 100, 140, 13);

        jbtnBrowse2.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse2.setText("...");
        jbtnBrowse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse2);
        jbtnBrowse2.setBounds(420, 100, 30, 17);

        jtxtmember_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_number.setText("member_number_fr");
        jtxtmember_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_number);
        jtxtmember_number.setBounds(260, 100, 150, 23);

        jtxtnama_member_fr.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtnama_member_fr.setText("nama_member_fr");
        jtxtnama_member_fr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtnama_member_frFocusGained(evt);
            }
        });
        getContentPane().add(jtxtnama_member_fr);
        jtxtnama_member_fr.setBounds(260, 120, 400, 23);

        jlblnama_departemen6.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen6.setText("Nama Anggota");
        getContentPane().add(jlblnama_departemen6);
        jlblnama_departemen6.setBounds(70, 120, 140, 13);

        jlblnama_departemen7.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen7.setText("Nomor Persetujuan");
        getContentPane().add(jlblnama_departemen7);
        jlblnama_departemen7.setBounds(70, 160, 140, 13);

        jtxtdocument_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdocument_number.setText("member_number_to");
        jtxtdocument_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocument_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdocument_number);
        jtxtdocument_number.setBounds(260, 160, 150, 23);

        jbtnBrowse4.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse4.setText("...");
        jbtnBrowse4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse4);
        jbtnBrowse4.setBounds(420, 160, 30, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jbtnBrowse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse2ActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_anggota, "", jtxtmember_number,jtxtnama_member_fr);
}//GEN-LAST:event_jbtnBrowse2ActionPerformed

private void jtxtmember_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtmember_numberFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtmember_numberFocusGained

private void jtxtnama_member_frFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtnama_member_frFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtnama_member_frFocusGained

private void jtxtdocument_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdocument_numberFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdocument_numberFocusGained

private void jbtnBrowse4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse4ActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_transaksi_setuju, "member_number='"+jtxtmember_number.getText()+"'", jtxtdocument_number);
}//GEN-LAST:event_jbtnBrowse4ActionPerformed

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmRTKO05().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse2;
    private javax.swing.JButton jbtnBrowse4;
    private javax.swing.JLabel jlblnama_departemen4;
    private javax.swing.JLabel jlblnama_departemen6;
    private javax.swing.JLabel jlblnama_departemen7;
    private javax.swing.JTextField jtxtdocument_number;
    private javax.swing.JTextField jtxtmember_number;
    private javax.swing.JTextField jtxtnama_member_fr;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

   

    public void newData() throws CodeException {
        istatus=1;

        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        Map parameter = new HashMap();

        parameter.put("member_number", jtxtmember_number.getText());
        parameter.put("document_number", jtxtdocument_number.getText());
        parameter.put("audituser", (GlobalUtils.getUserId()));

        // Versi 1
        String file ="";
        if(GlobalUtils.getAppDir()){
            try{
                file = GlobalUtils.getCurrentDir() +"/Reports/RTKO-05.jrxml";
                jasperReport = JasperCompileManager.compileReport(file);
                //System.out.println("file: "+file);
                System.out.println("isi parameter RTKO-05:"+parameter);
                jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, appsettinghandler.db.getConnection());
                JasperViewer.viewReport(jasperPrint, false);
            }catch (Exception e) {
            e.printStackTrace();
            }
        }
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);
    }

    public void setData() throws CodeException {
        if (istatus==1){
        }
    }

    public void undo() throws CodeException {
        istatus = 0;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    

    
}
