/*
 * From op_salesman
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ko.component;


import kopkar.ar.component.*;
import kopkar.ap.component.*;
import classinterface.NavigatorFormInt;
import common.component.FrmMainFrame;
import common.component.FrmMainFrame;
import java.util.HashMap;
import java.util.Map;
import jdbc.DbBean;
import kopkar.utils.browsecontroller;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import utils.CodeException;
import utils.GlobalUtils;
import utils.appsettinghandler;

/**
 *
 * @author  Generator
 */

public class FrmRTSP10 extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 1;
    public static String CLASSNAME="FrmRTPS03";
    browsecontroller obrowse=new browsecontroller();
    JasperPrint jasperPrint;
    JasperReport jasperReport;
    DbBean db=appsettinghandler.db;
    String status="";
    String type="0";



    FrmMainFrame mf ;

   
    /** Creates new form Area */
    public FrmRTSP10() throws CodeException {
        initComponents();

    }
    
    public FrmRTSP10(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jlblsalesman_code3 = new javax.swing.JLabel();
        kzodocument_date_to = new org.kazao.calendar.KazaoCalendarDate();
        kzodocument_date_fr = new org.kazao.calendar.KazaoCalendarDate();
        jlblsalesman_code4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtnBrowse = new javax.swing.JButton();
        jlblsalesman_code = new javax.swing.JLabel();
        jtxtmember_number_fr = new javax.swing.JTextField();
        jtxtmember_number_to = new javax.swing.JTextField();
        jbtnBrowse1 = new javax.swing.JButton();
        jlblsalesman_code1 = new javax.swing.JLabel();
        jtxtmember_number_to_desc = new javax.swing.JTextField();
        jtxtmember_number_fr_desc = new javax.swing.JTextField();
        jchckisbulanakh = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jbtnBrowse2 = new javax.swing.JButton();
        jlblsalesman_code2 = new javax.swing.JLabel();
        jtxtdepartment_code_fr = new javax.swing.JTextField();
        jtxtdepartment_code_to = new javax.swing.JTextField();
        jbtnBrowse3 = new javax.swing.JButton();
        jlblsalesman_code5 = new javax.swing.JLabel();
        jtxtdepartment_code_to_desc = new javax.swing.JTextField();
        jtxtdepartment_code_fr_desc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buku Simpanan  Report");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Buku Simpanan  Report");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 200, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tanggal Transaksi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N
        jPanel1.setLayout(null);

        jlblsalesman_code3.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsalesman_code3.setText("Dari");
        jPanel1.add(jlblsalesman_code3);
        jlblsalesman_code3.setBounds(30, 30, 120, 20);

        kzodocument_date_to.setFont(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date_to.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date_to.setOpaque(false);
        jPanel1.add(kzodocument_date_to);
        kzodocument_date_to.setBounds(150, 50, 120, 20);

        kzodocument_date_fr.setFont(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date_fr.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date_fr.setOpaque(false);
        jPanel1.add(kzodocument_date_fr);
        kzodocument_date_fr.setBounds(150, 30, 120, 20);

        jlblsalesman_code4.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsalesman_code4.setText("Sampai");
        jPanel1.add(jlblsalesman_code4);
        jlblsalesman_code4.setBounds(30, 50, 120, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 110, 720, 100);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Anggota", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N
        jPanel2.setLayout(null);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowse);
        jbtnBrowse.setBounds(250, 40, 30, 17);

        jlblsalesman_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsalesman_code.setText("Sampai");
        jPanel2.add(jlblsalesman_code);
        jlblsalesman_code.setBounds(30, 60, 120, 20);

        jtxtmember_number_fr.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanel2.add(jtxtmember_number_fr);
        jtxtmember_number_fr.setBounds(150, 40, 90, 23);

        jtxtmember_number_to.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanel2.add(jtxtmember_number_to);
        jtxtmember_number_to.setBounds(150, 60, 90, 23);

        jbtnBrowse1.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse1.setText("...");
        jbtnBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBrowse1);
        jbtnBrowse1.setBounds(250, 60, 30, 17);

        jlblsalesman_code1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsalesman_code1.setText("Dari");
        jPanel2.add(jlblsalesman_code1);
        jlblsalesman_code1.setBounds(30, 40, 120, 20);

        jtxtmember_number_to_desc.setEditable(false);
        jtxtmember_number_to_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanel2.add(jtxtmember_number_to_desc);
        jtxtmember_number_to_desc.setBounds(290, 60, 390, 23);

        jtxtmember_number_fr_desc.setEditable(false);
        jtxtmember_number_fr_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanel2.add(jtxtmember_number_fr_desc);
        jtxtmember_number_fr_desc.setBounds(290, 40, 390, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(70, 340, 720, 110);

        jchckisbulanakh.setFont(new java.awt.Font("Dialog", 1, 10));
        jchckisbulanakh.setText("Transaksi  1 (Satu) Bulan Terakhir");
        getContentPane().add(jchckisbulanakh);
        jchckisbulanakh.setBounds(70, 80, 300, 24);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Departemen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N
        jPanel3.setLayout(null);

        jbtnBrowse2.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse2.setText("...");
        jbtnBrowse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse2ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnBrowse2);
        jbtnBrowse2.setBounds(250, 40, 30, 17);

        jlblsalesman_code2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsalesman_code2.setText("Sampai");
        jPanel3.add(jlblsalesman_code2);
        jlblsalesman_code2.setBounds(30, 60, 120, 20);

        jtxtdepartment_code_fr.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanel3.add(jtxtdepartment_code_fr);
        jtxtdepartment_code_fr.setBounds(150, 40, 90, 23);

        jtxtdepartment_code_to.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanel3.add(jtxtdepartment_code_to);
        jtxtdepartment_code_to.setBounds(150, 60, 90, 23);

        jbtnBrowse3.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse3.setText("...");
        jbtnBrowse3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse3ActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnBrowse3);
        jbtnBrowse3.setBounds(250, 60, 30, 17);

        jlblsalesman_code5.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsalesman_code5.setText("Dari");
        jPanel3.add(jlblsalesman_code5);
        jlblsalesman_code5.setBounds(30, 40, 120, 20);

        jtxtdepartment_code_to_desc.setEditable(false);
        jtxtdepartment_code_to_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanel3.add(jtxtdepartment_code_to_desc);
        jtxtdepartment_code_to_desc.setBounds(290, 60, 390, 23);

        jtxtdepartment_code_fr_desc.setEditable(false);
        jtxtdepartment_code_fr_desc.setFont(new java.awt.Font("Dialog", 0, 10));
        jPanel3.add(jtxtdepartment_code_fr_desc);
        jtxtdepartment_code_fr_desc.setBounds(290, 40, 390, 23);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(70, 220, 720, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jbtnBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse1ActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.ko_anggota, "", jtxtmember_number_to,jtxtmember_number_to_desc);
}//GEN-LAST:event_jbtnBrowse1ActionPerformed

private void jbtnBrowse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse2ActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.ko_departemen, "", jtxtdepartment_code_fr,jtxtdepartment_code_fr_desc);
}//GEN-LAST:event_jbtnBrowse2ActionPerformed

private void jbtnBrowse3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse3ActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.ko_departemen, "", jtxtdepartment_code_to,jtxtdepartment_code_to_desc);
}//GEN-LAST:event_jbtnBrowse3ActionPerformed
                                     
private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
    obrowse.showbrowser(obrowse.ko_anggota, "", jtxtmember_number_fr,jtxtmember_number_fr_desc);
}                                                                                 

    public void execute() throws CodeException {


        Map parameter = new HashMap();


        String isbulanakh="N";
        if (jchckisbulanakh.isSelected()){
            isbulanakh="Y";
        }
        parameter.put("isbulanakh", isbulanakh);
        parameter.put("document_date_fr", GlobalUtils.formatDate(kzodocument_date_fr.getDate(),"yyyy-MM-dd"));
        parameter.put("document_date_to", GlobalUtils.formatDate(kzodocument_date_to.getDate(),"yyyy-MM-dd"));
        parameter.put("department_code_fr", jtxtdepartment_code_fr.getText());
        parameter.put("department_code_to", jtxtdepartment_code_to.getText());
        parameter.put("member_number_fr", jtxtmember_number_fr.getText());
        parameter.put("member_number_to", jtxtmember_number_to.getText());
        parameter.put("audituser", (GlobalUtils.getUserId()));

        // Versi 1
        String file ="";
        String rptFile="RTSP-10.jrxml";
        if(GlobalUtils.getAppDir()){
            try{
            file = GlobalUtils.getCurrentDir() +"/Reports/"+rptFile;
            jasperReport = JasperCompileManager.compileReport(file);
            //System.out.println("file: "+file);
            System.out.println("isi parameter Report PO:"+parameter);
            jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, db.getConnection());
            JasperViewer.viewReport(jasperPrint, false);
    }catch (Exception e) {
        e.printStackTrace();
    }
        }
        // Versi 2
        /*
        String file ="";
        if(GlobalUtils.getAppDir()){
            file = GlobalUtils.getCurrentDir() +"/Reports/ap_supplier.jrxml";
            GlobalUtils.printReport(file, parameter, false);
            System.out.println("file: "+file);
            System.out.println("isi parameter FAR-06:"+parameter);
        }
         *
         */



    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmRTSP10().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jHeader;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowse1;
    private javax.swing.JButton jbtnBrowse2;
    private javax.swing.JButton jbtnBrowse3;
    private javax.swing.JCheckBox jchckisbulanakh;
    private javax.swing.JLabel jlblsalesman_code;
    private javax.swing.JLabel jlblsalesman_code1;
    private javax.swing.JLabel jlblsalesman_code2;
    private javax.swing.JLabel jlblsalesman_code3;
    private javax.swing.JLabel jlblsalesman_code4;
    private javax.swing.JLabel jlblsalesman_code5;
    private javax.swing.JTextField jtxtdepartment_code_fr;
    private javax.swing.JTextField jtxtdepartment_code_fr_desc;
    private javax.swing.JTextField jtxtdepartment_code_to;
    private javax.swing.JTextField jtxtdepartment_code_to_desc;
    private javax.swing.JTextField jtxtmember_number_fr;
    private javax.swing.JTextField jtxtmember_number_fr_desc;
    private javax.swing.JTextField jtxtmember_number_to;
    private javax.swing.JTextField jtxtmember_number_to_desc;
    private org.kazao.calendar.KazaoCalendarDate kzodocument_date_fr;
    private org.kazao.calendar.KazaoCalendarDate kzodocument_date_to;
    // End of variables declaration//GEN-END:variables

 

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);

        if (istatus==1){
            jbtnBrowse.setEnabled(false);
        } else {
            jbtnBrowse.setEnabled(true);
        }
    }

    public void delete() throws CodeException {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void moveFirst() throws CodeException {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void movePrevious() throws CodeException {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void moveNext() throws CodeException {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void moveLast() throws CodeException {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void newData() throws CodeException {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void saveData() throws CodeException {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void printData() throws CodeException {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void showData() throws CodeException {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setData() throws CodeException {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void undo() throws CodeException {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void searchData() throws CodeException {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void importCsv() throws CodeException {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void exportCsv() throws CodeException {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void importText() throws CodeException {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void exportText() throws CodeException {
        //throw new UnsupportedOperationException("Not supported yet.");
    }
    
}
