/*
 * From ko_departemen
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.ko.component;


import kopkar.ko.objectclasses.ko_monthly_processext;
import classinterface.NavigatorFormInt;
import common.component.FrmMainFrame;
import java.util.HashMap;
import java.util.Map;
import kopkar.utils.browsecontroller;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import utils.CodeException;
import utils.GlobalUtils;
import utils.appsettinghandler;

/**
 *
 * @author  Generator
 */

public class FrmRTKO08 extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 1;
    public static String CLASSNAME="Frmko_Auto_Pot_Pinjaman";
    
    FrmMainFrame mf ;

    ko_monthly_processext opinj;
    private browsecontroller obrowse;
    private JasperReport jasperReport;
    private JasperPrint jasperPrint;

    /** Creates new form Area */
    public FrmRTKO08() throws CodeException {
        initComponents();
    }
    
    public FrmRTKO08(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();

        jtxtdepartment_code_fr.setText("");
        jtxtnama_departemen_fr.setText("");
        jtxtdepartment_code_to.setText("");
        jtxtnama_departemen_to.setText("");

        jtxtmember_number_fr.setText("");
        jtxtnama_member_fr.setText("");
        jtxtmember_number_to.setText("");
        jtxtnama_member_to.setText("");
        fillyear();
        jcmbTahun.setSelectedItem(GlobalUtils.toInt(GlobalUtils.getCurrentYear()));

        jcmbBulan.setSelectedIndex(GlobalUtils.toInt(GlobalUtils.getCurrentMonth())-1);
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jlblkode_departemen = new javax.swing.JLabel();
        jlblnama_departemen = new javax.swing.JLabel();
        jcmbTahun = new javax.swing.JComboBox();
        jcmbBulan = new javax.swing.JComboBox();
        jlblnama_departemen1 = new javax.swing.JLabel();
        jlblnama_departemen2 = new javax.swing.JLabel();
        jbtnBrowse = new javax.swing.JButton();
        jtxtdepartment_code_fr = new javax.swing.JTextField();
        jtxtnama_departemen_fr = new javax.swing.JTextField();
        jlblnama_departemen3 = new javax.swing.JLabel();
        jbtnBrowse1 = new javax.swing.JButton();
        jtxtdepartment_code_to = new javax.swing.JTextField();
        jtxtnama_departemen_to = new javax.swing.JTextField();
        jlblnama_departemen4 = new javax.swing.JLabel();
        jlblnama_departemen5 = new javax.swing.JLabel();
        jbtnBrowse2 = new javax.swing.JButton();
        jtxtmember_number_fr = new javax.swing.JTextField();
        jtxtnama_member_fr = new javax.swing.JTextField();
        jlblnama_departemen6 = new javax.swing.JLabel();
        jbtnBrowse3 = new javax.swing.JButton();
        jtxtmember_number_to = new javax.swing.JTextField();
        jtxtnama_member_to = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bon Bukti Pemotongan Gaji");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Bon Bukti Pemotongan Gaji");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 320, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jlblkode_departemen.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblkode_departemen.setText("Tahun");
        getContentPane().add(jlblkode_departemen);
        jlblkode_departemen.setBounds(70, 100, 140, 13);

        jlblnama_departemen.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen.setText("Mulai");
        getContentPane().add(jlblnama_departemen);
        jlblnama_departemen.setBounds(70, 170, 140, 13);

        jcmbTahun.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbTahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013", "2012" }));
        getContentPane().add(jcmbTahun);
        jcmbTahun.setBounds(260, 100, 80, 20);

        jcmbBulan.setFont(new java.awt.Font("Dialog", 0, 10));
        jcmbBulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        getContentPane().add(jcmbBulan);
        jcmbBulan.setBounds(260, 120, 80, 20);

        jlblnama_departemen1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen1.setText("Periode");
        getContentPane().add(jlblnama_departemen1);
        jlblnama_departemen1.setBounds(70, 120, 140, 13);

        jlblnama_departemen2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen2.setText("Departemen");
        getContentPane().add(jlblnama_departemen2);
        jlblnama_departemen2.setBounds(70, 150, 140, 13);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(420, 170, 30, 17);

        jtxtdepartment_code_fr.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdepartment_code_fr.setText("department_code_fr");
        jtxtdepartment_code_fr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdepartment_code_frFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdepartment_code_fr);
        jtxtdepartment_code_fr.setBounds(260, 170, 150, 23);

        jtxtnama_departemen_fr.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtnama_departemen_fr.setText("nama_departemen_fr");
        jtxtnama_departemen_fr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtnama_departemen_frFocusGained(evt);
            }
        });
        getContentPane().add(jtxtnama_departemen_fr);
        jtxtnama_departemen_fr.setBounds(460, 170, 400, 23);

        jlblnama_departemen3.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen3.setText("Sampai");
        getContentPane().add(jlblnama_departemen3);
        jlblnama_departemen3.setBounds(70, 190, 140, 13);

        jbtnBrowse1.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse1.setText("...");
        jbtnBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse1);
        jbtnBrowse1.setBounds(420, 190, 30, 17);

        jtxtdepartment_code_to.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdepartment_code_to.setText("department_code_to");
        jtxtdepartment_code_to.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdepartment_code_toFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdepartment_code_to);
        jtxtdepartment_code_to.setBounds(260, 190, 150, 23);

        jtxtnama_departemen_to.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtnama_departemen_to.setText("nama_departemen_to");
        jtxtnama_departemen_to.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtnama_departemen_toFocusGained(evt);
            }
        });
        getContentPane().add(jtxtnama_departemen_to);
        jtxtnama_departemen_to.setBounds(460, 190, 400, 23);

        jlblnama_departemen4.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen4.setText("Mulai");
        getContentPane().add(jlblnama_departemen4);
        jlblnama_departemen4.setBounds(70, 240, 140, 13);

        jlblnama_departemen5.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen5.setText("Anggota");
        getContentPane().add(jlblnama_departemen5);
        jlblnama_departemen5.setBounds(70, 220, 140, 13);

        jbtnBrowse2.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse2.setText("...");
        jbtnBrowse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse2);
        jbtnBrowse2.setBounds(420, 240, 30, 17);

        jtxtmember_number_fr.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_number_fr.setText("member_number_fr");
        jtxtmember_number_fr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_number_frFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_number_fr);
        jtxtmember_number_fr.setBounds(260, 240, 150, 23);

        jtxtnama_member_fr.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtnama_member_fr.setText("nama_member_fr");
        jtxtnama_member_fr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtnama_member_frFocusGained(evt);
            }
        });
        getContentPane().add(jtxtnama_member_fr);
        jtxtnama_member_fr.setBounds(460, 240, 400, 23);

        jlblnama_departemen6.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_departemen6.setText("Sampai");
        getContentPane().add(jlblnama_departemen6);
        jlblnama_departemen6.setBounds(70, 260, 140, 13);

        jbtnBrowse3.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse3.setText("...");
        jbtnBrowse3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse3);
        jbtnBrowse3.setBounds(420, 260, 30, 17);

        jtxtmember_number_to.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtmember_number_to.setText("member_number_to");
        jtxtmember_number_to.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtmember_number_toFocusGained(evt);
            }
        });
        getContentPane().add(jtxtmember_number_to);
        jtxtmember_number_to.setBounds(260, 260, 150, 23);

        jtxtnama_member_to.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtnama_member_to.setText("nama_member_to");
        jtxtnama_member_to.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtnama_member_toFocusGained(evt);
            }
        });
        getContentPane().add(jtxtnama_member_to);
        jtxtnama_member_to.setBounds(460, 260, 400, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_departemen, "", jtxtdepartment_code_fr,jtxtnama_departemen_fr);
}//GEN-LAST:event_jbtnBrowseActionPerformed

private void jtxtdepartment_code_frFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdepartment_code_frFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdepartment_code_frFocusGained

private void jtxtnama_departemen_frFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtnama_departemen_frFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtnama_departemen_frFocusGained

private void jbtnBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse1ActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_departemen, "", jtxtdepartment_code_to,jtxtnama_departemen_to);
}//GEN-LAST:event_jbtnBrowse1ActionPerformed

private void jtxtdepartment_code_toFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdepartment_code_toFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdepartment_code_toFocusGained

private void jtxtnama_departemen_toFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtnama_departemen_toFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtnama_departemen_toFocusGained

private void jbtnBrowse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse2ActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_anggota, "", jtxtmember_number_fr,jtxtnama_member_fr);
}//GEN-LAST:event_jbtnBrowse2ActionPerformed

private void jtxtmember_number_frFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtmember_number_frFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtmember_number_frFocusGained

private void jtxtnama_member_frFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtnama_member_frFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtnama_member_frFocusGained

private void jbtnBrowse3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse3ActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.ko_anggota, "", jtxtmember_number_to,jtxtnama_member_to);
}//GEN-LAST:event_jbtnBrowse3ActionPerformed

private void jtxtmember_number_toFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtmember_number_toFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtmember_number_toFocusGained

private void jtxtnama_member_toFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtnama_member_toFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtnama_member_toFocusGained

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmRTKO08().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowse1;
    private javax.swing.JButton jbtnBrowse2;
    private javax.swing.JButton jbtnBrowse3;
    private javax.swing.JComboBox jcmbBulan;
    private javax.swing.JComboBox jcmbTahun;
    private javax.swing.JLabel jlblkode_departemen;
    private javax.swing.JLabel jlblnama_departemen;
    private javax.swing.JLabel jlblnama_departemen1;
    private javax.swing.JLabel jlblnama_departemen2;
    private javax.swing.JLabel jlblnama_departemen3;
    private javax.swing.JLabel jlblnama_departemen4;
    private javax.swing.JLabel jlblnama_departemen5;
    private javax.swing.JLabel jlblnama_departemen6;
    private javax.swing.JTextField jtxtdepartment_code_fr;
    private javax.swing.JTextField jtxtdepartment_code_to;
    private javax.swing.JTextField jtxtmember_number_fr;
    private javax.swing.JTextField jtxtmember_number_to;
    private javax.swing.JTextField jtxtnama_departemen_fr;
    private javax.swing.JTextField jtxtnama_departemen_to;
    private javax.swing.JTextField jtxtnama_member_fr;
    private javax.swing.JTextField jtxtnama_member_to;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jcmbTahun.setSelectedItem(GlobalUtils.getCurrentYear());
        jcmbBulan.setSelectedIndex(GlobalUtils.toInt(GlobalUtils.getCurrentMonth())-1);
    }

    public void newData() throws CodeException {
        istatus=1;
        clearfield();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        Map parameter = new HashMap();

        parameter.put("yop", GlobalUtils.churuf(jcmbTahun.getSelectedItem()));
        parameter.put("mop", GlobalUtils.churuf(jcmbBulan.getSelectedIndex()+1));
        parameter.put("department_code_fr", jtxtdepartment_code_fr.getText());
        parameter.put("department_code_to", jtxtdepartment_code_to.getText());
        parameter.put("member_number_fr", jtxtmember_number_fr.getText());
        parameter.put("member_number_to", jtxtmember_number_to.getText());
        parameter.put("audituser", (GlobalUtils.getUserId()));

        // Versi 1
        String file ="";
        if(GlobalUtils.getAppDir()){
            try{
                file = GlobalUtils.getCurrentDir() +"/Reports/RTKO-08.jrxml";
                jasperReport = JasperCompileManager.compileReport(file);
                //System.out.println("file: "+file);
                System.out.println("isi parameter potong_gaji_rpt:"+parameter);
                jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, appsettinghandler.db.getConnection());
                JasperViewer.viewReport(jasperPrint, false);
            }catch (Exception e) {
            e.printStackTrace();
            }
        }
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);
    }

    public void setData() throws CodeException {
        if (istatus==1){
        }
    }

    public void undo() throws CodeException {
        istatus = 0;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    private void fillyear() {
        jcmbTahun.removeAllItems();
        for (int i=2013;i<2020;i++){
            jcmbTahun.addItem(i);
        }
    }

    
}
