/*
 * From ap_purchase_order
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.gl.component;


import classinterface.NavigatorFormInt;
import common.component.FrmMainFrame;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import jdbc.DbBean;

import kopkar.gl.objectclasses.gl_kalender_detail1ext;
import kopkar.gl.objectclasses.gl_kalenderext;
import kopkar.gl.objectclasses.gl_kalenderextcol;
import kopkar.gl.objectclasses.gl_transaksi_rab_detail1ext;
import kopkar.gl.objectclasses.gl_transaksi_rab_detail1extcol;
import kopkar.gl.objectclasses.gl_transaksi_rabext;
import kopkar.gl.objectclasses.gl_rabext;
import kopkar.utils.browsecontroller;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.kazao.calendar.KazaoCalendarDateTimeException;
import utils.CodeException;
import utils.GlobalModel;
import utils.GlobalUtils;
import utils.appsettinghandler;
import utils.selectallJTable;

/**
 *
 * @author  Generator
 */

public class Frmgl_transaksi_rab extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmap_purchase_order";
    
    FrmMainFrame mf ;

    gl_transaksi_rabext obj=new gl_transaksi_rabext();
    gl_transaksi_rab_detail1extcol appods;
    browsecontroller obrowse=new browsecontroller();
    
    DefaultTableModel model=null;
    private gl_transaksi_rabext objtmp;
    private JasperReport jasperReport;
    DbBean db=appsettinghandler.db;
    private JasperPrint jasperPrint;
   
    /** Creates new form Area */
    public Frmgl_transaksi_rab() throws CodeException {
        initComponents();
    }
    
    public Frmgl_transaksi_rab(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();

        model=(DefaultTableModel) jtbldetail.getModel();

        showtahun();
        showbulan();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowseDocument_Number = new javax.swing.JButton();
        jlbldocument_number = new javax.swing.JLabel();
        jtxtdocument_number = new javax.swing.JTextField();
        jlbldocument_status = new javax.swing.JLabel();
        jtxtdocument_status = new javax.swing.JTextField();
        jlbldocument_date = new javax.swing.JLabel();
        jlblreference = new javax.swing.JLabel();
        jtxtreference = new javax.swing.JTextField();
        jlbldscription = new javax.swing.JLabel();
        jtxtdscription = new javax.swing.JTextField();
        jlbltotal_bfr_discount = new javax.swing.JLabel();
        jtxtrab_entry = new javax.swing.JTextField();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();
        jlblsupplier_code1 = new javax.swing.JLabel();
        jlblsupplier_code2 = new javax.swing.JLabel();
        kzodocument_date = new org.kazao.calendar.KazaoCalendarDate();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbldetail = new selectallJTable(model);
        jlbltotal_bfr_discount1 = new javax.swing.JLabel();
        jtxtrab_amount = new javax.swing.JTextField();
        jlblsupplier_code3 = new javax.swing.JLabel();
        jcmbmop = new javax.swing.JComboBox();
        jcmbyop = new javax.swing.JComboBox();
        jopt_complete_status_draff = new javax.swing.JRadioButton();
        jopt_complete_status_complete = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entry RAB");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Entry RAB");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 200, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 46, 750, 10);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jbtnBrowseDocument_Number.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowseDocument_Number.setText("...");
        jbtnBrowseDocument_Number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseDocument_NumberActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowseDocument_Number);
        jbtnBrowseDocument_Number.setBounds(1030, 80, 30, 17);

        jlbldocument_number.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_number.setText("No. Dokumen");
        getContentPane().add(jlbldocument_number);
        jlbldocument_number.setBounds(690, 80, 140, 13);

        jtxtdocument_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdocument_number.setText("document_number");
        jtxtdocument_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocument_numberFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdocument_number);
        jtxtdocument_number.setBounds(880, 80, 150, 23);

        jlbldocument_status.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_status.setText("Status");
        getContentPane().add(jlbldocument_status);
        jlbldocument_status.setBounds(690, 60, 140, 13);

        jtxtdocument_status.setEditable(false);
        jtxtdocument_status.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdocument_status.setText("document_status");
        jtxtdocument_status.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocument_statusFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdocument_status);
        jtxtdocument_status.setBounds(880, 60, 150, 23);

        jlbldocument_date.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldocument_date.setText("Tgl. Dokumen");
        getContentPane().add(jlbldocument_date);
        jlbldocument_date.setBounds(690, 100, 140, 13);

        jlblreference.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblreference.setText("Referensi");
        getContentPane().add(jlblreference);
        jlblreference.setBounds(70, 410, 140, 13);

        jtxtreference.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtreference.setText("reference");
        jtxtreference.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtreferenceFocusGained(evt);
            }
        });
        getContentPane().add(jtxtreference);
        jtxtreference.setBounds(260, 410, 270, 23);

        jlbldscription.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbldscription.setText("Keterangan");
        getContentPane().add(jlbldscription);
        jlbldscription.setBounds(70, 430, 140, 13);

        jtxtdscription.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdscription.setText("dscription");
        jtxtdscription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdscriptionFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdscription);
        jtxtdscription.setBounds(260, 430, 270, 23);

        jlbltotal_bfr_discount.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltotal_bfr_discount.setText("Jumlah Entry");
        getContentPane().add(jlbltotal_bfr_discount);
        jlbltotal_bfr_discount.setBounds(690, 140, 140, 13);

        jtxtrab_entry.setEditable(false);
        jtxtrab_entry.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtrab_entry.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtrab_entry.setText("rab_entry");
        jtxtrab_entry.setFocusable(false);
        getContentPane().add(jtxtrab_entry);
        jtxtrab_entry.setBounds(880, 140, 150, 23);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(620, 30, 170, 20);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(790, 30, 130, 20);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(920, 30, 140, 20);

        jlblsupplier_code1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsupplier_code1.setText("Periode");
        getContentPane().add(jlblsupplier_code1);
        jlblsupplier_code1.setBounds(70, 80, 140, 13);

        jlblsupplier_code2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsupplier_code2.setText("Bulan");
        getContentPane().add(jlblsupplier_code2);
        jlblsupplier_code2.setBounds(70, 120, 140, 13);

        kzodocument_date.setFont(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date.setFontDate(new java.awt.Font("Dialog", 0, 10));
        kzodocument_date.setOpaque(false);
        getContentPane().add(kzodocument_date);
        kzodocument_date.setBounds(880, 100, 100, 20);

        jtbldetail.setFont(new java.awt.Font("Dialog", 0, 10));
        jtbldetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode RAB", "Nama / Keterangan RAB", "Jumlah", "Referensi", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbldetail.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtbldetail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtbldetail.setSurrendersFocusOnKeystroke(true);
        jtbldetail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtbldetailFocusGained(evt);
            }
        });
        jtbldetail.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtbldetailPropertyChange(evt);
            }
        });
        jtbldetail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbldetailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtbldetailKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtbldetail);
        jtbldetail.getColumnModel().getColumn(0).setMinWidth(50);
        jtbldetail.getColumnModel().getColumn(0).setPreferredWidth(50);
        jtbldetail.getColumnModel().getColumn(0).setMaxWidth(50);
        jtbldetail.getColumnModel().getColumn(1).setMinWidth(120);
        jtbldetail.getColumnModel().getColumn(1).setPreferredWidth(120);
        jtbldetail.getColumnModel().getColumn(1).setMaxWidth(120);
        jtbldetail.getColumnModel().getColumn(2).setMinWidth(350);
        jtbldetail.getColumnModel().getColumn(2).setPreferredWidth(200);
        jtbldetail.getColumnModel().getColumn(2).setMaxWidth(200);
        jtbldetail.getColumnModel().getColumn(4).setMinWidth(150);
        jtbldetail.getColumnModel().getColumn(5).setMinWidth(220);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 190, 990, 220);

        jlbltotal_bfr_discount1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbltotal_bfr_discount1.setText("Jumlah Total");
        getContentPane().add(jlbltotal_bfr_discount1);
        jlbltotal_bfr_discount1.setBounds(690, 160, 140, 13);

        jtxtrab_amount.setEditable(false);
        jtxtrab_amount.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtrab_amount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtrab_amount.setText("rab_amount");
        jtxtrab_amount.setFocusable(false);
        jtxtrab_amount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtrab_amountFocusGained(evt);
            }
        });
        getContentPane().add(jtxtrab_amount);
        jtxtrab_amount.setBounds(880, 160, 150, 23);

        jlblsupplier_code3.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblsupplier_code3.setText("Tahun");
        getContentPane().add(jlblsupplier_code3);
        jlblsupplier_code3.setBounds(70, 100, 140, 13);

        jcmbmop.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbmop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jcmbmop);
        jcmbmop.setBounds(260, 110, 160, 20);

        jcmbyop.setFont(new java.awt.Font("Dialog", 1, 10));
        jcmbyop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmbyop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbyopItemStateChanged(evt);
            }
        });
        getContentPane().add(jcmbyop);
        jcmbyop.setBounds(260, 90, 80, 20);

        buttonGroup1.add(jopt_complete_status_draff);
        jopt_complete_status_draff.setFont(new java.awt.Font("Dialog", 0, 10));
        jopt_complete_status_draff.setSelected(true);
        jopt_complete_status_draff.setText("Draff");
        getContentPane().add(jopt_complete_status_draff);
        jopt_complete_status_draff.setBounds(70, 460, 52, 24);

        buttonGroup1.add(jopt_complete_status_complete);
        jopt_complete_status_complete.setFont(new java.awt.Font("Dialog", 0, 10));
        jopt_complete_status_complete.setText("Complete");
        getContentPane().add(jopt_complete_status_complete);
        jopt_complete_status_complete.setBounds(150, 460, 123, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jbtnBrowseDocument_NumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseDocument_NumberActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.gl_transaksi_rab, "", jtxtdocument_number);
        try {
            if (!jtxtdocument_number.getText().equalsIgnoreCase("")){
                obj.initdata(jtxtdocument_number.getText());
                showData();
            }
        } catch (CodeException ex) {
            Logger.getLogger(Frmgl_transaksi_rab.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}//GEN-LAST:event_jbtnBrowseDocument_NumberActionPerformed

private void jtbldetailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtbldetailFocusGained
    // TODO add your handling code here:
    if (jtbldetail.getRowCount()==0){
        insertnewlastrow();
    }
}//GEN-LAST:event_jtbldetailFocusGained

private void jtbldetailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbldetailKeyPressed
    // TODO add your handling code here:
    int col=jtbldetail.getSelectedColumn();
    int row=jtbldetail.getSelectedRow();
    switch (evt.getKeyCode()){
        case KeyEvent.VK_F5:
            evt.consume();
            switch (jtbldetail.getSelectedColumn()){
                case 1:
                    obrowse.showbrowser(obrowse.gl_rab, "", jtbldetail);
                    showrab((Integer)jtbldetail.getSelectedRow());
                    jtbldetailPropertyChange(null);
                    GlobalUtils.selectCellTable(jtbldetail, row, 3);
                    break;
            }
            break;
        case KeyEvent.VK_INSERT:
            evt.consume();
            insertnewlastrow();
            break;
        case KeyEvent.VK_DELETE:
            evt.consume();
            if (jtbldetail.getSelectedRow()<appods.size()){
            gl_transaksi_rab_detail1ext o = appods.get(jtbldetail.getSelectedRow());
                o.setstatus(gl_transaksi_rab_detail1ext.Status_delete);
            }
            jtbldetailPropertyChange(null);
            break;
        case KeyEvent.VK_ENTER:
            evt.consume();
            break;
    }
}//GEN-LAST:event_jtbldetailKeyPressed

private void jtbldetailPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtbldetailPropertyChange
    // TODO add your handling code here:
    int irow=jtbldetail.getSelectedRow();
    int icol=jtbldetail.getSelectedColumn();

    if (irow>-1){
        switch (icol){
            case 1:
                showrab(irow);
                break;
        }
        cekdetail();
        obj.calculatetotal();
        jtxtrab_entry.setText(GlobalUtils.formatnumber(obj.getrab_entry()));
        jtxtrab_amount.setText(GlobalUtils.formatnumber(obj.getrab_amount()));
    }
}//GEN-LAST:event_jtbldetailPropertyChange

private void jtbldetailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbldetailKeyReleased
        int col=jtbldetail.getSelectedColumn();
        int row=jtbldetail.getSelectedRow();
    // TODO add your handling code here:
        if (evt.getKeyCode()==evt.VK_ENTER&&row>-1){
            switch (col){
                case 1:
                    showrab(row);
                    jtbldetailPropertyChange(null);
                    GlobalUtils.selectCellTable(jtbldetail, row, 3);
                    break;
                case 6:
                    insertnewlastrow();
                    break;
                default:
                    if (col<model.getColumnCount()-1){
                        GlobalUtils.selectCellTable(jtbldetail, row, col+1);
                    } else {
                        insertnewlastrow();
                    }
                    break;
            }
        }
}//GEN-LAST:event_jtbldetailKeyReleased

private void jtxtrab_amountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtrab_amountFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtrab_amountFocusGained

private void jcmbyopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbyopItemStateChanged
    // TODO add your handling code here:
    showbulan();
}//GEN-LAST:event_jcmbyopItemStateChanged
                         

private void jtxtdocument_numberFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtdocument_number.setSelectionStart(0);
    jtxtdocument_number.setSelectionEnd(jtxtdocument_number.getText().length());
}                                               

private void jtxtdocument_statusFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtdocument_status.setSelectionStart(0);
    jtxtdocument_status.setSelectionEnd(jtxtdocument_status.getText().length());
}                                                                                           

private void jtxtreferenceFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    jtxtreference.setSelectionStart(0);
    jtxtreference.setSelectionEnd(jtxtreference.getText().length());
}                                         

private void jtxtdscriptionFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
    jtxtdscription.setSelectionStart(0);
    jtxtdscription.setSelectionEnd(jtxtdscription.getText().length());
}                                                                                    

private void jtxttotal_bfr_discountFocusGained(java.awt.event.FocusEvent evt) {                                                
        // TODO add your handling code here:
    jtxtrab_entry.setSelectionStart(0);
    jtxtrab_entry.setSelectionEnd(jtxtrab_entry.getText().length());
}                                                  


private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

                                                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmgl_transaksi_rab().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowseDocument_Number;
    private javax.swing.JComboBox jcmbmop;
    private javax.swing.JComboBox jcmbyop;
    private javax.swing.JLabel jlbldocument_date;
    private javax.swing.JLabel jlbldocument_number;
    private javax.swing.JLabel jlbldocument_status;
    private javax.swing.JLabel jlbldscription;
    private javax.swing.JLabel jlblreference;
    private javax.swing.JLabel jlblsupplier_code1;
    private javax.swing.JLabel jlblsupplier_code2;
    private javax.swing.JLabel jlblsupplier_code3;
    private javax.swing.JLabel jlbltotal_bfr_discount;
    private javax.swing.JLabel jlbltotal_bfr_discount1;
    private javax.swing.JRadioButton jopt_complete_status_complete;
    private javax.swing.JRadioButton jopt_complete_status_draff;
    private javax.swing.JTable jtbldetail;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtdocument_number;
    private javax.swing.JTextField jtxtdocument_status;
    private javax.swing.JTextField jtxtdscription;
    private javax.swing.JTextField jtxtrab_amount;
    private javax.swing.JTextField jtxtrab_entry;
    private javax.swing.JTextField jtxtreference;
    private org.kazao.calendar.KazaoCalendarDate kzodocument_date;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jtxtdocument_number.setText("");
        jtxtdocument_status.setText("Open");
        try {
            kzodocument_date.setDate(GlobalUtils.getCurrentDate());
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmgl_transaksi_rab.class.getName()).log(Level.SEVERE, null, ex);
        }
        jopt_complete_status_draff.setSelected(true);
        jtxtreference.setText("");
        jtxtdscription.setText("");
        jtxtrab_entry.setText("");
        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");

        GlobalModel.clearRow(model);

        if (jtbldetail.getRowCount()==0){
            insertnewlastrow();
        }
    }

    public void newData() throws CodeException {
        istatus=1;
        objtmp=obj;
        obj=new gl_transaksi_rabext();
        obj.setyop(GlobalUtils.getYear(GlobalUtils.sessiondate));
        obj.setmop(GlobalUtils.getMonth(GlobalUtils.sessiondate));
        showData();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.update();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        jtxtdocument_number.setText(obj.getdocument_number());
        try {
            kzodocument_date.setDate(GlobalUtils.formatDate(obj.getdocument_date(),"MM/dd/yyyy"));
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmgl_transaksi_rab.class.getName()).log(Level.SEVERE, null, ex);
        }

        jcmbyop.setSelectedItem(obj.getyop());
        jcmbmop.setSelectedIndex(obj.getmop()-1);
        
        jtxtreference.setText(obj.getreference());
        jtxtdscription.setText(obj.getdscription());
        jtxtrab_entry.setText(GlobalUtils.formatnumber(obj.getrab_entry()));
        jtxtrab_amount.setText(GlobalUtils.formatnumber(obj.getrab_amount()));

        jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getentrydate()));
        jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getauditdate()));
        jtxtUserID.setText(obj.getaudituser());

        jtxtdocument_status.setText(obj.getDocument_status_desc());

        if (obj.getcomplete_status().equalsIgnoreCase("Y")){
            jopt_complete_status_complete.setSelected(true);
        } else {
            jopt_complete_status_draff.setSelected(true);
        }
        appods=obj.getDetail1();
        
        GlobalModel.clearRow(model);

        if (jtbldetail.getRowCount()==0){
            insertnewlastrow();
        }
        int i=0;
        for (i=0;i<appods.size();i++){
            gl_transaksi_rab_detail1ext appod = appods.get(i);
            model.setValueAt(i+1, i, 0);
            model.setValueAt(appod.getkode_rab(), i, 1);
            model.setValueAt(appod.getnama_rab(), i, 2);


            model.setValueAt(appod.getjumlah(), i, 3);

            model.setValueAt(appod.getreferensi(), i, 4);
            model.setValueAt(appod.getketerangan(), i, 5);
            
            insertnewlastrow();
        }
        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        if (obj.delete()){
            obj.moveNext();
            showData();
        }
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);
//        if (obj.getdocument_status().equalsIgnoreCase("C")){
//            mf.setToolBar(iformtype,7);
//        }
        if (istatus==1){
            jbtnBrowseDocument_Number.setEnabled(false);
        } else {
            jbtnBrowseDocument_Number.setEnabled(true);
        }
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }
        obj.setdocument_number(jtxtdocument_number.getText());
        obj.setyop(GlobalUtils.toInt(GlobalUtils.churuf(jcmbyop.getSelectedItem())));
        obj.setmop(jcmbmop.getSelectedIndex()+1);
        obj.setdocument_date(kzodocument_date.getDate());
        
        obj.setreference(jtxtreference.getText());
        obj.setdscription(jtxtdscription.getText());
        obj.setrab_entry(GlobalUtils.toInt(jtxtrab_entry.getText()));
        obj.setrab_amount(GlobalUtils.toDbl(jtxtrab_amount.getText()));

        if (jopt_complete_status_draff.isSelected()){
            obj.setcomplete_status("N");
        } else {
            obj.setcomplete_status("Y");
        }
    }

    public void undo() throws CodeException {
        istatus = 0;
        obj=objtmp;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
        Map parameter = new HashMap();


        parameter.put("document_date_fr", obj.getdocument_date());
        parameter.put("document_date_to", obj.getdocument_date());
        parameter.put("document_number_fr", obj.getdocument_number());
        parameter.put("document_number_to", obj.getdocument_number());
        parameter.put("audituser", GlobalUtils.getUserId());


        // Versi 1
        String file ="";
        String rptFile="RTKK-01.jrxml";
        if(GlobalUtils.getAppDir()){
            try{
                file = GlobalUtils.getCurrentDir() +"/Reports/"+rptFile;
                jasperReport = JasperCompileManager.compileReport(file);
                //System.out.println("file: "+file);
                System.out.println("isi parameter Report PO:"+parameter);
                jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, db.getConnection());
                JasperViewer.viewReport(jasperPrint, false);
        }catch (Exception e) {
            e.printStackTrace();
        }
            }
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    private void insertnewlastrow() {
        if (!lastrowisempty()){
        model.addRow(new Object[model.getColumnCount()]);
        model.setValueAt(model.getRowCount(), model.getRowCount()-1, 0);
        model.setValueAt(0, model.getRowCount()-1, 3);
        model.setValueAt(0, model.getRowCount()-1, 4);
        
        GlobalUtils.selectCellTable(jtbldetail, model.getRowCount()-1, 1);
        } else {
            GlobalUtils.selectCellTable(jtbldetail, model.getRowCount()-1, 1);
        }
    }

    private void cekdetail() {
        int row = jtbldetail.getSelectedRow();
        int col = jtbldetail.getSelectedColumn();


        gl_transaksi_rab_detail1ext appod=new gl_transaksi_rab_detail1ext();
        if (row > appods.size() - 1) {
            appod = new gl_transaksi_rab_detail1ext();
            appod.setstatus(gl_transaksi_rab_detail1ext.Status_Insert);
            appods.add(appod);
        } else {
            appod = (gl_transaksi_rab_detail1ext) appods.get(row);
            if (!appod.getstatus().equals(gl_transaksi_rab_detail1ext.Status_Insert)&&!appod.getstatus().equals(gl_transaksi_rab_detail1ext.Status_delete)){
                appod.setstatus(gl_transaksi_rab_detail1ext.Status_update);
            }
        }

        appod.setkode_rab(GlobalUtils.churuf(model.getValueAt(row, 1)));
        
        appod.setjumlah(GlobalUtils.toDbl(GlobalUtils.churuf(model.getValueAt(row, 3))));
        appod.setreferensi(GlobalUtils.churuf(model.getValueAt(row, 4)));
        appod.setketerangan(GlobalUtils.churuf(model.getValueAt(row, 5)));

        
        appods.set(row, appod);

    }


    private boolean lastrowisempty() {
        if (model.getRowCount()>0){
            if (GlobalUtils.churuf(model.getValueAt(model.getRowCount()-1, 1)).equalsIgnoreCase("")){
                return true;
            }
        }
        return false;
    }

    private void showtahun() {
        gl_kalenderextcol okal=new gl_kalenderextcol();
        try {
            okal.initdata();
            jcmbyop.removeAllItems();
            for (int i=0;i<okal.size();i++){
                gl_kalenderext o = okal.get(i);
                jcmbyop.addItem(o.getyop());
            }
            jcmbyop.setSelectedItem(GlobalUtils.toInt(GlobalUtils.formatDate(GlobalUtils.sessiondate,"yyyy")));
        } catch (SQLException ex) {
            Logger.getLogger(Frmgl_transaksi_rab.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void showbulan() {
        gl_kalenderext okal=new gl_kalenderext();
        gl_kalender_detail1ext o;
        try {
            jcmbmop.removeAllItems();
            if (jcmbyop.getItemCount()>0&&jcmbyop.getSelectedIndex()>-1){
                if (okal.initdata((Integer) jcmbyop.getSelectedItem())) {
                    for (int i = 0; i < okal.getDetail1().size(); i++) {
                        o=okal.getDetail1().get(i);
                        jcmbmop.addItem(GlobalUtils.getMonthName(o.getmop()));
                    }
                }
                jcmbmop.setSelectedItem(GlobalUtils.getMonthName(GlobalUtils.toInt(GlobalUtils.formatDate(GlobalUtils.sessiondate,"MM"))));
            }
        } catch (CodeException ex) {
            Logger.getLogger(Frmgl_transaksi_rab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void showrab(Integer row) {
        gl_rabext orab=new gl_rabext();
        String koderab=GlobalUtils.churuf(model.getValueAt(row, 1));
        try {
            if (orab.initdata(koderab)) {
                model.setValueAt(orab.getkode_rab(), row, 1);
                model.setValueAt(orab.getnama_rab(), row, 2);
            }
        } catch (CodeException ex) {
            Logger.getLogger(Frmgl_transaksi_rab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
}
