/*
 * From gl_group_data_entry
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.gl.component;


import classinterface.NavigatorFormInt;
import common.component.FrmBrowseData;
import common.component.FrmMainFrame;
import kopkar.gl.objectclasses.gl_group_data_entryext;
import java.util.logging.Level;
import java.util.logging.Logger;
import kopkar.utils.browsecontroller;
import utils.CodeException;
import utils.GlobalUtils;

/**
 *
 * @author  Generator
 */

public class Frmgl_group_data_entry extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmgl_group_data_entry";
    
    FrmMainFrame mf ;

    gl_group_data_entryext obj=new gl_group_data_entryext();
   
    /** Creates new form Area */
    public Frmgl_group_data_entry() throws CodeException {
        initComponents();
    }
    
    public Frmgl_group_data_entry(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();
        jlblkode_gde = new javax.swing.JLabel();
        jtxtkode_gde = new javax.swing.JTextField();
        jlblnama_gde = new javax.swing.JLabel();
        jtxtnama_gde = new javax.swing.JTextField();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();
        jlblkode_gde1 = new javax.swing.JLabel();
        jtxtdayend_no = new javax.swing.JTextField();
        jlblkode_gde2 = new javax.swing.JLabel();
        jtxtdayend_date = new javax.swing.JTextField();
        jtxtdayend_user = new javax.swing.JTextField();
        jlblkode_gde3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Master Group Data Entry");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Master Group Data Entry");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 200, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(420, 100, 30, 17);

        jlblkode_gde.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblkode_gde.setText("Kode Grup Data Entri");
        getContentPane().add(jlblkode_gde);
        jlblkode_gde.setBounds(70, 100, 140, 13);

        jtxtkode_gde.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtkode_gde.setText("kode_gde");
        jtxtkode_gde.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtkode_gdeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtkode_gde);
        jtxtkode_gde.setBounds(260, 100, 150, 23);

        jlblnama_gde.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblnama_gde.setText("Keterangan");
        getContentPane().add(jlblnama_gde);
        jlblnama_gde.setBounds(70, 120, 140, 13);

        jtxtnama_gde.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtnama_gde.setText("nama_gde");
        jtxtnama_gde.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtnama_gdeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtnama_gde);
        jtxtnama_gde.setBounds(260, 120, 260, 23);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(360, 30, 170, 20);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(530, 30, 130, 20);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(660, 30, 140, 20);

        jlblkode_gde1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblkode_gde1.setText("Day End Seq No.");
        getContentPane().add(jlblkode_gde1);
        jlblkode_gde1.setBounds(70, 160, 140, 13);

        jtxtdayend_no.setEditable(false);
        jtxtdayend_no.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtdayend_no.setText("dayend_no");
        jtxtdayend_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtdayend_noActionPerformed(evt);
            }
        });
        jtxtdayend_no.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdayend_noFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdayend_no);
        jtxtdayend_no.setBounds(260, 160, 150, 23);

        jlblkode_gde2.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblkode_gde2.setText("Terakhir Process");
        getContentPane().add(jlblkode_gde2);
        jlblkode_gde2.setBounds(70, 180, 140, 13);

        jtxtdayend_date.setEditable(false);
        jtxtdayend_date.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdayend_date.setText("dayend_date");
        jtxtdayend_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtdayend_dateActionPerformed(evt);
            }
        });
        jtxtdayend_date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdayend_dateFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdayend_date);
        jtxtdayend_date.setBounds(260, 180, 150, 23);

        jtxtdayend_user.setEditable(false);
        jtxtdayend_user.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdayend_user.setText("dayend_user");
        jtxtdayend_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdayend_userFocusGained(evt);
            }
        });
        getContentPane().add(jtxtdayend_user);
        jtxtdayend_user.setBounds(260, 200, 150, 23);

        jlblkode_gde3.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblkode_gde3.setText("User");
        getContentPane().add(jlblkode_gde3);
        jlblkode_gde3.setBounds(70, 200, 140, 13);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
    // TODO add your handling code here:
    browsecontroller obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.gl_group_data_entry, "", jtxtkode_gde);
    if (!jtxtkode_gde.getText().equalsIgnoreCase("")){
            try {
                if (obj.initdata(jtxtkode_gde.getText())) {
                    showData();
                }
            } catch (CodeException ex) {
                Logger.getLogger(Frmgl_group_data_entry.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
}//GEN-LAST:event_jbtnBrowseActionPerformed

private void jtxtdayend_noFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdayend_noFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdayend_noFocusGained

private void jtxtdayend_dateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdayend_dateFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdayend_dateFocusGained

private void jtxtdayend_userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdayend_userFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdayend_userFocusGained

private void jtxtdayend_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtdayend_noActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdayend_noActionPerformed

private void jtxtdayend_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtdayend_dateActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtdayend_dateActionPerformed

private void jtxtkode_gdeFocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtkode_gde.setSelectionStart(0);
    jtxtkode_gde.setSelectionEnd(jtxtkode_gde.getText().length());
}                                        

private void jtxtnama_gdeFocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtnama_gde.setSelectionStart(0);
    jtxtnama_gde.setSelectionEnd(jtxtnama_gde.getText().length());
}                                        

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmgl_group_data_entry().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JLabel jlblkode_gde;
    private javax.swing.JLabel jlblkode_gde1;
    private javax.swing.JLabel jlblkode_gde2;
    private javax.swing.JLabel jlblkode_gde3;
    private javax.swing.JLabel jlblnama_gde;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtdayend_date;
    private javax.swing.JTextField jtxtdayend_no;
    private javax.swing.JTextField jtxtdayend_user;
    private javax.swing.JTextField jtxtkode_gde;
    private javax.swing.JTextField jtxtnama_gde;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jtxtkode_gde.setText("");
        jtxtnama_gde.setText("");
        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");
    }

    public void newData() throws CodeException {
        istatus=1;
        clearfield();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.update();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        jtxtkode_gde.setText(obj.getkode_gde());
        jtxtnama_gde.setText(obj.getnama_gde());

        jtxtdayend_no.setText(GlobalUtils.churuf(obj.getdayend_no()));
        jtxtdayend_date.setText(obj.getdayend_date());
        jtxtdayend_user.setText(obj.getdayend_user());

        jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getentrydate()));
        jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getauditdate()));
        jtxtUserID.setText(obj.getaudituser());

        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        if (obj.delete()){
            obj.moveNext();
            showData();
        }
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);

        if (istatus==1){
            jbtnBrowse.setEnabled(false);
        } else {
            jbtnBrowse.setEnabled(true);
        }
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }
        obj.setkode_gde(jtxtkode_gde.getText());
        obj.setnama_gde(jtxtnama_gde.getText());

        
    }

    public void undo() throws CodeException {
        istatus = 0;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    
}
