/*
 * From gl_option
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.gl.component;


import classinterface.NavigatorFormInt;
import common.component.FrmBrowseData;
import common.component.FrmMainFrame;
import kopkar.gl.objectclasses.gl_optionext;
import java.util.logging.Level;
import java.util.logging.Logger;
import kopkar.utils.browsecontroller;
import utils.CodeException;
import utils.GlobalUtils;

/**
 *
 * @author  Generator
 */

public class Frmgl_option extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmgl_option";
    
    FrmMainFrame mf ;

    gl_optionext obj=new gl_optionext();
    browsecontroller obrowse=new browsecontroller();
   
    /** Creates new form Area */
    public Frmgl_option() throws CodeException {
        initComponents();
    }
    
    public Frmgl_option(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jlblcompany_id = new javax.swing.JLabel();
        jtxtcompany_id = new javax.swing.JTextField();
        jlblcompany_name = new javax.swing.JLabel();
        jtxtcompany_name = new javax.swing.JTextField();
        jlblactive_sts = new javax.swing.JLabel();
        jtxtactive_sts = new javax.swing.JTextField();
        jlbladdress1 = new javax.swing.JLabel();
        jtxtaddress1 = new javax.swing.JTextField();
        jtxtaddress2 = new javax.swing.JTextField();
        jlblcity = new javax.swing.JLabel();
        jtxtcity = new javax.swing.JTextField();
        jlblstate = new javax.swing.JLabel();
        jtxtstate = new javax.swing.JTextField();
        jlblzipcode = new javax.swing.JLabel();
        jtxtzipcode = new javax.swing.JTextField();
        jlblphone = new javax.swing.JLabel();
        jtxtphone = new javax.swing.JTextField();
        jlblfaximale = new javax.swing.JLabel();
        jtxtfaximale = new javax.swing.JTextField();
        jlblemail = new javax.swing.JLabel();
        jtxtemail = new javax.swing.JTextField();
        jlblpic = new javax.swing.JLabel();
        jtxtpic = new javax.swing.JTextField();
        jlblregister_date = new javax.swing.JLabel();
        jtxtregister_date = new javax.swing.JTextField();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();
        jlblprice_code = new javax.swing.JLabel();
        jtxtkode_gde = new javax.swing.JTextField();
        jbtnprice_code = new javax.swing.JButton();
        jtxtnama_gde = new javax.swing.JTextField();
        jlblprice_code1 = new javax.swing.JLabel();
        joptgabung_gde_N = new javax.swing.JRadioButton();
        joptgabung_gde_Y = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("gl_option");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : gl_option");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 200, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jlblcompany_id.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcompany_id.setText("Kode Instansi");
        getContentPane().add(jlblcompany_id);
        jlblcompany_id.setBounds(70, 117, 140, 13);

        jtxtcompany_id.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcompany_id.setText("company_id");
        jtxtcompany_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcompany_idFocusGained(evt);
            }
        });
        getContentPane().add(jtxtcompany_id);
        jtxtcompany_id.setBounds(260, 117, 150, 23);

        jlblcompany_name.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcompany_name.setText("Nama");
        getContentPane().add(jlblcompany_name);
        jlblcompany_name.setBounds(70, 134, 140, 13);

        jtxtcompany_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcompany_name.setText("company_name");
        jtxtcompany_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcompany_nameFocusGained(evt);
            }
        });
        getContentPane().add(jtxtcompany_name);
        jtxtcompany_name.setBounds(260, 134, 360, 23);

        jlblactive_sts.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblactive_sts.setText("active_sts");
        getContentPane().add(jlblactive_sts);
        jlblactive_sts.setBounds(70, 151, 140, 13);

        jtxtactive_sts.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtactive_sts.setText("active_sts");
        jtxtactive_sts.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtactive_stsFocusGained(evt);
            }
        });
        getContentPane().add(jtxtactive_sts);
        jtxtactive_sts.setBounds(260, 151, 150, 23);

        jlbladdress1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbladdress1.setText("Alamat");
        getContentPane().add(jlbladdress1);
        jlbladdress1.setBounds(70, 168, 140, 13);

        jtxtaddress1.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaddress1.setText("address1");
        jtxtaddress1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtaddress1FocusGained(evt);
            }
        });
        getContentPane().add(jtxtaddress1);
        jtxtaddress1.setBounds(260, 168, 360, 23);

        jtxtaddress2.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaddress2.setText("address2");
        jtxtaddress2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtaddress2FocusGained(evt);
            }
        });
        getContentPane().add(jtxtaddress2);
        jtxtaddress2.setBounds(260, 185, 360, 23);

        jlblcity.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcity.setText("city");
        getContentPane().add(jlblcity);
        jlblcity.setBounds(70, 202, 140, 13);

        jtxtcity.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcity.setText("city");
        jtxtcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcityFocusGained(evt);
            }
        });
        getContentPane().add(jtxtcity);
        jtxtcity.setBounds(260, 202, 360, 23);

        jlblstate.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblstate.setText("Propinsi");
        getContentPane().add(jlblstate);
        jlblstate.setBounds(70, 219, 140, 13);

        jtxtstate.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtstate.setText("state");
        jtxtstate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtstateFocusGained(evt);
            }
        });
        getContentPane().add(jtxtstate);
        jtxtstate.setBounds(260, 219, 360, 23);

        jlblzipcode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblzipcode.setText("zipcode");
        getContentPane().add(jlblzipcode);
        jlblzipcode.setBounds(70, 236, 140, 13);

        jtxtzipcode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtzipcode.setText("zipcode");
        jtxtzipcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtzipcodeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtzipcode);
        jtxtzipcode.setBounds(260, 236, 150, 23);

        jlblphone.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblphone.setText("phone");
        getContentPane().add(jlblphone);
        jlblphone.setBounds(70, 253, 140, 13);

        jtxtphone.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtphone.setText("phone");
        jtxtphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtphoneFocusGained(evt);
            }
        });
        getContentPane().add(jtxtphone);
        jtxtphone.setBounds(260, 253, 150, 23);

        jlblfaximale.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblfaximale.setText("faximale");
        getContentPane().add(jlblfaximale);
        jlblfaximale.setBounds(70, 270, 140, 13);

        jtxtfaximale.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtfaximale.setText("faximale");
        jtxtfaximale.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtfaximaleFocusGained(evt);
            }
        });
        getContentPane().add(jtxtfaximale);
        jtxtfaximale.setBounds(260, 270, 360, 23);

        jlblemail.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblemail.setText("email");
        getContentPane().add(jlblemail);
        jlblemail.setBounds(70, 287, 140, 13);

        jtxtemail.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtemail.setText("email");
        jtxtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtemailFocusGained(evt);
            }
        });
        getContentPane().add(jtxtemail);
        jtxtemail.setBounds(260, 287, 360, 23);

        jlblpic.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblpic.setText("pic");
        getContentPane().add(jlblpic);
        jlblpic.setBounds(70, 304, 140, 13);

        jtxtpic.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtpic.setText("pic");
        jtxtpic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtpicFocusGained(evt);
            }
        });
        getContentPane().add(jtxtpic);
        jtxtpic.setBounds(260, 304, 360, 23);

        jlblregister_date.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblregister_date.setText("Register Date");
        getContentPane().add(jlblregister_date);
        jlblregister_date.setBounds(70, 321, 140, 13);

        jtxtregister_date.setEditable(false);
        jtxtregister_date.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtregister_date.setText("register_date");
        jtxtregister_date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtregister_dateFocusGained(evt);
            }
        });
        getContentPane().add(jtxtregister_date);
        jtxtregister_date.setBounds(260, 321, 150, 23);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(360, 30, 170, 20);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(530, 30, 130, 20);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(660, 30, 140, 20);

        jlblprice_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblprice_code.setText("Format Jurnal Entry");
        getContentPane().add(jlblprice_code);
        jlblprice_code.setBounds(70, 400, 140, 13);

        jtxtkode_gde.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtkode_gde.setText("kode_gde");
        getContentPane().add(jtxtkode_gde);
        jtxtkode_gde.setBounds(260, 370, 90, 23);

        jbtnprice_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnprice_code.setText("...");
        jbtnprice_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnprice_codeActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnprice_code);
        jbtnprice_code.setBounds(350, 370, 30, 17);

        jtxtnama_gde.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtnama_gde.setText("nama_gde");
        jtxtnama_gde.setFocusable(false);
        getContentPane().add(jtxtnama_gde);
        jtxtnama_gde.setBounds(390, 370, 280, 23);

        jlblprice_code1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblprice_code1.setText("Sumber Data");
        getContentPane().add(jlblprice_code1);
        jlblprice_code1.setBounds(70, 370, 140, 13);

        buttonGroup1.add(joptgabung_gde_N);
        joptgabung_gde_N.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        joptgabung_gde_N.setText("Rinci");
        getContentPane().add(joptgabung_gde_N);
        joptgabung_gde_N.setBounds(390, 400, 123, 24);

        buttonGroup1.add(joptgabung_gde_Y);
        joptgabung_gde_Y.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        joptgabung_gde_Y.setSelected(true);
        joptgabung_gde_Y.setText("Gabung");
        getContentPane().add(joptgabung_gde_Y);
        joptgabung_gde_Y.setBounds(260, 400, 64, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jbtnprice_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnprice_codeActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.gl_group_data_entry, "", jtxtkode_gde,jtxtnama_gde);
}//GEN-LAST:event_jbtnprice_codeActionPerformed
                                 

private void jtxtcompany_idFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
    jtxtcompany_id.setSelectionStart(0);
    jtxtcompany_id.setSelectionEnd(jtxtcompany_id.getText().length());
}                                          

private void jtxtcompany_nameFocusGained(java.awt.event.FocusEvent evt) {                                          
        // TODO add your handling code here:
    jtxtcompany_name.setSelectionStart(0);
    jtxtcompany_name.setSelectionEnd(jtxtcompany_name.getText().length());
}                                            

private void jtxtactive_stsFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
    jtxtactive_sts.setSelectionStart(0);
    jtxtactive_sts.setSelectionEnd(jtxtactive_sts.getText().length());
}                                          

private void jtxtaddress1FocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtaddress1.setSelectionStart(0);
    jtxtaddress1.setSelectionEnd(jtxtaddress1.getText().length());
}                                        

private void jtxtaddress2FocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtaddress2.setSelectionStart(0);
    jtxtaddress2.setSelectionEnd(jtxtaddress2.getText().length());
}                                        

private void jtxtcityFocusGained(java.awt.event.FocusEvent evt) {                                  
        // TODO add your handling code here:
    jtxtcity.setSelectionStart(0);
    jtxtcity.setSelectionEnd(jtxtcity.getText().length());
}                                    

private void jtxtstateFocusGained(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    jtxtstate.setSelectionStart(0);
    jtxtstate.setSelectionEnd(jtxtstate.getText().length());
}                                     

private void jtxtzipcodeFocusGained(java.awt.event.FocusEvent evt) {                                     
        // TODO add your handling code here:
    jtxtzipcode.setSelectionStart(0);
    jtxtzipcode.setSelectionEnd(jtxtzipcode.getText().length());
}                                       

private void jtxtphoneFocusGained(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    jtxtphone.setSelectionStart(0);
    jtxtphone.setSelectionEnd(jtxtphone.getText().length());
}                                     

private void jtxtfaximaleFocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtfaximale.setSelectionStart(0);
    jtxtfaximale.setSelectionEnd(jtxtfaximale.getText().length());
}                                        

private void jtxtemailFocusGained(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    jtxtemail.setSelectionStart(0);
    jtxtemail.setSelectionEnd(jtxtemail.getText().length());
}                                     

private void jtxtpicFocusGained(java.awt.event.FocusEvent evt) {                                 
        // TODO add your handling code here:
    jtxtpic.setSelectionStart(0);
    jtxtpic.setSelectionEnd(jtxtpic.getText().length());
}                                   

private void jtxtregister_dateFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxtregister_date.setSelectionStart(0);
    jtxtregister_date.setSelectionEnd(jtxtregister_date.getText().length());
}                                             

                                   

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
    
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmgl_option().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnprice_code;
    private javax.swing.JLabel jlblactive_sts;
    private javax.swing.JLabel jlbladdress1;
    private javax.swing.JLabel jlblcity;
    private javax.swing.JLabel jlblcompany_id;
    private javax.swing.JLabel jlblcompany_name;
    private javax.swing.JLabel jlblemail;
    private javax.swing.JLabel jlblfaximale;
    private javax.swing.JLabel jlblphone;
    private javax.swing.JLabel jlblpic;
    private javax.swing.JLabel jlblprice_code;
    private javax.swing.JLabel jlblprice_code1;
    private javax.swing.JLabel jlblregister_date;
    private javax.swing.JLabel jlblstate;
    private javax.swing.JLabel jlblzipcode;
    private javax.swing.JRadioButton joptgabung_gde_N;
    private javax.swing.JRadioButton joptgabung_gde_Y;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtactive_sts;
    private javax.swing.JTextField jtxtaddress1;
    private javax.swing.JTextField jtxtaddress2;
    private javax.swing.JTextField jtxtcity;
    private javax.swing.JTextField jtxtcompany_id;
    private javax.swing.JTextField jtxtcompany_name;
    private javax.swing.JTextField jtxtemail;
    private javax.swing.JTextField jtxtfaximale;
    private javax.swing.JTextField jtxtkode_gde;
    private javax.swing.JTextField jtxtnama_gde;
    private javax.swing.JTextField jtxtphone;
    private javax.swing.JTextField jtxtpic;
    private javax.swing.JTextField jtxtregister_date;
    private javax.swing.JTextField jtxtstate;
    private javax.swing.JTextField jtxtzipcode;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){

        jtxtcompany_id.setText("");
        jtxtcompany_name.setText("");
        jtxtactive_sts.setText("");
        jtxtaddress1.setText("");
        jtxtaddress2.setText("");
        jtxtcity.setText("");
        jtxtstate.setText("");
        jtxtzipcode.setText("");
        jtxtphone.setText("");
        jtxtfaximale.setText("");
        jtxtemail.setText("");
        jtxtpic.setText("");
        jtxtregister_date.setText("");


        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");
    }

    public void newData() throws CodeException {
        istatus=1;
        clearfield();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.update();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);


        jtxtcompany_id.setText(obj.getcompany_id());
        jtxtcompany_name.setText(obj.getcompany_name());
        jtxtactive_sts.setText(obj.getactive_sts());
        jtxtaddress1.setText(obj.getaddress1());
        jtxtaddress2.setText(obj.getaddress2());
        jtxtcity.setText(obj.getcity());
        jtxtstate.setText(obj.getstate());
        jtxtzipcode.setText(obj.getzipcode());
        jtxtphone.setText(obj.getphone());
        jtxtfaximale.setText(obj.getfaximale());
        jtxtemail.setText(obj.getemail());
        jtxtpic.setText(obj.getpic());
        jtxtregister_date.setText(obj.getregister_date());

        jtxtkode_gde.setText(obj.getkode_gde());
        jtxtnama_gde.setText(obj.getnama_gde());
        if(obj.getgabung_gde().equalsIgnoreCase("Y")){
            joptgabung_gde_Y.setSelected(true);
        } else {
            joptgabung_gde_N.setSelected(true);
        }

        jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getentrydate()));
        jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getauditdate()));
        jtxtUserID.setText(obj.getaudituser());

        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        if (obj.delete()){
            obj.moveNext();
            showData();
        }
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);
        mf.btnNew.setEnabled(false);

        
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }
        obj.setcompany_id(jtxtcompany_id.getText());
        obj.setcompany_name(jtxtcompany_name.getText());
        obj.setactive_sts(jtxtactive_sts.getText());
        obj.setaddress1(jtxtaddress1.getText());
        obj.setaddress2(jtxtaddress2.getText());
        obj.setcity(jtxtcity.getText());
        obj.setstate(jtxtstate.getText());
        obj.setzipcode(jtxtzipcode.getText());
        obj.setphone(jtxtphone.getText());
        obj.setfaximale(jtxtfaximale.getText());
        obj.setemail(jtxtemail.getText());
        obj.setpic(jtxtpic.getText());
        obj.setregister_date(jtxtregister_date.getText());

        obj.setkode_gde(jtxtkode_gde.getText());
        if (joptgabung_gde_Y.isSelected()){
            obj.setgabung_gde("Y");
        } else {
            obj.setgabung_gde("N");
        }
        
        

    }

    public void undo() throws CodeException {
        istatus = 0;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    
}
