/*
 * From in_so_entry
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.in.component;


import classinterface.NavigatorFormInt;
import common.component.FrmBrowseData;
import common.component.FrmMainFrame;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import kopkar.in.objectclasses.in_so_entry_detail1ext;
import kopkar.in.objectclasses.in_so_entryext;
import java.util.logging.Level;
import java.util.logging.Logger;
import kopkar.in.objectclasses.in_productext;
import kopkar.in.objectclasses.in_so_entry_detail1extcol;
import kopkar.in.objectclasses.in_so_sheet_detail1ext;
import kopkar.in.objectclasses.in_so_sheet_detail1extcol;
import kopkar.in.objectclasses.in_so_sheetext;
import kopkar.utils.browsecontroller;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.kazao.calendar.KazaoCalendarDateTimeException;
import utils.CodeException;
import utils.GlobalModel;
import utils.GlobalUtils;
import utils.appsettinghandler;
import utils.selectallJTable;

/**
 *
 * @author  Generator
 */

public class Frmin_so_entry extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmin_so_entry";
    
    FrmMainFrame mf ;

    in_so_entryext obj=new in_so_entryext();
    private DefaultTableModel model;
    private in_so_entry_detail1extcol objd;
    private browsecontroller obrowse;
    private in_so_entryext objtmp;
   
    /** Creates new form Area */
    public Frmin_so_entry() throws CodeException {
        initComponents();
    }
    
    public Frmin_so_entry(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
        model=(DefaultTableModel) jtbldetail.getModel();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse_document = new javax.swing.JButton();
        jlbldocument_number = new javax.swing.JLabel();
        jtxtdocument_number = new javax.swing.JTextField();
        jlbldocument_status = new javax.swing.JLabel();
        jtxtdocument_status = new javax.swing.JTextField();
        jlblcomplete_status = new javax.swing.JLabel();
        jlbldocument_date = new javax.swing.JLabel();
        jlblbrand_code_fr = new javax.swing.JLabel();
        jtxtbrand_code_fr = new javax.swing.JTextField();
        jlblbrand_code_to = new javax.swing.JLabel();
        jtxtbrand_code_to = new javax.swing.JTextField();
        jlblwarehouse_code = new javax.swing.JLabel();
        jtxtwarehouse_code = new javax.swing.JTextField();
        jlblemployee = new javax.swing.JLabel();
        jtxtemployee = new javax.swing.JTextField();
        jlblreference = new javax.swing.JLabel();
        jtxtreference = new javax.swing.JTextField();
        jlbldscription = new javax.swing.JLabel();
        jtxtdscription = new javax.swing.JTextField();
        jlbltotal_adm_qty = new javax.swing.JLabel();
        jtxttotal_adm_qty = new javax.swing.JTextField();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbldetail = new selectallJTable(model);
        jlblbrand_code_fr1 = new javax.swing.JLabel();
        joptcomplete_status_Complete = new javax.swing.JRadioButton();
        joptcomplete_status_draff = new javax.swing.JRadioButton();
        kzodocument_date = new org.kazao.calendar.KazaoCalendarDate();
        jbtnBrowse_warehouse = new javax.swing.JButton();
        jbtnBrowse_brand_code_fr = new javax.swing.JButton();
        jbtnBrowse_brand_code_to = new javax.swing.JButton();
        jtxtbrand_code_to_name = new javax.swing.JTextField();
        jtxtbrand_code_fr_name = new javax.swing.JTextField();
        jtxtReffNo = new javax.swing.JTextField();
        jbtnBrowse_reffno = new javax.swing.JButton();
        jlblbrand_code_fr2 = new javax.swing.JLabel();
        jlblbrand_code_to1 = new javax.swing.JLabel();
        jtxtcategory_code_fr = new javax.swing.JTextField();
        jtxtcategory_code_to = new javax.swing.JTextField();
        jbtnBrowse_brand_code_to1 = new javax.swing.JButton();
        jbtnBrowse_brand_code_fr1 = new javax.swing.JButton();
        jtxtcategory_code_fr_name = new javax.swing.JTextField();
        jtxtcategory_code_to_name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entri Stock Opname");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Entri Stock Opname");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);

        jbtnBrowse_document.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowse_document.setText("...");
        jbtnBrowse_document.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_documentActionPerformed(evt);
            }
        });

        jlbldocument_number.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlbldocument_number.setText("No. Dokumen");

        jtxtdocument_number.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtdocument_number.setText("document_number");
        jtxtdocument_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocument_numberFocusGained(evt);
            }
        });

        jlbldocument_status.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlbldocument_status.setText("Status");

        jtxtdocument_status.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtdocument_status.setText("document_status");
        jtxtdocument_status.setFocusable(false);
        jtxtdocument_status.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdocument_statusFocusGained(evt);
            }
        });

        jlblcomplete_status.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblcomplete_status.setText("complete_status");

        jlbldocument_date.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlbldocument_date.setText("Tgl. Dokumen");

        jlblbrand_code_fr.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblbrand_code_fr.setText("Reff.No");

        jtxtbrand_code_fr.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtbrand_code_fr.setText("brand_code_fr");
        jtxtbrand_code_fr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtbrand_code_frFocusGained(evt);
            }
        });

        jlblbrand_code_to.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblbrand_code_to.setText("S/d Brand");

        jtxtbrand_code_to.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtbrand_code_to.setText("brand_code_to");
        jtxtbrand_code_to.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtbrand_code_toFocusGained(evt);
            }
        });

        jlblwarehouse_code.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblwarehouse_code.setText("Kode Gudang");

        jtxtwarehouse_code.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtwarehouse_code.setText("warehouse_code");
        jtxtwarehouse_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtwarehouse_codeFocusGained(evt);
            }
        });

        jlblemployee.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblemployee.setText("Petugas Stock Opname");

        jtxtemployee.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtemployee.setText("employee");
        jtxtemployee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtemployeeFocusGained(evt);
            }
        });

        jlblreference.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblreference.setText("Referensi");

        jtxtreference.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtreference.setText("reference");
        jtxtreference.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtreferenceFocusGained(evt);
            }
        });

        jlbldscription.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlbldscription.setText("Keterangan");

        jtxtdscription.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtdscription.setText("dscription");
        jtxtdscription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdscriptionFocusGained(evt);
            }
        });

        jlbltotal_adm_qty.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlbltotal_adm_qty.setText("Total Varian");

        jtxttotal_adm_qty.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxttotal_adm_qty.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxttotal_adm_qty.setText("total_adm_qty");
        jtxttotal_adm_qty.setFocusable(false);
        jtxttotal_adm_qty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttotal_adm_qtyFocusGained(evt);
            }
        });

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtTanggalEntry.setText("TanggalEntry");

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtTanggalUpdate.setText("TanggalUpdate");

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtUserID.setText("UserID");

        jButton1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtbldetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "Kd.Barang", "Nama Barang", "UOM2", "UOM3", "Box.Qty", "Inr.Qty", "Pcs.Qty", "TtlPcs.Qty", "Adm.Qty", "Var.Qty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true, true, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbldetail.setSurrendersFocusOnKeystroke(true);
        jtbldetail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtbldetailFocusGained(evt);
            }
        });
        jtbldetail.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtbldetailPropertyChange(evt);
            }
        });
        jtbldetail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbldetailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtbldetailKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtbldetail);
        if (jtbldetail.getColumnModel().getColumnCount() > 0) {
            jtbldetail.getColumnModel().getColumn(0).setMaxWidth(30);
            jtbldetail.getColumnModel().getColumn(2).setMinWidth(300);
        }

        jlblbrand_code_fr1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblbrand_code_fr1.setText("Dari Brand");

        buttonGroup1.add(joptcomplete_status_Complete);
        joptcomplete_status_Complete.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        joptcomplete_status_Complete.setText("Complete");

        buttonGroup1.add(joptcomplete_status_draff);
        joptcomplete_status_draff.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        joptcomplete_status_draff.setSelected(true);
        joptcomplete_status_draff.setText("Draff");

        kzodocument_date.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        kzodocument_date.setFontDate(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        kzodocument_date.setOpaque(false);

        jbtnBrowse_warehouse.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowse_warehouse.setText("...");
        jbtnBrowse_warehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_warehouseActionPerformed(evt);
            }
        });

        jbtnBrowse_brand_code_fr.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowse_brand_code_fr.setText("...");
        jbtnBrowse_brand_code_fr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_brand_code_frActionPerformed(evt);
            }
        });

        jbtnBrowse_brand_code_to.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowse_brand_code_to.setText("...");
        jbtnBrowse_brand_code_to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_brand_code_toActionPerformed(evt);
            }
        });

        jtxtbrand_code_to_name.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtbrand_code_to_name.setText("brand_code_to_name");
        jtxtbrand_code_to_name.setFocusable(false);

        jtxtbrand_code_fr_name.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtbrand_code_fr_name.setText("brand_code_fr_name");
        jtxtbrand_code_fr_name.setFocusable(false);

        jtxtReffNo.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtReffNo.setText("brand_code_fr");
        jtxtReffNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtReffNoFocusGained(evt);
            }
        });

        jbtnBrowse_reffno.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowse_reffno.setText("...");
        jbtnBrowse_reffno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_reffnoActionPerformed(evt);
            }
        });

        jlblbrand_code_fr2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblbrand_code_fr2.setText("Dari Kategori");

        jlblbrand_code_to1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblbrand_code_to1.setText("S/d Kategori");

        jtxtcategory_code_fr.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtcategory_code_fr.setText("category_code_fr");
        jtxtcategory_code_fr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcategory_code_frFocusGained(evt);
            }
        });

        jtxtcategory_code_to.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtcategory_code_to.setText("category_code_to");
        jtxtcategory_code_to.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcategory_code_toFocusGained(evt);
            }
        });

        jbtnBrowse_brand_code_to1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowse_brand_code_to1.setText("...");
        jbtnBrowse_brand_code_to1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_brand_code_to1ActionPerformed(evt);
            }
        });

        jbtnBrowse_brand_code_fr1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowse_brand_code_fr1.setText("...");
        jbtnBrowse_brand_code_fr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse_brand_code_fr1ActionPerformed(evt);
            }
        });

        jtxtcategory_code_fr_name.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtcategory_code_fr_name.setText("category_code_fr_name");
        jtxtcategory_code_fr_name.setFocusable(false);

        jtxtcategory_code_to_name.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtcategory_code_to_name.setText("category_code_to_name");
        jtxtcategory_code_to_name.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtTanggalEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jtxtTanggalUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jtxtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(HorizontalLine))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlblbrand_code_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlblbrand_code_fr1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlblbrand_code_to, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlblbrand_code_fr2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlblbrand_code_to1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlblemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtxtReffNo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jbtnBrowse_reffno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jbtnBrowse_brand_code_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jtxtbrand_code_fr_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jtxtcategory_code_to, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtxtcategory_code_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtxtbrand_code_to, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jbtnBrowse_brand_code_to, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jbtnBrowse_brand_code_to1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jtxtbrand_code_to_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtxtcategory_code_fr_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addComponent(jbtnBrowse_brand_code_fr1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(110, 110, 110)
                                                .addComponent(jtxtcategory_code_to_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jtxtemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtbrand_code_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlbldocument_status, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlbldocument_number, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlbldocument_date, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlblwarehouse_code, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jtxtdocument_status, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtxtdocument_number, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kzodocument_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jbtnBrowse_document, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtxtwarehouse_code, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(jbtnBrowse_warehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(110, 110, 110)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbldscription, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(jtxtdscription, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlblcomplete_status, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(joptcomplete_status_draff)
                                        .addGap(16, 16, 16)
                                        .addComponent(joptcomplete_status_Complete, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlblreference, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(jtxtreference, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlbltotal_adm_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(jtxttotal_adm_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtTanggalEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTanggalUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HorizontalLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblbrand_code_fr)
                                .addGap(7, 7, 7)
                                .addComponent(jlblbrand_code_fr1)
                                .addGap(7, 7, 7)
                                .addComponent(jlblbrand_code_to)
                                .addGap(7, 7, 7)
                                .addComponent(jlblbrand_code_fr2)
                                .addGap(7, 7, 7)
                                .addComponent(jlblbrand_code_to1)
                                .addGap(7, 7, 7)
                                .addComponent(jlblemployee))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtReffNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnBrowse_reffno, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jbtnBrowse_brand_code_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jtxtbrand_code_fr_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jtxtcategory_code_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jtxtcategory_code_fr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtxtbrand_code_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnBrowse_brand_code_to, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23)
                                        .addComponent(jbtnBrowse_brand_code_to1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtxtbrand_code_to_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jtxtcategory_code_fr_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jbtnBrowse_brand_code_fr1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jtxtcategory_code_to_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jtxtemployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jtxtbrand_code_fr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlbldocument_status)
                                    .addGap(7, 7, 7)
                                    .addComponent(jlbldocument_number)
                                    .addGap(7, 7, 7)
                                    .addComponent(jlbldocument_date)
                                    .addGap(7, 7, 7)
                                    .addComponent(jlblwarehouse_code))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtxtdocument_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(jtxtdocument_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(40, 40, 40)
                                            .addComponent(kzodocument_date, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(jbtnBrowse_document, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtxtwarehouse_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jbtnBrowse_warehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(17, 17, 17)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblreference)
                            .addComponent(jtxtreference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbltotal_adm_qty)
                            .addComponent(jtxttotal_adm_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbldscription)
                            .addComponent(jtxtdscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblcomplete_status)
                            .addComponent(joptcomplete_status_draff)
                            .addComponent(joptcomplete_status_Complete)))
                    .addComponent(jSeparator3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jbtnBrowse_warehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_warehouseActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.in_warehouse, "", jtxtwarehouse_code);
}//GEN-LAST:event_jbtnBrowse_warehouseActionPerformed

private void jbtnBrowse_documentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_documentActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.in_so_entry, "", jtxtdocument_number);

    if (!jtxtdocument_number.getText().equalsIgnoreCase("")){
            try {
                if (obj.initdata(jtxtdocument_number.getText())) {
                    showData();
                }
            } catch (CodeException ex) {
                Logger.getLogger(Frmin_so_entry.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
}//GEN-LAST:event_jbtnBrowse_documentActionPerformed

private void jbtnBrowse_brand_code_frActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_brand_code_frActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.in_brand, "", jtxtbrand_code_fr,jtxtbrand_code_fr_name);
}//GEN-LAST:event_jbtnBrowse_brand_code_frActionPerformed

private void jbtnBrowse_brand_code_toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_brand_code_toActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.in_brand, "", jtxtbrand_code_to,jtxtbrand_code_to_name);
}//GEN-LAST:event_jbtnBrowse_brand_code_toActionPerformed

private void jtbldetailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtbldetailFocusGained
    // TODO add your handling code here:
    if (jtbldetail.getRowCount()==0){
        insertnewlastrow();
    }
}//GEN-LAST:event_jtbldetailFocusGained

private void jtbldetailPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtbldetailPropertyChange
    // TODO add your handling code here:
    int irow=jtbldetail.getSelectedRow();
    int icol=jtbldetail.getSelectedColumn();

    if (irow>-1){
        switch (icol){
            case 1:
                showproduct(irow);
                break;
        }
        cekdetail(irow);
        in_so_entry_detail1ext appod = objd.get(irow);
        switch (icol){
            case 5:
                appod.calculatetotalqty(false);
                break;
            case 6:
                appod.calculatetotalqty(false);
                break;
            case 7:
                appod.calculatetotalqty(false);
                break;
            case 8:
                appod.calculatetotalqty(true);
                break;
        }
        model.setValueAt(appod.getuom3_qty(), irow, 5);
        model.setValueAt(appod.getuom2_qty(), irow, 6);
        model.setValueAt(appod.getpcs_qty(), irow, 7);
        model.setValueAt(appod.gettotal_pcs(), irow, 8);
        model.setValueAt(appod.getvariant(), irow, 10);
        obj.calculatetotal();
        cekdetail(irow);
        jtxttotal_adm_qty.setText(GlobalUtils.formatnumber(obj.gettotal_adm_qty()));
        jHeader.setText(" : : Lembar Kerja Stock Opname ("+objd.size()+")");
    }
}//GEN-LAST:event_jtbldetailPropertyChange

private void jtbldetailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbldetailKeyPressed
    // TODO add your handling code here:
    int col=jtbldetail.getSelectedColumn();
    int row=jtbldetail.getSelectedRow();
    switch (evt.getKeyCode()){
        case KeyEvent.VK_F5:
            switch (jtbldetail.getSelectedColumn()){
                case 1:
                    obrowse=new browsecontroller();
                    obrowse.showbrowser(obrowse.in_product, "", jtbldetail);
                    showproduct((Integer)jtbldetail.getSelectedRow());
                    jtbldetailPropertyChange(null);
                    GlobalUtils.selectCellTable(jtbldetail, row, 3);
                    break;
            }
            break;
        case KeyEvent.VK_INSERT:
            evt.consume();
            insertnewlastrow();
            break;
        case KeyEvent.VK_DELETE:
            evt.consume();
            if (jtbldetail.getSelectedRow()<objd.size()){
            in_so_entry_detail1ext o = objd.get(jtbldetail.getSelectedRow());
                o.setstatus(in_so_entry_detail1ext.Status_delete);
            }
            jtbldetailPropertyChange(null);
            break;
        case KeyEvent.VK_ENTER:
            evt.consume();
            break;
    }
}//GEN-LAST:event_jtbldetailKeyPressed

private void jtbldetailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbldetailKeyReleased
    // TODO add your handling code here:
    int col=jtbldetail.getSelectedColumn();
    int row=jtbldetail.getSelectedRow();
// TODO add your handling code here:
    if (evt.getKeyCode()==evt.VK_ENTER&&row>-1){
        switch (col){
            case 1:
                showproduct(row);
                jtbldetailPropertyChange(null);
                GlobalUtils.selectCellTable(jtbldetail, row, 3);
                break;
            case 5:
                insertnewlastrow();
                break;
        }
    }
}//GEN-LAST:event_jtbldetailKeyReleased

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    if (obj.retrievedata(jtxtbrand_code_fr.getText(),jtxtbrand_code_to.getText(),jtxtwarehouse_code.getText())){
        showdetail();
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jtxtReffNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtReffNoFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtReffNoFocusGained

private void jbtnBrowse_reffnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_reffnoActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.in_so_sheet, "document_status='O'", jtxtReffNo);

    if (!jtxtReffNo.getText().equalsIgnoreCase("")){
        showlembarkerja();
    }
}//GEN-LAST:event_jbtnBrowse_reffnoActionPerformed

private void jtxtcategory_code_frFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtcategory_code_frFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtcategory_code_frFocusGained

private void jtxtcategory_code_toFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtcategory_code_toFocusGained
    // TODO add your handling code here:
}//GEN-LAST:event_jtxtcategory_code_toFocusGained

private void jbtnBrowse_brand_code_to1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_brand_code_to1ActionPerformed
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.in_category, "", jtxtcategory_code_to,jtxtcategory_code_to_name);
}//GEN-LAST:event_jbtnBrowse_brand_code_to1ActionPerformed

private void jbtnBrowse_brand_code_fr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse_brand_code_fr1ActionPerformed
    // TODO add your handling code here:
    // TODO add your handling code here:
    obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.in_category, "", jtxtcategory_code_fr,jtxtcategory_code_fr_name);
}//GEN-LAST:event_jbtnBrowse_brand_code_fr1ActionPerformed

private void jtxtdocument_numberFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtdocument_number.setSelectionStart(0);
    jtxtdocument_number.setSelectionEnd(jtxtdocument_number.getText().length());
}                                               

private void jtxtdocument_statusFocusGained(java.awt.event.FocusEvent evt) {                                             
        // TODO add your handling code here:
    jtxtdocument_status.setSelectionStart(0);
    jtxtdocument_status.setSelectionEnd(jtxtdocument_status.getText().length());
}                                               

private void jtxtbrand_code_frFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxtbrand_code_fr.setSelectionStart(0);
    jtxtbrand_code_fr.setSelectionEnd(jtxtbrand_code_fr.getText().length());
}                                             

private void jtxtbrand_code_toFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxtbrand_code_to.setSelectionStart(0);
    jtxtbrand_code_to.setSelectionEnd(jtxtbrand_code_to.getText().length());
}                                             

private void jtxtwarehouse_codeFocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
    jtxtwarehouse_code.setSelectionStart(0);
    jtxtwarehouse_code.setSelectionEnd(jtxtwarehouse_code.getText().length());
}                                              

private void jtxtemployeeFocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtemployee.setSelectionStart(0);
    jtxtemployee.setSelectionEnd(jtxtemployee.getText().length());
}                                        

private void jtxtreferenceFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
    jtxtreference.setSelectionStart(0);
    jtxtreference.setSelectionEnd(jtxtreference.getText().length());
}                                         

private void jtxtdscriptionFocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
    jtxtdscription.setSelectionStart(0);
    jtxtdscription.setSelectionEnd(jtxtdscription.getText().length());
}                                          

private void jtxttotal_adm_qtyFocusGained(java.awt.event.FocusEvent evt) {                                           
        // TODO add your handling code here:
    jtxttotal_adm_qty.setSelectionStart(0);
    jtxttotal_adm_qty.setSelectionEnd(jtxttotal_adm_qty.getText().length());
}                                             

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
    FrmBrowseData frmbrowse=new FrmBrowseData("in_so_entry", "");
    frmbrowse.setModal(true);
    frmbrowse.setVisible(true);
    try {
        obj.initdata(frmbrowse.getValue());
        showData();
    } catch (CodeException ex) {
        Logger.getLogger(Frmin_so_entry.class.getName()).log(Level.SEVERE, null, ex);
    }
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmin_so_entry().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse_brand_code_fr;
    private javax.swing.JButton jbtnBrowse_brand_code_fr1;
    private javax.swing.JButton jbtnBrowse_brand_code_to;
    private javax.swing.JButton jbtnBrowse_brand_code_to1;
    private javax.swing.JButton jbtnBrowse_document;
    private javax.swing.JButton jbtnBrowse_reffno;
    private javax.swing.JButton jbtnBrowse_warehouse;
    private javax.swing.JLabel jlblbrand_code_fr;
    private javax.swing.JLabel jlblbrand_code_fr1;
    private javax.swing.JLabel jlblbrand_code_fr2;
    private javax.swing.JLabel jlblbrand_code_to;
    private javax.swing.JLabel jlblbrand_code_to1;
    private javax.swing.JLabel jlblcomplete_status;
    private javax.swing.JLabel jlbldocument_date;
    private javax.swing.JLabel jlbldocument_number;
    private javax.swing.JLabel jlbldocument_status;
    private javax.swing.JLabel jlbldscription;
    private javax.swing.JLabel jlblemployee;
    private javax.swing.JLabel jlblreference;
    private javax.swing.JLabel jlbltotal_adm_qty;
    private javax.swing.JLabel jlblwarehouse_code;
    private javax.swing.JRadioButton joptcomplete_status_Complete;
    private javax.swing.JRadioButton joptcomplete_status_draff;
    private javax.swing.JTable jtbldetail;
    private javax.swing.JTextField jtxtReffNo;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtbrand_code_fr;
    private javax.swing.JTextField jtxtbrand_code_fr_name;
    private javax.swing.JTextField jtxtbrand_code_to;
    private javax.swing.JTextField jtxtbrand_code_to_name;
    private javax.swing.JTextField jtxtcategory_code_fr;
    private javax.swing.JTextField jtxtcategory_code_fr_name;
    private javax.swing.JTextField jtxtcategory_code_to;
    private javax.swing.JTextField jtxtcategory_code_to_name;
    private javax.swing.JTextField jtxtdocument_number;
    private javax.swing.JTextField jtxtdocument_status;
    private javax.swing.JTextField jtxtdscription;
    private javax.swing.JTextField jtxtemployee;
    private javax.swing.JTextField jtxtreference;
    private javax.swing.JTextField jtxttotal_adm_qty;
    private javax.swing.JTextField jtxtwarehouse_code;
    private org.kazao.calendar.KazaoCalendarDate kzodocument_date;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jtxtdocument_number.setText("");
        jtxtdocument_status.setText("");

        joptcomplete_status_draff.setSelected(true);
        try {
            kzodocument_date.setDate(GlobalUtils.getCurrentDate());
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmin_so_entry.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtxtReffNo.setText("");
        jtxtbrand_code_fr.setText("");
        jtxtbrand_code_to.setText("");

        jtxtcategory_code_fr.setText("");
        jtxtcategory_code_to.setText("");

        
        jtxtwarehouse_code.setText("");
        jtxtemployee.setText("");
        jtxtreference.setText("");
        jtxtdscription.setText("");
        jtxttotal_adm_qty.setText("0");

        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");

        jtxtbrand_code_fr_name.setText("");
        jtxtbrand_code_to_name.setText("");

        jtxtcategory_code_fr_name.setText("");
        jtxtcategory_code_to_name.setText("");

        GlobalModel.clearRow(model);
        insertnewlastrow();
    }

    public void newData() throws CodeException {
        istatus=1;
        objtmp=obj;
        obj=new in_so_entryext();
        showData();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.calculatetotal();
        obj.update();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        jtxtdocument_number.setText(obj.getdocument_number());
        jtxtdocument_status.setText(obj.getdocument_status_desc());
        if (obj.getcomplete_status().equalsIgnoreCase("Y")){
            joptcomplete_status_Complete.setSelected(true);
        }  else {
            joptcomplete_status_draff.setSelected(true);
        }
        try {
            kzodocument_date.setDate(GlobalUtils.formatDate(obj.getdocument_date(),"MM/dd/yyyy"));
        } catch (KazaoCalendarDateTimeException ex) {
            Logger.getLogger(Frmin_so_entry.class.getName()).log(Level.SEVERE, null, ex);
        }
        jtxtReffNo.setText(obj.getreference_number());
        jtxtbrand_code_fr.setText(obj.getbrand_code_fr());
        jtxtbrand_code_fr_name.setText(obj.getbrand_name_fr());
        jtxtbrand_code_to.setText(obj.getbrand_code_to());
        jtxtbrand_code_to_name.setText(obj.getbrand_name_to());

        jtxtcategory_code_fr.setText(obj.getcategory_code_fr());
        jtxtcategory_code_fr_name.setText(obj.getcategory_name_fr());
        jtxtcategory_code_to.setText(obj.getcategory_code_to());
        jtxtcategory_code_to_name.setText(obj.getcategory_name_to());
        
        jtxtwarehouse_code.setText(obj.getwarehouse_code());
        jtxtemployee.setText(obj.getemployee());
        jtxtreference.setText(obj.getreference());
        jtxtdscription.setText(obj.getdscription());
        jtxttotal_adm_qty.setText(GlobalUtils.formatnumber(obj.gettotal_adm_qty()));

        jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getentrydate()));
        jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getauditdate()));
        jtxtUserID.setText(obj.getaudituser());

        GlobalModel.clearRow(model);
        showdetail();
        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        if (obj.delete()){
            obj.moveNext();
            showData();
        }
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);

        if (istatus==1){
            jbtnBrowse_document.setEnabled(false);
        } else {
            jbtnBrowse_document.setEnabled(true);
        }
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }
        obj.setdocument_number(jtxtdocument_number.getText());
        obj.setdocument_status(jtxtdocument_status.getText());
        if (joptcomplete_status_Complete.isSelected()){
            obj.setcomplete_status("Y");
        } else {
            obj.setcomplete_status("N");
        }
        obj.setreference_number(jtxtReffNo.getText());
        obj.setdocument_date(kzodocument_date.getDate());
        obj.setbrand_code_fr(jtxtbrand_code_fr.getText());
        obj.setbrand_code_to(jtxtbrand_code_to.getText());
        obj.setcategory_code_fr(jtxtcategory_code_fr.getText());
        obj.setcategory_code_to(jtxtcategory_code_to.getText());
        obj.setwarehouse_code(jtxtwarehouse_code.getText());
        obj.setemployee(jtxtemployee.getText());
        obj.setreference(jtxtreference.getText());
        obj.setdscription(jtxtdscription.getText());
        obj.settotal_adm_qty(GlobalUtils.toInt(jtxttotal_adm_qty.getText()));
        
    }

    public void undo() throws CodeException {
        istatus = 0;
        obj=objtmp;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
        Map parameter = new HashMap();

        parameter.put("document_date_fr", obj.getdocument_date());
        parameter.put("document_date_to", obj.getdocument_date());
        parameter.put("document_number_fr", obj.getdocument_number());
        parameter.put("document_number_to", obj.getdocument_number());
        parameter.put("audituser", (GlobalUtils.getUserId()));

        // Versi 1
        String file ="";
        JasperReport jasperReport;
        JasperPrint jasperPrint;
        if(GlobalUtils.getAppDir()){
            try{
            file = GlobalUtils.getCurrentDir() +"/Reports/FTSO-02.jrxml";
            jasperReport = JasperCompileManager.compileReport(file);
            //System.out.println("file: "+file);
            System.out.println("isi parameter "+file+":"+parameter);
            jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, appsettinghandler.db.getConnection());
            JasperViewer.viewReport(jasperPrint, false);
            }catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    private void insertnewlastrow() {
        if (!lastrowisempty()){
        model.addRow(new Object[model.getColumnCount()]);
        model.setValueAt(model.getRowCount()-1, model.getRowCount()-1, 0);
        model.setValueAt("", model.getRowCount()-1, 1);
        model.setValueAt(0, model.getRowCount()-1, 3);
        model.setValueAt(0, model.getRowCount()-1, 4);
        model.setValueAt(0, model.getRowCount()-1, 5);
        model.setValueAt(0, model.getRowCount()-1, 6);
        model.setValueAt(0, model.getRowCount()-1, 7);
        model.setValueAt(0, model.getRowCount()-1, 8);
        model.setValueAt(0, model.getRowCount()-1, 9);
        model.setValueAt(0, model.getRowCount()-1, 10);
        GlobalUtils.selectCellTable(jtbldetail, model.getRowCount()-1, 1);
        }
    }

    private boolean lastrowisempty() {
        if (model.getRowCount()>0){
            if (GlobalUtils.churuf(model.getValueAt(model.getRowCount()-1, 1)).equalsIgnoreCase("")){
                return true;
            }
        }
        return false;
    }

    private void showproduct(Integer irow) {
        in_productext oin_product=new in_productext();

        String sproduct_code=GlobalUtils.churuf(model.getValueAt(irow, 1));
        try {
            if (oin_product.initdata(sproduct_code)) {
                model.setValueAt(oin_product.getproduct_name(), irow, 2);
            }
        } catch (CodeException ex) {
            Logger.getLogger(Frmin_so_entry.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void cekdetail(int row) {
        int col = jtbldetail.getSelectedColumn();


        in_so_entry_detail1ext appod=new in_so_entry_detail1ext(obj.getdocentry());
        if (row > objd.size() - 1) {
            appod = new in_so_entry_detail1ext(obj.getdocentry());
            appod.setstatus(in_so_entry_detail1ext.Status_Insert);
            objd.add(appod);
        } else {
            appod = (in_so_entry_detail1ext) objd.get(row);
            if (!appod.getstatus().equals(in_so_entry_detail1ext.Status_Insert)&&!appod.getstatus().equals(in_so_entry_detail1ext.Status_delete)){
                appod.setstatus(in_so_entry_detail1ext.Status_update);
            }
        }
        appod.setproduct_code(GlobalUtils.churuf(model.getValueAt(row, 1)));
        appod.setuom2(GlobalUtils.toDbl(GlobalUtils.churuf(model.getValueAt(row, 3))));
        appod.setuom3(GlobalUtils.toDbl(GlobalUtils.churuf(model.getValueAt(row, 4))));
        
        appod.setuom3_qty(GlobalUtils.toDbl(GlobalUtils.churuf(model.getValueAt(row, 5))));
        appod.setuom2_qty(GlobalUtils.toDbl(GlobalUtils.churuf(model.getValueAt(row, 6))));
        appod.setpcs_qty(GlobalUtils.toDbl(GlobalUtils.churuf(model.getValueAt(row, 7))));
        appod.settotal_pcs(GlobalUtils.toDbl(GlobalUtils.churuf(model.getValueAt(row, 8))));

        appod.setbase_total_pcs(GlobalUtils.toDbl(GlobalUtils.churuf(model.getValueAt(row, 9))));

        objd.set(row, appod);
    }

    private void showdetail() {
        objd=obj.getdetail();
        if (jtbldetail.getRowCount()==0){
            insertnewlastrow();
        }
        for (int i=0;i<objd.size();i++){
            in_so_entry_detail1ext o = objd.get(i);
            model.addRow(new Object[model.getColumnCount()]);
            
            model.setValueAt(i+1, i, 0);
            model.setValueAt(o.getproduct_code(), i, 1);
            model.setValueAt(o.getproduct_name(), i, 2);
            model.setValueAt(o.getuom2(), i, 3);
            model.setValueAt(o.getuom3(), i, 4);
            model.setValueAt(o.getuom3_qty(), i, 5);
            model.setValueAt(o.getuom2_qty(), i, 6);
            model.setValueAt(o.getpcs_qty(), i, 7);
            model.setValueAt(o.gettotal_pcs(), i, 8);
            model.setValueAt(o.getbase_total_pcs(), i, 9);
            model.setValueAt(o.getvariant(), i, 10);
            insertnewlastrow();
        }
        obj.calculatetotal();
        jtxttotal_adm_qty.setText(GlobalUtils.formatnumber(obj.gettotal_adm_qty()));
    }

    private void showlembarkerja() {
        in_so_sheetext osheet=new in_so_sheetext();
        in_so_sheet_detail1ext o;
        in_so_sheet_detail1extcol osheetd;
        try {
            if (osheet.initdata(jtxtReffNo.getText())) {
                clearfield();
                jtxtReffNo.setText(osheet.getdocument_number());
                jtxtbrand_code_fr.setText(osheet.getbrand_code_fr());
                jtxtbrand_code_fr_name.setText(osheet.getbrand_name_fr());
                jtxtbrand_code_to.setText(osheet.getbrand_code_to());
                jtxtbrand_code_to_name.setText(osheet.getbrand_name_to());

                jtxtcategory_code_fr.setText(osheet.getcategory_code_fr());
                jtxtcategory_code_fr_name.setText(osheet.getcategory_name_fr());
                jtxtcategory_code_to.setText(osheet.getcategory_code_to());
                jtxtcategory_code_to_name.setText(osheet.getcategory_name_to());

                jtxtwarehouse_code.setText(osheet.getwarehouse_code());
                jtxtemployee.setText(osheet.getemployee());

                osheetd=osheet.getdetail();
                if (jtbldetail.getRowCount()==0){
                    insertnewlastrow();
                }
                for (int i=0;i<osheetd.size();i++){
                    o=osheetd.get(i);
                    model.addRow(new Object[model.getColumnCount()]);
                    model.setValueAt(i+1, i, 0);
                    model.setValueAt(o.getproduct_code(), i, 1);
                    model.setValueAt(o.getproduct_name(), i, 2);
                    model.setValueAt(o.getuom2(), i, 3);
                    model.setValueAt(o.getuom3(), i, 4);
                    model.setValueAt(o.getbase_total_pcs(), i, 9);
                    cekdetail(i);
//                    GlobalUtils.selectCellTable(jtbldetail, i, 1);
//                    jtbldetailPropertyChange(null);
//                    insertnewlastrow();
                }
            }
        } catch (CodeException ex) {
            Logger.getLogger(Frmin_so_entry.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
}
