/*
 * From in_warehouse
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.in.component;



import classinterface.NavigatorFormInt;
import common.component.FrmBrowseData;
import common.component.FrmMainFrame;
import java.util.logging.Level;
import java.util.logging.Logger;
import kopkar.in.objectclasses.in_warehouseext;
import kopkar.utils.browsecontroller;
import utils.CodeException;
import utils.GlobalUtils;

/**
 *
 * @author  Generator
 */

public class Frmin_warehouse extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmin_warehouse";
    String isonhand="";
    
    FrmMainFrame mf ;

    in_warehouseext obj=new in_warehouseext();
    browsecontroller obrowse=new browsecontroller();


    /** Creates new form Area */
    public Frmin_warehouse() throws CodeException {
        initComponents();
    }
    
    public Frmin_warehouse(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();
        jlblwarehouse_code = new javax.swing.JLabel();
        jtxtwarehouse_code = new javax.swing.JTextField();
        jlblwarehouse_name = new javax.swing.JLabel();
        jtxtwarehouse_name = new javax.swing.JTextField();
        jlbladdress1 = new javax.swing.JLabel();
        jtxtaddress1 = new javax.swing.JTextField();
        jtxtaddress2 = new javax.swing.JTextField();
        jlblcity = new javax.swing.JLabel();
        jtxtcity = new javax.swing.JTextField();
        jlblstate = new javax.swing.JLabel();
        jtxtstate = new javax.swing.JTextField();
        jlblzipcode = new javax.swing.JLabel();
        jtxtzipcode = new javax.swing.JTextField();
        jlblphone = new javax.swing.JLabel();
        jtxtphone = new javax.swing.JTextField();
        jlblfaximale = new javax.swing.JLabel();
        jtxtfaximale = new javax.swing.JTextField();
        jlblemail = new javax.swing.JLabel();
        jtxtemail = new javax.swing.JTextField();
        jlblpic = new javax.swing.JLabel();
        jtxtpic = new javax.swing.JTextField();
        jlblwarehouse_type = new javax.swing.JLabel();
        jtxtwarehouse_type = new javax.swing.JTextField();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();
        chck_onhand = new javax.swing.JCheckBox();
        jbtnBrowse1 = new javax.swing.JButton();
        jtxt_whstypedesc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("in_warehouse");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Gudang");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 200, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(280, 100, 30, 17);

        jlblwarehouse_code.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblwarehouse_code.setText("Kode Gudang");
        getContentPane().add(jlblwarehouse_code);
        jlblwarehouse_code.setBounds(50, 100, 140, 13);

        jtxtwarehouse_code.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtwarehouse_code.setText("warehouse_code");
        jtxtwarehouse_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtwarehouse_codeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtwarehouse_code);
        jtxtwarehouse_code.setBounds(180, 100, 90, 23);

        jlblwarehouse_name.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblwarehouse_name.setText("Nama Gudang");
        getContentPane().add(jlblwarehouse_name);
        jlblwarehouse_name.setBounds(50, 120, 140, 13);

        jtxtwarehouse_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtwarehouse_name.setText("warehouse_name");
        jtxtwarehouse_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtwarehouse_nameFocusGained(evt);
            }
        });
        getContentPane().add(jtxtwarehouse_name);
        jtxtwarehouse_name.setBounds(180, 120, 380, 23);

        jlbladdress1.setFont(new java.awt.Font("Dialog", 1, 10));
        jlbladdress1.setText("Alamat");
        getContentPane().add(jlbladdress1);
        jlbladdress1.setBounds(50, 160, 140, 13);

        jtxtaddress1.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaddress1.setText("address1");
        jtxtaddress1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtaddress1FocusGained(evt);
            }
        });
        getContentPane().add(jtxtaddress1);
        jtxtaddress1.setBounds(180, 160, 380, 23);

        jtxtaddress2.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtaddress2.setText("address2");
        jtxtaddress2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtaddress2FocusGained(evt);
            }
        });
        getContentPane().add(jtxtaddress2);
        jtxtaddress2.setBounds(180, 180, 380, 23);

        jlblcity.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblcity.setText("Kota");
        getContentPane().add(jlblcity);
        jlblcity.setBounds(50, 200, 140, 13);

        jtxtcity.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcity.setText("city");
        jtxtcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcityFocusGained(evt);
            }
        });
        getContentPane().add(jtxtcity);
        jtxtcity.setBounds(180, 200, 380, 23);

        jlblstate.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblstate.setText("Propinsi");
        getContentPane().add(jlblstate);
        jlblstate.setBounds(50, 220, 140, 13);

        jtxtstate.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtstate.setText("state");
        jtxtstate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtstateFocusGained(evt);
            }
        });
        getContentPane().add(jtxtstate);
        jtxtstate.setBounds(180, 220, 380, 23);

        jlblzipcode.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblzipcode.setText("Kodepos");
        getContentPane().add(jlblzipcode);
        jlblzipcode.setBounds(50, 240, 140, 13);

        jtxtzipcode.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtzipcode.setText("zipcode");
        jtxtzipcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtzipcodeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtzipcode);
        jtxtzipcode.setBounds(180, 240, 380, 23);

        jlblphone.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblphone.setText("Telephone");
        getContentPane().add(jlblphone);
        jlblphone.setBounds(50, 260, 140, 13);

        jtxtphone.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtphone.setText("phone");
        jtxtphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtphoneFocusGained(evt);
            }
        });
        getContentPane().add(jtxtphone);
        jtxtphone.setBounds(180, 260, 380, 23);

        jlblfaximale.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblfaximale.setText("Fax");
        getContentPane().add(jlblfaximale);
        jlblfaximale.setBounds(50, 280, 140, 13);

        jtxtfaximale.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtfaximale.setText("faximale");
        jtxtfaximale.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtfaximaleFocusGained(evt);
            }
        });
        getContentPane().add(jtxtfaximale);
        jtxtfaximale.setBounds(180, 280, 380, 23);

        jlblemail.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblemail.setText("E-Mail");
        getContentPane().add(jlblemail);
        jlblemail.setBounds(50, 300, 140, 13);

        jtxtemail.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtemail.setText("email");
        jtxtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtemailFocusGained(evt);
            }
        });
        getContentPane().add(jtxtemail);
        jtxtemail.setBounds(180, 300, 380, 23);

        jlblpic.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblpic.setText("PIC");
        getContentPane().add(jlblpic);
        jlblpic.setBounds(50, 320, 140, 13);

        jtxtpic.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtpic.setText("pic");
        jtxtpic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtpicFocusGained(evt);
            }
        });
        getContentPane().add(jtxtpic);
        jtxtpic.setBounds(180, 320, 380, 23);

        jlblwarehouse_type.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblwarehouse_type.setText("Tipe Gudang");
        getContentPane().add(jlblwarehouse_type);
        jlblwarehouse_type.setBounds(50, 140, 140, 13);

        jtxtwarehouse_type.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtwarehouse_type.setText("warehouse_type");
        jtxtwarehouse_type.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtwarehouse_typeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtwarehouse_type);
        jtxtwarehouse_type.setBounds(180, 140, 90, 23);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(360, 30, 170, 20);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(530, 30, 130, 20);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(660, 30, 140, 20);

        chck_onhand.setFont(new java.awt.Font("Dialog", 1, 10));
        chck_onhand.setText("Check On Hand");
        chck_onhand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chck_onhandActionPerformed(evt);
            }
        });
        getContentPane().add(chck_onhand);
        chck_onhand.setBounds(330, 70, 180, 30);

        jbtnBrowse1.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse1.setText("...");
        jbtnBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse1);
        jbtnBrowse1.setBounds(280, 140, 30, 17);

        jtxt_whstypedesc.setFont(new java.awt.Font("Dialog", 1, 10));
        jtxt_whstypedesc.setText("warehouse_type_desc");
        getContentPane().add(jtxt_whstypedesc);
        jtxt_whstypedesc.setBounds(330, 140, 230, 13);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void chck_onhandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chck_onhandActionPerformed
    // TODO add your handling code here:
    if(chck_onhand.isSelected()){
        isonhand="Y";
    }else{
        isonhand="N";
    }
}//GEN-LAST:event_chck_onhandActionPerformed

private void jbtnBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse1ActionPerformed
    // TODO add your handling code here:
    obrowse.showbrowser(obrowse.in_warehouse_type, "", jtxtwarehouse_type, jtxt_whstypedesc);

}//GEN-LAST:event_jbtnBrowse1ActionPerformed

private void jtxtidFocusGained(java.awt.event.FocusEvent evt) {                                
        // TODO add your handling code here:
}                                  

private void jtxtwarehouse_codeFocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
    jtxtwarehouse_code.setSelectionStart(0);
    jtxtwarehouse_code.setSelectionEnd(jtxtwarehouse_code.getText().length());
}                                              

private void jtxtwarehouse_nameFocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
    jtxtwarehouse_name.setSelectionStart(0);
    jtxtwarehouse_name.setSelectionEnd(jtxtwarehouse_name.getText().length());
}                                              

private void jtxtcheck_ohFocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
}                                        

private void jtxtaddress1FocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtaddress1.setSelectionStart(0);
    jtxtaddress1.setSelectionEnd(jtxtaddress1.getText().length());
}                                        

private void jtxtaddress2FocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtaddress2.setSelectionStart(0);
    jtxtaddress2.setSelectionEnd(jtxtaddress2.getText().length());
}                                        

private void jtxtcityFocusGained(java.awt.event.FocusEvent evt) {                                  
        // TODO add your handling code here:
    jtxtcity.setSelectionStart(0);
    jtxtcity.setSelectionEnd(jtxtcity.getText().length());
}                                    

private void jtxtstateFocusGained(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    jtxtstate.setSelectionStart(0);
    jtxtstate.setSelectionEnd(jtxtstate.getText().length());
}                                     

private void jtxtzipcodeFocusGained(java.awt.event.FocusEvent evt) {                                     
        // TODO add your handling code here:
    jtxtzipcode.setSelectionStart(0);
    jtxtzipcode.setSelectionEnd(jtxtzipcode.getText().length());
}                                       

private void jtxtphoneFocusGained(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    jtxtphone.setSelectionStart(0);
    jtxtphone.setSelectionEnd(jtxtphone.getText().length());
}                                     

private void jtxtfaximaleFocusGained(java.awt.event.FocusEvent evt) {                                      
        // TODO add your handling code here:
    jtxtfaximale.setSelectionStart(0);
    jtxtfaximale.setSelectionEnd(jtxtfaximale.getText().length());
}                                        

private void jtxtemailFocusGained(java.awt.event.FocusEvent evt) {                                   
        // TODO add your handling code here:
    jtxtemail.setSelectionStart(0);
    jtxtemail.setSelectionEnd(jtxtemail.getText().length());
}                                     

private void jtxtpicFocusGained(java.awt.event.FocusEvent evt) {                                 
        // TODO add your handling code here:
    jtxtpic.setSelectionStart(0);
    jtxtpic.setSelectionEnd(jtxtpic.getText().length());
}                                   

private void jtxtwarehouse_typeFocusGained(java.awt.event.FocusEvent evt) {                                            
        // TODO add your handling code here:
    jtxtwarehouse_type.setSelectionStart(0);
    jtxtwarehouse_type.setSelectionEnd(jtxtwarehouse_type.getText().length());
}                                              

private void jtxtentrydateFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
}                                         

private void jtxtauditdateFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
}                                         

private void jtxtaudituserFocusGained(java.awt.event.FocusEvent evt) {                                       
        // TODO add your handling code here:
}                                         

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
    FrmBrowseData frmbrowse=new FrmBrowseData("in_warehouse", "");
    frmbrowse.setModal(true);
    frmbrowse.setVisible(true);
    try {
        obj.initdata(frmbrowse.getValue());
        showData();
    } catch (CodeException ex) {
        Logger.getLogger(Frmin_warehouse.class.getName()).log(Level.SEVERE, null, ex);
    }
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmin_warehouse().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JCheckBox chck_onhand;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowse1;
    private javax.swing.JLabel jlbladdress1;
    private javax.swing.JLabel jlblcity;
    private javax.swing.JLabel jlblemail;
    private javax.swing.JLabel jlblfaximale;
    private javax.swing.JLabel jlblphone;
    private javax.swing.JLabel jlblpic;
    private javax.swing.JLabel jlblstate;
    private javax.swing.JLabel jlblwarehouse_code;
    private javax.swing.JLabel jlblwarehouse_name;
    private javax.swing.JLabel jlblwarehouse_type;
    private javax.swing.JLabel jlblzipcode;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JLabel jtxt_whstypedesc;
    private javax.swing.JTextField jtxtaddress1;
    private javax.swing.JTextField jtxtaddress2;
    private javax.swing.JTextField jtxtcity;
    private javax.swing.JTextField jtxtemail;
    private javax.swing.JTextField jtxtfaximale;
    private javax.swing.JTextField jtxtphone;
    private javax.swing.JTextField jtxtpic;
    private javax.swing.JTextField jtxtstate;
    private javax.swing.JTextField jtxtwarehouse_code;
    private javax.swing.JTextField jtxtwarehouse_name;
    private javax.swing.JTextField jtxtwarehouse_type;
    private javax.swing.JTextField jtxtzipcode;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        //jtxtid.setText("");
        jtxtwarehouse_code.setText("");
        jtxtwarehouse_name.setText("");
        //jtxtcheck_oh.setText("");
        chck_onhand.setSelected(false);
        jtxtaddress1.setText("");
        jtxtaddress2.setText("");
        jtxtcity.setText("");
        jtxtstate.setText("");
        jtxtzipcode.setText("");
        jtxtphone.setText("");
        jtxtfaximale.setText("");
        jtxtemail.setText("");
        jtxtpic.setText("");
        jtxtwarehouse_type.setText("");
        jtxt_whstypedesc.setText("");
        //jtxtentrydate.setText("");
        //jtxtauditdate.setText("");
        //jtxtaudituser.setText("");
        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");
    }

    public void newData() throws CodeException {
        istatus=1;
        clearfield();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.update();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        //jtxtid.setText(obj.getid());
        jtxtwarehouse_code.setText(obj.getwarehouse_code());
        jtxtwarehouse_name.setText(obj.getwarehouse_name());
        //jtxtcheck_oh.setText(obj.getcheck_oh());
        if(obj.getcheck_oh().equalsIgnoreCase("Y")){
            chck_onhand.setSelected(true);
        }else{
            chck_onhand.setSelected(false);
        }
        jtxtaddress1.setText(obj.getaddress1());
        jtxtaddress2.setText(obj.getaddress2());
        jtxtcity.setText(obj.getcity());
        jtxtstate.setText(obj.getstate());
        jtxtzipcode.setText(obj.getzipcode());
        jtxtphone.setText(obj.getphone());
        jtxtfaximale.setText(obj.getfaximale());
        jtxtemail.setText(obj.getemail());
        jtxtpic.setText(obj.getpic());
        jtxtwarehouse_type.setText(obj.getwarehouse_type());
        //jtxtentrydate.setText(obj.getentrydate());
        //jtxtauditdate.setText(obj.getauditdate());
        //jtxtaudituser.setText(obj.getaudituser());
        jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getentrydate()));
        jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getauditdate()));
        jtxtUserID.setText(obj.getaudituser());

        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        if (obj.delete()){
            obj.moveNext();
            showData();
        }
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);

        if (istatus==1){
            jbtnBrowse.setEnabled(false);
        } else {
            jbtnBrowse.setEnabled(true);
        }
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }
        //obj.setid(jtxtid.getText());
        obj.setwarehouse_code(jtxtwarehouse_code.getText());
        obj.setwarehouse_name(jtxtwarehouse_name.getText());
        obj.setcheck_oh(isonhand);

        obj.setaddress1(jtxtaddress1.getText());
        obj.setaddress2(jtxtaddress2.getText());
        obj.setcity(jtxtcity.getText());
        obj.setstate(jtxtstate.getText());
        obj.setzipcode(jtxtzipcode.getText());
        obj.setphone(jtxtphone.getText());
        obj.setfaximale(jtxtfaximale.getText());
        obj.setemail(jtxtemail.getText());
        obj.setpic(jtxtpic.getText());
        obj.setwarehouse_type(jtxtwarehouse_type.getText());
        //obj.setentrydate(jtxtentrydate.getText());
        //obj.setauditdate(jtxtauditdate.getText());
        //obj.setaudituser(jtxtaudituser.getText());
        //obj.setInterval(jcmbInterval.getSelectedItem().toString());

    }

    public void undo() throws CodeException {
        istatus = 0;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    
}
