/*
 * test.java
 *
 * Created on March 9, 2007, 8:31 AM
 */

package kopkar.ar.component;

import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import jdbc.DbBean;
import kopkar.ar.objectclasses.ar_pos_returnext;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import utils.CodeException;
import utils.GlobalUtils;
import utils.appsettinghandler;


/**
 *
 * @author  ISParthama
 */
public class frmar_pos_return_payment extends javax.swing.JDialog {
    
    DbBean db=appsettinghandler.db;
    private DefaultTableModel model;
    private ar_pos_returnext obj;
    private JasperReport jasperReport;
    private JasperPrint jasperPrint;
    private HashMap parameter;
    
    public frmar_pos_return_payment(ar_pos_returnext obj) {
        initComponents();
        this.obj=obj;
        int i=0;
        showdata();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jHeader = new javax.swing.JLabel();
        jtxtjumlah_item = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxttotal_bfr_discount = new javax.swing.JTextField();
        jchkinclude_tax = new javax.swing.JCheckBox();
        jtxttax_percent = new javax.swing.JTextField();
        jtxttotal_discount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtpayment_voucher = new javax.swing.JTextField();
        jtxtvoucher_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtpayment_credit_card = new javax.swing.JTextField();
        jtxtcredit_card_name = new javax.swing.JTextField();
        jHeader1 = new javax.swing.JLabel();
        jHeader2 = new javax.swing.JLabel();
        jHeader3 = new javax.swing.JLabel();
        jtxtcredit_card_number = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtpayment_debit_card = new javax.swing.JTextField();
        jtxtdebit_card_name = new javax.swing.JTextField();
        jtxtdebit_card_number = new javax.swing.JTextField();
        optpayment_salary_potong_gaji = new javax.swing.JRadioButton();
        optpayment_salary_status_tunai = new javax.swing.JRadioButton();
        jtxttotal_aft_tax3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtpayment_salary = new javax.swing.JTextField();
        jtxttotal_aft_tax5 = new javax.swing.JTextField();
        jtxtpayment_cash = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 10));
        jButton1.setText("Cetak Faktur (F12)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(12, 399, 140, 25);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 10));
        jButton2.setText("Keluar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 400, 90, 25);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel1.setText("Jumlah Item");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 60, 67, 13);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHeader.setText("Nama Kartu");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(360, 190, 150, 20);

        jtxtjumlah_item.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtjumlah_item.setFocusable(false);
        getContentPane().add(jtxtjumlah_item);
        jtxtjumlah_item.setBounds(210, 60, 150, 23);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel2.setText("Potongan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 100, 54, 13);

        jtxttotal_bfr_discount.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttotal_bfr_discount.setText("customer_code");
        jtxttotal_bfr_discount.setFocusable(false);
        jtxttotal_bfr_discount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttotal_bfr_discountFocusGained(evt);
            }
        });
        jtxttotal_bfr_discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxttotal_bfr_discountKeyPressed(evt);
            }
        });
        getContentPane().add(jtxttotal_bfr_discount);
        jtxttotal_bfr_discount.setBounds(210, 80, 150, 23);

        jchkinclude_tax.setFont(new java.awt.Font("Dialog", 0, 10));
        jchkinclude_tax.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jchkinclude_taxItemStateChanged(evt);
            }
        });
        jchkinclude_tax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jchkinclude_taxKeyPressed(evt);
            }
        });
        getContentPane().add(jchkinclude_tax);
        jchkinclude_tax.setBounds(150, 100, 20, 24);

        jtxttax_percent.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttax_percent.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxttax_percent.setText("tax_percent");
        jtxttax_percent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttax_percentFocusGained(evt);
            }
        });
        jtxttax_percent.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jtxttax_percentPropertyChange(evt);
            }
        });
        jtxttax_percent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxttax_percentKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxttax_percentKeyReleased(evt);
            }
        });
        getContentPane().add(jtxttax_percent);
        jtxttax_percent.setBounds(170, 100, 40, 23);

        jtxttotal_discount.setEditable(false);
        jtxttotal_discount.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxttotal_discount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxttotal_discount.setText("tax_amount");
        jtxttotal_discount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttotal_discountFocusGained(evt);
            }
        });
        jtxttotal_discount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxttotal_discountKeyPressed(evt);
            }
        });
        getContentPane().add(jtxttotal_discount);
        jtxttotal_discount.setBounds(210, 100, 150, 23);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel3.setText("Sub TOtal");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 80, 54, 13);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel4.setText("Voucher");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 120, 48, 13);

        jtxtpayment_voucher.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtpayment_voucher.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtpayment_voucher.setText("customer_code");
        jtxtpayment_voucher.setNextFocusableComponent(jtxttotal_aft_tax5);
        jtxtpayment_voucher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtpayment_voucherFocusGained(evt);
            }
        });
        jtxtpayment_voucher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtpayment_voucherKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtpayment_voucherKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtpayment_voucher);
        jtxtpayment_voucher.setBounds(210, 120, 150, 23);

        jtxtvoucher_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtvoucher_name.setText("customer_code");
        jtxtvoucher_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtvoucher_nameFocusGained(evt);
            }
        });
        jtxtvoucher_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtvoucher_nameKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtvoucher_name);
        jtxtvoucher_name.setBounds(360, 120, 150, 23);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel5.setText("Credit Card");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 210, 150, 13);

        jtxtpayment_credit_card.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtpayment_credit_card.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtpayment_credit_card.setText("jtxtnilai");
        jtxtpayment_credit_card.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtpayment_credit_cardFocusGained(evt);
            }
        });
        jtxtpayment_credit_card.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtpayment_credit_cardKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtpayment_credit_cardKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtpayment_credit_card);
        jtxtpayment_credit_card.setBounds(210, 210, 150, 23);

        jtxtcredit_card_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcredit_card_name.setText("jtxtnama_kartu");
        jtxtcredit_card_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcredit_card_nameFocusGained(evt);
            }
        });
        jtxtcredit_card_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtcredit_card_nameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcredit_card_nameKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtcredit_card_name);
        jtxtcredit_card_name.setBounds(360, 210, 150, 23);

        jHeader1.setBackground(new java.awt.Color(102, 102, 102));
        jHeader1.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader1.setForeground(new java.awt.Color(255, 255, 255));
        jHeader1.setText(" :: Bayar Faktur Point of Sales");
        jHeader1.setAlignmentY(0.0F);
        jHeader1.setOpaque(true);
        getContentPane().add(jHeader1);
        jHeader1.setBounds(10, 20, 200, 20);

        jHeader2.setBackground(new java.awt.Color(102, 102, 102));
        jHeader2.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader2.setForeground(new java.awt.Color(255, 255, 255));
        jHeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHeader2.setText("Nilai");
        jHeader2.setAlignmentY(0.0F);
        jHeader2.setOpaque(true);
        getContentPane().add(jHeader2);
        jHeader2.setBounds(210, 190, 150, 20);

        jHeader3.setBackground(new java.awt.Color(102, 102, 102));
        jHeader3.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader3.setForeground(new java.awt.Color(255, 255, 255));
        jHeader3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jHeader3.setText("No. Kartu");
        jHeader3.setAlignmentY(0.0F);
        jHeader3.setOpaque(true);
        getContentPane().add(jHeader3);
        jHeader3.setBounds(510, 190, 150, 20);

        jtxtcredit_card_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtcredit_card_number.setText("jtxtno_kartu");
        jtxtcredit_card_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtcredit_card_numberFocusGained(evt);
            }
        });
        jtxtcredit_card_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtcredit_card_numberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcredit_card_numberKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtcredit_card_number);
        jtxtcredit_card_number.setBounds(510, 210, 150, 23);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel6.setText("Kembali");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 350, 240, 13);

        jtxtpayment_debit_card.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtpayment_debit_card.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtpayment_debit_card.setText("jtxtnilai");
        jtxtpayment_debit_card.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtpayment_debit_cardFocusGained(evt);
            }
        });
        jtxtpayment_debit_card.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtpayment_debit_cardKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtpayment_debit_cardKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtpayment_debit_card);
        jtxtpayment_debit_card.setBounds(210, 230, 150, 23);

        jtxtdebit_card_name.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdebit_card_name.setText("jtxtnama_kartu");
        jtxtdebit_card_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdebit_card_nameFocusGained(evt);
            }
        });
        jtxtdebit_card_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtdebit_card_nameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtdebit_card_nameKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtdebit_card_name);
        jtxtdebit_card_name.setBounds(360, 230, 150, 23);

        jtxtdebit_card_number.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtdebit_card_number.setText("jtxtno_kartu");
        jtxtdebit_card_number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtdebit_card_numberFocusGained(evt);
            }
        });
        jtxtdebit_card_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtdebit_card_numberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtdebit_card_numberKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtdebit_card_number);
        jtxtdebit_card_number.setBounds(510, 230, 150, 23);

        buttonGroup1.add(optpayment_salary_potong_gaji);
        optpayment_salary_potong_gaji.setFont(new java.awt.Font("Dialog", 1, 10));
        optpayment_salary_potong_gaji.setText("Potong Gaji");
        optpayment_salary_potong_gaji.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                optpayment_salary_potong_gajiItemStateChanged(evt);
            }
        });
        optpayment_salary_potong_gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optpayment_salary_potong_gajiActionPerformed(evt);
            }
        });
        optpayment_salary_potong_gaji.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                optpayment_salary_potong_gajiPropertyChange(evt);
            }
        });
        optpayment_salary_potong_gaji.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                optpayment_salary_potong_gajiKeyPressed(evt);
            }
        });
        getContentPane().add(optpayment_salary_potong_gaji);
        optpayment_salary_potong_gaji.setBounds(140, 260, 130, 24);

        buttonGroup1.add(optpayment_salary_status_tunai);
        optpayment_salary_status_tunai.setFont(new java.awt.Font("Dialog", 1, 10));
        optpayment_salary_status_tunai.setSelected(true);
        optpayment_salary_status_tunai.setText("Tunai");
        optpayment_salary_status_tunai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                optpayment_salary_status_tunaiItemStateChanged(evt);
            }
        });
        optpayment_salary_status_tunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optpayment_salary_status_tunaiActionPerformed(evt);
            }
        });
        optpayment_salary_status_tunai.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                optpayment_salary_status_tunaiPropertyChange(evt);
            }
        });
        optpayment_salary_status_tunai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                optpayment_salary_status_tunaiKeyPressed(evt);
            }
        });
        getContentPane().add(optpayment_salary_status_tunai);
        optpayment_salary_status_tunai.setBounds(50, 260, 80, 24);

        jtxttotal_aft_tax3.setEditable(false);
        jtxttotal_aft_tax3.setFont(new java.awt.Font("Dialog", 1, 24));
        jtxttotal_aft_tax3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxttotal_aft_tax3.setText("total_aft_tax");
        jtxttotal_aft_tax3.setFocusable(false);
        jtxttotal_aft_tax3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttotal_aft_tax3FocusGained(evt);
            }
        });
        jtxttotal_aft_tax3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxttotal_aft_tax3KeyPressed(evt);
            }
        });
        getContentPane().add(jtxttotal_aft_tax3);
        jtxttotal_aft_tax3.setBounds(290, 340, 370, 40);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel7.setText("Debet Card");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 230, 150, 13);

        jtxtpayment_salary.setEditable(false);
        jtxtpayment_salary.setFont(new java.awt.Font("Dialog", 1, 24));
        jtxtpayment_salary.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtpayment_salary.setText("total_aft_tax");
        jtxtpayment_salary.setFocusable(false);
        jtxtpayment_salary.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtpayment_salaryFocusGained(evt);
            }
        });
        jtxtpayment_salary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtpayment_salaryKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtpayment_salaryKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtpayment_salary);
        jtxtpayment_salary.setBounds(290, 260, 370, 40);

        jtxttotal_aft_tax5.setEditable(false);
        jtxttotal_aft_tax5.setFont(new java.awt.Font("Dialog", 1, 24));
        jtxttotal_aft_tax5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxttotal_aft_tax5.setText("total_aft_tax");
        jtxttotal_aft_tax5.setFocusable(false);
        jtxttotal_aft_tax5.setNextFocusableComponent(jtxtpayment_credit_card);
        jtxttotal_aft_tax5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxttotal_aft_tax5FocusGained(evt);
            }
        });
        jtxttotal_aft_tax5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxttotal_aft_tax5KeyPressed(evt);
            }
        });
        getContentPane().add(jtxttotal_aft_tax5);
        jtxttotal_aft_tax5.setBounds(290, 150, 370, 40);

        jtxtpayment_cash.setFont(new java.awt.Font("Dialog", 1, 24));
        jtxtpayment_cash.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtpayment_cash.setText("total_aft_tax");
        jtxtpayment_cash.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtpayment_cashFocusGained(evt);
            }
        });
        jtxtpayment_cash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtpayment_cashKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtpayment_cashKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtpayment_cash);
        jtxtpayment_cash.setBounds(290, 300, 370, 40);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24));
        jLabel8.setText("Nilai Faktur");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 153, 240, 30);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 10));
        jLabel9.setText("Bayar");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 310, 240, 13);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        exit();       					// free the system resources
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        doSelect();
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtjumlah_itemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtjumlah_itemFocusGained
        // TODO add your handling code here:
        jtxtjumlah_item.setSelectionStart(0);
        jtxtjumlah_item.setSelectionEnd(jtxtjumlah_item.getText().length());
}//GEN-LAST:event_jtxtjumlah_itemFocusGained

    private void jtxtjumlah_itemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtjumlah_itemKeyPressed
        // TODO add your handling code here:
        runaction(evt);
}//GEN-LAST:event_jtxtjumlah_itemKeyPressed

    private void jtxttotal_bfr_discountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxttotal_bfr_discountFocusGained
        // TODO add your handling code here:
        jtxttotal_bfr_discount.setSelectionStart(0);
        jtxttotal_bfr_discount.setSelectionEnd(jtxttotal_bfr_discount.getText().length());
    }//GEN-LAST:event_jtxttotal_bfr_discountFocusGained

    private void jtxttotal_bfr_discountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxttotal_bfr_discountKeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jtxttotal_bfr_discountKeyPressed

    private void jchkinclude_taxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jchkinclude_taxItemStateChanged
        // TODO add your handling code here:
        if (!jchkinclude_tax.isSelected()){
            obj.setpayment_discount(new Double(0));
            obj.settotal_discount(new Double(0));
            jtxttax_percent.setText("0");
            jtxttotal_discount.setText("0");

        }
}//GEN-LAST:event_jchkinclude_taxItemStateChanged

    private void jtxttax_percentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxttax_percentFocusGained
        // TODO add your handling code here:
        jtxttax_percent.setSelectionStart(0);
        jtxttax_percent.setSelectionEnd(jtxttax_percent.getText().length());
    }//GEN-LAST:event_jtxttax_percentFocusGained

    private void jtxttotal_discountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxttotal_discountFocusGained
        // TODO add your handling code here:
         jtxttotal_discount.setSelectionStart(0);
        jtxttotal_discount.setSelectionEnd(jtxttotal_discount.getText().length());
    }//GEN-LAST:event_jtxttotal_discountFocusGained

    private void jtxtpayment_voucherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtpayment_voucherFocusGained
        // TODO add your handling code here:
        jtxtpayment_voucher.setSelectionStart(0);
        jtxtpayment_voucher.setSelectionEnd(jtxtpayment_voucher.getText().length());
    }//GEN-LAST:event_jtxtpayment_voucherFocusGained

    private void jtxtpayment_voucherKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpayment_voucherKeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jtxtpayment_voucherKeyPressed

    private void jtxtvoucher_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtvoucher_nameFocusGained
        // TODO add your handling code here:
        jtxtvoucher_name.setSelectionStart(0);
        jtxtvoucher_name.setSelectionEnd(jtxtvoucher_name.getText().length());
    }//GEN-LAST:event_jtxtvoucher_nameFocusGained

    private void jtxtvoucher_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtvoucher_nameKeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jtxtvoucher_nameKeyPressed

    private void jtxtpayment_credit_cardFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtpayment_credit_cardFocusGained
        // TODO add your handling code here:
        jtxtpayment_credit_card.setSelectionStart(0);
        jtxtpayment_credit_card.setSelectionEnd(jtxtpayment_credit_card.getText().length());
    }//GEN-LAST:event_jtxtpayment_credit_cardFocusGained

    private void jtxtpayment_credit_cardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpayment_credit_cardKeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jtxtpayment_credit_cardKeyPressed

    private void jtxtcredit_card_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtcredit_card_nameFocusGained
        // TODO add your handling code here:
        jtxtcredit_card_name.setSelectionStart(0);
        jtxtcredit_card_name.setSelectionEnd(jtxtcredit_card_name.getText().length());
    }//GEN-LAST:event_jtxtcredit_card_nameFocusGained

    private void jtxtcredit_card_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcredit_card_nameKeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jtxtcredit_card_nameKeyPressed

    private void jtxtcredit_card_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtcredit_card_numberFocusGained
        // TODO add your handling code here:
        jtxtcredit_card_number.setSelectionStart(0);
        jtxtcredit_card_number.setSelectionEnd(jtxtcredit_card_number.getText().length());
    }//GEN-LAST:event_jtxtcredit_card_numberFocusGained

    private void jtxtcredit_card_numberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcredit_card_numberKeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jtxtcredit_card_numberKeyPressed

    private void jtxtpayment_debit_cardFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtpayment_debit_cardFocusGained
        // TODO add your handling code here:
        jtxtpayment_debit_card.setSelectionStart(0);
        jtxtpayment_debit_card.setSelectionEnd(jtxtpayment_debit_card.getText().length());
    }//GEN-LAST:event_jtxtpayment_debit_cardFocusGained

    private void jtxtpayment_debit_cardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpayment_debit_cardKeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jtxtpayment_debit_cardKeyPressed

    private void jtxtdebit_card_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdebit_card_nameFocusGained
        // TODO add your handling code here:
        jtxtdebit_card_name.setSelectionStart(0);
        jtxtdebit_card_name.setSelectionEnd(jtxtdebit_card_name.getText().length());
    }//GEN-LAST:event_jtxtdebit_card_nameFocusGained

    private void jtxtdebit_card_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtdebit_card_nameKeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jtxtdebit_card_nameKeyPressed

    private void jtxtdebit_card_numberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtdebit_card_numberFocusGained
        // TODO add your handling code here:
        jtxtdebit_card_number.setSelectionStart(0);
        jtxtdebit_card_number.setSelectionEnd(jtxtdebit_card_number.getText().length());
    }//GEN-LAST:event_jtxtdebit_card_numberFocusGained

    private void jtxtdebit_card_numberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtdebit_card_numberKeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jtxtdebit_card_numberKeyPressed

    private void jtxttotal_aft_tax3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxttotal_aft_tax3FocusGained
        // TODO add your handling code here:
        jtxttotal_aft_tax3.setSelectionStart(0);
        jtxttotal_aft_tax3.setSelectionEnd(jtxttotal_aft_tax3.getText().length());
    }//GEN-LAST:event_jtxttotal_aft_tax3FocusGained

    private void jtxtpayment_salaryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtpayment_salaryFocusGained
        // TODO add your handling code here:
        jtxtpayment_salary.setSelectionStart(0);
        jtxtpayment_salary.setSelectionEnd(jtxtpayment_salary.getText().length());
    }//GEN-LAST:event_jtxtpayment_salaryFocusGained

    private void jtxttotal_aft_tax5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxttotal_aft_tax5FocusGained
        // TODO add your handling code here:
        jtxttotal_aft_tax5.setSelectionStart(0);
        jtxttotal_aft_tax5.setSelectionEnd(jtxttotal_aft_tax5.getText().length());
    }//GEN-LAST:event_jtxttotal_aft_tax5FocusGained

    private void jtxtpayment_cashFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtpayment_cashFocusGained
        // TODO add your handling code here:
        jtxtpayment_cash.setSelectionStart(0);
        jtxtpayment_cash.setSelectionEnd(jtxtpayment_cash.getText().length());
    }//GEN-LAST:event_jtxtpayment_cashFocusGained

    private void jtxtpayment_cashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpayment_cashKeyPressed
        // TODO add your handling code here:
        runaction(evt);
        hitungkembalian();
    }//GEN-LAST:event_jtxtpayment_cashKeyPressed

    private void jtxttax_percentPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jtxttax_percentPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtxttax_percentPropertyChange

    private void jtxttax_percentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxttax_percentKeyReleased
        // TODO add your handling code here:
        obj.settotal_discount(obj.gettotal_bfr_discount()*(GlobalUtils.toDbl(jtxttax_percent.getText())/100));
        jtxttotal_discount.setText(GlobalUtils.formatnumber(obj.gettotal_discount()));
        obj.settotal_aft_discount(obj.gettotal_bfr_discount()-obj.gettotal_discount()-obj.getpayment_voucher());
        calculatenetsales();


    }//GEN-LAST:event_jtxttax_percentKeyReleased

    private void jtxtpayment_voucherKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpayment_voucherKeyReleased
        // TODO add your handling code here:
        GlobalUtils.domasking(jtxtpayment_voucher);
        obj.setpayment_voucher(GlobalUtils.toDbl(jtxtpayment_voucher.getText()));
        obj.settotal_aft_discount(obj.gettotal_bfr_discount()-obj.gettotal_discount()-obj.getpayment_voucher());
        calculatenetsales();
    }//GEN-LAST:event_jtxtpayment_voucherKeyReleased

    private void jtxtpayment_credit_cardKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpayment_credit_cardKeyReleased
        // TODO add your handling code here:
        GlobalUtils.domasking(jtxtpayment_credit_card);
        obj.setpayment_credit_card(GlobalUtils.toDbl(jtxtpayment_credit_card.getText()));
        calculatepaymentsalary();
        
    }//GEN-LAST:event_jtxtpayment_credit_cardKeyReleased

    private void jtxtpayment_debit_cardKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpayment_debit_cardKeyReleased
        // TODO add your handling code here:
        GlobalUtils.domasking(jtxtpayment_debit_card);
        obj.setpayment_debit_card(GlobalUtils.toDbl(jtxtpayment_debit_card.getText()));
        calculatepaymentsalary();
    }//GEN-LAST:event_jtxtpayment_debit_cardKeyReleased

    private void jtxtpayment_salaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpayment_salaryKeyReleased
        // TODO add your handling code here:
        GlobalUtils.domasking(jtxtpayment_salary);
    }//GEN-LAST:event_jtxtpayment_salaryKeyReleased

    private void jtxtpayment_cashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpayment_cashKeyReleased
        // TODO add your handling code here:
        GlobalUtils.domasking(jtxtpayment_cash);
        obj.setpayment_cash(GlobalUtils.toDbl(jtxtpayment_cash.getText()));
        hitungkembalian();
    }//GEN-LAST:event_jtxtpayment_cashKeyReleased

    private void jtxtcredit_card_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcredit_card_nameKeyReleased
        // TODO add your handling code here:
        obj.setcredit_card_name(jtxtcredit_card_name.getText());
    }//GEN-LAST:event_jtxtcredit_card_nameKeyReleased

    private void jtxtcredit_card_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcredit_card_numberKeyReleased
        // TODO add your handling code here:
        obj.setcredit_card_number(jtxtcredit_card_number.getText());
    }//GEN-LAST:event_jtxtcredit_card_numberKeyReleased

    private void jtxtdebit_card_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtdebit_card_nameKeyReleased
        // TODO add your handling code here:
        obj.setdebit_card_name(jtxtdebit_card_name.getText());
    }//GEN-LAST:event_jtxtdebit_card_nameKeyReleased

    private void jtxtdebit_card_numberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtdebit_card_numberKeyReleased
        // TODO add your handling code here:
        obj.setdebit_card_number(jtxtdebit_card_number.getText());
    }//GEN-LAST:event_jtxtdebit_card_numberKeyReleased

    private void optpayment_salary_status_tunaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_optpayment_salary_status_tunaiItemStateChanged
        // TODO add your handling code here:
        doselection_salary();
    }//GEN-LAST:event_optpayment_salary_status_tunaiItemStateChanged

    private void optpayment_salary_potong_gajiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_optpayment_salary_potong_gajiItemStateChanged
        // TODO add your handling code here:
        doselection_salary();
    }//GEN-LAST:event_optpayment_salary_potong_gajiItemStateChanged

    private void jchkinclude_taxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jchkinclude_taxKeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jchkinclude_taxKeyPressed

    private void jtxttax_percentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxttax_percentKeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jtxttax_percentKeyPressed

    private void jtxttotal_discountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxttotal_discountKeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jtxttotal_discountKeyPressed

    private void optpayment_salary_status_tunaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_optpayment_salary_status_tunaiKeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_optpayment_salary_status_tunaiKeyPressed

    private void optpayment_salary_potong_gajiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_optpayment_salary_potong_gajiKeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_optpayment_salary_potong_gajiKeyPressed

    private void jtxtpayment_salaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtpayment_salaryKeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jtxtpayment_salaryKeyPressed

    private void jtxttotal_aft_tax5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxttotal_aft_tax5KeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jtxttotal_aft_tax5KeyPressed

    private void jtxttotal_aft_tax3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxttotal_aft_tax3KeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jtxttotal_aft_tax3KeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        runaction(evt);
    }//GEN-LAST:event_jButton2KeyPressed

    private void optpayment_salary_potong_gajiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_optpayment_salary_potong_gajiPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_optpayment_salary_potong_gajiPropertyChange

    private void optpayment_salary_status_tunaiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_optpayment_salary_status_tunaiPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_optpayment_salary_status_tunaiPropertyChange

    private void optpayment_salary_status_tunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optpayment_salary_status_tunaiActionPerformed
        // TODO add your handling code here:
        doselection_salary();
    }//GEN-LAST:event_optpayment_salary_status_tunaiActionPerformed

    private void optpayment_salary_potong_gajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optpayment_salary_potong_gajiActionPerformed
        // TODO add your handling code here:
        doselection_salary();
    }//GEN-LAST:event_optpayment_salary_potong_gajiActionPerformed
    
     
    /**
     * @param args the command line arguments
     */
     
     
    public static void main(String args[]) {
        
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jHeader;
    private javax.swing.JLabel jHeader1;
    private javax.swing.JLabel jHeader2;
    private javax.swing.JLabel jHeader3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox jchkinclude_tax;
    private javax.swing.JTextField jtxtcredit_card_name;
    private javax.swing.JTextField jtxtcredit_card_number;
    private javax.swing.JTextField jtxtdebit_card_name;
    private javax.swing.JTextField jtxtdebit_card_number;
    private javax.swing.JTextField jtxtjumlah_item;
    private javax.swing.JTextField jtxtpayment_cash;
    private javax.swing.JTextField jtxtpayment_credit_card;
    private javax.swing.JTextField jtxtpayment_debit_card;
    private javax.swing.JTextField jtxtpayment_salary;
    private javax.swing.JTextField jtxtpayment_voucher;
    private javax.swing.JTextField jtxttax_percent;
    private javax.swing.JTextField jtxttotal_aft_tax3;
    private javax.swing.JTextField jtxttotal_aft_tax5;
    private javax.swing.JTextField jtxttotal_bfr_discount;
    private javax.swing.JTextField jtxttotal_discount;
    private javax.swing.JTextField jtxtvoucher_name;
    private javax.swing.JRadioButton optpayment_salary_potong_gaji;
    private javax.swing.JRadioButton optpayment_salary_status_tunai;
    // End of variables declaration//GEN-END:variables

    private void doSelect() {
        try {
            if (obj.update()) {
                this.setVisible(false);
                parameter = new HashMap();
                parameter.put("document_number", obj.getdocument_number());
                // Versi 1
                String file = "";
                if (GlobalUtils.getAppDir()) {
                    try {
                        file = appsettinghandler.getAppPath() + "/Reports/Struk.jrxml";
                        jasperReport = JasperCompileManager.compileReport(file);
                        //System.out.println("file: "+file);
                        System.out.println("isi parameter sruk:" + parameter);
                        jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, db.getConnection());
                        JasperViewer.viewReport(jasperPrint, false);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        } catch (CodeException ex) {
            Logger.getLogger(frmar_pos_return_payment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void showdata() {
        clearfield();
        if (obj.getpayment_salary_status().equalsIgnoreCase("N")){
            optpayment_salary_status_tunai.setSelected(true);
        } else {
            optpayment_salary_potong_gaji.setSelected(true);
        }
        jtxtjumlah_item.setText(GlobalUtils.churuf(this.obj.getDetail1().size()));
        jtxtcredit_card_name.setText(this.obj.getcredit_card_name());
        jtxtdebit_card_name.setText(this.obj.getdebit_card_name());
        jtxtpayment_credit_card.setText(GlobalUtils.formatnumber(this.obj.getpayment_credit_card()));
        jtxtpayment_debit_card.setText(GlobalUtils.formatnumber(this.obj.getpayment_debit_card()));
        jtxtcredit_card_number.setText(this.obj.getcredit_card_number());
        jtxtdebit_card_number.setText(this.obj.getdebit_card_number());
        jtxttotal_discount.setText(GlobalUtils.formatnumber(this.obj.gettotal_discount()));
        jtxttax_percent.setText("0");
        jtxttotal_bfr_discount.setText(GlobalUtils.formatnumber(this.obj.gettotal_bfr_discount()));
        jtxtpayment_voucher.setText(GlobalUtils.formatnumber(this.obj.getpayment_voucher()));
        jtxtvoucher_name.setText(this.obj.getvoucher_name());
        calculatenetsales();
        jtxtpayment_salary.setText(GlobalUtils.formatnumber(obj.gettotal_net_sales()-(obj.getpayment_credit_card()+obj.getpayment_debit_card())));
        //jtxtpayment_salary.setText(GlobalUtils.formatnumber(this.obj.getpayment_salary()));
        jtxttotal_aft_tax5.setText(GlobalUtils.formatnumber(this.obj.gettotal_aft_discount()));
        jtxtpayment_cash.setText(GlobalUtils.formatnumber(this.obj.getpayment_cash()));
        jtxttotal_aft_tax3.setText(GlobalUtils.formatnumber(obj.getkembalian()));
    }

    private void clearfield() {
        jtxtjumlah_item.setText("0");
        jtxtcredit_card_name.setText("");
        jtxtdebit_card_name.setText("");
        jtxtpayment_credit_card.setText("0");
        jtxtpayment_debit_card.setText("0");
        jtxtcredit_card_number.setText("");
        jtxtdebit_card_number.setText("");
        jtxttotal_discount.setText("0");
        jtxttax_percent.setText("0");
        jtxttotal_bfr_discount.setText("0");
        jtxtpayment_voucher.setText("0");
        jtxtvoucher_name.setText("0");
        jtxttotal_aft_tax3.setText("0");
        jtxtpayment_salary.setText("0");
        jtxttotal_aft_tax5.setText("0");
        jtxtpayment_cash.setText("0");
    }

    private void hitungkembalian() {
        obj.setkembalian(obj.gettotal_net_sales()-(obj.getpayment_credit_card()+obj.getpayment_debit_card())-obj.getpayment_cash());
        jtxttotal_aft_tax3.setText(GlobalUtils.formatnumber(obj.getkembalian()));
    }

    private void calculatepaymentsalary() {
        if (optpayment_salary_potong_gaji.isSelected()){
            obj.setpayment_salary(obj.gettotal_net_sales()-(obj.getpayment_credit_card()+obj.getpayment_debit_card()));
        } else {
            obj.setpayment_salary(new Double(0));
        }
        jtxtpayment_salary.setText(GlobalUtils.formatnumber(obj.gettotal_net_sales()-(obj.getpayment_credit_card()+obj.getpayment_debit_card())));
        if (obj.getpayment_cash()>0){
        hitungkembalian();
        }
    }

    private void calculatenetsales() {
        obj.settotal_net_sales(obj.gettotal_bfr_discount()-(obj.gettotal_discount()+obj.getpayment_voucher()));
        jtxttotal_aft_tax5.setText(GlobalUtils.formatnumber(obj.gettotal_net_sales()));
        calculatepaymentsalary();
    }

    private void runaction(KeyEvent evt) {
        switch (evt.getKeyCode()){
            case KeyEvent.VK_F12:
                doSelect();
                break;
            case KeyEvent.VK_ESCAPE:
                exit();
                break;
        }
    }

    private void exit() {
        setVisible(false);     
    }

    private void doselection_salary() {
        calculatenetsales();
        calculatepaymentsalary();
        if (optpayment_salary_status_tunai.isSelected()){
            obj.setpayment_salary_status("N");
            jtxtpayment_cash.setText(GlobalUtils.formatnumber(obj.getpayment_cash()));
        } else {
            obj.setpayment_salary_status("Y");
            jtxtpayment_cash.setText(GlobalUtils.formatnumber(obj.getpayment_salary()));
        }
        
    }

    
    
}
