/*
 * FrmLogin.java
 *
 * Created on August 5, 2009, 12:38 PM
 * 
 * FrmLogin is used for user to log in to application
 * 
 * Please see :
 * - FrmMasteruser
 * - FrmMastergroup
 * - FrmMastermodule
 * 
 */

package common.component;

import common.objectclasses.Mastercompany;
import common.objectclasses.extended.MasterCompanyExt;
import common.objectclasses.extended.MasterUserExt;
import common.objectclasses.extended.Mastercompanycols;
import common.objectclasses.extended.Mastergroupdetailcols;
import jdbc.DbBean;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import utils.GlobalUtils;
import utils.appsettinghandler;

/**
 *
 * @author  wgata
 */
public class FrmLogin extends javax.swing.JDialog {

    FrmMainFrame fm;
    /** Creates new form frmLogin */
    public FrmLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public FrmLogin() {
        initComponents();

        try {
            Mastercompanycols mastercompanys  = new Mastercompanycols();
            mastercompanys.initdata();
            int i=0;
            for(i=0;i<mastercompanys.size();i++) {
                   Mastercompany m = mastercompanys.get(i);
                   jcmbCompany.addItem(m.getCompany());

                   if (m.getSelected()==1) {
                       jcmbCompany.setSelectedIndex(jcmbCompany.getItemCount()-1);
                   }
            }
        }catch(Exception e) {
            e.printStackTrace();
        }
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblUser = new javax.swing.JLabel();
        jlblPassword = new javax.swing.JLabel();
        jtxtUser = new javax.swing.JTextField();
        jtbnLogin = new javax.swing.JButton();
        jtxtPassword = new javax.swing.JPasswordField();
        jbtnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcmbCompany = new javax.swing.JComboBox();
        kbatchdate = new org.kazao.calendar.KazaoCalendarDate();
        jlblbatchdate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(100, 100));
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jlblUser.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblUser.setText("Username");
        getContentPane().add(jlblUser);
        jlblUser.setBounds(20, 20, 90, 13);

        jlblPassword.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblPassword.setText("Password");
        getContentPane().add(jlblPassword);
        jlblPassword.setBounds(20, 50, 90, 20);

        jtxtUser.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtUser.setToolTipText("Username");
        jtxtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtUserKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtUser);
        jtxtUser.setBounds(110, 20, 100, 23);

        jtbnLogin.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtbnLogin.setText("Login");
        jtbnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jtbnLogin);
        jtbnLogin.setBounds(50, 140, 88, 25);

        jtxtPassword.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtPassword);
        jtxtPassword.setBounds(110, 50, 100, 23);

        jbtnExit.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit);
        jbtnExit.setBounds(150, 140, 90, 25);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel1.setText("Company");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 80, 80, 13);

        jcmbCompany.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jcmbCompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcmbCompanyKeyPressed(evt);
            }
        });
        getContentPane().add(jcmbCompany);
        jcmbCompany.setBounds(110, 80, 120, 23);

        kbatchdate.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        kbatchdate.setFontDate(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        kbatchdate.setOpaque(false);
        getContentPane().add(kbatchdate);
        kbatchdate.setBounds(110, 110, 100, 20);

        jlblbatchdate.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblbatchdate.setText("Session Date");
        getContentPane().add(jlblbatchdate);
        jlblbatchdate.setBounds(20, 110, 140, 13);

        setSize(new java.awt.Dimension(303, 184));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed

    System.exit(0);
}//GEN-LAST:event_jbtnExitActionPerformed


private void login() {
    setCursor(GlobalUtils.HOURGLASSCURSOR);

    try {
        MasterUserExt mu = new MasterUserExt();

        if (mu.initdata(jtxtUser.getText())) {
            if (mu.getPassword().equals(jtxtPassword.getText())) {
                
                GlobalUtils.userid=mu.getUser();
                GlobalUtils.setAuditUser(mu.getNama());
                GlobalUtils.sessiondate=kbatchdate.getDate();
                GlobalUtils.sessiondate_mysql=GlobalUtils.formatDate(kbatchdate.getDate(),"yyyy-MM-dd");
                GlobalUtils.company=jcmbCompany.getSelectedItem().toString();

                setVisible(false); 

                MasterCompanyExt mcps = new MasterCompanyExt();
                if (mcps.initdata(jcmbCompany.getSelectedItem() + "")){
                    DbBean db=new DbBean(mcps.getDatabase());
                    db.connect();
                    appsettinghandler.db=db;
                }

                GlobalUtils.mastergroupdetails = new Mastergroupdetailcols();
                GlobalUtils.mastergroupdetails.initdata(mu.getUser(), jcmbCompany.getSelectedItem() + "") ;
                
                jtxtUser.setText("");
                jtxtPassword.setText("");

                DbBean  dbc = appsettinghandler.dbcom;
                try {
                        dbc.execute("Update mastercompany set selected = 0;");
                        dbc.execute("Update mastercompany set selected = 1 where company ='" + jcmbCompany.getSelectedItem() + "' ");
                                            
                }catch (Exception e) {
                    e.printStackTrace();
                }

                
            }else {
                JOptionPane.showMessageDialog(null, "Password Incorrect ", "login", JOptionPane.ERROR_MESSAGE);
                jtxtPassword.requestFocus();
                jtxtPassword.setSelectionStart(0);
                jtxtPassword.setSelectionEnd(jtxtPassword.getText().length());

            }
            
        }else {
            JOptionPane.showMessageDialog(null, "User Is Not Found ", "login", JOptionPane.ERROR_MESSAGE);
        }
    }catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Cannot connect to database");
        System.exit(1);
    }
    setCursor(GlobalUtils.NORMALCURSOR);

}
private void jtbnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnLoginActionPerformed

    login();
    
}//GEN-LAST:event_jtbnLoginActionPerformed

private void jtxtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPasswordKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        login();
    }
}//GEN-LAST:event_jtxtPasswordKeyPressed

private void jtxtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtUserKeyPressed

    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jtxtPassword.requestFocus();
    }
}//GEN-LAST:event_jtxtUserKeyPressed

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    // TODO add your handling code here:
    jtxtUser.requestFocusInWindow();
}//GEN-LAST:event_formWindowActivated

    private void jcmbCompanyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcmbCompanyKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==evt.VK_ENTER){
            login();
        }
    }//GEN-LAST:event_jcmbCompanyKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmLogin dialog = new FrmLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JComboBox jcmbCompany;
    private javax.swing.JLabel jlblPassword;
    private javax.swing.JLabel jlblUser;
    private javax.swing.JLabel jlblbatchdate;
    private javax.swing.JButton jtbnLogin;
    private javax.swing.JPasswordField jtxtPassword;
    public javax.swing.JTextField jtxtUser;
    private org.kazao.calendar.KazaoCalendarDate kbatchdate;
    // End of variables declaration//GEN-END:variables

}
