/*
 * From Template
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmMastermodule;
 * 
 * .......
 * 
 try {
        if (frmmastermodule == null) {
            frmmastermodule = new FrmMastermodule(this);
        }
        
        showForm(frmmastermodule);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package common.component;

import classinterface.NavigatorFormInt;
import common.objectclasses.extended.MasterModuleExt;
import java.util.logging.Level;
import java.util.logging.Logger;
import kopkar.utils.browsecontroller;
import utils.CodeException;
import utils.GlobalUtils;


/**
 *
 * @author  Generator
 */

public class FrmMastermodule extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    protected static int iformtype = 0;
    public static String CLASSNAME="FrmMastermodule";
    
    FrmMainFrame mf ;
    
    
    public MasterModuleExt obj = new MasterModuleExt();
    private MasterModuleExt objtmp;
    
   
    /** Creates new form Area */
    public FrmMastermodule() throws CodeException {
        initComponents();
    }
    
    public FrmMastermodule(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }

    protected void inisialisasicomponents(){
        initComponents();
    }
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jlblModule = new javax.swing.JLabel();
        jtxtModule = new javax.swing.JTextField();
        jlblDescription = new javax.swing.JLabel();
        jtxtDescription = new javax.swing.JTextField();
        jbtnBrowse = new javax.swing.JButton();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mastermodule");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10));
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : Mastermodule");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 130, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jlblModule.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblModule.setText("Module");
        getContentPane().add(jlblModule);
        jlblModule.setBounds(70, 100, 140, 13);

        jtxtModule.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtModule.setText("Module");
        getContentPane().add(jtxtModule);
        jtxtModule.setBounds(260, 100, 180, 23);

        jlblDescription.setFont(new java.awt.Font("Dialog", 1, 10));
        jlblDescription.setText("Description");
        getContentPane().add(jlblDescription);
        jlblDescription.setBounds(70, 120, 140, 13);

        jtxtDescription.setFont(new java.awt.Font("Dialog", 0, 10));
        jtxtDescription.setText("Description");
        getContentPane().add(jtxtDescription);
        jtxtDescription.setBounds(260, 120, 300, 23);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10));
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(450, 100, 30, 17);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(530, 30, 130, 20);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(360, 30, 170, 20);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8));
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(660, 30, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowseActionPerformed
    browsecontroller obrowse=new browsecontroller();
    obrowse.showbrowser(obrowse.mastermodule, "", jtxtModule);
    if (!jtxtModule.getText().equalsIgnoreCase("")){
            try {
                if (obj.initdata(jtxtModule.getText())){
                    showData();
                }
            } catch (CodeException ex) {
                Logger.getLogger(FrmMastermodule.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
}//GEN-LAST:event_jbtnBrowseActionPerformed


    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
        setToolBar(iformtype,istatus);
        mfseticon();

    }

	
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmMastermodule().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JLabel jlblDescription;
    private javax.swing.JLabel jlblModule;
    private javax.swing.JTextField jtxtDescription;
    private javax.swing.JTextField jtxtModule;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        showData();
        mfseticon();
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();
        showData();
        mfseticon();
    }

    public void moveNext() throws CodeException {
        obj.moveNext();
        showData();
        mfseticon();
    }

    public void moveLast() throws CodeException {
        obj.moveLast();
        showData();
        mfseticon();
    }

    public void searchData() throws CodeException {
        obj = new MasterModuleExt();
        obj.initdata(this.jtxtModule.getText());
        showData();
        mfseticon();
    }
    public void newData() throws CodeException {
        objtmp=obj;
        obj = new MasterModuleExt();
        istatus=1;
        showData();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.update();
        
        showData();
        istatus = 0;
        setToolBar(iformtype,istatus);
        mfseticon();
    }

    public void showData() throws CodeException {
            setCursor(GlobalUtils.HOURGLASSCURSOR);
	
             jtxtModule.setText(obj.getModule());
             jtxtDescription.setText(obj.getDescription());
             jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getTanggalEntry()));
             jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getTanggalUpdate()));
             jtxtUserID.setText(obj.getUserId());
             
            setCursor(GlobalUtils.NORMALCURSOR);

    }

    public void delete() throws CodeException {
        obj.delete();
        obj.moveFirst();
        showData();
        mfseticon();
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);        
    }

    public void setData() throws CodeException {
        
          if (istatus==1){
              obj.insert();
          }
          obj.setModule(jtxtModule.getText()) ;
          obj.setDescription(jtxtDescription.getText()) ;
          
    }

    public void undo() throws CodeException {
        obj=objtmp;
        istatus = 0;
        moveFirst();
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }


    public void importCsv() throws CodeException {
       
    }

    public void exportCsv() throws CodeException {
        
    }

    public void importText() throws CodeException {
       
    }

    public void exportText() throws CodeException {
       
    }
    public void printData() throws CodeException {
       
    }

    protected void mfseticon() {
        mf.setIcon(CLASSNAME);
    }
    
}
