/*
 * From report_files
 *
 * Created on June 29, 2007, 2:00 PM
 * 
 * 
 * How to Call this Form on FrmMainFrame
 * Sample : 
 *    
 * import common.component.FrmCompany;
 * 
 * .......
 * 
 * 
 * FrmCompany frmCompany;
 * 
 * .......
 * 
 try {
        if (frmCompany == null) {
            frmmCompany = new FrmCompany(this);
        }
        
        showForm(frmCompany);
        
    }catch(Exception e) {
        e.printStackTrace();
    }
 * 
 */

package kopkar.report_files.component;


import classinterface.NavigatorFormInt;
import common.component.FrmBrowseData;
import common.component.FrmMainFrame;
import kopkar.report_files.objectclasses.report_filesext;
import java.util.logging.Level;
import java.util.logging.Logger;
import kopkar.report_files.objectclasses.report_categoryext;
import kopkar.utils.browsecontroller;
import utils.CodeException;
import utils.GlobalUtils;

/**
 *
 * @author  Generator
 */

public class Frmreport_files extends javax.swing.JInternalFrame implements NavigatorFormInt {

    private static int istatus = 0;
    private static int iformtype = 0;
    public static String CLASSNAME="Frmreport_files";
    
    browsecontroller obrowse=new browsecontroller();
    
    FrmMainFrame mf ;

    report_filesext obj=new report_filesext();
   
    /** Creates new form Area */
    public Frmreport_files() throws CodeException {
        initComponents();
    }
    
    public Frmreport_files(FrmMainFrame mf) throws CodeException{
        this.mf = mf;
        initComponents();
    }
     
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JLabel();
        HorizontalLine = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jbtnBrowse = new javax.swing.JButton();
        jlblreport_code = new javax.swing.JLabel();
        jtxtreport_code = new javax.swing.JTextField();
        jlblreport_desc = new javax.swing.JLabel();
        jtxtreport_desc = new javax.swing.JTextField();
        jlblreport_category_code = new javax.swing.JLabel();
        jtxtreport_category_code = new javax.swing.JTextField();
        jlblreport_file = new javax.swing.JLabel();
        jtxtreport_file = new javax.swing.JTextField();
        jtxtTanggalEntry = new javax.swing.JTextField();
        jtxtTanggalUpdate = new javax.swing.JTextField();
        jtxtUserID = new javax.swing.JTextField();
        jbtnBrowse1 = new javax.swing.JButton();
        jtxtreport_category_desc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("report_files");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jHeader.setBackground(new java.awt.Color(102, 102, 102));
        jHeader.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jHeader.setForeground(new java.awt.Color(255, 255, 255));
        jHeader.setText(" : : report_files");
        jHeader.setAlignmentY(0.0F);
        jHeader.setOpaque(true);
        getContentPane().add(jHeader);
        jHeader.setBounds(30, 30, 200, 20);

        HorizontalLine.setForeground(new java.awt.Color(102, 102, 102));
        HorizontalLine.setAlignmentX(0.0F);
        HorizontalLine.setAlignmentY(0.0F);
        getContentPane().add(HorizontalLine);
        HorizontalLine.setBounds(160, 50, 650, 6);

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.0F);
        jSeparator3.setAlignmentY(0.0F);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(30, 50, 6, 400);

        jbtnBrowse.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowse.setText("...");
        jbtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse);
        jbtnBrowse.setBounds(420, 80, 30, 17);

        jlblreport_code.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblreport_code.setText("Report Code");
        getContentPane().add(jlblreport_code);
        jlblreport_code.setBounds(70, 80, 140, 13);

        jtxtreport_code.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtreport_code.setText("report_code");
        jtxtreport_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtreport_codeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtreport_code);
        jtxtreport_code.setBounds(260, 80, 150, 23);

        jlblreport_desc.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblreport_desc.setText("Report Description");
        getContentPane().add(jlblreport_desc);
        jlblreport_desc.setBounds(70, 100, 140, 13);

        jtxtreport_desc.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtreport_desc.setText("report_desc");
        jtxtreport_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtreport_descFocusGained(evt);
            }
        });
        getContentPane().add(jtxtreport_desc);
        jtxtreport_desc.setBounds(260, 100, 400, 23);

        jlblreport_category_code.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblreport_category_code.setText("Report Category");
        getContentPane().add(jlblreport_category_code);
        jlblreport_category_code.setBounds(70, 120, 140, 13);

        jtxtreport_category_code.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtreport_category_code.setText("report_category_code");
        jtxtreport_category_code.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtreport_category_codeFocusGained(evt);
            }
        });
        getContentPane().add(jtxtreport_category_code);
        jtxtreport_category_code.setBounds(260, 120, 100, 23);

        jlblreport_file.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jlblreport_file.setText("Report File");
        getContentPane().add(jlblreport_file);
        jlblreport_file.setBounds(70, 140, 140, 13);

        jtxtreport_file.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtreport_file.setText("report_file");
        jtxtreport_file.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtreport_fileFocusGained(evt);
            }
        });
        getContentPane().add(jtxtreport_file);
        jtxtreport_file.setBounds(260, 140, 400, 23);

        jtxtTanggalEntry.setEditable(false);
        jtxtTanggalEntry.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtTanggalEntry.setText("TanggalEntry");
        getContentPane().add(jtxtTanggalEntry);
        jtxtTanggalEntry.setBounds(360, 30, 170, 20);

        jtxtTanggalUpdate.setEditable(false);
        jtxtTanggalUpdate.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtTanggalUpdate.setText("TanggalUpdate");
        getContentPane().add(jtxtTanggalUpdate);
        jtxtTanggalUpdate.setBounds(530, 30, 130, 20);

        jtxtUserID.setEditable(false);
        jtxtUserID.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jtxtUserID.setText("UserID");
        getContentPane().add(jtxtUserID);
        jtxtUserID.setBounds(660, 30, 140, 20);

        jbtnBrowse1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jbtnBrowse1.setText("...");
        jbtnBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrowse1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBrowse1);
        jbtnBrowse1.setBounds(370, 120, 30, 17);

        jtxtreport_category_desc.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jtxtreport_category_desc.setText("report_code");
        jtxtreport_category_desc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtreport_category_descFocusGained(evt);
            }
        });
        getContentPane().add(jtxtreport_category_desc);
        jtxtreport_category_desc.setBounds(410, 120, 250, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
         try {
            moveFirst();

         } catch (CodeException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formInternalFrameOpened

private void kdatePurchaseDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kdatePurchaseDateFocusLost

}//GEN-LAST:event_kdatePurchaseDateFocusLost

private void kdatePurchaseDateCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_kdatePurchaseDateCaretPositionChanged

}//GEN-LAST:event_kdatePurchaseDateCaretPositionChanged

private void kdatePurchaseDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kdatePurchaseDatePropertyChange

}//GEN-LAST:event_kdatePurchaseDatePropertyChange

    private void jbtnBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrowse1ActionPerformed
        // TODO add your handling code here:
        obrowse.showbrowser(obrowse.report_category, "", jtxtreport_category_code, jtxtreport_category_desc);
    }//GEN-LAST:event_jbtnBrowse1ActionPerformed

    private void jtxtreport_category_descFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtreport_category_descFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtreport_category_descFocusGained

private void jtxtreport_codeFocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    jtxtreport_code.setSelectionStart(0);
    jtxtreport_code.setSelectionEnd(jtxtreport_code.getText().length());
}                                           

private void jtxtreport_descFocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    jtxtreport_desc.setSelectionStart(0);
    jtxtreport_desc.setSelectionEnd(jtxtreport_desc.getText().length());
}                                           

private void jtxtreport_category_codeFocusGained(java.awt.event.FocusEvent evt) {                                                  
        // TODO add your handling code here:
    jtxtreport_category_code.setSelectionStart(0);
    jtxtreport_category_code.setSelectionEnd(jtxtreport_category_code.getText().length());
}                                                    

private void jtxtreport_fileFocusGained(java.awt.event.FocusEvent evt) {                                         
        // TODO add your handling code here:
    jtxtreport_file.setSelectionStart(0);
    jtxtreport_file.setSelectionEnd(jtxtreport_file.getText().length());
}                                           

                                    

private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {                                            
    setToolBar(iformtype,istatus);
    mf.setIcon(CLASSNAME);
}                                           

private void jbtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {                                           
    FrmBrowseData frmbrowse=new FrmBrowseData("report_files", "");
    frmbrowse.setModal(true);
    frmbrowse.setVisible(true);
    try {
        obj.initdata(frmbrowse.getValue());
        showData();
    } catch (CodeException ex) {
        Logger.getLogger(Frmreport_files.class.getName()).log(Level.SEVERE, null, ex);
    }
}                                                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Frmreport_files().setVisible(true);
                } catch (CodeException ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator HorizontalLine;
    private javax.swing.JLabel jHeader;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnBrowse;
    private javax.swing.JButton jbtnBrowse1;
    private javax.swing.JLabel jlblreport_category_code;
    private javax.swing.JLabel jlblreport_code;
    private javax.swing.JLabel jlblreport_desc;
    private javax.swing.JLabel jlblreport_file;
    private javax.swing.JTextField jtxtTanggalEntry;
    private javax.swing.JTextField jtxtTanggalUpdate;
    private javax.swing.JTextField jtxtUserID;
    private javax.swing.JTextField jtxtreport_category_code;
    private javax.swing.JTextField jtxtreport_category_desc;
    private javax.swing.JTextField jtxtreport_code;
    private javax.swing.JTextField jtxtreport_desc;
    private javax.swing.JTextField jtxtreport_file;
    // End of variables declaration//GEN-END:variables

 
    public void moveFirst() throws CodeException {
        obj.moveFirst();
        
        showData();
        mf.setIcon(CLASSNAME);
    }

    public void movePrevious() throws CodeException {
        obj.movePrevious();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveNext() throws CodeException {
        obj.moveNext();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void moveLast() throws CodeException {
        obj.moveLast();

        showData();
        mf.setIcon(CLASSNAME);
    }

    public void searchData() throws CodeException {
        showData();
        mf.setIcon(CLASSNAME);

    }

    private void clearfield(){
        jtxtreport_code.setText("");
        jtxtreport_desc.setText("");
        jtxtreport_category_code.setText("");
        jtxtreport_file.setText("");
        jtxtTanggalEntry.setText("");
        jtxtTanggalUpdate.setText("");
        jtxtUserID.setText("");
    }

    public void newData() throws CodeException {
        istatus=1;
        clearfield();
        setToolBar(iformtype,istatus);
    }

    public void saveData() throws CodeException {
        setData();
        obj.update();
        showData();

        istatus = 0;
        setToolBar(iformtype,istatus);
        mf.setIcon(CLASSNAME);
    }

    public void showData() throws CodeException {
        setToolBar(iformtype,istatus);
        setCursor(GlobalUtils.HOURGLASSCURSOR);

        jtxtreport_code.setText(obj.getreport_code());
        jtxtreport_desc.setText(obj.getreport_desc());
        jtxtreport_category_code.setText(GlobalUtils.churuf(obj.getreport_category_code()));
        jtxtreport_file.setText(obj.getreport_file());
        jtxtTanggalEntry.setText(GlobalUtils.churuf(obj.getentrydate()));
        jtxtTanggalUpdate.setText(GlobalUtils.churuf(obj.getauditdate()));
        jtxtUserID.setText(obj.getaudituser());
        
        report_categoryext ocat=new report_categoryext();
        ocat.initdata(obj.getreport_category_code());
        jtxtreport_category_desc.setText(ocat.getreport_category_desc());

        setCursor(GlobalUtils.NORMALCURSOR);
    }

    public void delete() throws CodeException {
        if (obj.delete()){
            obj.moveNext();
            showData();
        }
        mf.setIcon(CLASSNAME);
    }

    public void setToolBar(int iFormType, int istatus) {
        mf.setToolBar(iformtype,istatus);

        if (istatus==1){
            jbtnBrowse.setEnabled(false);
        } else {
            jbtnBrowse.setEnabled(true);
        }
    }

    public void setData() throws CodeException {
        if (istatus==1){
            obj.insert();
        }
        obj.setreport_code(jtxtreport_code.getText());
        obj.setreport_desc(jtxtreport_desc.getText());
        obj.setreport_category_code(GlobalUtils.toInt(jtxtreport_category_code.getText()));
        obj.setreport_file(jtxtreport_file.getText());
        
    }

    public void undo() throws CodeException {
        istatus = 0;
        showData();
    }

    public void execute() throws CodeException {
       saveData();
    }

    public void printData() throws CodeException {
    }

    public void importCsv() throws CodeException {
            

    }

    public void exportCsv() throws CodeException {
        
        
    }

    public void importText() throws CodeException {
        
    }

    public void exportText() throws CodeException {
        
    }

    
}
